### ISSUE TITLE
Easiest way to install on a Debian machine

### ISSUE THREAD

**Issue by Robinjoeh** [slact/nchan#113]
Hey.

I am using Linux Debian "Wheezy", installed using aptitude/apt-get from the following sources.list:
deb http://nginx.org/packages/debian/ wheezy nginx
deb-src http://nginx.org/packages/debian/ wheezy nginx

Nginx installation details:
nginx version: nginx/1.8.0
built by gcc 4.7.2 (Debian 4.7.2-5)
built with OpenSSL 1.0.1e 11 Feb 2013
TLS SNI support enabled
Installation directory: /etc/nginx

I would like to add nchan to this installation, without removing the installed nginx. Is that possible? Which way would be the easiest in order to install nchan? I want as little downtime as possible..

**Comment by slact** [comment]
That depends on what your sysadmin criteria are. Do you need everything to be packaged? Do you want another nginx binary installed next to the default nginx? Do you want to replace the existing nginx package with an nchan-enabled nginx? And lastly, do you want to build it yourself, or are you okay with using a pre-built statically-linked package?

**Comment by Robinjoeh** [comment]
Thanks for the reply.

I would really just want this up and running as easy as possible. I think the easiest is to use some existing package to overwrite the current nginx installation, as long as the nginx updates are up-to-date (like it is from nginx own package above). I don't have to build it myself, in fact, I think it is better not to because I don't think I have those requirements, if we don't count nchan (as nginx has to be compiled with chan). Which means that a pre-built package would be alright, again, as long as it is up-to-date.

Thanks a lot!

**Comment by slact** [comment]
Ok, that's easy then. Grab the latest .deb package from https://nchan.slact.net/#download . Uninstall nginx, and install that one with `dpkg -i`. Let me know if it works, I'm still testing out the debian packages.

**Comment by Robinjoeh** [comment]
Hey, thanks a lot for the reply once again.

So in other words, this wont even affect any php5-fpm processes running? Nginx will operate just as normal with current configurations, even with chan installed?

**Comment by slact** [comment]
I don't have enough feedback with the debian install yet to positively say yes. In theory, the answer is yes. Nchan is an nginx module, and the static build I'm hosting has all the default options. If you give me the output of your `nginx -V` command, I can be a little more certain. 

Having said all that, it sounds like you want to try this sill-in-beta module on a production machine. While I've tested it very thoroughly, I don't think I would recommend you to immediately install it in production without testing it out yourself first. That's my word of caution. If you're feeling brave, go ahead. Otherwise, install it somewhere else first to test, or wait a month or two until it trickles into the nginx-extra package.

**Comment by Robinjoeh** [comment]
Understood.

The complete output of `nginx -V` is here:

nginx version: nginx/1.8.0
built by gcc 4.7.2 (Debian 4.7.2-5)
built with OpenSSL 1.0.1e 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-http_spdy_module --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,--as-needed' --with-ipv6

I think it is pretty easy to just uninstall the current nginx software, and then just install yours that is pre-packed already. If something goes wrong or doesn't work, I can just uninstall it, remove the `.deb` file and install the previous nginx back again.

Do you think you can check the above `nginx -V` output and see if you can find anything that you think would be an issue, or if it should be pretty safe to go ahead?

**Comment by slact** [comment]
Okay, I've matched the config args to the debian ones, but i'm not sure the nginx user is created and permissions of various dirs, so...

you should probably just grab the binary tarball from https://nchan.slact.net/download/nginx-nchan-latest.tar.gz, extract it somewhere local (don't sudo it!), then replace the nginx package's /usr/sbin/nginx with the extracted one. don't forget to make a backup! 

It's ugly, but it's the easiest and least risky way.

**Comment by Robinjoeh** [comment]
Nice idea actually, even if it is a pretty ugly solution. Totally agree with you that it is the least risky way to do it. My `/usr/sbin/nginx` is just 859 KB. Checking your tarball `/usr/sbin/nginx`, which is 12833 KB.

Is this normal? Why is there such a big difference between the two?

**Comment by slact** [comment]
Mine is statically compiled.  That means it includes libc, openssl, libpcre etc,  which considerably bloats the size of the binary.  This is normal. I'm building on arch linux and I don't have native package distributions yet for anything other than Arch. A static binary can be run pretty much on any linux.

**Comment by Robinjoeh** [comment]
Alright, thanks a lot. I have been thinking about this and I will try to do the following:

1. Place `nginx` in `/usr/local/sbin` (from your tarball).
2. Create a `symlink` from `/usr/sbin/nginx` to `/usr/local/sbin/nginx`.

I will try this later today. I will update with results :)

**Comment by Robinjoeh** [comment]
Alright, I have tried it now. Went pretty smooth but got the following error when trying to start nginx:

`/usr/sbin/nginx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/sbin/nginx)`

After this, I guess there will be even more that will be required.. I do think it might be easier to just install the deb-file after all...

**Comment by slact** [comment]
Hmm... well, in that case, you should just build nginx yourself. use the /configure parameters you found in your nginx install, and add --add-module=path/to/nchan_source/ take the nginx binary from that and replace the package's binary. guaranteed to work while i mess around some more with this static build... or get a native debian build going

**Comment by Robinjoeh** [comment]
I will close this issue now, but I will throw you an e-mail regarding some other stuff. Thanks a lot!
