### ISSUE TITLE
Max 255 channels per location, what are the implications?

### ISSUE THREAD

**Issue by kajmagnus79** [slact/nchan#115]
Hi Leo / Slact,

The docs read: _"Any subscriber location can be an endpoint for up to 255 channels"_ — does this mean that e.g. `http://server/location/?channelId=....` supports at most 255 channel ids in total? Or is it 255 channel ids per browser? That is, can 2 different browser each connect to 255 channels, and assuming they use different channels, there'd be a total of 255+255 = 510 channels?

I think I'd like to use nchan for some forum software I'm building — but one nginx server would handle many forums, and many forums * many topics in each forum, easily gets beyond 255. Now, assuming I want one channel for each "active" forum topic, in order to push events to browsers viewing that topic, then, this channel + url structure wouldn't really work: `http://server/forum-events-location?topicId=<site-id>-<forum-topic-id>` — because there will be more than 255 forums * topics. Am I interpreting the 255 limit correctly, and this is an issue, in my case? Or am I misunderstanding something, or is there some workaround / other way of doing what I want?

(I won't be able to edit / update the nginx config file dynamically/automatically to add more locations.)

**Comment by slact** [comment]
The limit refers to the maximum number of channels that a subscriber can subscribe to via a *single connection*. So if you want to subscribe to several channels  with a single GET request, you'd do something like a `GET /subscribe?channels=foo,bar,baz,bzb,etc`. for up to 255 separate channel id values. That is, the limit refers to channel *multiplexing* over one connection. There is no limit on the number of subscriber connection to a location (although it can be configured to be limited).

However, I think you're interpreting the documentation correctly, and it was my mistake to leave this ambiguity. It will be corrected. Thank you for your question.

**Comment by kajmagnus** [comment]
I'm getting the impression I interpreted the docs incorrectly :-) I thought a publisher could publish to at most 255 separate channel id values, per location.  And that all subscriber at that location could subscribe to at most 255 channel ids, in total.

& thanks for your reply too :-)  This nginx module actually seems like great, because it lets me place the WebSocket / long-polling stuff directly on the load balancer (assuming I use nginx as a load balancer) and in that way I (think that I) don't need to care about sticky sessions between the browsers and app servers behind the load balancer.

**Comment by slact** [comment]
> I'm getting the impression I interpreted the docs incorrectly

Maybe... Either way, I've corrected the ambiguity in the documentation

> it lets me place the WebSocket / long-polling stuff directly on the load balancer (assuming I use nginx as a load balancer) and in that way I (think that I) don't need to care about sticky sessions between the browsers and app servers behind the load balancer.

Yup, that's the idea.

If you end up finding Nchan useful, please consider supporting its development with a donation. Thanks for your interest, and happy coding.

**Comment by kajmagnus** [comment]
Okay :-)  I likely won't start using this the nearest time (because I'm working with other things right now). I'll add a note in my chat notes section though

**Comment by kajmagnus** [comment]
@slact Now 3 months later I donated some money via PayPal. (Did you receive them?)

**Comment by slact** [comment]
I did, and thank you! Feel free to make any other feature suggestions, by the way, I've found our discussions quite helpful, and our other conversation useful to others with similar questions. (By the way, I've thought of an elegant way to switch channels without losing messages, but it won't work for websocket just yet...)
