### ISSUE TITLE
Enable nchan_subscribe_existing_channels_only or nchan_authorize_request to prevent DoS attacks?

### ISSUE THREAD

**Issue by kajmagnus** [slact/nchan#117]
Hi, does nchan e.g. allocate memory whenever a browser subscribes to a channel? Or does it do something else that makes it possible to denial-of-service attack nchan by subscribing to 99999999 different channels?

If so, it seems to me that such DoS attacks can be prevented via `nchan_subscribe_existing_channels_only` (and let only some backend application server create channels) and/or `nchan_authorize_request`? — Would you recommend enabling them (or something else), to prevent DoS attacks?  (assuming that one wants to prevent DoS attacks)

**Comment by slact** [comment]
>  does nchan e.g. allocate memory whenever a browser subscribes to a channel?
Yes, about 50-100 bytes per subscriber, and I think about 150-200 bytes per channel.

> such DoS attacks can be prevented via nchan_subscribe_existing_channels_only (and let only some backend application server create channels) and/or nchan_authorize_request

That's precisely the motivation behind `nchan_subscribe_existing_channels_only`, and `nchan_authorize_request` can be used for the same effect. You can also limit the number of subscribers per channel with `nchan_max_channel_subscribers`. If you're concerned about DoS attacks, you should definitely tweak these parameters.

**Comment by kajmagnus** [comment]
Okay, thanks :-)
