### ISSUE TITLE
pubsub one channel but also publish to another

### ISSUE THREAD

**Issue by fictorial** [slact/nchan#120]
I am learning about this for an hour but I don't see how I can do the following. Any help would be appreciated!

Say there's some activity between some clients and they exchange messages related to the activity via a pubsub endpoint.  I'd like their published messages to be viewable to clients acting as viewers or watchers of their activity.  The watchers/viewers cannot publish to the endpoint.  

I can use `nchan_publisher_upstream_request <url>` to send the published messages to an upstream and then have the upstream publish to the viewer's sub endpoint but I'd rather not.  Is there a way in the nginx config to do a sub-request to sort of forward the published messages on the pubsub endpoint to the sub-only endpoint?

Great project BTW. Thanks!

**Comment by slact** [comment]
Hey, I'm glad you're finding Nchan useful.

If I understand your question correctly, why not do something like this:

```nginx
  location {
    location ~ /pubsub/(.+)$ {
    nchan_channel_id $1;
    nchan_pubsub;
  }
  location {
    location ~ /sub/(.+)$ {
    nchan_channel_id $1;
    nchan_subscriber;
  }
```

And have the pubsub clients connect to `/pubsub/foo`, and the viewers to `/sub/foo`. That way the channel `foo` is exposed for publishing and subscribing  via the `/pubsub/foo` url, and only for subscribing bia the `/sub/foo` url.

If you also need to protect the pubsub endpoint from unauthorized access, you can use the mechanisms outlined in the [Securing Channels](https://nchan.slact.net/details#securing-channels) section of the documentation.

Does that answer your question?

**Comment by fictorial** [comment]
Yes, that'll work just fine. Thank you.
