### ISSUE TITLE
When test  the basic config, I meet 400 error!

### ISSUE THREAD

**Issue by yuan666** [slact/nchan#121]
Hello. I study websocket communication recently, and I find the nchan supports it. I configure the basic directives, which are the same as your examples.

worker_processes 5;

http {  
  server {
    listen       80;

    location = /sub {
      nchan_subscriber;
      nchan_channel_id foobar;
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_id foobar;
    }
  }
}

However I test the basic function by the curl, I meet a problem:400 Bad Request ! The curl command is
      curl --request POST --data "test message" http://127.0.0.1:80/pub

 I went to check the /logs/error.log file.I find the following error:
2016/01/19 21:34:40 [info] 18130 # 0: * 1 client sent invalid method while reading client pipelined request line, client: 127.0.0.1, server: localhost, request: "test message"

 I have spent a long time on the problem, but I can't find the solution. I really appreciate your help.

**Comment by slact** [comment]
Can you give me some more information? What version of nginx are you using? What linux distribution?

I've had another report about this issue, but so far I have been unable to replicate it. It would really help me if you could capture the traffic between curl and nginx with wireshark and send me the log from that. I can advise you on how to set this up if you need.

**Comment by yuan666** [comment]
Thank you for your response.My environment is Ubuntu 12.04 LTS, nginx 1.9.9, nchan 0.97 and curl 7.22.0.

I try the curl command with the --verbose option, the results are listed here:
yuan@linux:~$ curl -v --request POST --data "test message" http://localhost/pub
* About to connect() to localhost port 80 (#0)
*   Trying 127.0.0.1... connected
> POST /pub HTTP/1.1
> User-Agent: curl/7.22.0 (i686-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: localhost
> Accept: */*
> Content-Length: 12
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 12out of 12 bytes
< HTTP/1.1 400 Bad Request
< Server: nginx/1.9.9
< Date: Wed, 20 Jan 2016 12:10:09 GMT
< Content-Type: text/html
< Content-Length: 172
< Connection: close
< 
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.9.9</center>
</body>
</html>
* Closing connection #0

When I use the curl command without the --verbose option,I also capture the traffic between curl and nginx with wireshark.The captured package uploaded as 22.zip,and I hope it will be useful to you. 
[22.zip](https://github.com/slact/nchan/files/97450/22.zip)

**Comment by slact** [comment]
Thank you, this is helpful. I still haven't been able to replicate this issue, but I'm working on it. Could you also give me the output of `nginx -V`?

**Comment by slact** [comment]
Nevermind the above, I'm able to replicate the issue. It's particular to 32-bit systems. I'll have it fixed shortly.

**Comment by slact** [comment]
This is now fixed in master, and I'll have a new release in a few days. Thanks for your bug report!

**Comment by yuan666** [comment]
Yes! My machine  is 32 bit. Maybe this is problem. Thank you very much,and I will try  64-bit again.

**Comment by slact** [comment]
fixed in v0.98
