### ISSUE TITLE
MEMSTORE:05: something went wrong, the channel owner is invalid. i: 0 h: 4086991717, max: 1

### ISSUE THREAD

**Issue by Xenofex** [slact/nchan#122]
Hi Leo,

First, thanks for your work.

Here I got a problem. I set the nginx with a pub location, a sub location, authenticated by my app. It worked. Then because I'm only interested on the messages pushed in real time, I tried to set `nchan_message_buffer_length` to 0. That led to the error in the title line in nginx's error log:

```log
MEMSTORE:05: something went wrong, the channel owner is invalid. i: 0 h: 4086991717, max: 1
worker process 39458 exited on signal 11
```

Both `EventSource` in browser and curl received empty responses. 

After played around with it for a while, I found that,

1. setting `nchan_message_buffer_length` to 5 was fine, but setting it to 3 led to the same error as well.
2. commenting out `nchan_authorize_request /sub/auth/user` also gave me the error above, no matter what value 
`nchan_message_buffer_length` is or even not setting it at all.

I'm on OS X 10.11.2, and I installed nchan via homebrew, from the formula you provided: 
```shell
brew tap homebrew/nginx; brew install nginx-full --with-nchan-module
```

which gives me nginx 1.8.0. Not sure nchan's version.

And here is my nginx config:

```nginx
http {

  server {
    #available only on localhost
    listen  127.0.0.1:3002;
    location ~ /pub/users/(\w+)$ {
      nchan_publisher;
      nchan_channel_group my_group;
      nchan_channel_id $1;
      # nchan_store_messages off;
      nchan_message_buffer_length 5;
    }
  }

  server {
    #available to the world
    listen *:3001;
    #SSL config goes here
    location ~ ^/sub/users/(\d+)$ {
      nchan_subscriber;
      nchan_channel_group my_group;
      nchan_channel_id "$1";
      # nchan_authorize_request /sub/auth/user;

      add_header 'Access-Control-Allow-Origin' '*';
      access_log .../log/nchan_sub.log;
    }

    location = /sub/auth/user {
      proxy_pass http://my_app/sub/auth/user;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
      proxy_set_header X-Prev-Message-Id $nchan_prev_message_id;
      proxy_set_header X-Channel-Id $nchan_channel_id;
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header X-Forwarded-For $remote_addr;
    }

    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://my_app;
    }
  }

  upstream my_app {
    server 127.0.0.1:3000;
  }

}


```

**Comment by slact** [comment]
how many nginx workers are you running? can you give me the full nginx config (you can omit the nginx user and other sensitive information if you'd like)?

Also, I need to know your usage pattern. How many channels were you using, how frequently were messages sent, etc.

Could you also enable debug logging and send me the log up to the logged error you've reported? 

These things will really help me reproduce the issue.

**Comment by Xenofex** [comment]
Hi Leo, thanks for the response. Though this is almost the entire nginx config that I was playing with. For the nginx events block:

```
events {
  worker_connections  1024;  ## Default: 1024
}
```

I only sent messages manually via curl, that is - very infrequently, with only one channel.

I'll get to the nginx debug log later.

- Eli

**Comment by slact** [comment]
Hmm... I've tried reproducing this on OS X 10.10.1, so far unsuccessfully. If the logs don't offer me enough hints to track this down, I might ask you to send me a coredump later. I can walk you through that process if necessary.

**Comment by Xenofex** [comment]
Enabling nginx debug log did gave me something: I set nginx worker connections to 256, but my system has `ulimit -n` 256, nginx generates a warning in the debug log.

After I set the worker connections to 256, everything seems to be fine. Setting that back to 1024 makes a bunch of weird errors. For instance, curl hung up forever after posting to a sub channel. 

So far I'm able to go with `nchan_message_buffer_length 0` and `nchan_authorize_request /sub/auth/user`. Hope that nchan could generate a warning for the incorrect configuration. Or make it somewhere in the doc.

Thanks!

**Comment by slact** [comment]
Thanks for the update. I'd still like to track down where this error came from.

So just to clarify, you're not seeing the "something went wrong" error after setting worker_connections to 256? As far as I can tell, that error still shouldn't have happened -- although things do start behaving strangely when out of sockets. How many subscribers did you have when you saw the error in your logs?

**Comment by Xenofex** [comment]
This is the nginx error log from a fresh start, with `worker_connections 1024` while the system only has `ulimit -n = 256`. The behavior was different than what I originally posted: the pub request just hung there until timeout. 

For this log, I did 2 pub request. One from my rails app and the other one from curl command. Both hung up while the log shows `IPC:IPC send alert code 5 to slot 0`

[nginx_error.log.zip](https://github.com/slact/nchan/files/101714/nginx_error.log.zip)
For comparison, the above log is the another fresh start with the *correct* configuration, aka `worker_connections 256` (where the system has exactly ulimit -n 256)



```log
/* nginx error log with worker_connections 1024 (system has ulimit -n 256) */

2016/01/23 12:52:09 [info] 22010#0: *37 client prematurely closed connection while sending to client, client: 127.0.0.1, server: , request: "GET /sub/users/2861 HTTP/1.1", host: "happy-lemon.lvh.me:3001", referrer: "http://happy-lemon.lvh.me:3001/wechat"
2016/01/23 12:52:09 [debug] 22010#0: SUB:LONGPOLL:00007FFDD2E1A3C0 dequeue
2016/01/23 12:52:09 [debug] 22010#0: SPOOL:sub 00007FFDD2E1A3C0 dequeue callback
2016/01/23 12:52:09 [debug] 22010#0: MEMSTORE:01: Chanhead gc add 00007FFDD2E1A740 jkb_group/2861: sub count == 0 after spooler dequeue
2016/01/23 12:52:09 [error] 22010#0: MEMSTORE:01: tried adding WAITING chanhead 00007FFDD2E1A740 jkb_group/2861 to chanhead_gc. why?
2016/01/23 12:52:09 [debug] 22010#0: SUB:LONGPOLL:00007FFDD2E1A3C0 destroy for req 00007FFDD3802250
2016/01/23 12:52:10 [debug] 22010#0: SUB:LONGPOLL:create for req 00007FFDD4002850
2016/01/23 12:52:10 [debug] 22010#0: SUB:LONGPOLL:00007FFDD6100080 created for request 00007FFDD4002850
2016/01/23 12:52:10 [debug] 22010#0: SUB:EVENTSOURCE:00007FFDD6100080 create subscriber
2016/01/23 12:52:10 [debug] 22010#0: SUB:LONGPOLL:hodl request 00007FFDD4002850
2016/01/23 12:52:10 [debug] 22010#0: SUB:LONGPOLL:00007FFDD6100080 reserve for req 00007FFDD4002850, reservations: 1
2016/01/23 12:52:10 [debug] 22010#0: SUB:LONGPOLL:00007FFDD6100080 release for req 00007FFDD4002850. reservations: 0
2016/01/23 12:52:10 [debug] 22010#0: MEMSTORE:01: ensure chanhead ready: chanhead 00007FFDD2E1A740, status 2, foreign_ipc_sub:0000000000000000
2016/01/23 12:52:10 [debug] 22010#0: RBTREE:found node 00007FFDD2C04560
2016/01/23 12:52:10 [debug] 22010#0: SPOOL:found spool node 00007FFDD2C04560 with msgid 0:0
2016/01/23 12:52:10 [debug] 22010#0: SUB:EVENTSOURCE:00007FFDD6100080 output status to subscriber
2016/01/23 12:52:10 [debug] 22010#0: SUB:LONGPOLL:00007FFDD6100080 enqueue
2016/01/23 12:52:42 [debug] 22010#0: MEMSTORE:01: ensure chanhead ready: chanhead 00007FFDD2E1A740, status 140724603453442, foreign_ipc_sub:0000000000000000
2016/01/23 12:52:42 [debug] 22010#0: IPC-HANDLERS(1):IPC: send publish message to 0 ch jkb_group/2861
2016/01/23 12:52:42 [debug] 22010#0: IPC-HANDLERS(1):create shm_str 0000000105966060 (data@ 0000000105966070) jkb_group/2861
2016/01/23 12:52:42 [debug] 22010#0: IPC:IPC send alert code 5 to slot 0
2016/01/23 12:54:09 [debug] 22010#0: MEMSTORE:01: ensure chanhead ready: chanhead 00007FFDD2E1A740, status 140724603453442, foreign_ipc_sub:0000000000000000
2016/01/23 12:54:09 [debug] 22010#0: IPC-HANDLERS(1):IPC: send publish message to 0 ch jkb_group/2861
2016/01/23 12:54:09 [debug] 22010#0: IPC-HANDLERS(1):create shm_str 0000000105966080 (data@ 0000000105966090) jkb_group/2861
2016/01/23 12:54:09 [debug] 22010#0: IPC:IPC send alert code 5 to slot 0

```

**Comment by slact** [comment]
That's very helpful, thank you. I'll update this in a day or two after I understand what's happening a little better.

**Comment by slact** [comment]
Just to update this: I haven't been able to replicate this issue exactly, but I did find another problem which may have caused this. Are you still experiencing this issue after having increased max open fds to match or exceed worker_connections?

**Comment by Xenofex** [comment]
Just tried, still have the problem. Though it behaves slightly differently:

When I have `worker_connections 256` everything is fine - this is the same.
When I have `worker_connections 1024`, no matter I have `nchan_message_buffer_length 0` or not, either the pub connection or the sub connection may hang there until timeout. I suspect that certain resources got leaked, so that it may work one or two times, but always hang there for available resources later on.

**Comment by Xenofex** [comment]
And I updated nginx-full formula to 1.8.1, same problem. I think just keep this issue in mind until you can manage to reproduce it. Anyways for me setting worker_connections to an appropriate value fixes my problem for the moment.

**Comment by slact** [comment]
Hm, alright, thanks for the update. I'll keep debugging then.

**Comment by slact** [comment]
Alright, I've replicated and fixed this. You can test it out from master, or just wait until it's included in the next release. Thank you for your bug report.

**Comment by Xenofex** [comment]
Great! Thanks for fixing!
