### ISSUE TITLE
Assertion `spool != nuspool' failed.

### ISSUE THREAD

**Issue by vtslothy** [slact/nchan#124]
I got this in my nginx error.log:

nchan-master/src/store/spool.c:219: spool_fetch_msg_callback: Assertion `spool != nuspool' failed.

**Comment by slact** [comment]
I need some more information to debug this problem. What does your nginx config look like? What were you doing when this happened? How many channels were in use, and how many subscribers were there?

**Comment by vtslothy** [comment]
config looks like this (a bit simplified from the real one):

nchan_redis_url "redis://10.1.1.1:6300/";
server {
        charset utf-8;
        listen 80 backlog=16384;
        server_name localhost;

        root /var/www;
        index index.html index.htm index.php;

        location ~ /pub/(\w+)$ {
                allow 127.0.0.1;
                deny  all;

                nchan_publisher;
                nchan_channel_group defaultgroup;
                nchan_channel_id $1;
        }

        location ~ /sub/(\w+)$ {
                nchan_subscriber;
                nchan_longpoll_multipart_response on;
                nchan_channel_group defaultgroup;
                nchan_channel_id $1;
                nchan_subscriber_first_message oldest;
        }
}


I had one bash script doing a post to the /pub/test endpoint every 3 seconds, and I was doing a no-extra-headers curl call to hit the /sub/test every 10-20 seconds.  Single subscriber, although the stats coming out of /pub/ had a higher subscriber count (because it probably thought my individual curl calls were different clients).

**Comment by slact** [comment]
Ok, thanks. One more thing: i see you have `nchan_redis_url "redis://10.1.1.1:6300/";` , but no `nchan_use_redis on;`. If that's correct, redis was not being used according to your config. Is that right?

**Comment by vtslothy** [comment]
That appears to be the case.  Thanks, I hadn't realized that yet.

**Comment by slact** [comment]
This, too should not be fixed in v0.99.6
