### ISSUE TITLE
Channels with a dash(-) in the string fail with a 404

### ISSUE THREAD

**Issue by vtslothy** [slact/nchan#125]
With a redis backstore and an endpoint like this:

location ~ /pub/(\w+)$ {
                allow 127.0.0.1;
                deny  all;

                nchan_publisher;
                nchan_channel_group defaultgroup;
                nchan_channel_id $1;
                nchan_message_timeout  24h;
                nchan_message_buffer_length     100;
        }

If you try to post to "/pub/words-words", you get an immediate 404.  Replacing the dash with an underscore fixes the problem.

**Comment by slact** [comment]
I'll check this out, thanks

**Comment by vtslothy** [comment]
Nevermind - I'm 99% sure it's the \w in the nginx regex.  

"A word character is a character from a-z, A-Z, 0-9, including the _ (underscore) character."

**Comment by slact** [comment]
Excellent.
