### ISSUE TITLE
'head->foreign_owner_ipc_sub == d->d.subscriber' assert, other errors in error.log

### ISSUE THREAD

**Issue by vtslothy** [slact/nchan#128]
2016/01/28 19:30:41 [error] 13933#0: IPC-HANDLERS(3):channel/10 sub count already shared, don't update
nchan-master/src/store/memory/ipc-handlers.c:152: receive_subscribe_reply: Assertion `head->foreign_owner_ipc_sub == d->d.subscriber' failed.
2016/01/28 19:30:41 [alert] 13928#0: worker process 13933 exited on signal 6 (core dumped)
2016/01/28 19:30:42 [alert] 13928#0: worker process 3545 exited on signal 11 (core dumped)

2016/01/28 19:28:42 [error] 13933#0: REDISTORE: gc_add chanhead channel/72: already added
2016/01/28 19:28:42 [error] 13933#0: REDISTORE: [Command] connection to redis for redis://10.1.1.1:6379/ closed: [Command]

I have a handful of clients subscribing to mostly-empty channels, very very rarely is anything getting published right now.

**Comment by vtslothy** [comment]
Running master (commit 5f417070f5be1bc40ba79e69864e3d2969a676b0 to fix warnings)

**Comment by slact** [comment]
Any chance you could get me a coredump + binary to look at?

**Comment by vtslothy** [comment]
Also:
2016/01/28 21:23:50 [error] 18275#0: MEMSTORE:02: just-published messages is no longer the last message for some reason... This is unexpected.
2016/01/28 21:23:50 [error] 18275#0: MEMSTORE:02: can't enqueue shared message for channel channel/9
2016/01/28 21:25:02 [error] 18275#0: MEMSTORE:02: just-published messages is no longer the last message for some reason... This is unexpected.
2016/01/28 21:25:02 [error] 18275#0: MEMSTORE:02: can't enqueue shared message for channel channel/9
2016/01/28 21:31:11 [error] 18275#0: REDISTORE: [Command] connection to redis for redis://10.1.1.1:6379/ closed: [Command]
2016/01/28 21:40:30 [error] 18275#0: MEMSTORE:02: just-published messages is no longer the last message for some reason... This is unexpected.
2016/01/28 21:40:30 [error] 18275#0: MEMSTORE:02: can't enqueue shared message for channel channel/9
2016/01/28 21:41:40 [error] 18275#0: MEMSTORE:02: just-published messages is no longer the last message for some reason... This is unexpected.
2016/01/28 21:41:40 [error] 18275#0: MEMSTORE:02: can't enqueue shared message for channel channel/9
2016/01/28 21:45:42 [error] 18275#0: MEMSTORE:02: just-published messages is no longer the last message for some reason... This is unexpected.
2016/01/28 21:45:42 [error] 18275#0: MEMSTORE:02: can't enqueue shared message for channel channel/9

**Comment by vtslothy** [comment]
I can definitely provide those.  I'm working on getting you a core + binary now.

**Comment by slact** [comment]
Thanks. Debugging the redis - memory store bridge is tricky, it's the main reason I haven't taken the beta label off of Nchan just yet. Thanks for your help!

**Comment by slact** [comment]
This should be fixed after v0.99.6
