### ISSUE TITLE
nchan_message_buffer_length usable with nchan_publisher or nchan_subscriber?

### ISSUE THREAD

**Issue by brunoqc** [slact/nchan#133]
In the doc on https://nchan.slact.net/#nchan_message_buffer_length, `nchan_message_buffer_length` doesn't specify if it should be used with `nchan_publisher` or `nchan_subscriber`.

I'm guessing it should be used with `nchan_publisher` just like `nchan_message_timeout`.

**Comment by slact** [comment]
These are publisher settings. I'll update the docs to address this.
