### ISSUE TITLE
Batch messages in longpolling

### ISSUE THREAD

**Issue by prawnsalad** [slact/nchan#138]
I may be missing something obvious but I can't find it anywhere in the docs. If there is a large backlog of messages for a client to load it would be beneficial to batch a configurable number of messages into one response, separated by a configurable delimiter.

In my use case I am broadcasting lines of JSON which can spike to several a second and keeping 50 messages of history. If I could batch these up to around 10 lines per long polling response separated by a newline then my clients would only have to make a fraction of the requests to catch up, saving huge amounts of traffic on both the client and server.

**Comment by slact** [comment]
Good news, this is already a feature! take a look at https://nchan.slact.net/#nchan_longpoll_multipart_response . 

The batch message response will look like this:

```
< HTTP/1.1 200 OK
< Server: nginx/1.9.11
< Date: Sun, 28 Feb 2016 17:06:06 GMT
< Content-Type: multipart/mixed; boundary=uSdRVM4mCUirhWXY2L3F6YgB8am95nD/
< Content-Length: 179
< Last-Modified: Sun, 28 Feb 2016 17:04:49 GMT
< Connection: keep-alive
< Etag: 0
< Vary: If-None-Match, If-Modified-Since
< 
--uSdRVM4mCUirhWXY2L3F6YgB8am95nD/

{foo:1}
--uSdRVM4mCUirhWXY2L3F6YgB8am95nD/

{foo:2}
--uSdRVM4mCUirhWXY2L3F6YgB8am95nD/

{foo:3}
--uSdRVM4mCUirhWXY2L3F6YgB8am95nD/--
```


Does that work for you?

**Comment by prawnsalad** [comment]
Aha... I must have read over the multipart subscriber interface a few times without clicking. Is there a config value to set the number of messages it can send at once or is that a hardcoded number?

**Comment by slact** [comment]
A minor aside: this is actually not the *multipart subscriber* interface, but the *multipart response* setting for the *long-poll* subscriber. It's a little confusing, I know, but they work differently. 

For the longpoll subscriber setting `nchan_longpoll_multipart_response`, if there is more than one message available for the subscriber, it will be sent as a multipart response. If there is only one message, it will be sent normally. There is no maximum-messages-per-multipart-response setting.

**Comment by prawnsalad** [comment]
Understood, thank you.

I've got the basics for the multipart response working correctly now so yes, this works for me so far. I'm putting together a generic no-dependancy and lightweight javascript library for this so that people can get up and running quickly while testing nchan out. Would you be interested in a PR to include something like this as an example?

**Comment by slact** [comment]
Yes, I'm currently collecting clientside implementations for reference and examples. The one I use is a little wonky and depends on Mootools, you can find it here: https://github.com/slact/nchapp/blob/master/app/assets/js/MessageMonitor.js .

**Comment by prawnsalad** [comment]
Handy to look over. I've got a very work-in-progress but working version so far which can be found here (target browsers being IE8+): https://gist.github.com/prawnsalad/6c6194853b0aac2109a8
Example usage being at the bottom.

Once completed I'll send a PR for you to take a look over.
