### ISSUE TITLE
Confusing use of CORS headers 

### ISSUE THREAD

**Issue by prawnsalad** [slact/nchan#139]
I have this config option set: `nchan_access_control_allow_origin "*";` which should be the default anyway. However when publishing I get this error: `No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://*.com' is therefore not allowed access.`

When I manually add this header via `add_header` then it results in two Access-Control-Allow-Origin headers being set (the header I add and *), presumably one by nchan.

When subscribing using log polling, the timeout does not receive the Access-Control-Allow-Origin header which makes sense. What is the recommended way to handle this as not to be throwing errors on the client? Implementing a client-side timer and aborting it before the server-side timer is hit?

**Comment by slact** [comment]
> I have this config option set: nchan_access_control_allow_origin "*"; which should be the default anyway. However when publishing I get this error: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://*.com' is therefore not allowed access.

> When I manually add this header via add_header then it results in two Access-Control-Allow-Origin headers being set (the header I add and *), presumably one by nchan.

I'll look into this. What client are you using? 

> When subscribing using log polling, the timeout does not receive the Access-Control-Allow-Origin header which makes sense. What is the recommended way to handle this as not to be throwing errors on the client? Implementing a client-side timer and aborting it before the server-side timer is hit?

Actually, I think the timeout responses *should* have an `Access-Control-Allow-Origin` header. It's a valid and expected response, after all. I think this is a bug and I'll fix this as well, unless you have a good argument for why this should not be the case.

**Comment by prawnsalad** [comment]
Using the javascript client I'm currently developing with CORS: https://gist.github.com/prawnsalad/ad4f3eb6698b120744d1
~~~javascript
var sub = nchan.sub('https://*.com/transport/sub?c=', {channel_delimiter: ','});
sub.subscribe('channel1');
sub.on('message', function(message) {
	console.log('[Message]', message);
});
~~~

For the timeout, I was assuming it was a client-side timeout but then I hadn't looked into that too careful. It makes more sense being the server-side timeout though, in which case you're right - that is a bug and it should be including the header.

**Comment by slact** [comment]
Tweaked and fixed in master.
