### ISSUE TITLE
Multipart longpoll bug

### ISSUE THREAD

**Issue by prawnsalad** [slact/nchan#140]
Use case: Subscribing via longpolling to 4 channels, disconnecting (when a webpage refreshes) and re-subscribing. Not all the time, but after around 4 times of doing this then I notice channel buffers are suddenly emptied and the nginx worker thread had died.

    2016/02/28 19:23:12 [error] 1694#0: SPOOL:nextmsg id same as curmsg (1456705367:0) nginx: worker process: ../nchan/src/store/spool.c:128: spool_nextmsg: Assertion `0' failed.
    2016/02/28 19:23:12 [alert] 1693#0: worker process 1694 exited on signal 6 (core dumped)

Not sure if it's related but I do see a few of these errors before it happened:

    2016/02/28 19:21:53 [alert] 1608#0: *156 header already sent, client: 162.158.34.180, server: *.com, request: "GET /transport/sub?c=global,chan1,chan2,chan3 HTTP/1.1", host: "*.com", referrer: "https://*.com/"
    2016/02/28 19:21:53 [error] 1608#0: MEMSTORE:01: tried adding WAITING chanhead 0000000000D6FDB0 m/^@/global^@/chan1^@/chan2^@/chan3^@ to chanhead_gc. why?

I'm sure these are related to just the memory store so switching to redis may just fix it (not that I've tried yet).

**Comment by slact** [comment]
send me an email to nchan@slact.net. I'll help you build nginx so that I can look at a coredump from that error. It'll take about 20 minutes.

**Comment by slact** [comment]
Appears related to multipart longpoll + multiplex channel issue.

Under above conditions, messages are not delivered correctly.

**Comment by slact** [comment]
Turned out to be an interaction between incorrect re-use of bufs and iovec upper limit of 64 chain links per socket send. fixed in master.
