### ISSUE TITLE
Errors when using redis backed channels when publishing a message

### ISSUE THREAD

**Issue by prawnsalad** [slact/nchan#141]
2016/02/28 21:30:24 [error] 1280#0: REDIS SCRIPT ERROR: publish : @user_script:229: user_script:229: attempt to compare number with string

**Comment by slact** [comment]
what version of nchan are you using?

**Comment by prawnsalad** [comment]
I can't find a way to get the version at runtime? `nginx -V` doesn't show any nchan versions. But I'm currently testing with the static build, nginx-nchan-static-1.8.1.nchan0.99.6-1-x86_64

**Comment by slact** [comment]
Ok, I'll address this tomorrow.

**Comment by slact** [comment]
This was a problem with Redis' PUBSUB NUMSUB command for Redis versions < 2.8.14 (https://github.com/antirez/redis/issues/1561) Fixed in master.
