### ISSUE TITLE
Javascript client?

### ISSUE THREAD

**Issue by Jonovono** [slact/nchan#143]
Hi. I am wondering if there is an example of this being used in an actual app? Perhaps a javascript client or something? That would be super useful!

Thanks.

**Comment by slact** [comment]
There's no official client yet, but you can take a look at the client I've been using: https://github.com/slact/nchapp/blob/master/app/assets/js/MessageMonitor.js

**Comment by Jonovono** [comment]
@slact thanks! This will be helpful!
