### ISSUE TITLE
Documentation page unreachable?

### ISSUE THREAD

**Issue by bragma** [slact/nchan#146]
Hi,
I can't connect to [https://nchan.slact.net/](https://nchan.slact.net/), the browser tells me the page is unreachable.

**Comment by slact** [comment]
the provider where i'm hosting the nchan docs is having (serious) connectivity issues. I'm moving to a backup server now.

**Comment by slact** [comment]
Ok, it should be up now, as soon as the DNS record propagates.

**Comment by bragma** [comment]
It works, thanks!
