### ISSUE TITLE
nchan_max_channel_subscribers setting ignored

### ISSUE THREAD

**Issue by asgoel** [slact/nchan#151]
how does this get used? trying to get some things done with a number of concurrent subscribers and don't see this actually being used anywhere in the code base?

**Comment by slact** [comment]
Huh, you're right. I didn't have a test for this, and I must've lost the code handling this config in one of the refactorings. I will have this fixed shortly, especially because it's an important security-related setting.

**Comment by slact** [comment]
fixed in d4a2cbd . You can test it in master or wait a couple of days until I tag a new release.

Thanks for your bug report.
