### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#153]
Hello Leo,

I tried to compile the latest version
( git clone https://github.com/slact/nchan.git )

When compiling Nginx, i get the following error:

cc1: warnings being treated as errors
/root/nchan/src/store/memory/memstore.c: In function 'nchan_store_subscribe_continued':
/root/nchan/src/store/memory/memstore.c:1834: error: comparison between signed and unsigned integer expressions
make[1]: *** [objs/addon/memory/memstore.o] Error 1
make[1]: Leaving directory `/root/nginx-1.8.1'
make: *** [build] Error 2

This latest version is good ?

Thank you,
Valy

**Comment by slact** [comment]
I wasn't checking for -Wsign-compare warning in the fix for #151. fixed in master.
