### ISSUE TITLE
Error on start services (first time)

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#155]
Hello Leo,

I don't know if the problem is specifically NCAN, but I hope to find a solution.
This error occurs only on reboot, exactly when processes (NGINX and REDIS) starts.

If I restart Nginx LATER, things return to normal.

2016/04/16 18:39:24 [error] 1120#0: redis_nginx_adapter: could not create the redis sync context for 127.0.0.1:6379 - Connection refused
2016/04/16 18:39:25 [error] 1120#0: redis_nginx_adapter: could not select redis database
2016/04/16 18:39:25 [error] 1120#0: REDISTORE: [Command] connection to redis for redis://127.0.0.1:6379 closed: Connection refused
2016/04/16 18:39:25 [error] 1120#0: redis_nginx_adapter: connection to redis failed - Connection refused
2016/04/16 18:39:25 [error] 1120#0: redis_nginx_adapter: could not select redis database
2016/04/16 18:39:25 [error] 1120#0: REDISTORE: [Pubsub] connection to redis for redis://127.0.0.1:6379 closed: Connection refused
2016/04/16 18:39:25 [error] 1120#0: redis_nginx_adapter: connection to redis failed - Connection refused

Thank you,
Valy

**Comment by slact** [comment]
This is because redis is not running (or has not finished starting) when nginx starts. Make sure redis starts before nginx.

**Comment by valydvweb** [comment]
Solved. Thank's
