### ISSUE TITLE
upstream timed out (110: Connection timed out) while reading response header from upstream, client

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#156]
Hello Leo,

I made a test configuration with  nchan_authorize_request directive.
```
# TEST
        location /test {
            nchan_pubsub;
            nchan_authorize_request "/auth";
            nchan_channel_id "test";
        }

        location /auth {
            proxy_pass "http://mysite.com/auth.php";
        }
```
/auth.php is a empty php or something
```php
<?php http_response_code(200); ?>
```
But is irrelevant, response code is 200 ... anyway

On testing:
`curl --request POST --data "test message" http://mysite.com/test`

I expect a lot and ... finally, analyzing error logs:
```
upstream timed out (110: Connection timed out) while reading response header from upstream, client
```
My NGINX version is 1.8.1

What is wrong?

Thank's,
Valy

**Comment by notedit** [comment]
"http://mysite.com/auth.php"  can be visited by brower?

**Comment by valydvweb** [comment]
Yes ... can be visited

**Comment by slact** [comment]
How much traffic was there? I'm guessing the php interpreter couldn't keep up with the requests.

**Comment by valydvweb** [comment]
There is no traffic ... It is a test page / script

**Comment by slact** [comment]
Can you ensure that the script is receiving the request?

**Comment by valydvweb** [comment]
If I remove the directive 
nchan_authorize_request "/auth";

work's fine

[root@test ~]# curl --request POST --data "test message" http://mywebsite/test
queued messages: 3
last requested: 77 sec. ago
active subscribers: 1
last message id: 1461169085

**Comment by slact** [comment]
That's not what I mean. Can you make sure the php script is receiving the request from Nginx? By logging it to a file, or to stdout, or a database.

**Comment by valydvweb** [comment]
yes ... sorry
That's what I am doing right now

**Comment by valydvweb** [comment]
The script is not called

**Comment by valydvweb** [comment]
An CURL Request

[root@test ~]# curl --request POST --data "test message" http://mywebsite/test
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.8.1</center>
</body>
</html>

**Comment by valydvweb** [comment]
And error log
[error] 6388#0: *46 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ......

**Comment by valydvweb** [comment]
/auth is not called. No database log.

**Comment by valydvweb** [comment]
I could try to compile Nginx with the latest NCHAN?

**Comment by slact** [comment]
I don't think this is an Nchan issue. What happens with
    curl http://mywebsite/auth
?

**Comment by valydvweb** [comment]
This request is OK ... Normally ... without responsebecause auth.php is empty

**Comment by slact** [comment]
Could you give me the output of `curl -v http://mywebsite/auth` ?

**Comment by valydvweb** [comment]
# curl -v http://mydomain.com/auth
* About to connect() to mydomain.com port 80 (#0)
*   Trying myip... connected
* Connected to mydomain.com (myip) port 80 (#0)
> GET /auth HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: mydomain.com
> Accept: */*
YES

< HTTP/1.1 200 OK
< Server: nginx/1.8.1
< Date: Wed, 20 Apr 2016 17:59:48 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/5.6.19
<
* Connection #0 to host mydomain.com left intact
* Closing connection #0

**Comment by slact** [comment]
can you try adding a response to the php script's body, and try it again?

**Comment by valydvweb** [comment]
Yes

[root@test ~]# curl -v http://mydomain.com/auth
* About to connect() to mydomain.com port 80 (#0)
*   Trying myip... connected
* Connected to mydomain.com (myip) port 80 (#0)
> GET /auth HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: mydomain.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.8.1
< Date: Wed, 20 Apr 2016 18:11:14 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/5.6.19
<
* Connection #0 to host mydomain.com left intact
* Closing connection #0
ABC[root@test ~]#

**Comment by valydvweb** [comment]
echo 'ABC';

**Comment by slact** [comment]
Thanks. I'm investigating this.

**Comment by slact** [comment]
Ok, this is a bug where the content-length for the upstream request was not being set properly. I've just fixed this and I'm tagging a new version with the fix.

**Comment by valydvweb** [comment]
Thank's

**Comment by slact** [comment]
Alright. Please try Nchan v0.99.13 and let me know if it fixed the issue.

**Comment by valydvweb** [comment]
Work's fine

Thank's
