### ISSUE TITLE
Are channels isolated per Nginx server block, or shall I use nchan_channel_group?

### ISSUE THREAD

**Issue by kajmagnus** [slact/nchan#157]
Hi, If I have two different `server {...}` blocks that use the same channel names, then if I publish to one such channel in the second server, will events then be generated in the first server?

Detailed example: Assume there are these two servers, which use the same Nchan channel, `foobar`:

```
http {  
  server {
    server_name  the-first-server;
    listen 80;

    location = /sub {
      nchan_subscriber;
      nchan_channel_id foobar;      <-- foobar
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_id foobar;      <-- foobar
    }
  }
}

http {  
  server {
    server_name  the-second-server;
    listen 80;

    location = /sub {
      nchan_subscriber;
      nchan_channel_id foobar;       <-- foobar
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_id foobar;        <-- foobar
    }
  }
}
```

and then I publish something to `http://the-second-server/pub`. Now, will this be published only to clients who have connected to the second server?  But the clients connected to the first server won't get any messages?  Or will the clients in the first server receive the message too?

Is it perhaps my own responsibility to create namespaces, via the [nchan_channel_group](https://nchan.slact.net/#nchan_channel_group) directive? (the docs says: _"[...] Think of it as a prefix string for the channel id."_ )  I could then, in the first server: `nchan_channel_group theFirstServer` and in the second server: `nchan_channel_group theSecondServer`, to isolate them from each other. I would want to do that, because my app runs many websites not realted to each other (each one in its own server block).

At the same time, I might actually _also_ want two different `server { ...}` directives to sometimes be able to access the same channels. I would make one server block listen on port 80 — it would be the one all browsers connect to, to listen to events. And another server block on port 81, to which my app server connects, in order to _publish_ events. And I'd tell the firewall to _deny_ access to port 81 from the outside world, so only my appserver will be able to connect & publish. But then of course the server on port 81 needs access to the channels in the server block for port 80. — Can the server on port 81 reach them, if I simply declare both the port-80 and port-81 server blocks to be in the same `nchan_channel_group`?

Best regards,
KajMagnus

((Related StackOverflow question: http://stackoverflow.com/questions/36734697/nginx-can-i-deny-some-port-not-an-ip-in-a-location ))

**Comment by slact** [comment]
> Hi, If I have two different server {...} blocks that use the same channel names, then if I publish to one such channel in the second server, will events then be generated in the first server?

Yes.

>  I could then, in the first server: nchan_channel_group theFirstServer and in the second server: nchan_channel_group theSecondServer, to isolate them from each other. I would want to do that, because my app runs many websites not realted to each other (each one in its own server block).

Yup. That is precisely the fuction of `nchan_channel_group`.


> At the same time, I might actually also want two different server { ...} directives to sometimes be able to access the same channels. I would make one server block listen on port 80 — it would be the one all browsers connect to, to listen to events. And another server block on port 81, to which my app server connects, in order to publish events. 

This is described in the https://nchan.slact.net/details#securing-channels part of the documentation:

```nginx
http {
  server {
    #available only on localhost
    listen  127.0.0.1  8080;
    location ~ /pub/(\w+)$ {
      nchan_publisher;
      nchan_channel_group my_app_group;
      nchan_channel_id $1;
    }
  }

  server {
    #available to the world
    listen 80;
    location ~ /sub/(\w+)$ {
      nchan_subscriber;
      nchan_channel_group my_app_group;
      nchan_channel_id $1;
    }
  }
}
```

**Comment by kajmagnus** [comment]
Thanks :- ) This seems to be exactly what I need.  & thanks for the #securing-channels docs link, there's lots of stuff there that I didn't know about or have forgotten.

**Comment by slact** [comment]
You're quite welcome.
