### ISSUE TITLE
Channel ID dinammically

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#158]
Hello again,

There is a possibility to setting channel ID and/or channel group dinammically ?

EG:

ws://connectHost/operatorID -> AUTH SCRIPT (cookie, db auth, etc) -> REDIRECT TO ws://connectHost/uniqueID

uniqueID is a dinnamic custom ID

Thank's,
Valy

**Comment by slact** [comment]
Yes, this is possible with the X-Accel-Redirect functionality: https://nchan.slact.net/details#authenticate-and-hide-the-channel-id-with-x-accel-redirect

**Comment by valydvweb** [comment]
ooo ... yes ... good start
