### ISSUE TITLE
REDISTORE: SYNC subscriber_unregister command

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#159]
Hello

I compile NGINX (last version) with NCHAN module (last version)

This error was receiving in error.log
2016/04/21 18:57:16 [error] 14796#0: REDISTORE: SYNC subscriber_unregister command

Can I ignore this?

Thank's,
Valy

**Comment by slact** [comment]
Does this happen when shutting down or restarting nginx?

**Comment by valydvweb** [comment]
OK
