### ISSUE TITLE
Redirection mechanism

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#160]
Hello,

I have a question about the following situation:

My message is send in JSON format ... same as:
{
  text: 'Message text',
  channel: CUSTOM_CHANNEL_ID
}

This is sent to COMMON_CHANNEL_ID

But ... I want to send the message to CUSTOM_CHANNEL_ID

Basically on 2 channels (COMMON_CHANNEL_ID and CUSTOM_CHANNEL_ID)

First solution is nchan_publisher_upstream_request
A script (CURL based) which send message to CUSTOM_CHANNEL_ID

There is another solution that does not use CURL script ?
Or ... simply ... another optimized solution, using only WebSocket connection (one request ... no more)
Or ... it is the best soluttion ?

Thank's,
Valy

**Comment by slact** [comment]
I'm sorry, I don't quite understand your question. Do you want to publish the same message to 2 channels?

**Comment by valydvweb** [comment]
Yes
The same message to 2 channels
But, channel 2 must be provided in the message content.

**Comment by slact** [comment]
You can publish to 2 channels simultaneously: https://nchan.slact.net/#channel-multiplexing

**Comment by valydvweb** [comment]
Yes ... I know that
But ... in my case channel name is sent along with the message

Message is sent in json format

Eg:

This is my message
{
text: "some text",
channel: channel name (X)
}

This message is sent to the common channel.
But i also want to send the message to channels name (X) specified in the message content.

Thank's

**Comment by slact** [comment]
I don't understand why the sender of the message could not send it to both channels. Whoever constructs the message can send to the common channel and channel (X) at the same time.

**Comment by valydvweb** [comment]
Channel X is created afterwards and is unknown at the beginning (when the WebSocket connection is opened)

A new client connects later and basically a new channel is opened.

I want to send data through that channel without opening a new connection or reconnecting.

**Comment by notedit** [comment]
you can do this in your  application logic.

**Comment by valydvweb** [comment]
Yes ... I know that ... but I am skeptical about using CURL when it comes to high traffic

**Comment by slact** [comment]
> Channel X is created afterwards and is unknown at the beginning (when the WebSocket connection is opened)
> A new client connects later and basically a new channel is opened.
> I want to send data through that channel without opening a new connection or reconnecting.

Ah, okay, I understand now. You're publishing this message through a websocket publisher client. The two options here are:
1. Don't publish through websocket but with an HTTP request to both channels.
2. Publish through websocket, then upstream the publisher request to your app, which in turn publishes to channel X.

> Yes ... I know that ... but I am skeptical about using CURL when it comes to high traffic

You are right to be skeptical. You can, make use of curl's persistent connections, and then it's not a problem. Check your language's curl library to find out how to do this.

**Comment by valydvweb** [comment]
Thank's
