### ISSUE TITLE
nchan_message_buffer_length 1

### ISSUE THREAD

**Issue by brunoqc** [slact/nchan#161]
I'm using `nchan_message_buffer_length 1` and while testing I got the last value instead of the actual one.

Let's say the latest value was 9 earlier and now it's 10. My ws clients are showing 10 but I tested with curl and I got 9.

Then I tested in Chrome. I got 9. I refreshed and got 10 so I was thinking that maybe the buffer was acting like it has a length of 2 and that I needed to refresh so nchan could serve the second value based on if-modified-since and if-none-match.

I refreshed again and I got 9. Not sure what to think anymore. Refreshed a couple of time and still got 9.

Since this is in production, the values has now changed and I can't reproduce right now.

I'm using redis with nchan to prevent data loss in nginx crashes.

nginx 1.9.15
nchan 0.99.13

**Comment by slact** [comment]
can you show me the nginx config? Specifically, the `nchan_message_timeout` setting.

**Comment by brunoqc** [comment]
```
location ~ /sub/(\w+)$ {
        nchan_subscriber;
        nchan_message_buffer_length 1;
        nchan_channel_id $1; #first capture of the location match
    }

location ~ /pub/(\w+)$ {
        allow 127.0.0.1;
        deny all;

        nchan_publisher;
        nchan_channel_id $1;
        nchan_message_buffer_length 1;
        nchan_message_timeout 0;
    }
```

I should remove `nchan_message_buffer_length` from the sub location.

**Comment by slact** [comment]
Ah, ok. The issue here is the buffer length setting does not get forwarded from redis to the memory-store cache. I'll have it fixed for the next release (probably in a few days).

**Comment by brunoqc** [comment]
OK, no hurry. :)
