### ISSUE TITLE
X-Accell Gateway Time-out

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#164]
Hello again,

I want to test x-accel-redirect and encountered the following problem:

[root@test ~]#  curl --request POST --data "test message" http://mydomain.com/client
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.9.15</center>

My NGINX version is 1.9.15
NGINX Conf file:

      location /client {
             proxy_pass http://mydomain.com/test.php;
       }

        location /test {
           internal;
           nchan_pubsub;
           nchan_channel_id test;
        }

test.php looks like:
<?php

header('X-Accel-Redirect: /test');
header('X-Accel-Buffering: no');

?>

What is wrong?

Thank's

**Comment by slact** [comment]
What's the output of `curl -v http://mydomain.com/test.php`?

**Comment by valydvweb** [comment]
[root@test ~]# curl -v http://mydomain.com/test.php
* About to connect() to mydomain.com port 80 (#0)
*   Trying myip... connected
* Connected to mydomain.com (myip) port 80 (#0)
> GET /test.php HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: mydomain.com
> Accept: */*
>


and ... waiting ... more time

**Comment by slact** [comment]
This is a problem with your php script then. You might need to output an empty string or something to get a response.

**Comment by valydvweb** [comment]
Hello,

I solved this problem ... but greet another problem ( similar )

location ~ \.php$ {
            root /home/prinro/connect;
            try_files $uri =404;
            fastcgi_pass   unix:/tmp/mydomain.com-fpm.sock;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
            fastcgi_ignore_headers X-Accel-Redirect;
            fastcgi_ignore_headers X-Accel-Buffering;
            fastcgi_pass_header X-Accel-Redirect;
            fastcgi_pass_header X-Accel-Buffering;
        }

[root@test ~]# curl -v http://mydomain.com/test.php
* About to connect() to connect.printmark.ro port 80 (#0)
*   Trying myip... connected
* Connected to mydomain.com (myip) port 80 (#0)
> GET /test.php HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: mydomain.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.9.15
< Date: Tue, 26 Apr 2016 15:44:08 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/5.6.19
< X-Accel-Redirect: /pubsub
< X-Accel-Buffering: no
<
* Connection #0 to host mydomain.com left intact
* Closing connection #0

BUT 

[root@test ~]# curl --request POST --data "test message" http://connect.printmark.ro/client

WAITING ... MORE TIME AND ... NOT WORKING

My nginx.conf ... looks like this:

    location /client {
        proxy_pass http://connect.printmark.ro/test.php;
     }

     location = /pubsub {
        internal;
        nchan_pubsub;
        nchan_channel_id foobar;
    }

**Comment by slact** [comment]
I looked into this, and it's a bug. The POST request to a pubsub endpoint is being treated as a subscriber GET after an X-Accel-Redirect. I will have this fixed shortly.

**Comment by slact** [comment]
Looks like Nginx forces the request method to GET upon X-Accel-Redirect. I'll see if I can find a way around this.

**Comment by slact** [comment]
alright, this is not fixed in master at commit 30bd9756. Please rebuild from master and let me know if this solves the problem.

**Comment by valydvweb** [comment]
Now work's fine. Thank's
