### ISSUE TITLE
how can i config nchan to have poll sub connection?

### ISSUE THREAD

**Issue by notedit** [slact/nchan#165]
i do not mean long poll,  what i want to do is to have a long  stream connection,  will not disconnect  after receive a message.

i can do this in nginx-push-stream module.

**Comment by notedit** [comment]
i  can do this by add  multipart header.

i  receive some thing like this
```
Last-Modified: Wed, 27 Apr 2016 06:32:51 GMT
Etag: 0
Content-Type: application/x-www-form-urlencoded

test message
--CTiGBa5a2NmR40ErOg4XiN/GlQpevqR7

```

what "--CTiGBa5a2NmR40ErOg4XiN/GlQpevqR7" is?

**Comment by slact** [comment]
You can use either the [multipart/mixed](https://nchan.slact.net#http-multipart-mixed), [chunked](https://nchan.slact.net#http-chunked-transfer) or [EventSource](https://nchan.slact.net#eventsource) subscribers.
