### ISSUE TITLE
last_message_id always "0:0"

### ISSUE THREAD

**Issue by deviantmk** [slact/nchan#169]
Publishing seems to be working fine

`{"messages": 9, "requested": 293, "subscribers": 0, "last_message_id": "1461975441:0" }`

but always returns empty message id

`{"messages": 9, "requested": 112, "subscribers": 1, "last_message_id": "0:0" }`

**Comment by slact** [comment]
I need more information. What does your config look like, where are you publishing, what method? Also, what version of Nginx and Nchan are you using?

**Comment by deviantmk** [comment]
I just downloaded nchan and nginx from the download page installed them as per the doc instructions and did same as described in the Conceptual Overview

nginx version: **nginx/1.9.14**

`curl --request POST --data "test message" -H "Accept: text/json" http://127.0.0.2:80/pub`
`curl -v --request GET -H "Accept: text/json" http://127.0.0.2:80/pub`

config

`server {
  listen       8080;

  location = /sub {
    nchan_subscriber;
    nchan_channel_id foobar;
  }

  location = /pub {
    nchan_publisher;
    nchan_channel_id foobar;
  }
}
`

**Comment by slact** [comment]
Ah, I see. GET requests to publishers indeed show the last_message_id as 0:0. I'll have this fixed shortly.

**Comment by deviantmk** [comment]
thanks for checking it out

**Comment by slact** [comment]
fixed in 494548198. You can build from master or wait until the next release (today or tomorrow) to test it out. Thanks for your bug report!
