### ISSUE TITLE
Upstream Request not properly working

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#170]
Hello,

I did a test configuration

When I connect with WebSocket and send ... my message is an empty string

# TEST
        location /test {
          nchan_pubsub;
          nchan_channel_id "test";
          nchan_store_messages off;
          nchan_publisher_upstream_request "/pub";
        }

        location /pub {
            return 304;
        }

My NGINX version is 1.9.15

Thank's

**Comment by slact** [comment]
You're not doing anything it your /pub location. It should be proxying the request to your app or somewhere else. I double-checked and the functionality works correctly.

**Comment by valydvweb** [comment]
Same problem in this case:

# TEST
        location /test {
          nchan_pubsub;
          nchan_channel_id "test";
          nchan_store_messages off;
          nchan_publisher_upstream_request "/pub";
        }

        location /pub {
            proxy_pass "http://mydomain.com/x.php";
        }

x.php file:

<?php
http_response_code(304); // set Not Modified response code
?>

[root@test ~]# curl -v mydomain.com/x.php
* About to connect() to mydomain.com port 80 (#0)
*   Trying myip... connected
* Connected to mydomain.com (myip) port 80 (#0)
> GET /x.php HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: mydomain.com
> Accept: */*
>
< HTTP/1.1 304 Not Modified
< Server: nginx/1.9.15
< Date: Sat, 30 Apr 2016 18:15:11 GMT
< Connection: keep-alive
< X-Powered-By: PHP/5.6.19
<
* Connection #0 to host mydomain.com left intact
* Closing connection #0

**Comment by deviantmk** [comment]
@valydvweb what are you trying to accomplish?

you are not forwarding anything...

you are calling your script directly instead trough nginx

**Comment by valydvweb** [comment]
A 304 Not Modified will publish the message as it was received from the publisher.
My message is published but is empty.
I tested using HTML5 WebSocket

**Comment by valydvweb** [comment]
var cn = new WebSocket('ws://mydomain.com/test');

    cn.onopen = function() {
        console.log('Connected');
		cn.send('test');
    }
    cn.onmessage = function(e) {
        console.log(e.data); // EMPTY LOG
    }

**Comment by slact** [comment]
Yes, I'm seeing this. I'll have a fix shortly.

**Comment by slact** [comment]
fixed in  d8b4b6a. Thanks for your bug report.

(However, there is still a bug  when publishing with websocket too fast -- before the previous published message's upstream request has responded. It's unrelated but I noticed it while fixing this bug. This will also be fixed shortly)

**Comment by valydvweb** [comment]
cc1: warnings being treated as errors
/root/nchan/src/util/nchan_msgid.c: In function 'nchan_parse_compound_msgid':
/root/nchan/src/util/nchan_msgid.c:287: error: 'len' may be used uninitialized in this function
make[1]: *** [objs/addon/util/nchan_msgid.o] Error 1
make[1]: Leaving directory `/root/nginx-1.9.15'
make: *** [build] Error 2

**Comment by slact** [comment]
the compiler is wrong in this case. there is no way 'len' can be used uninitialized in that code. 

I've fixed the warning anyway, but my gcc doesn't generate it. Neither does clang. Can you tell me what compiler and version you were using?

**Comment by slact** [comment]
ok, i've fixed the other issue as well in 314cca9 . please pull from master and try again.

**Comment by valydvweb** [comment]
Work's fine now. Thank's
