### ISSUE TITLE
feature: code testing 

### ISSUE THREAD

**Issue by deviantmk** [slact/nchan#171]
testing the code is essential for a stable product

**Comment by slact** [comment]
Did you even look a the test suite I'm using?
https://github.com/slact/nchan/blob/master/dev/test.rb

It doesn't have 100% code coverage -- but it's caught quite a few issues, and I am adding new tests whenever there is time.

Of course, if you can, please submit more tests -- I'll be quite happy to incorporate them and give you credit.

**Comment by deviantmk** [comment]
missed it, sorry

I am not familiar with C sadly
