### ISSUE TITLE
What is wrong in this case ?

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#172]
Hello,

I want to publish a message on two channels in the following way:

# TEST
        location /test {
          nchan_pubsub;
          nchan_channel_id "test";
          nchan_store_messages off;
          nchan_publisher_upstream_request "/pub";
        }

        location /pub {
           nchan_publisher;
           nchan_publisher_channel_id "foo";
           return 304;
        }

        location /foo {
            nchan_pubsub;
            nchan_channel_id "foo";
            nchan_store_messages off;
        }
    
The message is published only "test" channel.

I intend to do the next thing

    location /pub {
        nchan_publisher;
       if ($request_body = "test") { 
           nchan_publisher_channel_id "foo";
        }

        return 304;
    }

**Comment by slact** [comment]
Please show me how you are publishing the messages.

**Comment by valydvweb** [comment]
HTML5 Websocket

    var cn = new WebSocket('ws://mydomain.com/test');

    cn.onopen = function() {
	console.log('Open test connection');
	
	setTimeout(function() {
		cn.send('message');
	}, 1000);
    }

    cn.onmessage = function(e) {
	console.log('Receiving test message ' + e.data);
    }

    var foo = new WebSocket('ws://mydomain.com/foo');
    
    foo.onopen = function() {
	console.log('Open foo connection');
    }

    foo.onmessage = function(e) {
	console.log('Receiving test message ' + e.data);	
    }

**Comment by slact** [comment]
that's not how upstream_request works. you must have an upstream proxy in the upstream_request location.

**Comment by valydvweb** [comment]
something like ?

nchan_publisher_upstream_request "http://mydomain.com/pub"

**Comment by valydvweb** [comment]
I tried another method but is the same problem ...

        location /test {
          nchan_pubsub;
          nchan_channel_id "test";
          nchan_store_messages off;
          nchan_publisher_upstream_request "/pub";
        }

        location /pub {
           proxy_pass "http://mydomain.com/proxy";
        }

        location /proxy {
           nchan_publisher;
           nchan_publisher_channel_id "foo";
           return 304;
        }

        location /foo {
            nchan_pubsub;
            nchan_channel_id "foo";
            nchan_store_messages off;
        }

**Comment by slact** [comment]
What do you nginx access logs say?

**Comment by valydvweb** [comment]
myip - - [02/May/2016:18:12:10 +0300] "GET /test.php HTTP/1.1" 200 741 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
myip - - [02/May/2016:18:12:10 +0300] "GET /test HTTP/1.1" 101 11 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
myip - - [02/May/2016:18:12:10 +0300] "GET /foo HTTP/1.1" 101 2 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"
136.243.206.7 - - [02/May/2016:18:12:12 +0300] "POST /proxy HTTP/1.0" 304 0 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"

**Comment by slact** [comment]
I think the "return 304" is interfering  with the nchan directive. Nginx configs are a little weird, they aren't really evaluated top-to-bottom. Use an application script to do what you're trying to do.

**Comment by valydvweb** [comment]
It was a verry optimized solution than by calling a script. You can not do anything about it?

**Comment by slact** [comment]
You can publish to more than one channel with an HTTP request, or with websocket by using

```nginx
    location /test {
      nchan_pubsub;
      nchan_subscriber_channel_id "test";
      nchan_publisher_channel_id "test" $arg_extra_channel
      nchan_store_messages off;
      nchan_publisher_upstream_request "/pub";
    }
```

then a POST to /test?extra_channel=extra wiull publish to 'test' and 'extra'

**Comment by valydvweb** [comment]
I know ... But I want to use WebSocket (no more calling)

**Comment by slact** [comment]
Sorry, there's currently no way to do this from a websocket publisher.

**Comment by valydvweb** [comment]
OK ... thank's
