### ISSUE TITLE
Message not received

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#174]
Hello,

I recompile NGINX (1.9.15) with NCHAN module (last)

I did a simple test using HTML5 Websocket and encountered the following problem:
Not all messages are received
Especially ... if they are sent quickly

MyConf:
-----------

    location /test {
          nchan_pubsub;
          nchan_channel_id "test";
          nchan_store_messages off;
     }

MyScript:
-------------
    <script>
    var cn = new WebSocket('ws://mydomain.com/test');
	
	var i = 0;
	
        cn.onopen = function() {
	    console.log('Open test connection');
	}
	
    function send() {
         i++;
	console.log('Send test message ' + i);		
        cn.send('message ' + i); // custom message
    }

    cn.onmessage = function(e) {
        console.log('Receiving test message ' + e.data);
    }

    </script>
    <button onClick="send()" type="button">SEND MESSAGE</button>

Thank's

**Comment by slact** [comment]
You've disabled message buffering with `nchan_store_messages off`, You may lose some messages this way, because if the subscriber is not ready to receive a message when it is published, it will be discarded.

Don't turn off message buffering if you don't want missed messages.

**Comment by valydvweb** [comment]
Yes ... This is the problem.
I set nchan_store_messages on; 
And now work's fine

Thank's
