### ISSUE TITLE
Custom Response

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#175]
Hello,

Can I customize this response (completly) ?

Request:
-------------
curl --request POST --data "test message" http://127.0.0.1:80/pub

Response
---------------

 queued messages: 5
 last requested: 18 sec. ago
 active subscribers: 0
 last message id: 1450755280:0

TO:
------

Request:
-------------
curl --request POST --data "test message" http://127.0.0.1:80/pub

Response:
----------------
test message

Thank's

**Comment by slact** [comment]
No, you can only configure the format the channel publication metadata (json, yaml, xml, etc.).

**Comment by valydvweb** [comment]
Neither the NGINX directive ?

I tried
return 201 "My Custom Body";

 But no longer send

    location /my-location {
    ...
    ....
    return 201 "My Custom Body";
    }

**Comment by slact** [comment]
I don;t think that will work, then nchan directives take priority over the 'return' directive. Remember, Nginx configs are not a programming environment, but a (qurky) config language.

**Comment by valydvweb** [comment]
Hmmm .... But if I find a solution that does not use return?

**Comment by slact** [comment]
Please let me know, as I don't think this is possible.

**Comment by valydvweb** [comment]
Yes ... You are right ...
Anyway .. Thank's
