### ISSUE TITLE
Resend request

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#177]
Hello,

What is wrong in this experimental case ?

I want to open a WebSocket connection and send a message. This message contains the name of the channel. Initially this model works fine, but $request_body always seems to be the same. 

Where is the mistake? 
Is there another solution?

This is my NGINX conf:
-------------------------------

        # TEST
        location /test {
          nchan_pubsub;
          nchan_channel_id "test";
          nchan_publisher_upstream_request /test-upstream;
        }

        location /test-upstream {
           proxy_pass "http://mydomain.com/send";
           proxy_set_header "X-CHANNEL" "$request_body";
           proxy_set_header Accept "text/json";
        }

        location /send {
            nchan_publisher;
            nchan_channel_id "$http_x_channel";
        }

AND

This this is a test script
-------------------------------

    var cn = new WebSocket('ws://mydomain.com/test');

    cn.onopen = function() {
        console.log('Open test connection');
    }

    function send(channel) {
        console.log('Send to channel ' + channel);
        cn.send(channel); // custom message
    }

    cn.onmessage = function(e) {
        console.log('Receiving test message ' + e.data);
    }
		
</script>

<button onClick="send(1)" type="button">SEND MESSAGE TO CHANNEL 1</button><br />
<button onClick="send(2)" type="button">SEND MESSAGE TO CHANNEL 2</button>

Thank's

**Comment by slact** [comment]
the $request_body variable applies to HTTP requests only. It doesn't process or understand websocket messages.

**Comment by valydvweb** [comment]
OK ... Thank's
