### ISSUE TITLE
"raw forwarder" subscriber mode

### ISSUE THREAD

**Issue by 5lava** [slact/nchan#180]
Hi Leo,

We're currently using [nginx-push-stream-module](https://github.com/wandenberg/nginx-push-stream-module/) to deliver notifications to our iOS and Android application. We're considering switching to nchan.

nchan supports various types of subscriber endpoints (websocket, eventsource, etc.) it but it lacks a pretty simple one — just a "raw forwarder" or "proxy" (not sure if I picked a right name, but I'll explain what I mean below). Without this it doesn't seem possible for us to migrate to nchan (without significant modifications to both our server and client code). I'd appreciate if you could take a look into our case.

Here's our nginx configuration (simplified):
```nginx.conf
push_stream_ping_message_text "\n";

location = /pub {
  push_stream_publisher admin;
  push_stream_channels_path $arg_id;
}

location /sub {
  push_stream_subscriber;
  push_stream_channels_path $arg_id;
  push_stream_ping_message_interval 10;

  gzip on;
}
```

In our iOS app we perform a single(!) HTTP request to the endpoint and then just keep reading from the connection as long as the application is running.

As you can see, the setup is very simple yet powerful — it lets us have:
- HTTP/2.0;
- gzip;
- pings;
- no WebSockets, no other 3rd-party client libraries.

It works like `nchan_subscriber eventsource` yet it transfers data in raw without `id:` and `data:`. It works like `nchan_subscriber chunked` yet it's HTTP/2.0-compatible because `Content-Encoding` isn't `chunked`. It works like `nchan_subscriber websockets` with pings yet it's pure HTTP (gzippable and proxyable). It works like `nchan_subscriber multipart/mixed` yet we control boundary on our side (in our case we transfer JSON and boundary is just `\n`). Subscribers receive exactly the same data that was POST'ed by publishers.

Is a similar setup currently possible with nchan? I'm wondering if I missed something from the documentation. And if not, whether it's possible to add such "raw forwarder" feature.

Thank you very much.

**Comment by slact** [comment]
Hey, you're not the first to ask for this, and at this point it's pretty easy to implement. Pretty sure I can add this to the next release.

**Comment by 5lava** [comment]
Thanks a lot Leo. I look forward for the next release :)

**Comment by notedit** [comment]
+ for this，  i am using  nginx-push-stream-module too,  consider move to nchan.

**Comment by slact** [comment]
(Your wishes are granted)[https://github.com/slact/nchan/tree/http_raw_stream_client] . I'll have this tested and documented shortly. Meanwhile, you can play with it by setting `nginx_subscriber` to `http-raw-stream`

**Comment by 5lava** [comment]
It's not ugly, it's perfect! :) Thank you so much.
Few things though :)
- Something similar to `nchan_websocket_ping_interval` is needed. Apparently `nchan_ping_interval` (and keep `nchan_websocket_ping_interval` as an alias of `nchan_ping_interval` for backward compatibility).
- Something similar to [push_stream_ping_message_text](https://github.com/wandenberg/nginx-push-stream-module/blob/master/docs/directives/main.textile#push_stream_ping_message_text-).
- I couldn't make it work with gzip over HTTP/1.1. But it works perfectly fine with HTTP/2.0. This must have something to do with chunked transfer encoding, which is needed for gzipped streams over HTTP/1.1.

Everything else is awesome, thanks again :)

**Comment by 5lava** [comment]
Hmmm, maybe it would make sense to improve `chunked` mode instead of introducing `http-raw-stream`. Just make `chunked` not really chunked when it's requested with HTTP/2. Also, don't require `TE: chunked` request header if `chunked` is the only argument of `nchan_subscriber `. Not sure about all this.
And btw I couldn't make chunked HTTP/1 stream gzipped too.

**Comment by slact** [comment]
Definitely not going to do "chunked not really chunked" over http2. The chunked subscriber is for low-parsing-overhead clients like embedded devices. IF they speak http2, there's no need for low parsing overhead.

Anyway, I enabled chunked transfer for http-raw-stream client in ca519ec . I'll see what I can do about that ping.

**Comment by 5lava** [comment]
[This](https://github.com/slact/nchan/commit/ca519ec6ad10f1d7aba33eb57dd3982a6d7d5518) was the very first thing I tried to do :) But this neither enables chunked encoding, nor makes gzip work.

**Comment by slact** [comment]
Ok, I'll look into this further.

**Comment by slact** [comment]
I ran through the code and realized that I had disabled gzip for a reason -- using the default gzip module for every message consumes memory, and does not guarantee output when the message is actually published. I need to do gzip encoding + chunking outside the normal output module processing steps, which gets a little complicated. I will have gzip encoding implemented, however I think it will need to wait until a later release. I will probably have this ready and the websocket gzip extension at the same time.

**Comment by 5lava** [comment]
Thank you for your response.

> consumes memory, and does not guarantee output
Just FYI, we've been using nginx-push-stream-module + gzip for last 2 years without any issues. Not sure about memory consumption (never measured as it was never an issue), but I can say for sure that messages are sent (and delivered) immediately after they are published, regardless of message size (even if it's 1 byte).

> it will need to wait until a later release.
Depending on ETA maybe it would make sense to allow using native gzipping optionally?

**Comment by slact** [comment]
I'll check into how the push-stream folks get it done, but out approaches to making Nginx do things it's not supposed to do is pretty different.  I'd say a week or two on an ETA.

**Comment by slact** [comment]
I've release raw stream support in 0.99.15. It does not yet have gzip support, but otherwise works well.

**Comment by 5lava** [comment]
Thanks Leo!
Can't wait for ping and gzip support :)

**Comment by slact** [comment]
Closing this, see  #194 for gzip support info
