### ISSUE TITLE
Memory leak from 0.99.8 in subscribers

### ISSUE THREAD

**Issue by supertong** [slact/nchan#181]
Hi, I have been doing some performance testing using Nchan and planning to use it to our product if it goes well. 
During the test, I have set up around 15000 live connections (SSE with event-stream). I can see the memory goes up a bit when the number of connection are increasing, which make sense to me. However, when I start to publish message, each time I publish the message, the memory goes up a bit (around 30MB in my case). The message is as simple as "Hello World". If I keep doing this, it will eventually runs out of memory and become unresponsive (pub and sub url doesn't response. Other location seems ok.). 
And I can find the error logs show:
```
2016/05/12 08:53:22 [error] 6#0: IPC:got IPC alert delayed by 2 sec
2016/05/12 08:53:22 [error] 8#0: IPC:got IPC alert delayed by 2 sec
2016/05/12 08:53:42 [error] 7#0: IPC:got IPC alert delayed by 22 sec
```
Sometime the worker will get killed.

After I stops the connections, memory will be freed up. I also tried it using Reids on the backend, still the same result. It looks to me that each connection is holding a queue of all the message? Is that true? If that's the case, how do we scale Nchan horizontally?

Thanks in advance!!

**Comment by slact** [comment]
Hey supertong, thanks for your report, looks like you've found a bug. Would you be able to run your tests on Nchan [v0.99.8](https://github.com/slact/nchan/releases/tag/v0.99.8) ?  I suspect this was introduced in the following version as I rewrote much of the message output logic in the following version. Please let me know if you are able to test this, and I will also update this ticket as soon as I have something figured out.

**Comment by slact** [comment]
Nevermind, I've already found and fixed the issue. There's still room for _optimization_, but the leak itself has been fixed in 6292fdb.  Please give the code in master a try.

**Comment by supertong** [comment]
Hey @slact ,

Just tested with the fix and it looks greate so far. Thanks!! May I know when are you going to create a release for it?

![thumbs-8xSnw21AM7OQo](https://camo.githubusercontent.com/39e2cf0094dc38dad8947190b3aafd8d43ae5134/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3878536e773231414d374f516f2f67697068792e676966>)

**Comment by slact** [comment]
: )

I'll have a release sometime next week. I still have a couple of things to squeeze into it.
