### ISSUE TITLE
Question about Close connection

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#184]
Hello,

What are the best ways to handle these situations:
Let's say you have a connection between two clients. 

First client close the connection. (EG: Close web page, etc)
How could it be notified the second client?

Nchan_websocket_ping_interval is useful for this situation?

Thank's
Valy

**Comment by slact** [comment]
Until I get unsubscribe callbacks implemented, there is no convenient way to handle this strictly from within Nchan.

**Comment by valydvweb** [comment]
OK .. and when it will be ready this important update?

**Comment by slact** [comment]
closing this, see #154 for subscribe/unsubscribe callback feature status
