### ISSUE TITLE
Question about per-host connection limits

### ISSUE THREAD

**Issue by edwh** [slact/nchan#186]
I'm still on the old push module but considering upgrading.  One issue I have is that because my application starts long polls, if there are multiple tabs open for my application I hit per-host connection limits in the browser, and the multiple long polls block other requests.

I could potentially work around this, for example by using local storage to signal to other tabs when there is a long poll outstanding, so that only one of my tabs is doing that.  

However before I do that I wanted to check whether any of the other communication mechanisms which nchan supports can be used to bypass the connection limits?  Or do they have the same problem?

**Comment by slact** [comment]
There's no extra mechanism to hande the browser's per-host connection limits. However, as I recall Websockets have a separate connection limit count which is much higher. Also, I think I'm going to solve this problem quite soon (today?) in the [NchanSubscriber.js](https://github.com/slact/nchan/blob/master/NchanSubscriber.js) client using the `storage` event.

**Comment by edwh** [comment]
Could you explain how you're planning to solve it?

**Comment by slact** [comment]
The same way you were planning to, it seems, with a combined use of localStorage and window.addEventListener('storage', ...) events.

**Comment by slact** [comment]
Good news, i got it done in ac29648f437e023fe00fc16c897. It's still experimental, but please try it out and let me know how it works.

**Comment by slact** [comment]
Closing this, the feature is now pretty well-tested.
