### ISSUE TITLE
Invalid memory access when nchan_authorize_request fails

### ISSUE THREAD

**Issue by kneeke** [slact/nchan#191]
The nginx worker segfaults when we try to make a connection to an sse channel.
The segfault only happens when we use nchan_authorize_request, and in case this request returns a 403 status.
In case of no authorize request, or the request returning 200 everything works ok.

I don't know when the issue is introduced, at least with 0.99.6 everything was working as expected.
(somewhere between 0.99.6 and now something went wrong)..

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000041e280 in ngx_pnalloc ()
(gdb) bt
#0  0x000000000041e280 in ngx_pnalloc ()
#1  0x0000000000463e54 in ?? ()
#2  0x00000000004595a0 in ?? ()
#3  0x000000000045b1ec in ngx_http_free_request ()
#4  0x000000000045bdd3 in ?? ()
#5  0x00000000004d53b6 in nchan_respond_status ()
#6  0x00000000004dc8e4 in ?? ()
#7  0x000000000043aafe in ngx_event_expire_timers ()
#8  0x000000000043a72d in ngx_process_events_and_timers ()
#9  0x0000000000442435 in ?? ()
#10 0x0000000000440e4a in ngx_spawn_process ()
#11 0x00000000004426f0 in ?? ()
#12 0x00000000004437bd in ngx_master_process_cycle ()
#13 0x000000000041b7d9 in main ()
```

Example / test config:
```
location ~ /sse/testsub/(one|two)/([0-9]+) {
                nchan_authorize_request /is_authorized2.json;

                nchan_subscriber;
                nchan_channel_id $1_$2;
 }
location ~ /sse/testpub/(one|two)/([0-9]+) {
                nchan_publisher;
                nchan_channel_id $1_$2;
 }

```
Our server is running:
slackware 14.1
kernel 4.1.11
nginx 1.10.1
nchan 0.99.15

**Comment by slact** [comment]
Confirmed. I skipped writing unit tests for this functionality, and let this bug slip through. I'll have it fixed shortly.

**Comment by slact** [comment]
fixed in e5bb4c3 . I'll be adding some unit tests for this, and after that's finished, I'll tag and release a new version including this fix. Please test the code from master, if you could, to see if this indeed resolves your issue.

**Comment by slact** [comment]
added tests in  f21ddf4

**Comment by kneeke** [comment]
Checked, and working again
