### ISSUE TITLE
Deleting a channel disconnects other channels

### ISSUE THREAD

**Issue by joyzheng** [slact/nchan#196]
We're using `nginx=1.9.14-0` and `nchan=0.99.13`, and running into the following scenario: 

Here's the server block of our config:
```
server {
    listen 82;
    server_name test.com;

    location = /sub/a {
        nchan_subscriber;
        nchan_channel_id a/$arg_id;
        nchan_max_channel_subscribers 0;
    }

    location ~ /sub/b {
        nchan_subscriber;
        nchan_channel_id c/$arg_id b/$arg_id;
        nchan_max_channel_subscribers 0;
    }

    location ~ /pub/b/(.*) {
        nchan_publisher;
        nchan_channel_id b/$1;
    }
}
```

If we have separate subscribers on `/sub/a?id=1` and `/sub/b?id=2`, then call `DELETE /pub/b/2`, both are disconnected, whereas I'd only expect that to apply to the second subscriber. This doesn't happen if we replace the line `nchan_channel_id c/$arg_id b/$arg_id;` by `nchan_channel_id b/$arg_id;`.

**Comment by slact** [comment]
Can you tell me what subscriber types you are using?

**Comment by joyzheng** [comment]
Thanks! Looks like it's fixed in the latest version; we'd been using websocket subscribers, so I didn't realize that the deletion bug mentioned in the changelog also applied here.
