### ISSUE TITLE
Redis Cluster support

### ISSUE THREAD

**Issue by slact** [slact/nchan#197]

**Comment by slact** [comment]
@lordnynex : 
> I have a need to use redis cluster support. This cluster (hostname(s)/ports) would be consistent across all nginx locations. In effect the lua persistence scripts that are in the adapter, and the redis connection code itself would need to be aware of the cluster. An ideal solution is using pub/sub patterns to effectively use redis cluster as a network bus, and long term storage of events could happen from external processes doing pattern based subscriptions (PSUBSCRIBE).
This allows nchan to scale horizontally almost indefinitely as it becomes a function of adding additional redis cluster nodes and nginx frontend servers. At present, using a single redis host presents a single point of failure that is uncomfortable for large installations.

**Comment by slact** [comment]
So, I definitely want to get Cluster support up and running, but a fair amount of work is still needed to get there. Here are some things I can think of right away

- Redis server enumeration in upstream {} blocks
- cluster server discovery via cluster-related commands
- encapsulation of server handling logic to deal with several concurrent redis connections.
- channel-id-based key sharding between nodes using key hash tags (for all keys associated with a given channel).
- cluster fragmentation and modification reaction logic.

None of these are _hard_ problems, but at least a few are non-trivial. 

One other thing -- I don't understand your point about using PSUBSCRIBE. What do you mean when you're talking about long-term storage?

**Comment by lordnynex** [comment]
Hi @slact 

I want to participate int his conversation. I'm being pulled in a couple directions for work, but it's on my list to form a more thorough response. I will get back to you ASAP.

**Comment by slact** [comment]
update: I'm working on cluster support in the [redis_cluster](/slact/nchan/tree/redis_cluster) branch. You can already connect and use a wholly enumerated cluster. I still need to add node discovery, error handling, and node reconfiguration logic. And do a lot more testing.

**Comment by slact** [comment]
Cluster reconfiguration and node discovery also works. All that's left is MOVE and ASK error and retry handling.

**Comment by slact** [comment]
@lordnynex : The [redis_cluster](/slact/nchan/tree/redis_cluster) branch is ready for testing. Feel free to play around with it, I'll be merging it into master shortly

**Comment by lordnynex** [comment]
@slact Awesome! I need to write a small build harness for compiling this in. I've got some provisioning code for redis cluster that seems pretty stable. Any particular topologies, scenarios you want to know about?

**Comment by lordnynex** [comment]
@slact Wow, re-reading this thread it appears I've written 2 lengthy updates on this thread and failed to hit the submit button twice. Just a heads up, I will be testing this extensively with openresty. I can include vanilla nginx if you have concerns. 

Next on my wish list is direct integration with ngx_lua :)

**Comment by slact** [comment]
Yeah... too bad github doesn't store comments in git...

Please test with as many topologies as you'd like. Here's how to configure it:
```nginx
upstream redis_cluster {
    nchan_redis_server redis://127.0.0.1:7000;
    nchan_redis_server redis://127.0.0.1:7001;
}
 ```
Any number of nodes in a given cluster is enough to discover and connect to the entire thing. Adding nodes from different clusters to the same upstream block is not handled, and will result in undefined behavior.

to use a cluster in a location:
```nginx
    location ~ /pub/(\w+)$ {
      nchan_redis_pass redis_cluster;
      nchan_publisher;
      nchan_channel_id $1;
      nchan_channel_group redistest;
      #nchan_use_redis on;
    }
```

the `nchan_redis_pass` setting is not inherited by nested blocks unless you also enable `    nchan_redis_pass_inheritable on` (which I'm treating as a debugging option for now)

Note also that the Redis key scheme is not compatible with the pre-cluster one, and I haven't written an import script yet.

**Comment by slact** [comment]
Closing this, I haven't found any cluster-related bugs in the past week of testing. If you find anything, please one another issue.
