### ISSUE TITLE
subscriber callbacks

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#199]
Hello Leo,

I have a question.

How it works subscribe-callbacks (eg: customer close connection)
How can deploy exactly?

Thank's
Valy

**Comment by notedit** [comment]
you can read here  https://github.com/slact/nchan/issues/154

i haven't tested it yet

**Comment by valydvweb** [comment]
OK .. but how it works this update?
What he call and how?

Thank's

**Comment by notedit** [comment]
https://github.com/slact/nchan/commit/44b7c6a8d2b880852f8e7e205a66b1dc7267a016

there is some exmple in the code

**Comment by slact** [comment]
The code is currently working for websocket only, other subscribers are not yet implemented

**Comment by valydvweb** [comment]
ok .. thank's

**Comment by slact** [comment]
This feature has been implemented and is currently in master. It'll be available in the next release.
