### ISSUE TITLE
Question about Ping Interval

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#202]
Hello Leo,

I have a question about "nchan_websocket_ping_interval" directive.
How is working this mechanism? 
What calls?

I can call a request after N seconds? 
If so how?

Thank's
Valy

**Comment by slact** [comment]
`nchan_websocket_ping_interval num_sec;

Enabling this will send a [PING frame](https://tools.ietf.org/html/rfc6455#section-5.5.2) to the websocket subscriber every *num_sec* seconds. If the client fails to respond with a [PONG frame](https://tools.ietf.org/html/rfc6455#section-5.5.3), it is disconnected.

**Comment by jeverling** [comment]
Will the client in `NchanSubscriber.js` try to reconnect in that case?

**Comment by slact** [comment]
Yes, as long as the instance's `reconnect` property is true (which is the default).

**Comment by jeverling** [comment]
Thank you! And also many thanks for nchan! It's an amazing piece of work!
