### ISSUE TITLE
The $nchan_subscriber_type variable is not set

### ISSUE THREAD

**Issue by ayedo** [slact/nchan#203]
First of all: Thanks for your great work. I have really enjoyed working with Nchan so far!

I have the following configuration:

    server {
        listen 80;
     
        location = /authorize {
          proxy_pass http://api/authorize;
          proxy_pass_request_body off;
          proxy_set_header Content-Length "";
          proxy_set_header X-Channel-Id $nchan_channel_id;
          proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
        }

        location ~ /channel/(\w+)$ {
          nchan_pubsub;
          nchan_channel_id $1;
          nchan_authorize_request /authorize;
        }

      }

My problem: The X-Subscriber-Type is not set in the header. The X-Channel-Id is. Can you spot my mistake? I would expect either "subscribe" or "publish".

I'm using nginx version: 1.11.2, and nchan version: 0.99.16.

**Comment by slact** [comment]
For a pubsub location, you should also use the $nchan_publisher_type variable:

```nginx
server {
    listen 80;

    location = /authorize {
      proxy_pass http://api/authorize;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Channel-Id $nchan_channel_id;
      proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
      proxy_set_header X-Publisher-Type $nchan_publisher_type;
    }

    location ~ /channel/(\w+)$ {
      nchan_pubsub;
      nchan_channel_id $1;
      nchan_authorize_request /authorize;
    }

  }

```


I've just noticed, by the way, that  `$nchan_publisher_type` isn't in the documentation. I'll fix that shortly.

**Comment by slact** [comment]
Documentation updated.

**Comment by ayedo** [comment]
Thanks for your help and quick reply!
