### ISSUE TITLE
Subscriber receives messages from all channels.

### ISSUE THREAD

**Issue by MisterFlix** [slact/nchan#204]
Hello,

Because I'm mostly a noob when it comes to establishing an open connection with an address, I used the 'NchanSubscriber.js'. It works perfectly fine! Except it receives every message twice. 
When I later began experimenting with different channel IDs, I discovered that apparently every subscriber subscribed to every channel and then additionally to the channel(s) it is supposed to. For example, with one sub open to the channel 'foo', the channel 'foo' has 2 subscribers, and 'bar' has 1.

My nginx configuration is this:
```
        location = /push_tut/receive.html {
                nchan_subscriber;
                nchan_subscriber_first_message newest;
                nchan_channel_id = $arg_c;
        }

        location = /push_tut/send.html {
                nchan_publisher;
                nchan_channel_id = $arg_c;
        }
```

**Comment by slact** [comment]
Nchan thinks you want to publish to channels $arg_c and "=", and subscribe to the same. Get rid of that equal sign in `nchan_channel_id = $arg_c`, that should do it.

**Comment by MisterFlix** [comment]
Welp, looks like I should have read the documentation more closely. Thanks a lot, it works now!
