### ISSUE TITLE
Is there any limitation on the number of channels?

### ISSUE THREAD

**Issue by iNDicat0r** [slact/nchan#206]
Hi

I was wondering if it's possible to have channels based on a unique id..I saw that you are using ip of the client in one of your examples, so instead of ip I should lets say use a md5 hash from users email address. Can nchan handle this? Any limitations on the numbers?

**Comment by slact** [comment]
You can create as many channels as you want. For very large numbers, be sure to increase the `nchan_max_reserved_memory` value (default 32Mb). You can also set the maximum channel id length with `nchan_max_channel_id_length` (default 512);

**Comment by iNDicat0r** [comment]
Amazing, thanks Leo.

**Comment by slact** [comment]
You're quite welcome. Let me know if you have any more questions.
