### ISSUE TITLE
nchan_subscriber_first_message "newest" behaves more like "future"

### ISSUE THREAD

**Issue by rikur** [slact/nchan#207]
nchan doesn't send SSE subscribers the newest messages when nchan_subscriber_first_message is set to "newest", rather all the "future" messages from then on.

I would actually have a use-case for the "newest": I want new subscribers to receive the latest SSE message when they connect, without having to wait for a "future" message to get up to speed. These subscribe don't know the pub channel(and receive messages from many channels), so they can't query for the last message either.

**Comment by rikur** [comment]
Behaviour seems to be the same with WebSockets.

**Comment by slact** [comment]
I think you're right, "newest" is indeed a misnomer. I am going to expand this setting to accept numbers, that is, "nth newest message". So the equivalent of the functionality you want would be 
`nchan_subscriber_first_message 1`

The next release is dedicated mostly to redis features (mainly cluster support and some bugfixes), but I'll see if I can squeeze this one into it as well. It's been on my list for some time.

**Comment by rikur** [comment]
I like the idea of being able to request N newest messages. Also, please give the value "future" some thought before you commit to it, it was just the first one that came in to my mind :)

**Comment by slact** [comment]
Implemented in 4d6aae1b58fcd458. I've decided to keep 'newest' defined as is for backwards compatibility.
