### ISSUE TITLE
nchan and beanstalk

### ISSUE THREAD

**Issue by iotch** [slact/nchan#210]
Hello.
I'm sorry for the maybe stupid question, but is it possible to pub/sub from/to beanstalk queue directly somehow without using any interlayer?
thanks!

**Comment by slact** [comment]
There's no way to do this at the moment. I'm curious though, why would you want this?

**Comment by iotch** [comment]
We are using queues with php, and will be great to have a bidirectional websocket communication without having to write a websocket php client. 
But looking at the docs now, the `nchan_publisher_upstream_request` is may be what we need?

**Comment by slact** [comment]
That's the hook you'd want to use to mirror published messages via your application.

**Comment by iotch** [comment]
thanks!
