### ISSUE TITLE
Subscribers to multiplexed channels stop after receiving message from 0-buffer channel

### ISSUE THREAD

**Issue by willkelleher** [slact/nchan#212]
I'm using nchan with a websocket subscriber endpoint and two different HTTP publisher endpoints.  The difference between the publishers is the `nchan_message_buffer_length` setting.  Here is an example snippet of my config:

```nginx
# persistent publishes
location ~ /pub/(\w+)/(\w+)$ {
    nchan_publisher;
    nchan_channel_id "$1_$2";
    nchan_message_buffer_length 1;
    nchan_message_timeout 0;
}

# transient publishes
location ~ /pub/0/(\w+)/(\w+)$ {
    nchan_publisher;
    nchan_channel_id "$1_$2";
    nchan_message_buffer_length 0;
    nchan_message_timeout 0;
}

# all subscribers
location /sub/ws {
    nchan_subscriber;
    nchan_channel_id "$args";
    nchan_channel_id_split_delimiter ",";
}
```

I then subscribe via websocket to an address like `ws://localhost/sub/ws?fruit_banana,fruit_apple`.

If I publish via POST to `http://localhost/pub/fruit/banana`, the subscriber sees the data.  I can continue to POST updates and the subscriber will get them.

If I then publish via POST to `http://localhost/pub/0/fruit/apple`, the subscriber sees the data, but a subsequent POST to the first endpoint (`http://localhost/pub/fruit/banana`) no longer forwards the message the the subscriber.

I added another websocket subscriber to listen to the internal events and I see the following sequence:

1. Subscribe
> event: subscriber_enqueue fruit_banana

2. POST "banana" to `http://localhost/pub/fruit/banana`
> msg: banana
> event: channel_publish fruit_banana

3. POST "apple" to `http://localhost/pub/0/fruit/apple`
> msg: apple
> event: subscriber_enqueue fruit_banana
> event: channel_publish fruit_apple

4. POST "banana" to `http://localhost/pub/fruit/banana`
> event: channel_publish fruit_apple
_but no MSG is received_

5. POST "apple" to `http://localhost/pub/0/fruit/apple`
> msg: apple
> event: subscriber_enqueue fruit_banana
> event: channel_publish fruit_apple

The repeating `subscriber_enqueue fruit_banana` messages seem a little strange, too.

I am running nginx 1.9.15 with nchan 0.99.16.  I also experienced this with nchan 0.99.10.

**Comment by willkelleher** [comment]
Note that this problem does not occur if both publish endpoints have `nchan_message_buffer_length 1;`

**Comment by slact** [comment]
Confirmed, will fix shortly.

**Comment by slact** [comment]
fixed in master (c3975404c88ce7da, bf179eceb6467, test in 186693a). Please verify if you can.

**Comment by willkelleher** [comment]
Looks good, thanks!

**Comment by slact** [comment]
Ok, thanks for your bug report. This fix will be included in the next release.
