### ISSUE TITLE
Best way to get the channel id?

### ISSUE THREAD

**Issue by roneron** [slact/nchan#213]
Great project you have here. I have a question though. When a long-polling client is subscribed to multiple channels over a single connection (like server/sub/foo,bar,baz), what is the best way for him to determine which channel he just received a message from? Is it inevitable to include the channel id in the message itself, or is there something else I'm missing?

**Comment by slact** [comment]
A subscriber has no way of knowing which channel a message came from if it
subscribed on a multiplexed channel endpoint.This was a design decision
I made pretty early on. If you need the subscriber to know what channel
a message was published to, you should include it in the message body in
a way your subscriber can parse.

That is, it's pretty easy to add this data at the time of message
publication to the message, so Nchan doesn't offer this functionality.

The one 'exception' to this is that you can use EventSource event types to send the channel name along with the message. The `event:` field can be set when publishing by setting the
`X-EventSource-Event:` header on the publisher's POST request. In this case, you can set it to the channel id being published to (see
https://nchan.slact.net/#nchan_eventsource_event ). Of course, this is only useful for EventSource subscribers.

**Comment by roneron** [comment]
I see, thanks for clearing this up for me!
