### ISSUE TITLE
Error compile - last version

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#215]
Hello Leo,

This is error, occurred during compilation:
My NGINX version is 1.10.1

cc1: warnings being treated as errors
/root/nchan/src/store/memory/memstore.c: In function 'chanhead_find_next_message':
/root/nchan/src/store/memory/memstore.c:1694: error: 'prev' may be used uninitialized in this function
make[1]: *** [objs/addon/memory/memstore.o] Error 1
make[1]: Leaving directory `/root/nginx-1.10.1'
make: *** [build] Error 2

Thank's
Valy

**Comment by slact** [comment]
Ah, this warning shows on gcc5, but not with gcc6. Fixed anyway in 052409d.
