### ISSUE TITLE
'active subscribers' count incorrect

### ISSUE THREAD

**Issue by brunoqc** [slact/nchan#216]
I only have 1 client for one channel but I see 64 subscribers. 

I'm not sure how to debug this. There's almost no traffic for this channel in the access log.

nginx-1.11.3
nchan v0.99.16

```
$ curl https://<host>/pub/<channel>
queued messages: 2
last requested: -1 sec. ago
active subscribers: 64
last message id: 0
```

**Comment by slact** [comment]
Config please?

**Comment by brunoqc** [comment]
```
    location ~ /sub/(\w+)$ {
        nchan_subscriber;
        nchan_message_buffer_length 1;
        nchan_channel_id $1; #first capture of the location match
    }

    location ~ /pub/(\w+)$ {
        nchan_publisher;
        nchan_channel_id $1; #first capture of the location match
        nchan_message_buffer_length 1;
        nchan_message_timeout 0;
    }
```

**Comment by brunoqc** [comment]
I don't know if it's related but I updated nginx today to 1.11.3 and I have a high cpu load (I don't know if it's related to nchan).

**Comment by slact** [comment]
I need more config -- specifically number of workers and whether redis is being used. As for high CPU load, if it persists and seems to you nchan-related, open another ticket.

**Comment by brunoqc** [comment]
worker_processes 2;
worker_rlimit_core  1024M;
nchan_use_redis on;

**Comment by slact** [comment]
One more thing: what kind of subscriber client are you using (longpoll/websocket/etc)?

**Comment by brunoqc** [comment]
websocket in that case I think. I'll confirm tomorrow.

**Comment by brunoqc** [comment]
yep, websocket.

**Comment by slact** [comment]
Ok, thanks. I haven't been able to reproduce this so far, still working on it.

**Comment by slact** [comment]
Still haven't been able to reproduce this, unfortunately. Have you found any consistent pattern to when this happens?

**Comment by brunoqc** [comment]
No I didn't really tried. Right now it seems fine but I restarted nginx recently. I'll set a reminder to check tomorrow or later.

**Comment by brunoqc** [comment]
I won't be able to test this. I'm not using nchan anymore. Thanks a lot for the support.

**Comment by slact** [comment]
Ok, thanks for your bug reports and helping with Nchan development. Hope you've found a more fitting tool for your needs. I'll keep this open in case anyone else experiences this issue.

**Comment by acritox** [comment]
I think I might be experiencing the same bug:

```
Wed Oct  5 21:07:11 CEST 2016   count: 130
Wed Oct  5 21:07:14 CEST 2016   count: 131
Wed Oct  5 21:07:16 CEST 2016   count: 132
Wed Oct  5 21:07:19 CEST 2016   count: 131
Wed Oct  5 21:07:21 CEST 2016   count: 72
Wed Oct  5 21:07:22 CEST 2016   count: 131
Wed Oct  5 21:07:24 CEST 2016   count: 132
Wed Oct  5 21:07:25 CEST 2016   count: 133
Wed Oct  5 21:07:28 CEST 2016   count: 134
Wed Oct  5 21:07:29 CEST 2016   count: 132
Wed Oct  5 21:07:35 CEST 2016   count: 135
Wed Oct  5 21:07:37 CEST 2016   count: 74
Wed Oct  5 21:07:38 CEST 2016   count: 134
Wed Oct  5 21:07:39 CEST 2016   count: 135
Wed Oct  5 21:07:40 CEST 2016   count: 136
Wed Oct  5 21:07:42 CEST 2016   count: 75
Wed Oct  5 21:07:43 CEST 2016   count: 135
Wed Oct  5 21:07:49 CEST 2016   count: 136
Wed Oct  5 21:07:50 CEST 2016   count: 138
Wed Oct  5 21:07:53 CEST 2016   count: 137
Wed Oct  5 21:07:54 CEST 2016   count: 138
Wed Oct  5 21:07:55 CEST 2016   count: 137
Wed Oct  5 21:07:57 CEST 2016   count: 136
Wed Oct  5 21:08:00 CEST 2016   count: 137
Wed Oct  5 21:08:09 CEST 2016   count: 136
Wed Oct  5 21:08:12 CEST 2016   count: 137
Wed Oct  5 21:08:13 CEST 2016   count: 138
Wed Oct  5 21:08:19 CEST 2016   count: 139
Wed Oct  5 21:08:20 CEST 2016   count: 77
Wed Oct  5 21:08:21 CEST 2016   count: 138
```

it 'jumps' around +/- 64 subscribers sometimes for no apparent reason for a few seconds

**Comment by slact** [comment]
What kind of subscribers are you using? If it's long-polling, the subscriber count will fluctuate after every response.

**Comment by slact** [comment]
Fixing #289 should have fixed this as well.
