### ISSUE TITLE
Question about nchan_channel_events_channel_id and bug reporting

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#217]
Hello Leo,

"nchan_channel_events_channel_id" directive, can be used to WebSocket connection?
I tried to add (for testing) but I encountered the following error:

[ error.log ]
ker process: /root/nchan/src/store/redis/rdsstore.c:1461: chanhead_redis_create: Assertion `channel_id->data[0]!='m'' failed.
2016/08/10 22:01:31 [alert] 25295#0: worker process 25306 exited on signal 6 (core dumped)

My test conf:
------------------
```nginx
      location ~ "^\/my\-location$" {

            internal;
            nchan_pubsub;

            nchan_publisher_upstream_request "/my-upstream";
            nchan_publisher_channel_id "x" "y";
            nchan_subscriber_channel_id "y";
            nchan_message_buffer_length 30;
            nchan_message_timeout 1m;
            nchan_subscriber_first_message newest;
            nchan_channel_events_channel_id "test";
        }
```
Thank's,
Valy

**Comment by slact** [comment]
Fixed. This was a problem in some of the new code I merged into master earlier today. Thanks for reporting it.

**Comment by valydvweb** [comment]
No errors .. for this time
But .. no received (any) messages on "test" channel

**Comment by slact** [comment]
to access the events channel, use the 'meta' channel group:

```nginx
    location ~ /events {
      nchan_subscriber;
      nchan_channel_group meta;
      nchan_channel_id test;
    }
```

**Comment by valydvweb** [comment]
now is very good

Thank's
