### ISSUE TITLE
Error compile - last version

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#221]
Hi Leo,

I try to compile last version and ...

cc1: warnings being treated as errors
/root/nchan/src/store/redis/rdsstore.c: In function 'redisChannelFindCallback':
/root/nchan/src/store/redis/rdsstore.c:1809: error: 'rdata' may be used uninitialized in this function
/root/nchan/src/store/redis/rdsstore.c: In function 'redisChannelDeleteCallback':
/root/nchan/src/store/redis/rdsstore.c:1763: error: 'rdata' may be used uninitialized in this function
make[1]: *** [objs/addon/redis/rdsstore.o] Error 1
make[1]: Leaving directory `/root/nginx-1.10.1'
make: *** [build] Error 2

Thank's,
Valy

**Comment by slact** [comment]
fixed in  21814e8
