### ISSUE TITLE
HTML5 WebSocket and nchan_websocket_ping_interval

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#222]
Hello again,

The directive "nchan_websocket_ping_interval" may have some utility if I use HTML5 WebSocket?

E.g:

When the client close connection or leave the page  I can know this , using "nchan_channel_event". 

BUT if the connection is lost or isn't normal closed?
What is the best method to manage this problem?

Thank's,
Valy

**Comment by slact** [comment]
An abnormally terminated connection still produces a channel event. The `nchan_websocket_ping_interval` is only for sending Websocket PING / PONG frames.

**Comment by valydvweb** [comment]
OK , but if the connection is lost (for a long time) ?

**Comment by slact** [comment]
It doesn't make a difference. When a subscriber connection terminates, an unsubscribe event is produced.

**Comment by valydvweb** [comment]
Mmmm .. I'm not sure about that.
I have tested, interrupting the internet connection and the event has not been called.

**Comment by slact** [comment]
Ok, I'll double-check.

**Comment by valydvweb** [comment]
any progress?

**Comment by slact** [comment]
Not yet, I haven't had time. Will look into this and your other issue later this evening.

**Comment by slact** [comment]
Ok, fixed in  d7cb0ea . 

One thing I should have noted is that "interrupting" a connection is not the same as "abnormally terminating" it. Interrupted TCP connections are still considered valid, and unless the `so_keepalive` parameter is specified for the nginx `listen` directive, may stay open indefinitely (or however long the OS thinks it should be). See https://serverfault.com/questions/181724/is-it-possible-to-configure-nginx-to-send-tcp-keepalive for details.

**Comment by valydvweb** [comment]
Is perfect.

One last question:

A lower value of ping interval (e,g: 10 seconds), can affect " load average " ?
(where many customers are online)

This question may seem strange ... but  .. it's still important

Thank's

**Comment by slact** [comment]
> A lower value of ping interval (e,g: 10 seconds), can affect " load average " ?
(where many customers are online)

I just did a benchmark, and with 4 workers and 10K websocket subscribers subscribed to 1 channel I see an average CPU load of:
  with ping interval of 5s, 2-5% per worker
  with ping interval of 20s: mostly 0%, 1.5% every 10s or so.

**Comment by valydvweb** [comment]
Thank's :)
