### ISSUE TITLE
Buffer length changing

### ISSUE THREAD

**Issue by supertong** [slact/nchan#224]
Hey, you might find this background description looks familiar, I just copied it from the other PR.

### Background
I am using Nchan to serve messages which have two types - snapshot and delta. The message queue looks like
```
snapshot1 - delta1 - delta1 - delta1 - delta1 - snapshot2 - delta2 ...
```
The requirement is that when a new subscriber connected, Nchan only serve user with the latest snapshot following by deltas. In above example, it will serve user with
```
snapshot2 - delta2...
```
I am able to achieve this functionality through following config
```nginx
server {
    listen 80;
    location = /pub/snapshot {
      nchan_publisher;
      nchan_channel_group test;
      nchan_channel_id test-streaming-data;
      nchan_message_buffer_length 1;
    }

    location = /pub/delta {
      nchan_publisher;
      nchan_channel_group test;
      nchan_channel_id test-streaming-data;
      nchan_message_buffer_length 1000;
    }
  }
```

### Problems
I noticed sudden connection drops some times and find a lots of errors in log like following.
```
 2016/08/17 01:33:59 [error] 6#0: NCHAN MSG_ID:verify_msg_id: not a multimsg tag, different times. could be a missed message.
 2016/08/17 01:33:59 [error] 6#0: NCHAN MSG_ID:missed a message for an unknown reason. Maybe it's a bug or maybe the message queue length is too small.
 2016/08/17 01:33:59 [error] 6#0: NCHAN MSG_ID:verify_msg_id: not a multimsg tag, different times. could be a missed message.
 2016/08/17 01:33:59 [error] 6#0: NCHAN MSG_ID:missed a message for an unknown reason. Maybe it's a bug or maybe the message queue length is too small.
```
I can understand how this error happens because I update the buffer length to be 1 and previous message has been removed which causes the `sub->last_msgid != msg->prev_id` for some subscribers. However, I don't quite understand how this contribute to connection dropping? It's like whole bunch of connection drops at same time.
I am going to increase the snapshot buffer length to be a bigger value, like 5 and see if it will reduce the error rate. Do you have any better suggestions?

Thanks

**Comment by slact** [comment]
I'm not sure what's causing the connection drops. Can you post your nginx config, as well as what clients you're using?

(The missed-message error can be ignored in this case, but I may also have a way to suppress it in this situation)

**Comment by supertong** [comment]
Here is the config
```
daemon off;
worker_processes 1;
worker_rlimit_nofile 50000;

http {

  log_format combined_xforwardfor '$remote_addr $http_x_forwarded_for - $remote_user [$time_local] '
                                  '"$request" $status $body_bytes_sent '
                                  '"$http_referer" "$http_user_agent" $request_time ';
  access_log /var/log/nginx/access.log combined_xforwardfor buffer=16k;

  nchan_use_redis on;
  nchan_redis_url xxx:6379;
  nchan_max_reserved_memory 1024M;
  nchan_subscriber_timeout 3600;
  nchan_max_channel_subscribers 40000;

  server {
    listen 80;

    location ~* ^/ {
      return 200;
    }

    location = /live-data/sub {
      nchan_subscriber;
      nchan_channel_group scores;
      nchan_channel_id live-data;
    }
  }

  server {
    listen 81;
    location = /live-data/pub/snapshot {
      nchan_publisher;
      nchan_channel_group scores;
      nchan_channel_id live-data;
      nchan_message_buffer_length 1;
    }

    location = /live-data/pub/delta {
      nchan_publisher;
      nchan_channel_group scores;
      nchan_channel_id live-data;
      nchan_message_buffer_length 1000;
    }
  }
}

events {
  worker_connections 41000;
}

```
And we are using Event Source.
Giving you more info here, we only set `worker_process = 1` because we thought the dropping is related to IPC and after we set it to 1, the dropping happens less often. When I test redis with two Nchan instance (each with only 1 worker) this morning, the dropping happens more often again.

**Comment by supertong** [comment]
By the way, all dropped connection have a 204 code, which seems like it's closed gracefully?

**Comment by supertong** [comment]
I think this debug info can be helpful
```
 2016/08/17 06:38:16 [error] 6#0: SPOOL:00005562FF54E2A8 fetch msg 1471415859:0 for channel vision/vision-live-data
 2016/08/17 06:38:16 [error] 6#0: SPOOL:fetchmsg callback for spool 00005562FF54E2A8 msg FOUND 00007F91826C3C00 1471415890:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:spool 00005562FF54E2A8 (1471415859:0) (subs: 1) respond with msg 00007F91826C3C00 or code 0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:msgid: 1471415890:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:prev: 1471415859:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:remove spool node 00005562FF54E280
 2016/08/17 06:38:16 [error] 6#0: SPOOL:destroy spool node 00005562FF54E280
 2016/08/17 06:38:16 [error] 6#0: SPOOL:spool 00005562FAA908C8 (1471415890:0) (subs: 7677) respond with msg 0000000000000000 or code 204
 2016/08/17 06:38:16 [error] 6#0: SPOOL:00005562FF550A68 fetch msg 0:0 for channel vision/vision-live-data
 2016/08/17 06:38:16 [error] 6#0: SPOOL:fetchmsg callback for spool 00005562FF550A68 msg FOUND 00007F91826C4400 1471415769:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:spool 00005562FF550A68 (0:0) (subs: 1) respond with msg 00007F91826C4400 or code 0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:msgid: 1471415769:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:prev: 1471415660:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:00005562FF550A68 fetch msg 1471415769:0 for channel vision/vision-live-data
 2016/08/17 06:38:16 [error] 6#0: SPOOL:fetchmsg callback for spool 00005562FF550A68 msg FOUND 00007F91826C3000 1471415799:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:spool 00005562FF550A68 (1471415769:0) (subs: 1) respond with msg 00007F91826C3000 or code 0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:msgid: 1471415799:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:prev: 1471415769:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:00005562FF550A68 fetch msg 1471415799:0 for channel vision/vision-live-data
 2016/08/17 06:38:16 [error] 6#0: SPOOL:fetchmsg callback for spool 00005562FF550A68 msg FOUND 00007F91826C3400 1471415830:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:spool 00005562FF550A68 (1471415799:0) (subs: 1) respond with msg 00007F91826C3400 or code 0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:msgid: 1471415830:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:prev: 1471415799:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:00005562FF550A68 fetch msg 1471415830:0 for channel vision/vision-live-data
 2016/08/17 06:38:16 [error] 6#0: SPOOL:fetchmsg callback for spool 00005562FF550A68 msg FOUND 00007F91826C3800 1471415859:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:spool 00005562FF550A68 (1471415830:0) (subs: 1) respond with msg 00007F91826C3800 or code 0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:msgid: 1471415859:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:prev: 1471415830:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:00005562FF550A68 fetch msg 1471415859:0 for channel vision/vision-live-data
 2016/08/17 06:38:16 [error] 6#0: SPOOL:fetchmsg callback for spool 00005562FF550A68 msg FOUND 00007F91826C3C00 1471415890:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:spool 00005562FF550A68 (1471415859:0) (subs: 1) respond with msg 00007F91826C3C00 or code 0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:msgid: 1471415890:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:prev: 1471415859:0
 2016/08/17 06:38:16 [error] 6#0: SPOOL:remove spool node 00005562FF550A40
 2016/08/17 06:38:16 [error] 6#0: SPOOL:destroy spool node 00005562FF550A40
 2016/08/17 06:38:16 [error] 6#0: SPOOL:spool 00005562FAA908C8 (1471415890:0) (subs: 7678) respond with msg 0000000000000000 or code 204
 2016/08/17 06:38:16 [error] 6#0: SPOOL:sub 00005562FF550700 dequeue callback
 2016/08/17 06:38:16 [error] 6#0: SPOOL:sub 00005562FF54B780 dequeue callback
 2016/08/17 06:38:16 [error] 6#0: SPOOL:sub 00005562FF541880 dequeue callback
 2016/08/17 06:38:16 [error] 6#0: SPOOL:sub 00005562FF53C900 dequeue callback
```
It seems like some times the `spool_respond_general` will be NULL message with code 204 and close all the connections.

**Comment by supertong** [comment]
I think this part of the log helps me narrow down to one piece of code
```
 2016/08/17 06:37:39 [error] 6#0: SPOOL:spool 00005562FAA908C8 (1471415830:0) (subs: 7119) respond with msg 0000000000000000 or code 204
 2016/08/17 06:37:39 [error] 6#0: SPOOL:spool 00005562FAA908C8 (1471415830:0) (subs: 7119) respond with msg 00007F91826C3800 or code 0
 2016/08/17 06:37:39 [error] 6#0: SPOOL:msgid: 1471415859:0
 2016/08/17 06:37:39 [error] 6#0: SPOOL:prev: 1471415830:0
 2016/08/17 06:37:39 [error] 6#0: SPOOL:00005562FAA908C8 fetch msg 1471415859:0 for channel vision/vision-live-data
 2016/08/17 06:37:39 [error] 6#0: SPOOL:fetchmsg callback for spool 00005562FAA908C8 msg EXPECTED
 2016/08/17 06:37:39 [error] 6#0: SPOOL:spool 00005562FAA908C8 (1471415859:0) (subs: 7119) respond with msg 0000000000000000 or code 204
```
spool `00005562FAA908C8` has `msg EXPECTED` and then it sends 204 to all subscribers. It shall be in this part of the code
```
  switch(findmsg_status) {
    case MSG_FOUND:
      spool->msg_status = findmsg_status;
      DBG("fetchmsg callback for spool %p msg FOUND %p %V", spool, msg, msgid_to_str(&msg->id));
      assert(msg != NULL);
      spool->msg = msg;
      spool_respond_general(spool, spool->msg, 0, NULL, 0);

      spool_nextmsg(spool, &msg->id);
      break;

    case MSG_EXPECTED:
      // ♫ It's gonna be the future soon ♫
      if(spool->id.time == NCHAN_NTH_MSGID_TIME) {
        //wait for message in the NEWEST_ID spool
        nchan_msg_id_t  newest_id = NCHAN_NEWEST_MSGID;
        spool_nextmsg(spool, &newest_id);
      }
      else {
        spool->msg_status = findmsg_status;
        DBG("fetchmsg callback for spool %p msg EXPECTED", spool);
        spool_respond_general(spool, NULL, NGX_HTTP_NO_CONTENT, NULL, 0);
        assert(msg == NULL);
        spool->msg = NULL;
      }
      break;
```
I think responding with NGX_HTTP_NO_CONTENT somehow close the EventSource connection?

**Comment by supertong** [comment]
Not sure if it's a coincident, all 204 response are followed by dequeue callbacks like
```
 2016/08/17 07:51:37 [error] 5#0: SPOOL:spool 0000561B7C0451A8 (1471420205:0) (subs: 5775) respond with msg 0000000000000000 or code 204
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F1FA2A0 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F1FCA60 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F1FF220 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F2019E0 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F2041A0 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F206960 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F209120 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F20B8E0 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F20E0A0 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F210860 dequeue callback
 2016/08/17 07:51:38 [error] 5#0: SPOOL:sub 0000561B7F213020 dequeue callback
```

**Comment by slact** [comment]
The 204 is a way to fool Nginx to keep the connections open, I don't think it has anything to do with anything. It's those dequeues I need to look at. Is there a test script you are using that I could run? If not, could you describe steps to reproduce this?

**Comment by slact** [comment]
I haven't found a way to reproduce this so far. Here's my (sloppy) test for it, uising the Nchan test harness:

```def test_changing_buffer_length_more
    chan = short_id
    sub = Subscriber.new url("sub/broadcast/#{chan}"), 500, client: :eventsource, quit_message: 'FIN'
    sub.on_failure do |resp|
      puts "sub FAILURE!"
      false
    end
    pub_delta = Publisher.new url("/pub/#{chan}")
    pub_snapshot = Publisher.new url("/pub_1message/#{chan}")
    
    sub.run
    sleep 10
    for i in (1...10000) do
      pub_snapshot.messages.clear
      pub_delta.messages.clear
      sub.messages.clear
      for j in (1..50) do
        pub_delta.post ["#{j}foo#{i}" "#{j}bar#{i}" "#{j}baz#{i}" "#{j}bzzzt#{i}"]
      end
      
      pub_snapshot.post ["blah#{i}" "anotherblah#{i}"]
      
      pub_snapshot.post "this is the real thing right here#{i}"
      
      pub_delta.post ["d1#{i}" "d2#{i}" "d3#{i}" "and_other_deltas#{i}" ]
    end
    pub_delta.post "FIN"
    sub.wait
  end
```

Maybe the publishing rate is too low, or maybe it's something else. How are you reproducing this?

**Comment by supertong** [comment]
Hey, thanks for looking into it. Haven't had time for this yesterday, will update you with more info today.

**Comment by supertong** [comment]
I think those connections are closed with `sudden_abort_handler` called.
```
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:sudden_abort_handler: sub_status: 0, dequeue_after_response: 0, destroy_after_dequeue: 1
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1B9BC80 dequeue
 2016/08/19 02:17:56 [error] 7#0: SPOOL:sub 00005584C1B9BC80 dequeue callback, status = 1, dequeue_after_response = 0
 2016/08/19 02:17:56 [error] 7#0: SPOOL:spool 00005584C1B5B1A8 , sub_count 19, msg_status: 6
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1B9BC80 destroy for req 00005584C1BA8D30
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:sudden_abort_handler: sub_status: 0, dequeue_after_response: 0, destroy_after_dequeue: 1
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1BA29C0 dequeue
 2016/08/19 02:17:56 [error] 7#0: SPOOL:sub 00005584C1BA29C0 dequeue callback, status = 1, dequeue_after_response = 0
 2016/08/19 02:17:56 [error] 7#0: SPOOL:spool 00005584C1B5B1A8 , sub_count 18, msg_status: 6
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1BA29C0 destroy for req 00005584C1B5B270
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:sudden_abort_handler: sub_status: 0, dequeue_after_response: 0, destroy_after_dequeue: 1
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1BA2B60 dequeue
 2016/08/19 02:17:56 [error] 7#0: SPOOL:sub 00005584C1BA2B60 dequeue callback, status = 1, dequeue_after_response = 0
 2016/08/19 02:17:56 [error] 7#0: SPOOL:spool 00005584C1B5B1A8 , sub_count 17, msg_status: 6
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1BA2B60 destroy for req 00005584C1BABD90
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:sudden_abort_handler: sub_status: 0, dequeue_after_response: 0, destroy_after_dequeue: 1
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1B9C560 dequeue
 2016/08/19 02:17:56 [error] 7#0: SPOOL:sub 00005584C1B9C560 dequeue callback, status = 1, dequeue_after_response = 0
 2016/08/19 02:17:56 [error] 7#0: SPOOL:spool 00005584C1B5B1A8 , sub_count 16, msg_status: 6
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1B9C560 destroy for req 00005584C1BB4EB0
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:sudden_abort_handler: sub_status: 0, dequeue_after_response: 0, destroy_after_dequeue: 1
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1B9EE40 dequeue
 2016/08/19 02:17:56 [error] 7#0: SPOOL:sub 00005584C1B9EE40 dequeue callback, status = 1, dequeue_after_response = 0
 2016/08/19 02:17:56 [error] 7#0: SPOOL:spool 00005584C1B5B1A8 , sub_count 15, msg_status: 6
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:00005584C1B9EE40 destroy for req 00005584C1BBDFD0
 2016/08/19 02:17:56 [error] 7#0: SUB:LONGPOLL:sudden_abort_handler: sub_status: 0, dequeue_after_response: 0, destroy_after_dequeue: 1
```

In what situation will `sudden_abort_handler` be called?

**Comment by supertong** [comment]
**New Findings**: I think I am looking at the wrong place. It has nothing to do with the buffer length change.

We are using AWS ELB in front of Nchan, and ELB has a connection idle timeout with 60 seconds. When I change the idle timeout to 3600 seconds, the connection drops does not happen again, at least before the time reaches 3600 seconds. I want to confirm my findings so I change the idle timeout back to 60 seconds and restart the test. This time I have a stopwatch (my phone 😄 ) with me. When the stopwatch reaches 60 seconds, that's when the dropping issue happens again. I have tried it few more time to make sure it's not a coincident. And, I was right, it wasn't a coincidence, it's the ELB disconnect the connection.

However, I am not sure if this is totally ELB's fault. The ELB only times out a connection when there is no data comes from Nchan. And, when it happens, it only drops few subscribers.
```
 | CONNECTING:0 | OPENED:1839 | ERROR:28 | TOTAL:1867
Last 5 errors:
status:undefined
status:undefined
status:undefined
status:undefined
status:undefined
```
so I am guessing that maybe Nchan somehow doesn't send messages through all subscriber_pools? It might missed 1 or 2 subscriber_pools which then cause the connection to drop? Does this ring any bell to you?
I am going to write a test script to test how many messages a subscriber receives. Will update you with more information.

**Comment by slact** [comment]
> In what situation will sudden_abort_handler be called?

When an HTTP request associated with a subscriber is finalized by anything other than a message or status response. The most likely possibility is an aborted TCP connection.

**Comment by slact** [comment]
> We are using AWS ELB 

Ah, yes, the dreaded Elastic Load Balancer. You may want to try setting nginx's `listen` directive with an aggressive `so_keepalive` option to keep the ELB happy. See https://serverfault.com/questions/181724/is-it-possible-to-configure-nginx-to-send-tcp-keepalive for details

**Comment by supertong** [comment]
Woot! Thanks for that. Let me have a try. 
Yes, I don't quite like the ELB too 👿 , it always has problem with long live connections. Under http listener, it somehow try to re-use the connections and caused many issues. Then, we changed it to TCP listener and thought it would behave better...

**Comment by slact** [comment]
Some notes:
`redis pending commands` : may spike during peak load. If this keeps increasing it means Nchan or Redis is overloaded.
`interprocess queued alerts` : may spike during peak load. If this keeps increasing it means Nchan is overloaded.
`total interprocess send delay` : May increase during peak load. Continuous increase means Nchan is overloaded.
`total interprocess receive delay` : May increase during peak load.

**Comment by supertong** [comment]
Thanks for the notes. By the way, do you think my guessing about some subscriber_pool get missed is still valid?

**Comment by slact** [comment]
> By the way, do you think my guessing about some subscriber_pool get missed is still valid? 
I just don't know at this point. It's certainly plausible.

> Also, when you say Nchan is overloaded, do you mean the CPU usage is overloaded?
Not necessarily, although I don't see how this can happen _without_ high CPU use. But I just mean that those things indicate that Nchan cannot keep up with the publisher/subscriber load thrown at it. If it's Redis that can't keep up, then it will definitely have a high CPU load.

**Comment by supertong** [comment]
Update:
Hey @slact , thanks for that `so_keepalive`, new knowledge learned 😄 . It makes ELB happy by extending the expire time, but I don't think it totally solve the dropping issue. After the extended expire time, the connection still drops. I have extended it to 180 seconds and after that few thousands of connection drops together. I reckon these connections are in the same suscriber_pool and somehow get's forgotten by Nchan. And,  it's not acceptable for our subscriber not receive anything in 180 seconds, so it's better to let them drop and reconnect in this case.
I will write more test cases to prove my point and try my best to debug it. If you want to close this issue, feel free to. I can open a new issue if I am able to prove my guess is correct.
Thanks again for your time!!

**Comment by slact** [comment]
Ok, that's good to know. Please do open another issue and let me know what you find.

**Comment by supertong** [comment]
Update as promised. Nchan delivers message as expected. It's our service didn't publish message as expected sometimes. Should have thought of it earlier 😢 . 
Nchan is a good boy 😄  .

**Comment by slact** [comment]
Phew, good to know. Thanks for the updates.
