### ISSUE TITLE
Conditional nessage publishing if subscribers in channel exceed threshold

### ISSUE THREAD

**Issue by bymaximus** [slact/nchan#225]
Would be awesome to have a way to only post to channel if n subscribers connected.

**Comment by slact** [comment]
You can do a GET to a publisher location first to see the number of subscribers, then POST if it meets the minimum threshold.

Can you give me a use case where this isn't enough?

**Comment by bymaximus** [comment]
for example when nchan using redis (also with other nchan servers using same redis server, scalled), instead of just post all data to channel only post if channel has at least N subscribers.

Some cases no reason to post data if no subscribers, instead of all nchan servers post all data to channel it only post data if N subscribers (means some subscriber is connected to any of nchan servers waiting data).

Just like nchan option nchan_subscribe_existing_channels_only

**Comment by slact** [comment]
Sorry, I still don't see it. `nchan_subscribe_existing_channels_only` is primarily a security-related setting to prevent DoS attacks on publicly available subscriber endpoints by spamming channel subscriptions to use up memory. 

Publisher endpoints are supposed to be treated with more care and restriction. So it could be IP-limited to your application, or authorized via an upstream request to same application.

I don't understand what problem this solves that cannot already be solved by an extra GET to the publisher location.

**Comment by bymaximus** [comment]
Think this scenario, analytics tracking live data, visitors loading websites which generates some data which is send do some servers which store and also post to nchan servers, cant make a GET request to every visitor request to check if should post or not data since are tons of requests all the time.

Chould just post data and instead of post this data to redis, check if it have subscribers to post to redis or not, no reason to post tons of data if no subscribers, bad to make tons of GET to nchans to know if there are subscribers or not, nchan know already if channel have subscribers or not then could avoid network/servers usage/load if we have this option to avoid posting data to redis if no subscribers

**Comment by slact** [comment]
Ok, let me think it over.

**Comment by bymaximus** [comment]
Sure, thanks for your time anyway

**Comment by amcgregor** [comment]
As a note, I use a message broker on the application-side that multiplexes messages out directly to per-user channels.  User subscription to "groups of interesting events" is handled application-side.  In other cases, where the messages are related to, say, the resource being viewed by the user (in the case of discussion forums, e.g. a thread) use a wholly shared channel for that resource.

In the former case messages are sent or not to Nchan based on existing knowledge; user not subscribed to the event, it's not sent their way.  No subscribers: nothing is sent—a very fast no-op for the message sender, with a single DB round-trip in the broker.  In the latter case the simple use of GET + conditional POST does the same.

**Comment by slact** [comment]
@bymaximus Sorry, I'm not going to implement this. However, your workaround using an internal eval is pretty clever.
