### ISSUE TITLE
Expose nchan_stub_status data as variables

### ISSUE THREAD

**Issue by bymaximus** [slact/nchan#228]
Possible expose strub_status variables values for nginx so we can easly make some control conditions based on these values, like post or not messages based on active subscribers value (related [https://github.com/slact/nchan/issues/225](https://github.com/slact/nchan/issues/225))

**Comment by slact** [comment]
I will definitely do that.

**Comment by slact** [comment]
Done in cd7e7e3. Here are the variables:
```
$nchan_stub_status_total_published_messages 
$nchan_stub_status_stored_messages 
$nchan_stub_status_shared_memory_used 
$nchan_stub_status_channels 
$nchan_stub_status_subscribers 
$nchan_stub_status_redis_pending_commands 
$nchan_stub_status_redis_connected_servers 
$nchan_stub_status_total_ipc_alerts_received 
$nchan_stub_status_ipc_queued_alerts 
$nchan_stub_status_total_ipc_send_delay 
$nchan_stub_status_total_ipc_receive_delay
```

These are usable if there is an `nchan_stub_status` on at least one location. Otherwise, they will not be tracked and will remain stuck at 0.

**Comment by bymaximus** [comment]
Excellent
