### ISSUE TITLE
Duplicate message queue items when two instances have different time.

### ISSUE THREAD

**Issue by supertong** [slact/nchan#229]
Referring to this issue. https://github.com/slact/nchan/issues/224

Hey @slact , I am working on the dropping issue that I encountered. Here is something new that I found, not sure if it's related to the dropping issue, but it looks like an issue to me.

Here is the log, I print out messages in the queue.
```
 2016/08/22 07:36:54 [error] 5#0: MEMSTORE:00: chanhead_gc max 1000 count 7
 2016/08/22 07:36:54 [error] 5#0: MEMSTORE:00: TTT: message queue for 0000562982B32480, channel_id = vision/vision-live-data
 2016/08/22 07:36:54 [error] 5#0: MEMSTORE:00:  -> 1471851398:0, msg = 00007F085CBCC000, stored_msg = 0000562986FE6460
 2016/08/22 07:36:54 [error] 5#0: MEMSTORE:00:  -> 1471851386:0, msg = 00007F085CBCF000, stored_msg = 00005629872A8220
 2016/08/22 07:36:54 [error] 5#0: MEMSTORE:00:  -> 1471851398:0, msg = 00007F085CBCF200, stored_msg = 0000562982F4E600
 2016/08/22 07:36:54 [error] 5#0: MEMSTORE:00:  -> 1471851389:0, msg = 00007F085CBCF400, stored_msg = 00005629873A2440
 2016/08/22 07:36:54 [error] 5#0: MEMSTORE:00:  -> 1471851398:0, msg = 00007F085CBCF600, stored_msg = 00005629851196A0
 2016/08/22 07:36:54 [error] 5#0: MEMSTORE:00:  -> 1471851391:0, msg = 00007F085CBCF800, stored_msg = 0000562984A40BC0
 2016/08/22 07:36:54 [error] 5#0: MEMSTORE:00:  -> 1471851398:0, msg = 00007F085CBCFA00, stored_msg = 00005629835BCA00
```
The problem is the message id `1471851398:0`, it gets duplicated in the queue. Let me explain how I ran into this problem.

I am still using the same config in the referenced issue. And the thing I want to highlight is that the two instances I am having do NOT have the same system time.

For example, I have two instances, A and B. And, they are synced over redis. And the system time on B is, for example, 10 seconds faster than A.

If I publish a message on A, and the system time on A is 1. The message queue will look like
```
   A         B
   1:0     1:0
```
Now I publish a message on B, and the system time on B is now 12.
```
   A          B
  1:0        1:0
  12:0      12:0
```
Now I back to A and publish another message, the system time on A is now 3.
```
   A              B
 1:0            1:0
  12:0         12:0
  3:0           12:1
  12:0         
```
Now the problem happens, A will somehow duplicate the second message in the queue `12:0` and B will increase the tag on last message. The message becomes out-synced in this case.

I can kind of solve it using `ntp` time syncing on the system to make two instance have the same time, but I doubt it will really solve the problem. What if the published message gets delayed during redis syncing etc. Does my worry make sense? Do you think this messed up message queue contribute to the dropping issue I am having (some subscriber pool gets missed during rbtree_walking)?

Cheers

**Comment by slact** [comment]
Hmm... I haven't stated it in the documentation, but all Nchan servers do need to have their times synced up to function properly. However, this would mainly affect servers through which messages are published, because the message timestamps are generated locally. So it's possible that message from published a server whose time lags by several seconds will not be received by other subscribers, or that it would be duplicated (though I haven't really considered the duplication scenario).

What I can do for now is add detection logic for when this happens, and issue a warning to sync up the times on the servers.

**Comment by supertong** [comment]
Thanks @slact , a warning would be enough.

**Comment by slact** [comment]
Yep, I added this to the readme in f0537d76ceda. I'll add detection code for this later.

**Comment by slact** [comment]
Added logging a warning when out-of-order message is detected in  5cfe06c829e0a62065291172c05dd4d6a8fd16cc

**Comment by supertong** [comment]
Hey @slact , new findings.
Even though the two instances have time synced, the message queue can still be messed up when there are suddenly a lots of publish happens and these publishes are balanced between two instances. As a result, the same message id will represent different messages and some messages is not delivered on one of the instances.

For example, there are two publish request with different message (a and b) come in at around same time and they are load balanced to different instance.
```
        a                            b
        |                             |
   Nchan1                  Nchan2
msg_id: 1:0 (a)     msg_id: 1:0 (b)
msg_id: 1:1 (b)      msg_id: 1:1 (a)
``` 
I think that's because the messaging syncing over redis is not faster then the time nchan receives the new message. And when Nchan receives new message, it always handle the mem-store first and then publish to redis-store.
Sometime even worst, the time becomes different even not only the tag. It will look like
```
        a, c                        b
        |                             |
   Nchan1                  Nchan2
msg_id: 1:0 (a)      msg_id: 1:0 (b)
msg_id: 2:0 (c)      msg_id: 1:1 (a)
msg_id: 1:0 (b)      msg_id: 2:0 (c)
msg_id: 2:0 (c) <-  duplicated
```
In this case, it is because the message C comes in faster than the message B syncing over from redis. In this case, the message B will not be delivered to subscribers connected on Nchan1. (I don't know why though..)

I am now moving to a single publish point to work around this issue. However, I think the better solution would be to use the Redis queue as the source of truth. For example, instead of creating the ngx_time() in the Nchan, can we get the time from Redis? so that we don't have to worry about time syncing anymore. Also, do you think it would be better when Nchan receives publish message, it handle the redis-store first to make sure the message queue is in order and then fall back to mem-store?

Cheers

**Comment by slact** [comment]
Your analysis is spot on. 

> I think the better solution would be to use the Redis queue as the source of truth. For example, instead of creating the ngx_time() in the Nchan, can we get the time from Redis? 

In the past this was not possible, because nondeterministic Lua scripts cannot alter keys. Getting the time from within a script makes it nondeterministic, which is why I had to provide the current time as an input to the publish.lua script.

From http://redis.io/commands/eval : 

> The main drawback with the whole scripts replication approach is that scripts are required to have the following property:
>    The script must always evaluates the same Redis write commands with the same arguments given the same input data set. Operations performed by the script cannot depend on any hidden (non-explicit) information or state that may change as script execution proceeds or between different executions of the script, nor can it depend on any external input from I/O devices.

However, the latest release, 3.2, introduced command replication, which does not have this constraint:

> Starting with Redis 3.2 (not yet stable) [[actually, it is]] it is possible to select an alternative replication method. Instead of replication whole scripts, we can just replicate single write commands generated by the script. We call this script effects replication.
> When script effects replication is enabled, the controls about non deterministic functions are disabled. You can, for example, use the TIME or SRANDMEMBER commands inside your scripts freely at any place.

So starting with version 3.2, we can use Redis, as you put it, as the "source of truth". With fallback behavior for lower versions, of course.

> Also, do you think it would be better when Nchan receives publish message, it handle the redis-store first to make sure the message queue is in order and then fall back to mem-store?

Yes. The current behavior now looks to me like a case of premature optimization.

I'll mess around with publish scripts tomorrow and let you know what I find.

**Comment by slact** [comment]
fixed in f037629. I've disabled publishing to memstore first when redis is enabled, and enabled getting the message time in Redis if it's version is >= 3.2.

**Comment by slact** [comment]
Another change related to this issue: 9e2d02f3002293 . Now publishing to redis doesn't even create a memstore channel.

**Comment by slact** [comment]
Closing this, please reopen if you're still having this issue.
