### ISSUE TITLE
[bug] nchan_publisher_upstream_request working?

### ISSUE THREAD

**Issue by bymaximus** [slact/nchan#233]
Is nchan_publisher_upstream_request config working?

I could not find any code using this ```nchan_publisher_upstream_request``` config, seems it doesnt evaluate variable values like

```
nchan_publisher_upstream_request "/test/$1";
```

It returns error 500 while posting data, no error log

```
        location ~ /pub/(\w+)$ {
                nchan_publisher http;
                nchan_channel_id "$1";
                nchan_publisher_upstream_request "/test?channel=$1";
        }
```

**Comment by bymaximus** [comment]
NVM, you can close if want, I see it only works for websocket publisher. Anyway, would be awesome if variables are evaluated I guess.

**Comment by slact** [comment]
Variables are not evaluated, but it should work for all publisher requests.

**Comment by bymaximus** [comment]
Right, thanks
