### ISSUE TITLE
Events - Upstream Request

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#236]
Hello Leo,

I want to send "event messages" to an application upstream. 
At the moment they are not sent. 
What is the reason for this problem?

```nginx
    location = "/events" {
            nchan_channel_id "events";
            nchan_channel_group "meta";
            nchan_pubsub;
            nchan_message_buffer_length 30;
            nchan_message_timeout 1m;
            nchan_subscriber_first_message newest;
            nchan_publisher_upstream_request "/events-pub";
        }
```

Thank's
Valy

**Comment by slact** [comment]
You can't publish directly to events channels, that's only done internally. I actually need to add an error that disallows `nchan_pubsub` or `nchan_publisher` when `nchan_channel_group "meta"` is present.

**Comment by valydvweb** [comment]
OK ... But I don't want to publish on this channel. I want to send internal messages (e.g. subscriber_enqueue ..) to an upstream request

**Comment by slact** [comment]
You can't do that directly either, because the `nchan_publisher_upstream_request` directive applies only to messages published from that location. I think you're just going to need to wait until I add subscribe/unsubscribe hooks to get the functionality you're looking for.

**Comment by valydvweb** [comment]
Hmmm it is very important for my project :(
Ok ... and when you think will be ready this update?

**Comment by slact** [comment]
A few weeks, maybe. It's a tricky feature, and my last attempt was unsuccessful. It requires a lot of digging in the guts of Nginx to get unsubscribe events done right. 

Meanwhile, you could have a standalone subscriber receive channel events and forward them to your application.

**Comment by valydvweb** [comment]
a standalone subscriber receive channel ... I didn't understand exactly ... can you give me more info ... please

**Comment by slact** [comment]
You can use a websocket subscriber listen on the "/events" channel and when it receives events, send requests to your application.

**Comment by valydvweb** [comment]
I understand. 
Besides this method can be a nginx trick to forward this message?

**Comment by slact** [comment]
> Besides this method can be a nginx trick to forward this message?

I'm not sure. Maybe there's something in the ngx_lua module to do this. However, I think doing this with a separate client is easier.

**Comment by valydvweb** [comment]
This mechanism is based only WebSocket?
not HTTP request

**Comment by slact** [comment]
You can use any subscriber type you want. Websocket, EventSource, Long-poll, HTTP-multipart, or HTTP-chunked. Websocket is probably the easiest to use though, because it has the most available libraries.

**Comment by valydvweb** [comment]
ok .. but events messages is only relevant for WebSocket connection ...

**Comment by slact** [comment]
No, they apply to all connections.

**Comment by valydvweb** [comment]
OK .. I ask this, because I was thinking of a config like this:

    location = "/events" {

            nchan_channel_id "events";
            nchan_channel_group "meta";
            nchan_subscriber;
            nchan_message_buffer_length 30;
            nchan_message_timeout 1m;
            nchan_subscriber_first_message newest;

           proxy_pass "my-upstream-to-forward-messages";
        }


But I don't think that is relevant.

**Comment by slact** [comment]
Right, that's not how proxy_pass works.

**Comment by valydvweb** [comment]
ok .. thank's
