### ISSUE TITLE
Message loss with nchan_store_messages=off

### ISSUE THREAD

**Issue by regnarg** [slact/nchan#238]
I have a simple configuration:

		location /pub {
			nchan_publisher;
			nchan_channel_id "mychan";
			nchan_store_messages off;
		}
		location /sub {
			nchan_subscriber;
			nchan_channel_id "mychan";
		}

I publish messages using simple POST requests and receive them using websockets. When I try to publish several messages in one second, only one of them gets delivered. However, when I change `nchan_store_messages` to `on`, it works correctly (even with a buffer length of 1, not a single message is lost).

A simple minimal working example is available in
[nchan-msg-loss.zip](https://github.com/slact/nchan/files/439382/nchan-msg-loss.zip).

Run `ngx.sh`, `listen.sh` and `flood.sh` in three terminals. You will see only one message per second output by `listen.sh`, whereas `flood.sh` is pushing messages in a tight loop.

Is this the expected behaviour? If it is, it should be probably documented. It is not clear to me at all what the `nchan_store_messages` directive is actually supposed to do.

Using nginx/1.11.3 and nchan 1.0.1.

    nginx version: nginx/1.11.3
    built with OpenSSL 1.0.1t  3 May 2016
    TLS SNI support enabled
    configure arguments: --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_gzip_static_module --without-http_browser_module --without-http_geo_module --without-http_limit_req_module --without-http_memcached_module --without-http_referer_module --without-http_scgi_module --without-http_split_clients_module --without-http_ssi_module --without-http_userid_module --add-module=.../nginx-nchan --add-module=.../nginx-upload-module

**Comment by regnarg** [comment]
The issue arises even with `worker_processes` set to `1`, so it does not seem to be an IPC synchronization issue.

It might be somehow related to messages getting duplicate IDs. When I look at output from `flood.sh` (these are the replies to the publishing POST requests):

~~~~~
Server: nginx/1.11.3
Date: Fri, 26 Aug 2016 13:55:51 GMT
Content-Type: text/json
Content-Length: 85
Connection: close

{"messages": 0, "requested": 0, "subscribers": 1, "last_message_id": "1472219751:0" }HTTP/1.1 201 Created
Server: nginx/1.11.3
Date: Fri, 26 Aug 2016 13:55:51 GMT
Content-Type: text/json
Content-Length: 85
Connection: close

{"messages": 0, "requested": 0, "subscribers": 1, "last_message_id": "1472219751:0" }HTTP/1.1 201 Created
Server: nginx/1.11.3
Date: Fri, 26 Aug 2016 13:55:52 GMT
Content-Type: text/json
Content-Length: 85
Connection: close

[...]

{"messages": 0, "requested": 0, "subscribers": 1, "last_message_id": "1472219752:0" }HTTP/1.1 201 Created
Server: nginx/1.11.3
Date: Fri, 26 Aug 2016 13:55:52 GMT
Content-Type: text/json
Content-Length: 85
Connection: close

{"messages": 0, "requested": 0, "subscribers": 1, "last_message_id": "1472219752:0" }HTTP/1.1 201 Created
Server: nginx/1.11.3
Date: Fri, 26 Aug 2016 13:55:52 GMT
Content-Type: text/json
Content-Length: 85
Connection: close

{"messages": 0, "requested": 0, "subscribers": 1, "last_message_id": "1472219752:0" }HTTP/1.1 201 Created
Server: nginx/1.11.3
Date: Fri, 26 Aug 2016 13:55:52 GMT
Content-Type: text/json
Content-Length: 85
Connection: close

[...]
~~~~~

**Comment by slact** [comment]
That's definitely a bug, and thanks for your detailed write-up. I'll have it fixed shortly.

**Comment by slact** [comment]
Fixed in ee492c9 and 7f83811 .

**Comment by slact** [comment]
Closing this, please reopen if you are still having issues.

**Comment by regnarg** [comment]
I upgraded to 1.0.2, this got fixed but I have another issue. Now in the same test setup mentioned above (one channel, one websocket subscriber, plain POST publisher), when worker_processes > 1, no message gets ever delivered, regardless of store_messages setting. When worker_processes = 1, it works well. I'm not sure how much it is related to this issue, perhaps I should open a new one?

After closing the subscriber connection, I get this in the logs:

    2016/08/31 09:42:10 [error] 23216#0: MEMSTORE:00: tried adding WAITING chanhead 0863F5E0 /mychan to chanhead_gc. why?
    unix: - - [31/Aug/2016:09:42:10 +0000] "GET /sub HTTP/1.1" 101 0 "-" "-"

I wanted to attach a debug log but github upload seems broken somehow, so it's here: http://regnarg.cz/tmp/newissue-dlog.txt

**Comment by regnarg** [comment]
I upgraded to 1.0.2, this got fixed but I have another issue. Now in the same test setup mentioned above (one channel, one websocket subscriber, plain POST publisher), when worker_processes > 1, no message gets ever delivered, regardless of store_messages setting. When worker_processes = 1, it works well. I'm not sure how much it is related to this issue, perhaps I should open a new one?

After closing the subscriber connection, I get this in the logs:

    2016/08/31 09:42:10 [error] 23216#0: MEMSTORE:00: tried adding WAITING chanhead 0863F5E0 /mychan to chanhead_gc. why?
    unix: - - [31/Aug/2016:09:42:10 +0000] "GET /sub HTTP/1.1" 101 0 "-" "-"

Attaching debug log from the session

**Comment by slact** [comment]
Sorry, I'm not seeing this behavior. I'll need to see your full nginx config, the nginx version, and OS info to try to replicate this. Something weird is happening to the websocket subscriber's file descriptor when it gets read -- and I suspect the OS may be to blame. I'm not sure though, and I can't replicate this yet, hence why I need the additional info.

**Comment by regnarg** [comment]
Ah, my mistake. Increased `worker_processes` without enabling `master_process`. With `master_process` it works as expected.

**Comment by slact** [comment]
No problem, this gave me an incentive to add unix socket support for my tests

**Comment by regnarg** [comment]
All issues I had with message loss seem resolved now, thank you very much. Just out of curiosity: you mentioned in the doc update that using `nchan_store_messages off` may cause message loss. How or under what circumstances? I tested 200 websocket subscribers and a continuous flood of messages without any losses. Is this specific to long-poll and similar subscribers? When nchan doesn't buffer the messages, where are they stored with websocket subscribers? In some sort of nginx internal IO buffers?

**Comment by slact** [comment]
When using channels with `nchan_store_messages off`, messages are still stored for a very short time, but not associated with the channel. This is because some buffering is needed internally to pass messages around from worker to worker. However, under heady load, the default internal buffer may not be enough to keep up with the message flow.

This would affect long-polling subscribers most, as they subscribe and unsubscribe on every request. In theory, this can affect the other subscribers (ws, eventsource etc.) as well, but I've never seen that happen in the wild.
