### ISSUE TITLE
Segfault parsing redis url

### ISSUE THREAD

**Issue by slact** [slact/nchan#241]
@brunoqc: 
> I have the same problem (I mean when trying to upgrade, I didn't test this issue yet). It's weird that I didn't have this problem when I tested nchan+redis with docker for another bug report.

> ``` 
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ngx_strnstr (s1=s1@entry=0x0, s2=0x835e1e0 "edis://", s2@entry=0x835e1df "redis://", len=7, len@entry=8) at src/core/ngx_string.c:641
641                 c1 = *s1++;
(gdb) bt
#0  ngx_strnstr (s1=s1@entry=0x0, s2=0x835e1e0 "edis://", s2@entry=0x835e1df "redis://", len=7, len@entry=8) at src/core/ngx_string.c:641
#1  0x0819a37c in parse_redis_url (url=url@entry=0x87626bc, rcp=rcp@entry=0xbfaac2a8) at /home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-1.0.1/src/store/redis/rdsstore.c:176
#2  0x081a0243 in redis_add_connection_data (rcf=rcf@entry=0x87626bc, lcf=0x87625c0, override_url=override_url@entry=0x0)
    at /home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-1.0.1/src/store/redis/rdsstore.c:2279
#3  0x081a03af in nchan_store_init_postconfig (cf=0xbfaac5fc) at /home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-1.0.1/src/store/redis/rdsstore.c:2323
#4  0x081ac588 in nchan_postconfig (cf=0xbfaac5fc) at /home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-1.0.1/src/nchan_setup.c:51
#5  0x080c01ad in ngx_http_block (cf=0xbfaac5fc, cmd=0x84179a0 <ngx_http_commands>, conf=0x8760ad8) at src/http/ngx_http.c:308
#6  0x080a3530 in ngx_conf_handler (last=1, cf=0xbfaac5fc) at src/core/ngx_conf_file.c:427
#7  ngx_conf_parse (cf=cf@entry=0xbfaac5fc, filename=filename@entry=0x876031c) at src/core/ngx_conf_file.c:283
#8  0x080a0cc7 in ngx_init_cycle (old_cycle=old_cycle@entry=0xbfaac78c) at src/core/ngx_cycle.c:274
#9  0x0808fb0a in main (argc=3, argv=0xbfaac954) at src/core/nginx.c:276
```

**Comment by slact** [comment]
Can you show me your nginx config?

**Comment by slact** [comment]
nevermind, fixed in 8bf4507.

**Comment by brunoqc** [comment]
nginx.conf
```
worker_processes 2;
worker_rlimit_core 1024M;
nchan_use_redis on;
```

vhost
```
    location ~ /sub/(\w+)$ {
        nchan_subscriber;
        nchan_message_buffer_length 1;
        nchan_channel_id $1; #first capture of the location match
    }

    location ~ /pub/(\w+)$ {
        nchan_publisher;
        nchan_channel_id $1; #first capture of the location match
        nchan_message_buffer_length 1;
        nchan_message_timeout 0;
    }
```

**Comment by brunoqc** [comment]
:+1:

**Comment by brunoqc** [comment]
I'll rebuild nginx now.

**Comment by brunoqc** [comment]
It doesn't build:

```
/home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-8bf45074a269bf48899e66d4c5d92c00093cb1f3/src/store/redis/rdsstore.c: In function ‘redis_add_connection_data’:
/home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-8bf45074a269bf48899e66d4c5d92c00093cb1f3/src/store/redis/rdsstore.c:2308:9: error: request for member ‘len’ in something not a structure or union
   if(url.len == 0) {
         ^
/home/bbigras/nginx/nginx-1.11.3/debian/modules/nchan-8bf45074a269bf48899e66d4c5d92c00093cb1f3/src/store/redis/rdsstore.c:2309:9: error: incompatible types when assigning to type ‘struct ngx_str_t *’ from type ‘ngx_str_t’
     url = default_redis_url;
```

**Comment by slact** [comment]
Oops, my bad: 0caff4e

**Comment by brunoqc** [comment]
nginx is running now. You can close this issue. Thanks.

**Comment by slact** [comment]
: )
