### ISSUE TITLE
the latest nchan deb install need libs too high.

### ISSUE THREAD

**Issue by notedit** [slact/nchan#242]
i am install nchan on ubuntu 14.04

several libs are too high,  i have to install manual

**Comment by slact** [comment]
Yes, I built the package on Ubuntu 16.04, as Canonical now recommends an upgrade from 14.04 to 16.04.

**Comment by notedit** [comment]
but some  vps  has not updateed to  16.04.

where i can find the old deb package?

**Comment by slact** [comment]
hey @notedit, why did you close this? I was planning on getting an Ubuntu 14.04 VM running to generate the ubuntu package. I will probably be able to do this on the weekend.

**Comment by notedit** [comment]
i build from source code.  

that would be nice have a 14.04 deb.

**Comment by slact** [comment]
verison 1.0.3 (the current release) was built on ubuntu 14.04. Thy that one.

**Comment by notedit** [comment]
finally  nchan has a version. 👍 

i use it in my project,  it works well so far.
