### ISSUE TITLE
Content-type not defined when using NchanSubscriber.js eventsource

### ISSUE THREAD

**Issue by MrDefacto** [slact/nchan#248]
Hi,

Maybe i'm doing something wrong but... issuing:

```shell
curl --request POST --data "`date`" -H "Accept: text/plain" -H "Content-type: text/script" http://host/publish/test
```
example result is:

`message:Thu Sep 1 10:13:05 CEST 2016 id:1472717586:0 content-type:undefined`

as far as i understand ther should be 'text/script' in content-type. My html code:
```js
    function messageReceived(message, message_metadata) {
        document.getElementById('messages').innerHTML += 'message:' + message + ' id:' +  message_metadata['id'] + ' content-type:' + message_metadata['content-type'] + '<br>';
    };

    if(typeof(EventSource) !== "undefined") {
	var sub = new NchanSubscriber('http://host/liveinfo/test', {
	    subscriber: 'eventsource',
	    reconnect: 'persist',
	    shared: true
	});
    } else {
	var sub = new NchanSubscriber('http://host/liveinfo/test', {
	    subscriber: 'websocket',
	    reconnect: 'persist',
	    shared: true
	});
	sub.reconnectTimeout = 1000;
    }

    sub.on("message", messageReceived);
    sub.reconnect = true;
    sub.lastMessageId = 0;

    sub.start();`
```
Maybe i metadate there also should be changed name for variable from content-type to contenttype ore something like that. Variable with '-' can't by used directly by calling:message_metadata.content-type. It's just a idea ;-)

**Comment by slact** [comment]
The EventSource protocol does not have the means to send the content-type with the message, so when using it it is unavailable. I've added a note about this in the readme:  036aa8b.

If you need the content-type, you can use 
```js
var sub = new NchanSubscriber('http://host/liveinfo/test', {
    subscriber: ['websocket', 'longpoll'],
    reconnect: 'persist',
    shared: true
});
```
This way NchanSubscriber will first try websocket, and if unavailable, fall-back to long-polling.

You also don't need to test for `typeof(EventSource) !== "undefined"`, `NchanSubscriber` does that automatcally.

**Comment by MrDefacto** [comment]
even if i have:

```
    var sub = new NchanSubscriber('http://host/liveinfo/test', {
	subscriber: 'websocket',
	reconnect: 'persist',
	shared: true
    });

    sub.on("message", messageReceived);
    sub.reconnect = true;
    sub.reconnectTimeout = 1000;
    sub.lastMessageId = 0;

    sub.start();
```

the content-type is not showing. On websocket also.

the test for typeof is for IE Browser. Without this on Internet Explorer page doesn't work.

**Comment by MrDefacto** [comment]
websocket looks ok. also works after nginx restart :-/

**Comment by slact** [comment]
Hmm. alright. Well, I'll fix that IE problem anyway.
