### ISSUE TITLE
Where do I find security vulnerability alerts, if any?

### ISSUE THREAD

**Issue by kajmagnus** [slact/nchan#252]
Hi Leo,

Where's the best place to find out about security vulnerabilities in Nchan? There isn't any email list, as of right now? If not, then I should perhaps monitor the Git commits list, or the issues list.

Background:  I'm building a security vulnerabilities alerts service that warns people about vulnerabilities in applications and software libraries they use.  I'd like to include Nchan in this vulnerabilities alerts service, because I use Nchan myself. So therefore I wonder about how to find out about vulnerabilities.

Best regards,
KajMagnus

**Comment by slact** [comment]
The most convenient place as of right now is the changelog.  Many of the request-side fixes have security ramifications. For example, 

```
 fix: invalid memory access if publisher POST request's connection terminates
    before receiving response
```

That could have been a DOS attack, but not anymore.

Taking a cue from the Nginx changelog, I can labeling tagging security-related fixes with 'security'. The changelog could then be parsed with a script to extract all security-related fixes.

**Comment by kajmagnus** [comment]
Hi, prefixing (?) security related commit messages with `security:` seems like a good idea, yes, that'd be great.

**Comment by slact** [comment]
By changelog I actually meant the  [changelog.txt](https://github.com/slact/nchan/blob/master/changelog.txt). That way you can see the security fixed just by looking at tarball contents.

**Comment by kajmagnus** [comment]
Aha, okay. Then I'll look at the changelog every now and then, instead of the commit log, or perhaps write a script. This will probably work fine, thanks.

**Comment by kajmagnus** [comment]
@slact  / Leo can I ask one more thing — your organization is name `slact` right?  (what does it mean :- ))

I'll then name any vulnerabilities like so: `slact:nchan:1.2.3`

**Comment by slact** [comment]
> I'll then name any vulnerable Nchan versions like so: slact:nchan:1.2.3

Sounds good to me

> Leo can I ask one more thing — your organization name is slact right? (what does it mean :- ))

Sort of. It's just my handle, so technically, yes, that's my "organization". As for its meaning -- I'm afraid that knowledge has been lost to history ; ) .
