### ISSUE TITLE
Nchan not reconnecting to standalone Redis server when configured for cluster mode

### ISSUE THREAD

**Issue by MrDefacto** [slact/nchan#254]
When for example redis server is restarted and redis sessions from nginx are disconnected there is no reconnection attempt.

```
2016/09/04 18:05:57 [error] 74646#101187: nchan: Can't connect to redis at redis://:@127.0.0.1:6379/0: Connection refused.
2016/09/04 18:05:57 [error] 74620#100370: REDIS REPLY ERROR: LOADING Redis is loading the dataset in memory

```

whole nginx must be reloaded.

**Comment by slact** [comment]
Are you sure that redis _isn't_ loading the dataset into memory when this error is given? 

What version of Redis are you using? Can you show me the redis log while this error is happening?

**Comment by MrDefacto** [comment]
Here's nginx config. Nothing unusal i guess.

```
upstream redis_cluster {
nchan_redis_server "redis://:password@127.0.0.1:6379/0";
}

location ~ /publish/(\w+)$ {
nchan_redis_pass redis_cluster;
nchan_redis_idle_channel_cache_timeout 30s;
nchan_publisher;
nchan_message_buffer_length $arg_buflen;
nchan_message_timeout $arg_timeout;
nchan_store_messages on;
nchan_channel_id "$1";
}

location ~ /live/(.*)$ {
nchan_redis_pass redis_cluster;
nchan_redis_idle_channel_cache_timeout 30s;
nchan_subscriber eventsource websocket;
nchan_subscriber_timeout 0;
nchan_websocket_ping_interval 5;
nchan_subscribe_existing_channels_only on;
nchan_channel_id "$1";
nchan_channel_id_split_delimiter ",";
}

```

Here is redis 3.2.3 log durning restart:

```
74652:M 04 Sep 21:24:47.276 # User requested shutdown...
74652:M 04 Sep 21:24:47.276 * Calling fsync() on the AOF file.
74652:M 04 Sep 21:24:47.341 * Saving the final RDB snapshot before exiting.
74652:M 04 Sep 21:24:47.385 * DB saved on disk
74652:M 04 Sep 21:24:47.385 * Removing the pid file.
74652:M 04 Sep 21:24:47.385 # Redis is now ready to exit, bye bye...
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 3.2.3 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 75048
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

75048:M 04 Sep 21:24:47.407 # Server started, Redis version 3.2.3
75048:M 04 Sep 21:24:47.953 * DB loaded from append only file: 0.545 seconds
75048:M 04 Sep 21:24:47.953 * The server is now ready to accept connections on port 6379

```

Also nothin special. Just nchan is'nt reconnecting...

**Comment by MrDefacto** [comment]
there is even more something wrong... when there are active subscriptions and websocket publish active and i restar redis... so nchan loses connection:

```
2016/09/04 21:46:16 [alert] 75102#101572: worker process 75106 exited on signal 11
2016/09/04 21:46:16 [error] 75133#101612: nchan: Can't connect to redis at redis://:password@127.0.0.1:6379/0: Connection refused.

```

signal 11 is not good a sign.

**Comment by slact** [comment]
It looks like you've configured Nchan to use a Redis cluster, but you're actually running a standalone Redis server. Please see https://nchan.slact.net/details#using-redis on how to configure Nchan to use a standalone Redis server.

While Nchan should not crash if you've configure it for cluster use, and connect it to a standalone Redis server, it will not work correctly with this configuration.

**Comment by MrDefacto** [comment]
it shouldn't matter if there is one or more servers. it should reconnect after specified amount of time. isn't he?

**Comment by slact** [comment]
Yes, but there's a reason I advise different configuration for cluster vs. standalone Redis server use. It is precisely because the autodetection code for whether a Redis Server is standalone or part of a cluster is not well-tested. That's why you're experiencing this error, you can avoid it by using different configuration methods for standalone servers and clusters.

**Comment by MrDefacto** [comment]
As i see now there is imposible to restart redis without restarting nginx. Even if there are two servers. When one is down and we restart nginx the nchan never start publishing again :-/ there must be two servers up.

**Comment by slact** [comment]
Have you tried my recommendation? When using Redis as a standalone server, and configuring nchan using `nchan_redis_url` with `nchan_use_redis on`, there should be no issues reconnecting.

**Comment by MrDefacto** [comment]
With nchan_redis_url it looks that is reconnecting. Problem only occurs with upstreem and cluster configuration.

**Comment by slact** [comment]
That's what I was trying to explain.  This problem only occurs when using *cluster configuration* but *not using* a Redis Cluster. It's still a bug, of course, but it's not one you need to deal with.

**Comment by MrDefacto** [comment]
Now it's test environment... but i will test it on production on full redis cluster :-) even so... it's strange for me than i can't define upstream with only one node.

**Comment by slact** [comment]
Yes, I understand. This is a temporary limitation and it will be fixed in the future.

**Comment by MrDefacto** [comment]
question from another topic ;-) sorry for bothering... but did you think about implementing function (GET parameter probably) that will allow modify existing messages in queue (based on id)?

like /publish/test?modify=[id_of_message]&newvalue=blabla 
or even
/publish/test?delete=[id_of_message] 

to delete specified message. so when new client connect it will receive modified queue messages.

there will be also usefull function to flush queue from memory/eg redis (/publish/test?flushqueue=true)

**Comment by slact** [comment]
>  but did you think about implementing function (GET parameter probably) that will allow modify existing messages in queue (based on id)?

This will not be a GET request, as that violates the idempotence requirement of a RESTful HTTP API. Could be a POST though...

> like `/publish/test?modify=[id_of_message]&newvalue=blabla` or even `/publish/test?delete=[id_of_message]`

I wasn't planning on it, but I can implement this if properly incentivized. Send me an email if you're interested.
