### ISSUE TITLE
Benchmark suggestions

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#257]
Hello Leo,

What are the best solutions recommended by you, to make Benchmark. 
eg opening multiple concurrent connections, get response time, resource monitoring, etc.

Thank's,
Valy

**Comment by slact** [comment]
It depends on what you want to benchmark. I have different suggestions for each of those things.

**Comment by valydvweb** [comment]
Hello Leo,

And .. sorry because I didn't answer.

I want to simulate a situation where many clients are connected (at the same time) and send data.

I want to monitor:

1. The response time of the NGINX server
2. The resources (CPU and memory) used

---

In another train of thoughts, I have a few small questions.
Sorry for posting these questions here, but I don't want to open a new issue.

1. What stage are you with the update "subscribe callback"?
2. In this moment "subscribe callback" (branch)  can work for WebSocket?
I tried to compile this branch (for curiosity) but I get an error.

Thank's
And I appreciate your work :)

**Comment by valydvweb** [comment]
Hello?

**Comment by slact** [comment]
Hey, sorry for the delay. Here are some answers:

Benchmarking: 

> I want to simulate a situation where many clients are connected (at the same time) and send data.

I've been using my ruby-based clients in [dev/](/slact/nchan/tree/master/dev). Here's how to use it:

```shell
bundle exec ./sub.rb --help                                              1 ↵
Usage: sub.rb [options] url
    -s SERVER (localhost:8082),      server and port.
        --server
    -p, --parallel NUM (1)           number of parallel clients
    -t, --timeout SEC (60)           Long-poll timeout
    -q, --quit STRING (FIN)          Quit message
    -l, --client STRING (longpoll)   sub client (one of websocket, longpoll, intervalpoll, eventsource, multipart, chunked)
    -c, --content-type               show received content-type
    -i, --id                         Print message id (last-modified and etag headers).
    -n, --no-message                 Don't output retrieved message.
        --origin STR                 Set Origin header if appplicable.
        --url URL                    full subscriber url
        --http2                      use HTTP/2
    -v, --verbose                    somewhat rather extraneously wordful output
```

You can use this to load up an nchan server with tens of thousands of subscribers per machine. 

You can monitor memory use with something like `htop`, and you can watch the shared memory usage by using `nchan_stub_status`. Unfortunately, the `sub.rb` client isn't itself fast enough for benchmarking response times (I mostly wrote these tools for testing). I recommend using some knd of simple client in a low-level language, or maybe a websocket client in a  node.js event loop would be good enough.

As for the subscribe-unsubscribe callback feature -- it's not ready yet. I haven't really had time to implement it in the past few weeks.

**Comment by valydvweb** [comment]
Thank you :+1:
