### ISSUE TITLE
Nchan enters a abnormal state when sending large data through redis.

### ISSUE THREAD

**Issue by supertong** [slact/nchan#260]
Hey @slact , be able to reproduce the problem. It's still related to large data size.
When publishing large data size frequently, Nchan will enter a state where it doesn't push any message to subscribers. Even new subscribers cannot get the message. It feels like the message queue is messed up and no spooler is available in the rbtree.
And I can see few error logs:

```
2016/09/15 08:23:42 [error] 1159#0: REDISTORE: redis command get_message took 136 msec
2016/09/15 08:23:42 [error] 1159#0: SPOOL:spool for msgid 1473927822:100 not found. discarding getmsg callback response.
2016/09/15 08:23:42 [error] 1159#0: REDISTORE: redis command get_message took 136 msec
2016/09/15 08:23:42 [error] 1159#0: SPOOL:spool for msgid 1473927822:101 not found. discarding getmsg callback response.
2016/09/15 08:23:42 [error] 1159#0: REDISTORE: redis command get_message took 136 msec
2016/09/15 08:23:42 [error] 1159#0: SPOOL:spool for msgid 1473927822:102 not found. discarding getmsg callback response.
2016/09/15 08:23:42 [error] 1159#0: REDISTORE: redis command get_message took 136 msec
2016/09/15 08:23:42 [error] 1159#0: SPOOL:spool for msgid 1473927822:103 not found. discarding getmsg callback response.
2016/09/15 08:23:42 [error] 1159#0: REDISTORE: redis command get_message took 136 msec
2016/09/15 08:23:42 [error] 1159#0: SPOOL:spool for msgid 1473927822:104 not found. discarding getmsg callback response.
2016/09/15 08:23:42 [error] 1159#0: REDISTORE: redis command get_message took 136 msec
2016/09/15 08:23:42 [error] 1159#0: SPOOL:spool for msgid 1473927822:105 not found. discarding getmsg callback response.
2016/09/15 08:23:42 [error] 1159#0: REDISTORE: redis command get_message took 136 msec
2016/09/15 08:23:42 [error] 1159#0: SPOOL:spool for msgid 1473927822:106 not found. discarding getmsg callback response.
2016/09/15 08:23:42 [error] 1159#0: REDISTORE: redis command get_message took 136 msec
2016/09/15 08:23:42 [error] 1159#0: SPOOL:spool for msgid 1473927822:107 not found. discarding getmsg callback response.
```

When this happens, I am still able to publish more message to Nchan, but I don't think it's inserted into the memstore queue. Follwing is the script I use to reproduce this issue.

```
const sleep = 30000;

var count = 0

function mimicJamedScoreUpdate() {
  for (var i = 0; i <= 200; i++) {
    if (count % 100 == 0) {
      var temp = new Buffer(largeBlock);
      console.log("posting large snapshot" + temp.length)
      rp.post(Nchan2Snapshot, {
        form: {
          content: `${largeBlock}`
        }
      });
    }
    rp.post(Nchan2Delta, {
      form: {
        content: `delta${i}`
      }
    });
    count += 1;
  }

  // Call myself
  setTimeout(mimicJamedScoreUpdate, sleep);
}
```

Here is the stub message output when it's in the abnormal state

```
total published messages: 210
stored messages: 211
shared memory used: 20K
channels: 1
subscribers: 1
redis pending commands: 0
redis connected servers: 1
total interprocess alerts received: 0
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
```

Even though it says `stored messages: 211`, but here is the log I have

```
2016/09/15 08:32:14 [error] 1159#0: MEMSTORE:00: chanhead_gc max 1 count 1
2016/09/15 08:32:14 [error] 1159#0: MEMSTORE:00: message GC results: started with 1, walked 0, deleted 0 msgs
2016/09/15 08:32:14 [error] 1159#0: MEMSTORE:00: not ready to reap vision/vision-live-data, 1 subs left
2016/09/15 08:32:18 [error] 1159#0: MEMSTORE:00: chanhead_gc max 1 count 1
2016/09/15 08:32:18 [error] 1159#0: MEMSTORE:00: message GC results: started with 1, walked 0, deleted 0 msgs
2016/09/15 08:32:18 [error] 1159#0: MEMSTORE:00: not ready to reap vision/vision-live-data, 1 subs left
2016/09/15 08:32:22 [error] 1159#0: MEMSTORE:00: chanhead_gc max 1 count 1
2016/09/15 08:32:22 [error] 1159#0: MEMSTORE:00: message GC results: started with 1, walked 0, deleted 0 msgs
2016/09/15 08:32:22 [error] 1159#0: MEMSTORE:00: not ready to reap vision/vision-live-data, 1 subs left
```

Let me know what you think.
Cheers

**Comment by slact** [comment]
Can you show me the full script you used to reproduce this? From what I see, I don't really know how large the messages are, or where they are being published. What kinds of subscribers are there? And what's your Nginx config?

**Comment by supertong** [comment]
Hey @slact ,
Here is my full test script
```
const rp = require('request');

const Nchan1Delta = 'http://192.168.99.100:81/live-data/pub/delta';
const Nchan2Delta = 'http://192.168.99.101:81/live-data/pub/delta';
const Nchan1Snapshot = 'http://192.168.99.100:81/live-data/pub/snapshot';
const Nchan2Snapshot = 'http://192.168.99.101:81/live-data/pub/snapshot';

const largeBlock = 'A'.repeat(1024*1023 + 1);
const sleep = 30000;

var count = 0

function mimicJamedScoreUpdate() {
  for (var i = 0; i <= 200; i++) {
    if (count % 100 == 0) {
      var temp = new Buffer(largeBlock);
      console.log("posting large snapshot" + temp.length)
      rp.post(Nchan2Snapshot, {
        form: {
          content: `${largeBlock}`
        }
      });
    }
    rp.post(Nchan2Delta, {
      form: {
        content: `delta${i}`
      }
    });
    count += 1;
  }

  // Call myself
  setTimeout(mimicJamedScoreUpdate, sleep);
}

function mimicNormalDeltaUpdate() {
  rp.post(Nchan2Delta, {
    form: {
      content: `delta-normal`
    }
  });
  // In real time, it could be faster than 1 seconds
  setTimeout(mimicNormalDeltaUpdate, 1000);
}

function mimicNormalSnapshotUpdate() {
  rp.post(Nchan2Snapshot, {
    form: {
      content: `snapshot-normal`
    }
  });
  // Every 30 seconds snapshot update
  setTimeout(mimicNormalSnapshotUpdate, 30000);
}

mimicJamedScoreUpdate();
mimicNormalDeltaUpdate();
mimicNormalSnapshotUpdate();
```
And my nginx config is
```
daemon off;
worker_processes 1;
worker_rlimit_nofile 30000;

http {

  log_format combined_xforwardfor '$remote_addr $http_x_forwarded_for - $remote_user [$time_local] '
                                  '"$request" $status $body_bytes_sent '
                                  '"$http_referer" "$http_user_agent" $request_time ';
  access_log /var/log/nginx/access.log combined_xforwardfor;

  nchan_use_redis on;
  nchan_redis_url 10.0.2.2:6379;
  nchan_max_reserved_memory 1024M;
  nchan_redis_publish_msgpacked_max_size 999999999;
  client_max_body_size 1m;

  server {
    listen 80;

    location = /live-data/sub {
      nchan_subscriber;
      nchan_channel_group test;
      nchan_channel_id test-data;
    }
  }

  server {
    listen 81;
    location = /live-data/pub/snapshot {
      nchan_publisher;
      nchan_channel_group test;
      nchan_channel_id test-data;
      nchan_message_buffer_length 1;
    }

    location = /live-data/pub/delta {
      nchan_publisher;
      nchan_channel_group test;
      nchan_channel_id test-data;
      nchan_message_buffer_length 1000;
    }

    location = /stub {
      nchan_stub_status;
    }

  }
}

events {
  worker_connections 38000;
}
```

The issue is pretty easy to reproduce. Start an Nchan instance with above config, and run the test script to publish things to it. Inside the test script, make sure you change the Nchan2Delta and Nchan2Snapshot address accordingly. The size of data I sent throught is `const largeBlock = 'A'.repeat(1024*1023 + 1);`. The reason I set to this number is because the default `client_max_body_size` for nginx is `1m`.

It's working fine in previous version where we update the memstore first and then redisstore, but it fails when the message propagate to other Nchan instance through Redis. In the latest version, we made Nchan to do redis-store update first and then do memstore update from `redis-subscriber-callback`. And, the problem starts to happen with even one instance running. Therefore, I believe the problem is in the path from `redis-subscriber-callback` to memstore message updates. Hope I explain it clearly. 😆 

Another silly question though, why do we need memstore_redis subscriber? Wouldn't it be easy just take the data from `redis-subscriber-callback` and call the publish function in memstore directly? Haha, I don't know, just a feeling.

Cheers

**Comment by supertong** [comment]
Update:
This problem doesn't happen if the message queue length doesn't change.

**Comment by slact** [comment]
I'm not a fan of the `nchan_message_marker` idea, I'd rather modifying the message buffer size work without bugs. I'l be debugging this thing tomrrow, thanks for the details.

> Another silly question though, why do we need memstore_redis subscriber? Wouldn't it be easy just take the data from redis-subscriber-callback and call the publish function in memstore directly? Haha, I don't know, just a feeling.

It's basically there to pre-fetch a channel's message buffer. The idea is that if a subscriber requests a message on a channel, it will probably want to request other messages as well. Rather than waiting for those requests, the `memstore_redis` subscriber does the pre-fetching.

**Comment by supertong** [comment]
Hey @slact , I think I now have a better understanding of the problem now. Yes, it has something todo with the async_get_message. This is what happened.

When the test script starts, it sends whole bunch of publish request to Nchan, which is enough to let the Nchan become busy for a while. Especially, when we are sending through large size data. Now, the nginx event loop will be piled up with publish requests and each publish request will fire a `async_get_message` to redis. Because it's async, so Nchan doesn't wait for the response and keep going with the next publish request. When finally Nchan got some capacity to process the `get_message_callback`, the info comes back from the callback is far more outdated. Then we set the subscriber spool with a far more outdated state, which doesn't seem right to me.

I understand your purpose of firing a `get_message` to redis to make sure it's data it up to date. But, because it's async, there is no way we can make sure that the info returned from the callback is up to date. When CPU is fast enough, then the callback can be processed immediately which doesn't cause a problem. However, when Nchan is busy, the callback could be queued in the event loop for a while to be processed. Maybe we shall think of a better way to do it.

Let me know what you think. I have temporarily made some change to 'turn off' the `async_get_message` call because it doesn't make much sense in our use case. In our use case, we have tolerance of missing message to an extent, but we don't allow out of order messages. In other words, we don't need to catch up with missing message because existing message is already delivered.

Let me know what you think, cheers.

**Comment by supertong** [comment]
Sorry, forgot about this issue. I managed to fix it by changing the redis_store to use `FETCH_IGNORE_MSG_NOTFOUND` policy. 

And I suspect that it was caused by the MSG_EXPIRED block in following code
```
    case MSG_NOTFOUND:
      if(spl->fetching_strategy == FETCH_IGNORE_MSG_NOTFOUND) {
        spool->msg_status = prev_status;
        break;
      }
    case MSG_EXPIRED:
      //is this right?
      //TODO: maybe message-expired notification
      spool->msg_status = findmsg_status;
      spool_respond_general(spool, NULL, NGX_HTTP_NO_CONTENT, NULL, 0);
      nuspool = get_spool(spool->spooler, &oldest_msg_id);
      if(spool != nuspool) {
        spool_transfer_subscribers(spool, nuspool, 1);
        destroy_spool(spool);
      }
      else {
        ERR("Unexpected spool == nuspool during spool fetch_msg_callback. This is weird, please report this to the developers. findmsg_status: %i", findmsg_status);
        assert(0);
      }
      break;

    case MSG_PENDING:
      ERR("spool %p set status to MSG_PENDING", spool);
      break;

    default:
      assert(0);
      break;
  }
```

**Comment by slact** [comment]
I think this issue is obsolete. The queue can now be entered at an arbitrary position, and queue size updates are propagated through Redis to other Nchan instances.
