### ISSUE TITLE
content-based filtering

### ISSUE THREAD

**Issue by kidd** [slact/nchan#262]
Hello, nchan looks really promising!  From what I read, I'm not sure
  it can do content-based filtering though, and I'm not sure how to proceed..

  An example use case:

  I have sports events that are in 'sports' channel.

  {"sport":"football", "match":12, "result":1}
  {"sport":"basketball", "match":15, "result":1}

  But different clients want to filter the info based on content. Just
  football, or some subset.

  The constraints could be arbitrarily complex, but the idea is that
  each subscriber just gets the subset of info he wants.

  One option is to create a channel for every subscriber, but I guess
  that defeats the purpose as we've basically created channel per
  subscriber (potentially).

  I imagine a subscriber connecting to /sub/sports?sport=football, and
  then nchan having something like nchan_publisher_upstream_request ,
  but for subscribers, and sending the url that subscriber used to
  connect, and also the message that about to be published.

  On the implementation part, I tried to use body_filter_by_lua but
  had no success at all...

  Do you have any suggestions on how to proceed? am I doing/wanting something
  fundamentally wrong? Do you think it's a valid usecase? 

  I can provide lua knowledge, redis knowledge and a cake if needed.

**Comment by slact** [comment]
You can use [channel multiplexing](https://nchan.slact.net/#channel-multiplexing) to do this. That is, you can publish to different channannels dedicated to each sport, and have subscribers subscribe to their desired sports. Here's what the config could look like:

```nginx
  
```

**Comment by kidd** [comment]
Yes, but this only works for 1 dimension (I think).

Let's say I have multiple sports and multiple type of event:

{"sport": "football", "type": "result", data: "FCB 1 - RM 0"}
{"sport": "football", "type": "news", data: "club foo buys guy X for gazilion dollars"}.

The idea would be to be able to filter by football&results.  In the general sense (and my use case in particular), the filtering could be arbitrarily complex, as in /sub/sports?q={"or": [{"type":"result", "sport":"football"}, {"type":"result", "sport":"basketball"}  ]}  .

Maybe creating an adhoc channel for every 'query' and do the filtering externally is the sanest option. Then push to the channel iff the message has to be posted to that channel.

**Comment by slact** [comment]
Ok, I understand. There's no direct way to do this, but there's very little overhead in creating a channel for every query. You can easily have millions of open channels. 

Alternately, you can use channel multiplexing to emulate an "or" operator, and pre-baked channels for "and" operations (football AND result). The arctitectural decision is your call. If you're interested, I can help out further. Shoot me an email and we can talk in more detail about what you're trying to do.

**Comment by kidd** [comment]
Thanks for the answers!
If/when I'm finally implementing this I'll reach out and try to build something that can be useful to others also and ping you for advice :)

Closing the issue for now, leaving it here as documentation for future readers.
