### ISSUE TITLE
Error when compiling the latest version

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#263]
Hello Leo,

I encountered an error when compiling the latest version.
My GCC compiler is probably to blame.

/root/nchan/src/subscribers/common.c: In function 'nchan_subscriber_unsubscribe_callback_http_test_reading':
/root/nchan/src/subscribers/common.c:463: error: 'ngx_use_epoll_rdhup' undeclared (first use in this function)
/root/nchan/src/subscribers/common.c:463: error: (Each undeclared identifier is reported only once
/root/nchan/src/subscribers/common.c:463: error: for each function it appears in.)
make[1]: *** [objs/addon/subscribers/common.o] Error 1
make[1]: Leaving directory `/root/nginx-1.10.1'
make: *** [build] Error 2

**Comment by slact** [comment]
What's your OS again? CentOS?

**Comment by slact** [comment]
Nevermind, that's not important. The issue is on my end, I had only tested some new code on Nginx 1.11.x.

**Comment by slact** [comment]
Fixed. please give it a try again.

**Comment by valydvweb** [comment]
Now everything is ok :+1: 
I will test the latest update (subscribe / unssubcribe callback)

Than's,
Valy
