### ISSUE TITLE
Core dumped on testing subscribe/unsubribe

### ISSUE THREAD

**Issue by valydvweb** [slact/nchan#264]
Hello Leo,

I compiled last version for testing new update (subscribe/unsubribe)
And I encountered more problems

This is my NGINX test config.
------------------------------------

     location = "/test" {
            nchan_channel_id "test";
            nchan_pubsub;
            nchan_store_messages off; # I don't know what doesn't work
            
           nchan_subscribe_request "/client-subscribe";
           nchan_unsubscribe_request "/client-unsubscribe";
        }
       
        # Client - Subscribe
        location "/client-subscribe" {
            proxy_pass http://myhost/subscribe.php;
            proxy_set_header X-Channel-Id $nchan_channel_id;
        }

        # Client - Unsubscribe
        location "/client-unsubscribe" {
            proxy_pass http://myhost/unsubscribe.php;
            proxy_ignore_client_abort on;
            proxy_set_header X-Channel-Id $nchan_channel_id;
        }

My NGINX version is 1.10.1

For testing I use HTML5 websocket

When I open multiple connections (3-4 or more) or refresh the web page, 
receive various errors

And subscribe / unsubscribe are not called correctly

Last time ... after 2-3 refresh (reconnect) I got this error
*** Glibc detected *** nginx: worker process: malloc (): Memory Corruption: 0x00000000028b1520 ***
...
...

Thank's
Valy

**Comment by slact** [comment]
Can you show me the error log you get? I need to see those "various errors", as I haven't observed this issue.

**Comment by valydvweb** [comment]
OK ... this is the last error .. after more refreshing on webpage

*** glibc detected *** nginx: worker process: malloc(): memory corruption: 0x00000000028b1520 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75f4e)[0x7f482475bf4e]
/lib64/libc.so.6(+0x7a41a)[0x7f482476041a]
/lib64/libc.so.6(__libc_malloc+0x5c)[0x7f4824760b1c]
nginx: worker process(ngx_alloc+0x1e)[0x435dd6]
nginx: worker process[0x41b52d]
nginx: worker process(ngx_palloc+0x43)[0x41b61a]
nginx: worker process[0x45e0d3]
nginx: worker process[0x45c595]
nginx: worker process[0x43b446]
nginx: worker process(ngx_process_events_and_timers+0xaa)[0x433748]
nginx: worker process[0x43974c]
nginx: worker process(ngx_spawn_process+0x43d)[0x438037]
nginx: worker process(ngx_master_process_cycle+0x479)[0x439f56]
nginx: worker process(main+0xb1e)[0x41a5a1]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7f4824704d5d]
nginx: worker process[0x418859]
======= Memory map: ========
00400000-004f6000 r-xp 00000000 b6:27e11 6291522                         /usr/sbin/nginx
006f6000-00708000 rw-p 000f6000 b6:27e11 6291522                         /usr/sbin/nginx
00708000-00978000 rw-p 00000000 00:00 0 
027c1000-0286b000 rw-p 00000000 00:00 0 
0286b000-028cf000 rw-p 00000000 00:00 0 
7f47fc000000-7f47fc021000 rw-p 00000000 00:00 0 
7f47fc021000-7f4800000000 ---p 00000000 00:00 0 
7f4802d17000-7f4802d2d000 r-xp 00000000 b6:27e11 5505069                 /lib64/libgcc_s-4.4.7-20120601.so.1
7f4802d2d000-7f4802f2c000 ---p 00016000 b6:27e11 5505069                 /lib64/libgcc_s-4.4.7-20120601.so.1
7f4802f2c000-7f4802f2d000 rw-p 00015000 b6:27e11 5505069                 /lib64/libgcc_s-4.4.7-20120601.so.1
7f4802f2d000-7f4822f2d000 rw-s 00000000 00:1a 3811842156                  (deleted)/dev/zero
7f4822f2d000-7f4822f32000 r-xp 00000000 b6:27e11 5505205                 /lib64/libnss_dns-2.12.so
7f4822f32000-7f4823131000 ---p 00005000 b6:27e11 5505205                 /lib64/libnss_dns-2.12.so
7f4823131000-7f4823132000 r--p 00004000 b6:27e11 5505205                 /lib64/libnss_dns-2.12.so
7f4823132000-7f4823133000 rw-p 00005000 b6:27e11 5505205                 /lib64/libnss_dns-2.12.so
7f4823133000-7f482313f000 r-xp 00000000 b6:27e11 5505258                 /lib64/libnss_files-2.12.so
7f482313f000-7f482333f000 ---p 0000c000 b6:27e11 5505258                 /lib64/libnss_files-2.12.so
7f482333f000-7f4823340000 r--p 0000c000 b6:27e11 5505258                 /lib64/libnss_files-2.12.so
7f4823340000-7f4823341000 rw-p 0000d000 b6:27e11 5505258                 /lib64/libnss_files-2.12.so
7f4823341000-7f482335e000 r-xp 00000000 b6:27e11 5505084                 /lib64/libselinux.so.1
7f482335e000-7f482355d000 ---p 0001d000 b6:27e11 5505084                 /lib64/libselinux.so.1
7f482355d000-7f482355e000 r--p 0001c000 b6:27e11 5505084                 /lib64/libselinux.so.1
7f482355e000-7f482355f000 rw-p 0001d000 b6:27e11 5505084                 /lib64/libselinux.so.1
7f482355f000-7f4823560000 rw-p 00000000 00:00 0 
7f4823560000-7f4823576000 r-xp 00000000 b6:27e11 5505288                 /lib64/libresolv-2.12.so
7f4823576000-7f4823776000 ---p 00016000 b6:27e11 5505288                 /lib64/libresolv-2.12.so
7f4823776000-7f4823777000 r--p 00016000 b6:27e11 5505288                 /lib64/libresolv-2.12.so
7f4823777000-7f4823778000 rw-p 00017000 b6:27e11 5505288                 /lib64/libresolv-2.12.so
7f4823778000-7f482377a000 rw-p 00000000 00:00 0 
7f482377a000-7f482377c000 r-xp 00000000 b6:27e11 5505194                 /lib64/libkeyutils.so.1.3
7f482377c000-7f482397b000 ---p 00002000 b6:27e11 5505194                 /lib64/libkeyutils.so.1.3
7f482397b000-7f482397c000 r--p 00001000 b6:27e11 5505194                 /lib64/libkeyutils.so.1.3
7f482397c000-7f482397d000 rw-p 00002000 b6:27e11 5505194                 /lib64/libkeyutils.so.1.3
7f482397d000-7f4823987000 r-xp 00000000 b6:27e11 5505365                 /lib64/libkrb5support.so.0.1
7f4823987000-7f4823b86000 ---p 0000a000 b6:27e11 5505365                 /lib64/libkrb5support.so.0.1
7f4823b86000-7f4823b87000 r--p 00009000 b6:27e11 5505365                 /lib64/libkrb5support.so.0.1
7f4823b87000-7f4823b88000 rw-p 0000a000 b6:27e11 5505365                 /lib64/libkrb5support.so.0.1
7f4823b88000-7f4823bb1000 r-xp 00000000 b6:27e11 5505216                 /lib64/libk5crypto.so.3.1
7f4823bb1000-7f4823db1000 ---p 00029000 b6:27e11 5505216                 /lib64/libk5crypto.so.3.1
7f4823db1000-7f4823db2000 r--p 00029000 b6:27e11 5505216                 /lib64/libk5crypto.so.3.1
7f4823db2000-7f4823db3000 rw-p 0002a000 b6:27e11 5505216                 /lib64/libk5crypto.so.3.1
7f4823db3000-7f4823db4000 rw-p 00000000 00:00 0 
7f4823db4000-7f4823db7000 r-xp 00000000 b6:27e11 5505047                 /lib64/libcom_err.so.2.1
7f4823db7000-7f4823fb6000 ---p 00003000 b6:27e11 5505047                 /lib64/libcom_err.so.2.1
7f4823fb6000-7f4823fb7000 r--p 00002000 b6:27e11 5505047                 /lib64/libcom_err.so.2.1
7f4823fb7000-7f4823fb8000 rw-p 00003000 b6:27e11 5505047                 /lib64/libcom_err.so.2.1
7f4823fb8000-7f4824093000 r-xp 00000000 b6:27e11 5505363                 /lib64/libkrb5.so.3.3
7f4824093000-7f4824293000 ---p 000db000 b6:27e11 5505363                 /lib64/libkrb5.so.3.3
7f4824293000-7f482429d000 r--p 000db000 b6:27e11 5505363                 /lib64/libkrb5.so.3.3
7f482429d000-7f482429f000 rw-p 000e5000 b6:27e11 5505363                 /lib64/libkrb5.so.3.3
7f482429f000-7f48242e0000 r-xp 00000000 b6:27e11 5505350                 /lib64/libgssapi_krb5.so.2.2
7f48242e0000-7f48244e0000 ---p 00041000 b6:27e11 5505350                 /lib64/libgssapi_krb5.so.2.2
7f48244e0000-7f48244e1000 r--p 00041000 b6:27e11 5505350                 /lib64/libgssapi_krb5.so.2.2
7f48244e1000-7f48244e3000 rw-p 00042000 b6:27e11 5505350                 /lib64/libgssapi_krb5.so.2.2
7f48244e3000-7f48244e5000 r-xp 00000000 b6:27e11 5505332                 /lib64/libfreebl3.so
7f48244e5000-7f48246e4000 ---p 00002000 b6:27e11 5505332                 /lib64/libfreebl3.so
7f48246e4000-7f48246e5000 r--p 00001000 b6:27e11 5505332                 /lib64/libfreebl3.so
7f48246e5000-7f48246e6000 rw-p 00002000 b6:27e11 5505332                 /lib64/libfreebl3.so
7f48246e6000-7f4824870000 r-xp 00000000 b6:27e11 5505181                 /lib64/libc-2.12.so
7f4824870000-7f4824a70000 ---p 0018a000 b6:27e11 5505181                 /lib64/libc-2.12.so
7f4824a70000-7f4824a74000 r--p 0018a000 b6:27e11 5505181                 /lib64/libc-2.12.so
7f4824a74000-7f4824a75000 rw-p 0018e000 b6:27e11 5505181                 /lib64/libc-2.12.so
7f4824a75000-7f4824a7a000 rw-p 00000000 00:00 0 
7f4824a7a000-7f4824a8f000 r-xp 00000000 b6:27e11 5505184                 /lib64/libz.so.1.2.3
7f4824a8f000-7f4824c8e000 ---p 00015000 b6:27e11 5505184                 /lib64/libz.so.1.2.3
7f4824c8e000-7f4824c8f000 r--p 00014000 b6:27e11 5505184                 /lib64/libz.so.1.2.3
7f4824c8f000-7f4824c90000 rw-p 00015000 b6:27e11 5505184                 /lib64/libz.so.1.2.3
7f4824c90000-7f4824e4a000 r-xp 00000000 b6:27e11 6291602                 /usr/lib64/libcrypto.so.1.0.1e
7f4824e4a000-7f4825049000 ---p 001ba000 b6:27e11 6291602                 /usr/lib64/libcrypto.so.1.0.1e
7f4825049000-7f4825064000 r--p 001b9000 b6:27e11 6291602                 /usr/lib64/libcrypto.so.1.0.1e
7f4825064000-7f4825070000 rw-p 001d4000 b6:27e11 6291602                 /usr/lib64/libcrypto.so.1.0.1e
7f4825070000-7f4825074000 rw-p 00000000 00:00 0 
7f4825074000-7f48250d6000 r-xp 00000000 b6:27e11 6295222                 /usr/lib64/libssl.so.1.0.1e
7f48250d6000-7f48252d5000 ---p 00062000 b6:27e11 6295222                 /usr/lib64/libssl.so.1.0.1e
7f48252d5000-7f48252d9000 r--p 00061000 b6:27e11 6295222                 /usr/lib64/libssl.so.1.0.1e
7f48252d9000-7f48252e0000 rw-p 00065000 b6:27e11 6295222                 /usr/lib64/libssl.so.1.0.1e
7f48252e0000-7f482530c000 r-xp 00000000 b6:27e11 5505217                 /lib64/libpcre.so.0.0.1
7f482530c000-7f482550c000 ---p 0002c000 b6:27e11 5505217                 /lib64/libpcre.so.0.0.1
7f482550c000-7f482550d000 rw-p 0002c000 b6:27e11 5505217                 /lib64/libpcre.so.0.0.1
7f482550d000-7f4825514000 r-xp 00000000 b6:27e11 5505031                 /lib64/libcrypt-2.12.so
7f4825514000-7f4825714000 ---p 00007000 b6:27e11 5505031                 /lib64/libcrypt-2.12.so
7f4825714000-7f4825715000 r--p 00007000 b6:27e11 5505031                 /lib64/libcrypt-2.12.so
7f4825715000-7f4825716000 rw-p 00008000 b6:27e11 5505031                 /lib64/libcrypt-2.12.so
7f4825716000-7f4825744000 rw-p 00000000 00:00 0 
7f4825744000-7f482575b000 r-xp 00000000 b6:27e11 5505281                 /lib64/libpthread-2.12.so
7f482575b000-7f482595b000 ---p 00017000 b6:27e11 5505281                 /lib64/libpthread-2.12.so
7f482595b000-7f482595c000 r--p 00017000 b6:27e11 5505281                 /lib64/libpthread-2.12.so
7f482595c000-7f482595d000 rw-p 00018000 b6:27e11 5505281                 /lib64/libpthread-2.12.so
7f482595d000-7f4825961000 rw-p 00000000 00:00 0 
7f4825961000-7f4825963000 r-xp 00000000 b6:27e11 5505192                 /lib64/libdl-2.12.so
7f4825963000-7f4825b63000 ---p 00002000 b6:27e11 5505192                 /lib64/libdl-2.12.so
7f4825b63000-7f4825b64000 r--p 00002000 b6:27e11 5505192                 /lib64/libdl-2.12.so
7f4825b64000-7f4825b65000 rw-p 00003000 b6:27e11 5505192                 /lib64/libdl-2.12.so
7f4825b65000-7f4825b85000 r-xp 00000000 b6:27e11 5505054                 /lib64/ld-2.12.so
7f4825d71000-7f4825d7a000 rw-p 00000000 00:00 0 
7f4825d80000-7f4825d82000 rw-p 00000000 00:00 0 
7f4825d82000-7f4825d83000 rw-s 00000000 00:1a 3811842158                  (deleted)/dev/zero
7f4825d83000-7f4825d84000 rw-p 00000000 00:00 0 
7f4825d84000-7f4825d85000 r--p 0001f000 b6:27e11 5505054                 /lib64/ld-2.12.so
7f4825d85000-7f4825d86000 rw-p 00020000 b6:27e11 5505054                 /lib64/ld-2.12.so
7f4825d86000-7f4825d87000 rw-p 00000000 00:00 0 
7ffdb2566000-7ffdb257b000 rw-p 00000000 00:00 0                          [stack]
7ffdb259c000-7ffdb259e000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
2016/10/13 00:47:02 [alert] 8682#0: worker process 8690 exited on signal 6 (core dumped)

**Comment by valydvweb** [comment]
It is the first time when this error occurs
usually - worker process ..  (core dumped)

**Comment by slact** [comment]
Alright, I've been able to reproduce this, thanks.

**Comment by slact** [comment]
fixed in 4d1320d

**Comment by valydvweb** [comment]
Now is fine. But .. One more question

Why "unsubribe" is always called after "subscribe", when I refresh the webpage (reconnect) ?

**Comment by valydvweb** [comment]
reconnect (disconnect > connect)

**Comment by slact** [comment]
The unsubscribe request in that case was delayed by 500ms. I've fixed this in 6ffb980a671907ade6.

**Comment by slact** [comment]
Closing this for now. Please open another ticket if you find anypure sub/unsub request issues.
