### ISSUE TITLE
Why do we need nchan_max_channel_subscribers on Redis store?

### ISSUE THREAD

**Issue by supertong** [slact/nchan#265]
Hey,

   I am setting `nchan_max_channel_subscribers = X` on both of my Nchan instances and expect that the total connection capacity would be `2X`. However, this is not the fact because of this line of code https://github.com/slact/nchan/blob/master/src/store/memory/memstore.c#L1969 . The real connection capacity is only X in total. When the subscriber count in Redis reaches number `X`, both Nchan stops accepting new connections.

   Do we really need this check on Redis? It seems unnecessary to me because we already implement the check on memstore level. And, it would also cause some ambiguities if we set `nchan_max_channel_subscribers` to be different numbers on each instance. Let me know what do you think. Thanks!

**Comment by slact** [comment]
You're right, that is not a useful behavior for `nchan_max_channel_subscribers` when using Redis. The idea behind this config is to prevent denial of service attacks, and that's relevant per Nchan server, not per shared Redis data. I will correct this and make a note of it in the config documentation.

**Comment by slact** [comment]
Please re-check the behavior against master, I've merged your changes.
