### ISSUE TITLE
nchan_subscriber_first_message [ oldest | newest | <number> ]

### ISSUE THREAD

**Issue by p34eu** [slact/nchan#267]
If number is used, it crashes nginx with the message in error log:
`invalid nchan_subscriber_first_message value: 1, must be either 'oldest' or 'newest'`

nginx version: nginx/1.11.5
nchan version:nchan-0.99.16

Maybe outdated docs? Otherwise all works fine. 
Thank you

**Comment by slact** [comment]
Numeric values for `nchan_subscriber_first_message` are available starting with version 1.0.0 . I recommend you upgrade your Nchan version, there have been a [lot of fixes since 0.99.16](/slact/nchan/blob/master/changelog.txt)

**Comment by p34eu** [comment]
Wow, thank you again. 
Somehow i missed this update, sorry.
