### ISSUE TITLE
tried adding WAITING chanhead - nchan worker process hang with SSE

### ISSUE THREAD

**Issue by b1c9g76** [slact/nchan#270]
After a bit of a google this seems similar to an earlier bug reported as issue #140 (https://github.com/slact/nchan/issues/140).

We're using version 1.0.3 on Centos 7 (Linux version 3.10.0-327.13.1.el7.x86_64)

We're using SSE rather than longpoll. Any known issues here?

Errors from log below. Basic config below that.

`2016/10/26 10:23:50 [error] 1274#0: MEMSTORE:01: tried adding WAITING chanhead 00007F2D2A342C20 /our_application to chanhead_gc. why?
2016/10/26 10:27:12 [error] 1273#0: MEMSTORE:00: tried adding WAITING chanhead 00007F2D2A342600 /our_application to chanhead_gc. why?
2016/10/26 10:29:18 [error] 1276#0: MEMSTORE:03: tried adding WAITING chanhead 00007F2D2A342C20 /our_application to chanhead_gc. why?
2016/10/26 10:30:21 [error] 1274#0: MEMSTORE:01: tried adding WAITING chanhead 00007F2D2A342C20 /our_application to chanhead_gc. why?
2016/10/26 10:31:26 [error] 1273#0: MEMSTORE:00: tried adding WAITING chanhead 00007F2D2A342600 /our_application to chanhead_gc. why?
2016/10/26 10:41:55 [error] 1274#0: MEMSTORE:01: tried adding WAITING chanhead 00007F2D2A342C20 /our_application to chanhead_gc. why?
2016/10/26 10:45:04 [error] 1274#0: MEMSTORE:01: tried adding WAITING chanhead 00007F2D2A342C20 /our_application to chanhead_gc. why?
2016/10/26 10:46:47 [error] 1276#0: MEMSTORE:03: tried adding WAITING chanhead 00007F2D2A342C20 /our_application to chanhead_gc. why?
2016/10/26 10:49:56 [error] 1274#0: MEMSTORE:01: tried adding WAITING chanhead 00007F2D2A342C20 /our_application to chanhead_gc. why?
2016/10/26 10:54:31 [error] 1273#0: MEMSTORE:00: tried adding WAITING chanhead 00007F2D2A342600 /our_application to chanhead_gc. why?`

Our config is pretty much as vanilla as you can get. We're posting XML to it.

`        location /primary/sse/ {
                nchan_pubsub;
                nchan_channel_id sse_all;
        }`

**Comment by slact** [comment]
Aside from those messages, are you seeing any incorrect behavior?

**Comment by b1c9g76** [comment]
Yes. The worker dies or goes to 100% CPU and no more messages get processed.

It takes an nginx/nchan restart to get things going again.

Thanks,
Brad

**Comment by slact** [comment]
Ok, I know you said your configuration is vanilla, but I still would like to see it. Edit out whatever you need to keep private.Also, how large are the messages being published, how often, and to many subscribers on average?

Basically, do you have a way to consistent reproduce this bug?

**Comment by b1c9g76** [comment]
Hi,

The nchan config is at the bottom of the original post. Just an endpoint and a channel id.

The messages being published range from a few hundred bytes up to 5 or 10 kbytes in length. The messages themselves are XML. Messages are typically less than 5 per second. Less than 10 subscribers.

Unfortunately no, we havent found a pattern yet.

I'm happy to email you the full config including the rest of the unrelated nginx config if you would like it.

Thanks,
Brad

**Comment by slact** [comment]
Yes, please send it to nchan@slact.net . I'll run some tests to see what I can find.

**Comment by tpneumat** [comment]
Hello.  Im having the same issue.  nginx version: nginx/1.6.2 and I installed v1.0.8   Centos 7 

Linux xxx 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Using super basic example of:

```
   location = /sub {
      nchan_subscriber;
      nchan_channel_id foobar;
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_id foobar;
    }

```
For me, it has to do with SSL:

curl --request POST --data "test message" https://mydomain/pub
curl: (52) Empty reply from server
AND worker segfaults
```
nginx log: 2016/12/30 17:23:11 [alert] 10005#0: worker process 10013 exited on signal 11
dmesg: [844154.939984] nginx[10013]: segfault at 0 ip 0000000000424fb9 sp 00007fffcc5e99d0 error 4 in nginx[400000+e1000]
```

SAME request as non SSL works.
curl --request POST --data "test message" http://mydomain/pub
queued messages: 1
last requested: 308 sec. ago
active subscribers: 1
last message id: 1483118902:0

With more advance 'multipub' config, I get these errors:

`2016/12/30 16:55:27 [error] 9529#0: MEMSTORE:01: tried adding WAITING chanhead 000000000147A880 /test to chanhead_gc. why?`

I am using a SHA-256 with RSA Encryption COMODO Wildcard Cert.  Same as I use for many other applications.  

Thx!

**Comment by slact** [comment]
hey @tpneumat , you're experiencing a different issue. Please head over to #299 for discussion of your issue. And yes, this particular issue had been resolved, I just hadn't closed out this ticket.

**Comment by b1c9g76** [comment]
Hi Leo, Yes I can confirm that 270 has not reared it's ugly head since your last commits on the 270 branch.

**Comment by slact** [comment]
Thanks for the confirmation. What a subtle mess that single off-by-one write caused...
