### ISSUE TITLE
'master_process off' segfaults

### ISSUE THREAD

**Issue by kidd** [slact/nchan#271]
For development I usually set these 2 directives 
```
master_process off;
daemon off;
```

if nginx is compiled with nchan, when C-c'ing (to exit nginx), I get a segfault. with any configuration file. just the master_process off is enough.

It is known that 'master_process off' can easily led to segfaults[0], so it may not be an issue of nchan, or we might have to leave with it, but I thought I'd write the issue for future reference.

[0]. https://trac.nginx.org/nginx/ticket/945 .

**Comment by slact** [comment]
fixed in 6650ae0 , it's not the first time I've forgotten to add logic for `master_process off`.

**Comment by slact** [comment]
Closing this, please reopen if you're still having problems.

**Comment by kidd** [comment]
Ah, sorry, I forgot to confirm it here, but it worked perfectly.

Thanks!
