### ISSUE TITLE
max_message buffer not set when channel already exists in redis

### ISSUE THREAD

**Issue by supertong** [slact/nchan#272]
Here is what happened.

When a new nchan instance comes up and connect to redis and the channel already exists in redis, the config `nchan_message_buffer_length` doesn't apply back to memory store. This is because of following lua code
```
if message_len_changed then
  unpacked[1] = "max_msgs+" .. unpacked[1]
  table.insert(unpacked, 2, tonumber(channel.max_stored_messages))
end
```
In redis perspective, the message length doesn't change. However, in the memory store, it's a totally new channel and max_message been set to `-1`, the default value. 
The easiest way to fix it is to let redis always send back `max_msgs+msg` type of information, so the message length in memory store can be updated accordingly. I don't see much performance impact in this way, since it just set the `chanhead->max_message` and do a gc, but still looking for your advises.

Cheers

**Comment by slact** [comment]
I don't want to run message gc every time, so I'm not going to do this the easy way. But your point is valid and I'm going to fix this the right way.

**Comment by slact** [comment]
Closing, this has been implemented for a while now.
