### ISSUE TITLE
Nchan a good fit for our many-user use-case?

### ISSUE THREAD

**Issue by mallyvai** [slact/nchan#283]
Hi Leo,

Nice work with nchan! Read the docs, and wanted to get your thoughts on if you think nchan is a fit for our use-case.

I have a mobile app with >10k concurrent users that send messages to each other and the servers. There's a fleet of <10 or so appservers needed to manage these, and each user may send a new message every 3-5 minutes. Each user is persistently connected to a single appserver for the duration of its session, which usually lasts a few hours.

I was originally thinking of creating a single channel per-user, and having each appserver subscribe to all the channels for each user connected to it. However, it looks like nchan has a 255-channels-per-endpoint limit, meaning this won't work (since we'd need to subscribe to 5-10k channels per endpoint at peak), and endpoints are entirely static. 

The only other thing I can think of is shoving some logic into the appserver subscriber method to setup N/255 connections to a single subscriber endpoint, although I might be misunderstanding something here.

Do you have on any thoughts on how we might properly configure nchan here, or do you think it's not a great fit for our use-case?

Thanks!
Vaibhav

**Comment by slact** [comment]
If I understand you correctly, it sounds like Nchan is just what you need.

So you have users and the app server talking to each other with each user receiving their own messages, and maybe messages from other users.

> I was originally thinking of creating a single channel per-user, and having each appserver subscribe to all the channels for each user connected to it.

Single-channel-per-user seems to be the correct pattern here. However, you don't need the appserver to subscribe to channels -- messages should be sent from users directly to your app, with regular HTTP requests, without the use of Nchan.

It might also make sense to subscribe users to their own channel and some kind of shared channel (for notifications to all the users). 

I hope that answers your question. Let me know if anything is still unclear.

(For in-depth architecting and development, you should hire me for consulting.)

**Comment by mallyvai** [comment]
Hi Leo,

So what you're saying is if I have an endpoint defined:

>     location = /sub {
>       nchan_subscriber;
>       nchan_channel_id $arg_id;
>     }
>
The 255-max-channel limit is for a single websocket (or other subscriber connection)? I could have, say, 10k distinct websockets, all subscribing to 10k different channels, on that same `/sub` endpoint? 

(FYI: The docs currently suggest `Any subscriber location can be an endpoint for up to 255 channels` and higher up says, `Each subscriber can listen to up to 255 channels per connection`, which is subtly conflicting and what led to my confusion) :)

Thanks for the heads-up about the architecture/development consulting (and your speedy response)!

**Comment by slact** [comment]
> The 255-max-channel limit is for a single websocket (or other subscriber connection)? I could have, say, 10k distinct websockets, all subscribing to 10k different channels, on that same /sub endpoint? 

Correct. I've tested it up to several hundred thousand in my own tests, others have had a few million subscribers in production. Beyond that I would recommend scaling out to multiple Nchan servers.

> [...] subtly conflicting and what led to my confusion

I see your point. I will clarify the documentation that the 255-channel limit refers to channel *multiplexing* per a *single subscriber connection*. Look for updated documentation in the next release.

**Comment by slact** [comment]
fixed documentation in d81bb91ae232e7919282

**Comment by foxmanbrasil** [comment]
hello , nchan is great, just i want to know ,,IF ,ther is a way to get somthing like nchan_publisher_upstream_request  ,( parallel)  i mean not waiting proxy url to respond with 200,or 304 publicate the message ??? like this , i can pub the message and send it to URL to save it , faster than waiting the response , thanks
