### ISSUE TITLE
Add NchanSubscriber.js to npm

### ISSUE THREAD

**Issue by joshuaadickerson** [slact/nchan#284]
I'd like to use npm to add a dependency for NchanSubscriber.js.

I would do this myself but I think it makes more sense to make a new repo: "nchan-client" or "nchan-subscriber" from the originator. Then add that to npm.

**Comment by slact** [comment]
I'll do this in a couple of days.

**Comment by kesavkolla** [comment]
Is it available on non now?

**Comment by slact** [comment]
Thanks for the reminder, I just published it. You can grab it with `npm install nchan`. It install exactly the same file NchanSubscriber.js, and it expects to have a window object, so it's strictly for browsers. I will be cleaning up and modularizing the package as  I add more features to it.

**Comment by slact** [comment]
This is done, see https://github.com/slact/nchan.js
