### ISSUE TITLE
Do we sort multiplex channel?

### ISSUE THREAD

**Issue by supertong** [slact/nchan#287]
Hey @slact ,

I notice that when we do multiplex subscribing, a new channel will be created by concatenating channel names. For example, if I subscribe to channel 1, 2 and 3. A channel called m/1,2,3 will be created.

My question is that do you think if it's better to sort the channel name first before we create the channel? Because I don't feel like the fact that to have m/1,2,3 and m/2,1,3 to pollute the channel hash table.

Let me know if I understand the logic correctly. If yes, let me know what you think about this.

Cheers

**Comment by slact** [comment]
Yes, it would be better to sort them. Some message-id-related hacks might break from this (when unsorted, the multi-channel message tags correspond to the channel id's index; sorting the ids will break this correspondence:
```
channel: m/1,2,3
message id: 1479885804:-,[0],-
```
However, the message id is supposed to be opaque to the user, so I do not object to breaking this (undocumented) assumption.

I'm a little busy fixing bugs at the moment. If you have the time, you're welcome to add this to the `nchan_process_multi_channel_id` function in `src/util/nchan_channel_id.c`, it seems like the ideal place for it.

**Comment by supertong** [comment]
Thanks @slact , happy to put this in my plate.

**Comment by slact** [comment]
didn't happen. closing.
