### ISSUE TITLE
Problem with nginx and nchan on Ubuntu

### ISSUE THREAD

**Issue by artukrap** [slact/nchan#292]
I did standard build from source, but still gives me this error `2016/12/14 11:17:28 [emerg] 11689#11689: unknown directive "nchan_subscriber" in /etc/nginx/sites-enabled/dyframe_api.conf:20`

**Comment by slact** [comment]
what's the output of `nginx -V`?

**Comment by artukrap** [comment]
Here it is
user@Lenovo-G50-80 /var/www/project_api $ nginx -V
nginx version: nginx/1.10.1
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module --add-dynamic-module=/build/nginx-STHBxL/nginx-1.10.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-STHBxL/nginx-1.10.1/debian/modules/nginx-dav-ext-module --add-dynamic-module=/build/nginx-STHBxL/nginx-1.10.1/debian/modules/nginx-echo --add-dynamic-module=/build/nginx-STHBxL/nginx-1.10.1/debian/modules/nginx-upstream-fair --add-dynamic-module=/build/nginx-STHBxL/nginx-1.10.1/debian/modules/ngx_http_substitutions_filter_module

**Comment by slact** [comment]
This Nginx binary was not built with Nchan. Are you sure this is the binary that you compiled?

**Comment by artukrap** [comment]
@slact I did built using this command `./configure --add-module=/home/mans_pc/Downloads/nchan`

**Comment by slact** [comment]
i think you're running the system's nginx, and not the version you've built. It may be easier for you to download and run the precompiled ubuntu packages from https://nchan.slact.net/#install

**Comment by artukrap** [comment]
What you you mean by run them? I already did installation of nginx-common and extras.

**Comment by slact** [comment]
Did you download and install them from nchan.slact.net? It looks like you installed them from the Ubuntu repository.

**Comment by artukrap** [comment]
Yes, I installed them from ubuntu repo

**Comment by slact** [comment]
Please uninstall those, and download the two Ubuntu packages from https://nchan.slact.net/#install , and follow the instructions there.

**Comment by artukrap** [comment]
Ok, thanks, will try and if it doesn't work, I will re open issue
