### ISSUE TITLE
Compilation error on freebsd

### ISSUE THREAD

**Issue by SunChero** [slact/nchan#293]
i know you may not support freebsd but thought you maybe interessted in this

/opt/nchan/src/subscribers/longpoll.c:415:16: error: variable 'double_newline_buf' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]
        *buf = double_newline_buf;
               ^~~~~~~~~~~~~~~~~~
/opt/nchan/src/subscribers/longpoll.c:343:3: note: variable 'double_newline_buf' is declared here
  ngx_buf_t             double_newline_buf ;
  ^
1 error generated.
*** Error code 1

**Comment by slact** [comment]
fixed in a619c34 . (The compilation warning is in wrong by the way, there's no possibility `double_newline_buf` may be uninitialized there)
