### ISSUE TITLE
Any chance for Mobile Library

### ISSUE THREAD

**Issue by amiri27** [slact/nchan#296]
Hi,

That would be nice if we could create an Android and IOS library which is ported directly from NchanSubscriber.js . Do you have any plan for that?

Regards,

**Comment by slact** [comment]
The short answer is yes, eventually -- especially if that's the sort of thing you want  to sponsor.

The long answer:

Nchan supports standard protocols  that could be used by any client, which means you can connect with any Android or iOS Websocket or EventSource client.  Websocket connections are resumable only when using the 'ws+meta.nchan' subprotocol, which would be unavailable using a plain client. 

Therefore, I recommend using EventSource clients to connect to Nchan from iOS ( [neilco/EventSource](https://github.com/neilco/EventSource), [SignalR-ObjC](https://github.com/DyKnow/SignalR-ObjC) ) and Android ( [tylerjroach/eventsource-android](https://github.com/tylerjroach/eventsource-android) ).
