### ISSUE TITLE
nchan_publisher_upstream_request does not pass query_string

### ISSUE THREAD

**Issue by seddonm1** [slact/nchan#297]
`nchan_authorize_request` passes $query_string to authorisation URL but `nchan_publisher_upstream_request` does not pass $query_string.

Could you please add it as it should be consistent and would be helpful for message mutation.

**Comment by slact** [comment]
fixed in a7f102e4

**Comment by seddonm1** [comment]
Thanks that works. Haven't been able to get the 200 message mutation to work yet but will keep battling.

**Comment by slact** [comment]
Ok, let me know if you need some help with that.

**Comment by seddonm1** [comment]
Thanks @slact - I am only new to nchan but it is looking great so far.

I have managed to get mutation working with the HTTP_OK (200) response.

Can you please confirm how statements are executed in a PUBLISH or SUBSCRIBE block:
Let's say i wanted authorise, mutate then publish a message to a 'secret' (from consumer) channel I would code something like below. Would this then be executed consistently in the correct order (auth -> mutate -> publish)?

Logically it would make sense that the X-Accel Redirection could validate and mutate the message using the same internal mechanisms as you have already built. Does that make sense?

```
# authorise
nchan_authorize_request /auth;

# mutate
nchan_publisher_upstream_request /mutate;

# publish to channel
proxy_pass http://upstream_app/subscriber_x_accel_redirect;
proxy_set_header X-Forwarded-For $remote_addr;
```

**Comment by seddonm1** [comment]
UPDATE:
I cannot get the HTTP_OK (200) mutation working. I set up a test service but when I do the `nchan_publisher_upstream_request` call it is using the response in the published message. Instead the publisher is inserting a null value (indicated by 'empty message' in a websocket subscriber).

```
curl -v localhost:8181/test
*   Trying ::1...
* Connected to localhost (::1) port 8181 (#0)
> GET /test HTTP/1.1
> Host: localhost:8181
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: openresty/1.11.2.2
< Date: Sun, 25 Dec 2016 00:38:02 GMT
< Content-Type: text/plain
< Connection: keep-alive
< Content-Length: 13
< 
* Excess found in a non pipelined read: excess = 1, size = 13, maxdownload = 13, bytecount = 0
* Connection #0 to host localhost left intact
{"test":"ok"}
```

**Comment by slact** [comment]
Your configuration is not quite right. If you are using X-Accel-Redirect for publishing, the separate requests for auth is unnecessary:
```nginx
location = /api/publish {
   proxy_pass http://upstream_app/publisher_auth_and_internal_redirect;
   proxy_set_header X-Forwarded-For $remote_addr;
}

location /internal/publish {
  internal; #for security
  nchan_publisher;
  nchan_channel_id publish_example;
  nchan_publisher_upstream_request /internal/mutate;
}

location = /internalb/mutate {
  internal; #for security
  proxy_pass http://upstream_app/mutate;
  proxy_set_header X-Forwarded-For $remote_addr;
}

```

Hope that makes more sense. You should also take a look at https://nchan.slact.net/details#application-callbacks if you haven't already.

**Comment by seddonm1** [comment]
Thanks @slact. I'm actually calling OpenResty services for mutation and redirection so maybe my config is a bit tricky.

**Comment by slact** [comment]
If you show me your current config (edited out for privacy, of course), I can show you how to make it work.

**Comment by seddonm1** [comment]
thanks. how about this as an example openresty integration? (I made it up so there may be some typos)

```nginx
# public API
location = /api/publish {
   proxy_pass /internal/publish/router
   proxy_set_header X-Forwarded-For $remote_addr;
}

# route to correct channel
location = /internal/publish/router {
  internal; #for security
  
  content_by_lua '
    ngx.status = ngx.HTTP_OK
    -- this would be dynamically calculated for routing with logic but hard coded here for demonstration
    ngx.header["X-Accel-Redirect"] = "/internal/publish/message" 
    ngx.header["X-Accel-Buffering"] = "no"
  ';
}

# multiple publishers would be here
location /internal/publish/message {
  internal; #for security
  
  nchan_publisher;
  nchan_channel_id publish_example;
  nchan_publisher_upstream_request /internal/publish/message/mutate;
}

# authenticate, validate and either reject or mutate
# ngx.HTTP_NO_CONTENT (204)
# ngx.HTTP_NOT_MODIFIED (304)
# ngx.HTTP_OK (200)
location = /internal/publish/message/mutate {
  internal;
  
  content_by_lua '
    local cjson = require "cjson"

    -- this would be set differently for different queue types
    local dec_body_data = {}
    dec_body_data["test"] = "ok"
    
    local enc_body_data = cjson.encode(dec_body_data)

    ngx.status = ngx.HTTP_OK
    ngx.say(enc_body_data)
  ';
}
```

**Comment by slact** [comment]
Just one simplification: 

```nginx
# public API
location = /api/publish {
  content_by_lua '
    ngx.status = ngx.HTTP_OK
    -- this would be dynamically calculated for routing with logic but hard coded here for demonstration
    ngx.header["X-Accel-Redirect"] = "/internal/publish/message" 
    ngx.header["X-Accel-Buffering"] = "no"
   -- you may want to use openresty's API to trigger the redirect, if X-Accel-Redirect doesn't work
  ';
}

# multiple publishers would be here
location /internal/publish/message {
  internal; #for security
  
  nchan_publisher;
  nchan_channel_id publish_example;
  nchan_publisher_upstream_request /internal/publish/message/mutate;
}

# authenticate, validate and either reject or mutate
# ngx.HTTP_NO_CONTENT (204)
# ngx.HTTP_NOT_MODIFIED (304)
# ngx.HTTP_OK (200)
location = /internal/publish/message/mutate {
  internal;
  content_by_lua '
    local cjson = require "cjson"

    -- this would be set differently for different queue types
    local dec_body_data = {}
    dec_body_data["test"] = "ok"
    
    local enc_body_data = cjson.encode(dec_body_data)

    ngx.status = ngx.HTTP_OK
    ngx.say(enc_body_data)
  ';
}
```

**Comment by seddonm1** [comment]
thanks for your help @slact 

I think perhaps a better model of integration of openresty/nchan is where the external API is the openresty component and it redirects to nchan where appropriate. It works and i think is clearer (in my head at least)

```nginx
location = /api/publish {
  content_by_lua '
    local cjson = require "cjson"

    -- authorise here
    -- hit database or something?

    -- mutate here
    ngx.req.read_body()
    local enc_body_data = ngx.req.get_body_data()
    local dec_body_data = cjson.decode(enc_body_data)

    dec_body_data["test"] = "ok"

    enc_body_data = cjson.encode(dec_body_data)
    ngx.req.set_body_data(enc_body_data)

    -- redirect here
    ngx.exec("/internal/publish/message")
  ';
}

location = /internal/publish/message {
  internal;

  nchan_publisher;
  nchan_channel_id message;
  nchan_use_redis on;
  nchan_channel_group "redis_backed_channel";
}
```

**Comment by slact** [comment]
That makes sense. But keep in mind, that message mutation in this case will not work for websocket publishers, because nginx doesn't see websocket frames as individual HTTP requests.

**Comment by seddonm1** [comment]
I cannot see on your site about scalability in the number of distinct channels. Have you done any testing?

**Comment by slact** [comment]
Yes, and I have yet to hit the limit. Basically, as much as you can fit into memory. A channel takes up about 100-200 bytes on each Nginx worker. For optimal Nchan scalability, the number of workers should match the number of CPU cores.

**Comment by seddonm1** [comment]
Thanks. I'll keep playing and see if I hit any other hurdles. Looks great so far!

**Comment by slact** [comment]
Ok. I'm going to close this issue, as we've gone off-topic. Open up another if you have any questions.
