### ISSUE TITLE
Crash when publishing via SSL on nginx 1.6.2

### ISSUE THREAD

**Issue by slact** [slact/nchan#299]
@tpneumat wrote:

nginx version: nginx/1.6.2 and I installed v1.0.8   Centos 7 

Linux xxx 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Using super basic example of:

```
   location = /sub {
      nchan_subscriber;
      nchan_channel_id foobar;
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_id foobar;
    }

```
For me, it has to do with SSL:

curl --request POST --data "test message" https://mydomain/pub
curl: (52) Empty reply from server
AND worker segfaults
```
nginx log: 2016/12/30 17:23:11 [alert] 10005#0: worker process 10013 exited on signal 11
dmesg: [844154.939984] nginx[10013]: segfault at 0 ip 0000000000424fb9 sp 00007fffcc5e99d0 error 4 in nginx[400000+e1000]
```

SAME request as non SSL works.
curl --request POST --data "test message" http://mydomain/pub
queued messages: 1
last requested: 308 sec. ago
active subscribers: 1
last message id: 1483118902:0

With more advance 'multipub' config, I get these errors:

`2016/12/30 16:55:27 [error] 9529#0: MEMSTORE:01: tried adding WAITING chanhead 000000000147A880 /test to chanhead_gc. why?`

I am using a SHA-256 with RSA Encryption COMODO Wildcard Cert.  Same as I use for many other applications.  

Thx!

**Comment by slact** [comment]
@tpneumat, I can't reproduce this on Nginx 1.6.2 with Nchan 1.0.8, although I'm not running it on CentOS. 

I'd like you to show me output of `nginx -V`, and I also need to see your full config. Feel free to edit out whatever you need for privacy.

**Comment by tpneumat** [comment]
@slact 
nginx version: nginx/1.6.2
built by gcc 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC)
TLS SNI support enabled
configure arguments: --with-http_ssl_module --with-http_stub_status_module --add-module=../nchan-1.0.8

**Comment by slact** [comment]
Can you show me your full nginx.conf as well? (Edit out whatever you need to for privacy)

**Comment by slact** [comment]
Ok, thanks. I'll be testing for this tomorrow.

**Comment by slact** [comment]
Hey, I'm still unable to replicate this. Would it be possible for me to look at your server? Email me at nchan@slact.net and we'll set up a time for me to check it out.

**Comment by tpneumat** [comment]
Hi @slact.  I upgraded my nginx server to nginx-1.10.2 and now everything is working.   Thank you for your efforts!

**Comment by slact** [comment]
ok, thanks for the update. Closing this.
