### ISSUE TITLE
Presence User on channel

### ISSUE THREAD

**Issue by amiri27** [slact/nchan#300]
Hi...

Does nchan provide presence feature based on channel?

Regards,

**Comment by slact** [comment]
Can you be more specific? There are ways to send an upstream request when a subscriber connects and disconnects, and you can also see how many subscribers there are in a channel.

**Comment by amiri27** [comment]
How can we see how many subscribers are in a channel?

**Comment by kidd** [comment]
@amiri27 https://nchan.slact.net/#other-publisher-endpoint-actions
