### ISSUE TITLE
benchmark tool

### ISSUE THREAD

**Issue by mapledan** [slact/nchan#301]
I'm interesting about your benchmark.
What is  your benchmark tool to test the response time?

**Comment by slact** [comment]
Those numbers are from a measurement from within Nchan. To see how it's done, take a look at the macro that enables the collection of the benchmark data: https://github.com/slact/nchan/search?q=NCHAN_BENCHMARK

Basically, this measures the internal time between Nchan receives a message, and publishes it to all relevant subscribers.

I am currently working on an external benchmarking tool that I will be able to use to compare Nchan's performance to that of other pubsub and websocket servers. You can see its progress in [/slact/nchan/tree/master/dev/bench](/slact/nchan/tree/master/dev/bench).

**Comment by mapledan** [comment]
Thanks @slact .

**Comment by minhjc** [comment]
Hi @slact,
