### ISSUE TITLE
MEMSTORE:08: multimsg * timeout!!

### ISSUE THREAD

**Issue by seddonm1** [slact/nchan#305]
I have seen some strange behaviour where a client is connected to nchan via eventsource but no messages were broadcast by nchan to subscriber.

I have been tailing the logs and saw these messages:
2017/01/15 20:15:02 [error] 112#112: MEMSTORE:08: multimsg 0000558721683740 timeout!!
2017/01/15 20:15:06 [error] 112#112: MEMSTORE:08: multimsg 0000558721698A60 timeout!!

Can you please advise what these represent and if I need to do anything to resolve them?

**Comment by slact** [comment]
This is a hundred-byte or so memory leak I had been tracking down for some time. It's [fixed in 1.1.0](https://github.com/slact/nchan/blob/master/changelog.txt#L7) in commit cd9ff92892b8e4a064f4.

**Comment by seddonm1** [comment]
Thanks. Will rebuild my docker image tonight and let it run for a few days.

**Comment by seddonm1** [comment]
Hi leo,
Can you confirm what this message means:
nchan: Missed message for eventsource subscriber: previous message multitag mismatch. Try increasing the message buffer length.

**Comment by slact** [comment]
It means the buffer size for at least one of the multiplexed channels  is too small for the rate at which  messages are being published. Increase the buffer length and this message should go away.

**Comment by seddonm1** [comment]
Havent seen since upgrade to 1.1.0
