### ISSUE TITLE
Can't get buffered messages for multiplexed websocket

### ISSUE THREAD

**Issue by michaelfig** [slact/nchan#306]
First off, thanks for Nchan... it's the cat's meow.

I have a situation where a websocket is subscribed to multiple channels, and I'd like to reconnect with different parameters.  I want to use the lastMessageId to fetch any messages that have been sent in the time since I disconnected the old websocket, the same sort of logic that is used for automatic reconnects.

However, messages sent during the time the client is disconnected appear to be buffered (according to the message publishing statistics), but the client doesn't receive them on reconnect.

Here is my reconnect code:

```javascript
var opt = {
    subscriber: ['websocket']
};
if (this.sub) {
    opt.id = this.sub.lastMessageId;
    this.sub.stop();
}
this.sub = new NchanSubscriber(this.endpoint, opt);
// Set up event handlers, then...
setTimeout(this.sub.start.bind(this.sub), 5000);
// Note that the above introduces a 5 second delay between disconnect and reconnect,
// just to test the message buffers.
```

Here is the nginx configuration, which seems to work fine... messages are routed perfectly through all the channels:

```
location /client/ {
    proxy_pass http://client-redirect.localhost:5000/
    # Authenticates, then returns:
    #  200 OK
    #  X-Accel-Redirect: /internal/client/sub-123,sub-456/AUTH-STRING
    #  X-Accel-Buffering: no
}

location ~ /internal/client/([^/]+)/(.*)$ {
    internal; # Force access via /client/ proxy.
    nchan_pubsub websocket;
    nchan_channel_group mia_devel;
    nchan_message_buffer_length 300;
    nchan_message_timeout 10s;
    nchan_channel_id_split_delimiter ",";
    nchan_subscriber_channel_id "from-server" "$1" "to-client/$2";
    nchan_subscriber_first_message newest;
}
```

When debugging, I notice that message ids for the pubsub look like: `1484850215:-,-,-,[0],-` or `1484852408:[0],-,-,-,-`.  The position of the [0] appears to correspond to the multiplexed channel the message was sent on.

Thanks for any help you can offer,
Michael.

**Comment by slact** [comment]
What do you mean by "reconnect with different parameters"?

**Comment by michaelfig** [comment]
Change the subscription list.

**Comment by slact** [comment]
Oh, ok. That's not really possible right now. Here's a feature proposal on how to do it: https://github.com/slact/nchan/issues/288 . Is that the sort of thing you're looking for?

**Comment by michaelfig** [comment]
Yes, that proposal would do the trick.  But my problem is that even when I don't change the subscription list, my websocket reconnect doesn't receive any of the messages that were buffered between disconnect and reconnect.

**Comment by slact** [comment]
I think the issue here is that the X-Accel-Redirect does not pass the query string to the subscriber location. This is needed because the last message id for Websocket and Eventsource is sent in the `last_event_id` query string parameter. (This is the default for the [nchan_subscriber_last_message_id](https://nchan.slact.net/#nchan_subscriber_last_message_id) setting, which NchanSubscriber.js assumes.)

Make sure to pass the query string, or at least the `last_event_id` parameter, to the subscriber location.

**Comment by michaelfig** [comment]
That was exactly the reason!
Thanks.

**Comment by slact** [comment]
Great! I'll make a note of this in the Readme.
