### ISSUE TITLE
$nchan_stub_status 'stored messages' and 'channels' count displaying extremely large numbers

### ISSUE THREAD

**Issue by brian-labelle** [slact/nchan#307]
We have been using Nchan in production for a little less than a week. Even after restarting nginx, it seems that the values in nchan_stub_status are extremely high. The number of channels and the number of stored messages is over 18 quintillion

```
total published messages: 10
stored messages: 18446744073709551615
shared memory used: 20K
channels: 18446744073709551614
subscribers: 1
redis pending commands: 0
redis connected servers: 0
total interprocess alerts received: 3459
interprocess alerts in transit: 4
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
```

nchan version 1.0.8

**Comment by slact** [comment]
Yeah, that definitely looks wrong. Is this on a 32-bit system? 

Can you also try the latest version (1.1.0) and see if this problem is still present for you?

**Comment by brian-labelle** [comment]
It is running on a 64-bit system. We are using Nchan 1.0.8 compiled against nginx 1.10.2 

The current counters seem to have reset back to normal values. After upgrading to 1.1.0, I will keep an eye on the status to see if the problem persists

**Comment by slact** [comment]
Ok, thanks. Starting with 1.1.0, you can also keep track of aggregate statistics with channel group accounting. I wonder, if this problem is still around, will it also manifest there too?

**Comment by amiri27** [comment]
Hi..

I have the same error with nchan 1.1.0.. The problem appear when we do a reload on nginx.

Here's the output after nginx reload:

total published messages: 6
stored messages: 18446744073709551615
shared memory used: 32K
channels: 18446744073709551406
subscribers: 18446744073709551555
redis pending commands: 0
redis connected servers: 0
total interprocess alerts received: 10300
interprocess alerts in transit: 148
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0


Regards,

**Comment by slact** [comment]
Thanks, I will investigate.

**Comment by slact** [comment]
This should be fixed in 23696c8b. (stub_status stats are also no longer reset after reloads.)

**Comment by amiri27** [comment]
Well done @slact . As soon as you tag a new version I can test that.. 

Regards,

**Comment by slact** [comment]
I tagged a new vbersion yesterday that includes this feature. Feel free to check out v1.1.1.
