### ISSUE TITLE
Receiving messages repeatedly

### ISSUE THREAD

**Issue by argb** [slact/nchan#309]
I saw this directive "nchan_store_messages" and its explanations bellow:
 Publisher configuration. "off" is equivalent to setting nchan_message_buffer_length 0, which disables the buffering of old messages. Using this setting is not recommended when publishing very quickly, as it may result in missed messages.

But It's weird that I repeatedly receive the same messages every time I connect to the server. In some scenarios, I just need one-time notification. For example, the "login notifications', of course, I don't hope to see many login notifications for one person.  But I am a bit of worry with this line: "Using this setting is not recommended when publishing very quickly, as it may result in missed messages." Does it mean I will lose those login notifications probably?

**Comment by slact** [comment]
It means that if you're publishing messages very quickly, there's a chance some may not get delivered to *long-polling* subscribers. Websocket and EventSource should not miss messages. 

For your purposes, you should use the (nchan_subscriber_first_message)[https://nchan.slact.net/#nchan_subscriber_first_message] command.

**Comment by slact** [comment]
You're quite welcome.
