### ISSUE TITLE
Detecting websocket lost connection from a client

### ISSUE THREAD

**Issue by iotch** [slact/nchan#311]
Hello!
Is there a way to detect the connection lost from a client-side? Like with Wi-Fi problems, etc.?

Something like heartbeat message that will be automatically replied by a server with a configured response, like:
```ini
nchan_heartbeat_expect '_ping_';
nchan_heartbeat_response '_pong_';
```
and somewhere in the client code:

```js
var ws = new WebSocket('wss://...');
ws.onmessage = function(e) {
    if(e.data === '_pong_') {
        // check if received within a defined timeout interval 
        // or try to reconnect
    }
}
ws.send('_ping_');
```

I'm aware of `nchan_websocket_ping_interval` but AFAIK it's impossible to read frames directly with browser's websocket client.

thanks!

**Comment by slact** [comment]
[Websocket](https://nchan.slact.net/#websocket) has a built-in ping/pong mechanism.  You can enable periodic pings in Nchan with [nchan_websocket_ping_interval](https://nchan.slact.net/#nchan_websocket_ping_interval).

**Comment by iotch** [comment]
I've tried to set ping every 2 seconds - `nchan_websocket_ping_interval 2` , then I opened a connection in Chrome 47, Firefox 51.0a2, IE11 and Opera 12.16 and disconnected the machine from the Internet. Nothing has happened after several minutes in all browsers - no `onclose` or `onerror` callbacks fired, only in IE11 I got an error `WebSocket Error: Network Error 12002, The operation timed out` after about 30 seconds after disconnect. Then, after about 5 minutes got error 1006 in Chrome and Firefox, but Opera still thought it was connected.

I'm trying to detect a disconnect on a _client_ to notify user about connection problems and try to reconnect. But can't figure out how to do that without echoing every message back and check the time interval or automatic replying to pings _sent as message_ as proposed in my first post.

**Comment by slact** [comment]
Oh, I'm sorry, I didn't read your question carefully.

Browser Websocket implementations don't have a client connection close notification, and only the W3C knows why. Your best bet for now is indeed to echo sent messages. 

And as much as I hate it (because it's such a hack), I might have to add your proposed heartbeat because W3C forgot about client-side pings.

**Comment by iotch** [comment]
Thank you, Leo! This feature will make possible to create a lightweight wrapper over native browser websocket API with reconnect support without involving upstream backend.

**Comment by slact** [comment]
Added in 678f335e.

**nchan_websocket_client_heartbeat** `<heartbeat_in> <heartbeat_out>`  
arguments: 2  
default: `none (disabled)`  
context: server, location, if  
> Most browser Websocket clients do not allow manually sending PINGs to the server. To overcome this oversight, this setting can be used to respond to set up a PING/PONG - like connection heartbeat. When the client sends the server messave <heartbeat_in> (PING), the server automatically responds with <heartbeat_out> (PONG).

**Comment by iotch** [comment]
Unfortunately, I can't test - getting build errors:

> ../nchan/src/store/redis/cmp.c: In function ‘cmp_write_float’:
../nchan/src/store/redis/cmp.c:409:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < sizeof(float); i++)
     ^
../nchan/src/store/redis/cmp.c:409:5: note: use option -std=c99 or -std=gnu99 to compile your code
../nchan/src/store/redis/cmp.c: In function ‘cmp_write_double’:
../nchan/src/store/redis/cmp.c:427:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < sizeof(double); i++)
     ^
../nchan/src/store/redis/cmp.c: In function ‘cmp_read_object’:
../nchan/src/store/redis/cmp.c:2162:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     obj->as.flt = *(float *)(void *)bytes;
     ^
../nchan/src/store/redis/cmp.c:2173:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     obj->as.dbl = *(double *)(void *)bytes;
     ^
cc1: all warnings being treated as errors

I've tried to pass `-std=c99` or `-std=gnu99` to nginx' `--with-cc-opt` but got other errors.

**Comment by slact** [comment]
Those build errors are the result of me updating the cmp message library, unrelated to this bug. (I might downgrade it back)

Please do open another ticket for the different response codes you're seeing in different browsers. I'll investigate it later today.

**Comment by iotch** [comment]
Should the <heartbeat_out> returned 'as-is' when using ws+meta.nchan subprotocol? It seems for me it should be outside of the 'main' messages flow to correctly compare with <heartbeat_in>. I'm not sure, though...

**Comment by slact** [comment]
That is indeed how it works. 

```
wscat -c "ws://127.0.0.2:8082/pubsub/foo" -s "ws+meta.nchan"
connected (press CTRL+C to quit)
> message
  < id: 1486069983:0

message
> _ping
  < _pong
> another message
  < id: 1486069993:0

another message
```

**Comment by iotch** [comment]
Yes, I'm sorry. I was checking with pubsub location.

**Comment by iotch** [comment]
Yes, I'm sorry. I was checking with pubsub location without enabling this setting, that's why there was a meta with the response.
