### ISSUE TITLE
Websocket: should close frame status codes be preserved?

### ISSUE THREAD

**Issue by iotch** [slact/nchan#312]
Hello, Leo.

Some other WS servers are sending back the same status code as provided in the close frame request. However, seems like nchan does not set any close code in response, so the browser always treats it as `1005`. 
Is this intentionally?

Example code:
```js
var ws = new WebSocket('wss://...');
ws.onopen = function() {
   ws.close(); 
   // or:
   // ws.close(4000, 'Custom reason');
}
ws.onclose = function(e) {
   console.log(e.code); // always 1005, instead of 1000 or 4000
}
```

I've checked the specs at https://tools.ietf.org/html/rfc6455#section-7.1.5 but found no clear answer.

thanks!

**Comment by slact** [comment]
Nchan does indeed set the Close code. You can confirm this by deleting a channel with some subscribers connected, you should get code 1001.

When the client sends the first Close frame, Nchan responds with a Close with code 1000. (I double-checked in wireshark). I think the browser doesn't care about the status at that point though, and just closes out with a 1005.

**Comment by iotch** [comment]
> The spec indeed does not specify that the Close code needs to be echoed back, which is why Nchan responds with a "1000".

Echoing close code back is useful because of async nature of the protocol. For example, to auto-reconnect client app should know what was the reason of the last close and wait for the status code, so the decision to reconnect or not should be made in `onclose` handler based on received code. And custom status codes in the range of 4000-4999 is the handy way to know that close request was initiated by the client and no reconnect needed (say, code 4000), or something wend wrong (1001, etc.)

I've tested my example with the `wss://echo.websocket.org` endpoint and custom codes were echoed back correctly.

**Comment by slact** [comment]
Disregard my previous reply.I double checked and I spoke way too soon. 

As you can see in the [code](https://github.com/slact/nchan/blob/master/src/subscribers/websocket.c#L1212-L1228), the responding frame read the incoming Close code and reason, but ignores them when responding. Instead, it sends a code-less Close in response which, of course, is code 1005 for the browser.

I dug around the spec some more, and found a relevant bit in section [5.5.1](https://tools.ietf.org/html/rfc6455#section-5.5.1):

>  (When sending a Close frame in response, the endpoint typically echos the status code it received.)

Weird phrasing for an RFC, as it's neither a MAY nor SHOULD rule. But looks like that's the "typical" behavior, and it seems useful.

So I've fixed this in 850cd289d4bddc9cff0. Now Nchan echoes the close code and reason in its response close frame.

**Comment by iotch** [comment]
Tested and works, thanks!

**Comment by iotch** [comment]
Nope, sorry - getting the following error when no reason specified:

> [alert] 1861#1861: *37 zero size buf in output t:0 r:0 f:0 0000000000AD9682 0000000000AD9682-0000000000AD9682 0000000000000000 0-0

**Comment by slact** [comment]
Ah, quite right. Doublefixed in 7c1807df.

**Comment by iotch** [comment]
Thank you!

**Comment by slact** [comment]
And thank you for submitting this report and testing the fix.
