### ISSUE TITLE
Websocket subscriber may be sent more than one CLOSE frame

### ISSUE THREAD

**Issue by slact** [slact/nchan#314]
@iotch :  

> I tried to send a message to a sub-only location and got closed connection, as expected, but with different close codes and reasons:
> 
> Firefox 51.0a2 - 1008 "Publishing not allowed."
> IE11 - 1005 "Publishing not allowed."
> Opera 12.16 - 1008 "Publishing not allowed."
> Chrome 47 - 1006 ''
> Additionally, Chrome throws WebSocket connection to 'wss://...' failed: Close received after close.

This happens because Nchan erroneously sends the Close frame twice. Chrome's error is most accurate.

**Comment by slact** [comment]
Fixed in b76c3a73. The browsers now report:

Firefox 54.0a1 : 1008 "Publishing not allowed."
IE11                : 1005 "Publishing not allowed." (I guess IE is still a bit dumb...)
Opera 12.14   : 1008 "Publishing not allowed."
Chromium  55 : 1008 "Publishing not allowed"

**Comment by iotch** [comment]
Thank you!
