### ISSUE TITLE
Subscriber disconnect callback/detection/notification

### ISSUE THREAD

**Issue by leung85** [slact/nchan#315]
@slact 

Is there are any client/subscriber disconnect callback/detection/notification??

Our product need a method for publisher to know which subscriber is disconnected, 

I find some similar issues,  but seems those are experimental method and not enough document, 
so I am not sure is below feature already enough for our to implement or not.

In issue #311" - Detecting WebSocket lost connection from a client", 
Is this feature for WebSocket only ?? 
What about for the other polling method ??

In issue  #80 - "Callback when client connect or disconnect",
Is it ready for use ?? 

Many Thanks

**Comment by kidd** [comment]
#80 is totally usable. 
Read the docs at https://nchan.slact.net/details#subsribe-and-unsubscribe-callbacks

**Comment by leung85** [comment]
Thanks @kidd 

Docs state that "the subscribe/unsubscribe hooks are disabled for long-poll and interval-poll clients"
Can I config this hook to be enabled for long-poll and interval-poll clients ??

**Comment by slact** [comment]
> Can I config this hook to be enabled for long-poll and interval-poll clients?

No. but I will enable this in a near future release. Bear in mind that for the poll clients, you'd get a subscrube/unsubscribe call per every message received.
