### ISSUE TITLE
SSE leaks?

### ISSUE THREAD

**Issue by b1c9g76** [slact/nchan#317]
Hi There,

Us again. Large XML messages to multiple endpoints. Using memory as storage. Nchan compiled in. Appears on both our old debug_270 branch and the current tip.

Global config includes: 

    nchan_max_reserved_memory 1024M;
    nchan_subscriber_timeout 70;
    nchan_message_timeout 60;

6 channels. Half like this one:

    location /test/sse/ {
        nchan_pubsub;
        nchan_channel_id test_all;
        nchan_message_buffer_length 100;
    }

and the other half like this:

    location ~ /test/sse/(.+)$ {
        nchan_pubsub;
        nchan_channel_id "$1";
        nchan_message_buffer_length 100;
    }

We see leaks over time in nchan. Quite a lot. 80 odd Mb an hour.

Less than 50 subscribers.

What am I doing wrong here?

Thanks,
Brad

**Comment by b1c9g76** [comment]
Whole nginx file:

# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;
worker_rlimit_core  1024M;
worker_rlimit_nofile 10000;         #temporary workaround for Issue 1078

events {
    worker_connections 1024;
}

http {

    nchan_max_reserved_memory 1024M;
    nchan_subscriber_timeout 70;
    nchan_message_timeout 60;



    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    # Nginx creates temporary files in /var/lib/nginx/tmp
    # if the size of a request is larger than client_body_buffer_size
    # these settings will increase the buffer size over default and
    # will cause them to be removed ("clean") after the request is processed
    client_body_buffer_size     32k;

    # unfortunately this doesn't appear to work?
    # client_body_in_file_only  clean;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;
}

**Comment by b1c9g76** [comment]
The other thing observed is that, after a while and the leaks become prevalent. SIGHUPing nginx leaves worker processes that will not die of their own accord.

**Comment by slact** [comment]
Ok, I'm going to need some more information.
- How large are the messages being sent?
- what Nginx version?
- do you see any suspicious messages in the error log? 
- how reliably reproducible is the issue?

**Comment by b1c9g76** [comment]
Hi,

Messages range in size from a few hundred bytes up to 15k. Most are either one or the other. That is, small or large.

Nginx 1.10.2 (It's also been observed in 1.10.1 with your debug_270 branch)

We've seen a bit of this recently. But likely as a forced restart:

2017/02/17 16:52:15 [error] 17105#0: MEMSTORE:02: force-reaping msg with refcount 1
2017/02/17 16:52:15 [error] 17105#0: MEMSTORE:02: force-reaping msg with refcount 1
2017/02/17 16:52:15 [error] 17105#0: MEMSTORE:02: force-reaping msg with refcount 1
2017/02/17 16:52:15 [error] 17105#0: MEMSTORE:02: force-reaping msg with refcount 1
2017/02/17 16:52:15 [error] 17105#0: MEMSTORE:02: force-reaping msg with refcount 1
2017/02/17 16:52:15 [error] 17105#0: MEMSTORE:02: force-reaping msg with refcount 1
2017/02/17 16:52:15 [error] 17105#0: MEMSTORE:02: force-reaping msg with refcount 1
2017/02/17 16:52:15 [error] 17105#0: MEMSTORE:02: force-reaping msg with refcount 1
2017/02/17 16:52:15 [error] 17105#0: MEMSTORE:02: force-reaping msg with refcount 1
2017/02/17 16:52:21 [info] 21328#0: Using 1048576KiB of shared memory for nchan in /etc/nginx/nginx.conf:52

We can also see this under high load:

2017/02/17 09:54:54 [error] 20755#0: nchan: Received 25 interprocess alerts delayed by 2 sec.
2017/02/17 09:54:54 [error] 20758#0: nchan: Received 24 interprocess alerts delayed by 2 sec.
2017/02/17 09:54:54 [error] 20757#0: nchan: Received 46 interprocess alerts delayed by 2 sec.
2017/02/17 09:54:09 [error] 20757#0: nchan: Received 33 interprocess alerts delayed by 3 sec.
2017/02/17 09:54:09 [error] 20755#0: nchan: Received 28 interprocess alerts delayed by 3 sec.
2017/02/17 09:54:08 [error] 20758#0: nchan: Received 25 interprocess alerts delayed by 2 sec.
2017/02/17 09:54:08 [error] 20757#0: nchan: Received 12 interprocess alerts delayed by 2 sec.
2017/02/17 09:54:00 [error] 20757#0: nchan: Received 1 interprocess alert delayed by 2 sec.
2017/02/17 09:50:12 [error] 20758#0: nchan: Received 7 interprocess alerts delayed by 4 sec.
2017/02/17 09:50:12 [error] 20755#0: nchan: Received 10 interprocess alerts delayed by 4 sec.
2017/02/17 09:50:12 [error] 20757#0: nchan: Received 27 interprocess alerts delayed by 4 sec.
2017/02/17 09:50:11 [error] 20758#0: nchan: Received 4 interprocess alerts delayed by 3 sec.
2017/02/17 09:50:11 [error] 20755#0: nchan: Received 3 interprocess alerts delayed by 3 sec.
2017/02/17 09:50:11 [error] 20757#0: nchan: Received 14 interprocess alerts delayed by 3 sec.
2017/02/17 09:50:10 [error] 20758#0: nchan: Received 24 interprocess alerts delayed by 2 sec.
2017/02/17 09:50:10 [error] 20755#0: nchan: Received 15 interprocess alerts delayed by 2 sec.
2017/02/17 09:50:10 [error] 20757#0: nchan: Received 33 interprocess alerts delayed by 2 s

What we have found since posting this bug that nchan isn't reloading it's config on a SIGHUP. So we might not have actually been running with the 

nchan_subscriber_timeout 70;
nchan_message_timeout 60;

lines. We've since hard restarted nginx but its still there on the server we're seeing this problem. On another server we can reproduce it by leaving these lines out and turn it off by putting them back in.

Either way, shouldn't the memory max out at the number of queued messages per channel?

Thanks.

**Comment by slact** [comment]
Ok, I'd like ou to try this with the latest version of Nchan (1.1.1). I added group accounting which keeps 
accurate track of reserved memory, so having this info will help me understand your issue.

https://nchan.io/#limits-and-accounting

You should also enable nchan_stub_status if you haven't already. This tracks total shared memory page use (so it's less granular, but more complete)

https://nchan.io/#nchan_stub_status-stats

Please make a few records of both while the leak is happening (10-20 minute intervals).  Basically, I need to see if this is a true leak of unaccounted memory, or if the garbage collector for messages failing to keeping.

The messages about delayed interprocess alert are of no issue. In fact, I need to downgrade them from ERROR to NOTICE. The force-reaped messages, however, could be related to this issue, but it's too early to tell at this point.

**Comment by b1c9g76** [comment]
Hi,

We're on the latest version (8th Feb).

I've enabled the group accounting and nchan_stub_status. I'll send some stats across the day as testing with the server ramps up and messages are generated and the issue can be observed.

Couple of questions:

With the group accounting, when the memory maxes out do older messages get culled in favour of newer ones so the system still works? Or just no new messages until the messages expire / get received?

Did you notice the note about SIGHUP? Should nchan reload it's settings along with nginx on a kill -1? On quick testing it appears that nchan is not. Just noting it in case it's a bug.

Thanks,
Brad

**Comment by b1c9g76** [comment]
Also, using your stock example for the group accounting, we're seeing this in the error log:

2017/02/18 07:13:26 [info] 23745#0: Using 1048576KiB of shared memory for nchan in /etc/nginx/nginx.conf:52
2017/02/18 07:17:59 [error] 23752#0: nchan: Group info string too long: max: 512, is: 533
2017/02/18 07:22:23 [error] 23751#0: nchan: Group info string too long: max: 512, is: 533
2017/02/18 07:25:24 [error] 23752#0: nchan: Group info string too long: max: 512, is: 533

**Comment by slact** [comment]
Ack, that's what I get for hardcoding values. Fixed the "group info string too long" error in 7e6aaef4. Please rebuild from master and give it another try.

> With the group accounting, when the memory maxes out do older messages get culled in favour of newer ones so the system still works? Or just no new messages until the messages expire / get received?

The latter -- no new messages until old ones ere evicted. I'm planning on adding forced eviction in the future.

> Did you notice the note about SIGHUP? Should nchan reload it's settings along with nginx on a kill -1? On quick testing it appears that nchan is not. Just noting it in case it's a bug.

This is what happens on a SIGHUP:
1. Nginx master reloads configuration
2. Spawns new workers
3. Sends SIGQUITs to old workers
4. SIGKILLs any remaining old workers

So the only way Nchan isn't receiving new configuration is if an nchan worker fails to terminate, and is unresponsive to a SIGKILL signal. In this case, I would expect the broken worker to be stuck at 100% CPU load. What do you see happening to Nginx workers when you issue a SIGHUP? Do all the old workers exit, or are some left over?

**Comment by b1c9g76** [comment]
Thanks. Group accounting does seem to be working so I'll leave it as is for now - I've not really got the ability to rebuild right now. But will and report back when I can.

On SIGHUP we see sometimes one or two workers get culled and then we have to -9 the rest (we run 4 workers). We haven't observed processor go to 100% but they certainly hang on to the memory until they're killed (as you'd expect). Mostly all 4 stay there and have to be killed separately. We've never seen a problem with new workers spawning or the master process misbehave.

**Comment by slact** [comment]
The issue seems to have been misconfiguration. Closing, reopen if you encounter this again.
