### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by MrDefacto** [slact/nchan#318]
Hi,

On FreeBSD there is compilation error related to redisContext. Latest github version.

`cc -c -fPIC -O2 -pipe  -fstack-protector -fno-strict-aliasing -I /usr/local/include -DNDK_SET_VAR -I src/core  -I src/event  -I src/event/modules  -I src/os/unix  -I /usr/ports/www/nginx/work/nginx_upstream_check_module-10782ea  -I /usr/ports/www/nginx/work/ngx_devel_kit-0.3.0/objs  -I objs/addon/ndk  -I /usr/ports/www/nginx/work/nchan/src  -I objs  -I src/http  -I src/http/modules  -I src/http/v2  -I /usr/ports/www/nginx/work/ngx_devel_kit-0.3.0/src  -I /usr/ports/www/nginx/work/ngx_devel_kit-0.3.0/src  -I /usr/ports/www/nginx/work/ngx_devel_kit-0.3.0/objs  -I objs/addon/ndk  -I src/stream  -o objs/addon/redis/rdsstore.o  /usr/ports/www/nginx/work/nchan/src/store/redis/rdsstore.c
/usr/ports/www/nginx/work/nchan/src/store/redis/rdsstore.c:788:17: error: no member named 'sockaddr' in 'struct redisContext'
  switch(ctx->c.sockaddr.sa_family) {
         ~~~~~~ ^
1 error generated.
*** Error code 1
`

**Comment by slact** [comment]
looking into it

**Comment by slact** [comment]
@MrDefacto, how are you building nchan?

**Comment by MrDefacto** [comment]
very simple way. copy nchan to /usr/ports/www/nginx/work right after "make patch".
and small ports Makefile modyfikaction of nginx port:
CONFIGURE_ARGS+=--add-dynamic-module=/usr/ports/www/nginx/work/nchan

It works flawlessly until now.

**Comment by slact** [comment]
Try re-running the build process from the start. Before, Nchan could use the system's hiredis client if it was installed. However, now it must use the (hacked) bundled version. The Nginx build process decides which to use during the ./configure phase. If all you're doing is re-running make with new Nchan source, you'll get this error.

Make sure you re-run the ./configure step of the Nginx build process to correctly link to the bundled source for the hiredis library. 

Let me know if this helps.

**Comment by MrDefacto** [comment]
Mentioning about hiredis You gave me a good clue... and this:

```
CONFIGURE_ARGS+=--add-dynamic-module=/usr/ports/www/nginx/work/nchan \
		--with-cc-opt="-I ${LOCALBASE}/include/hiredis"
LIB_DEPENDS+=libhiredis.so:databases/hiredis
```

helps ;-)

Thanks!

**Comment by slact** [comment]
Hmm... that shouldn't work though... Nchan should not be linking against the common hiredis library. Built like this, I'd expect it to crash if you try to connect to a redis server.

**Comment by slact** [comment]
Issue looks to have been resolved, closing.

**Comment by guizdiabolik** [comment]
it works for me when : 
deinstall hiredis package then re-run make process for nginx

$ pkg delete hiredis
$ cd /usr/ports/www/nginx && make install
$ pkg install hiredis
