### ISSUE TITLE
HTTP 500 when upgrade from 1.0.3 to 1.1.1 nchan_publisher_upstream_request

### ISSUE THREAD

**Issue by michaeltcoelho** [slact/nchan#319]
Hi everyone, 

I've upgraded my NCHAN from `1.0.3` to `1.1.1` then the directive `nchan_publisher_upstream_request` started not working returning 500 http code.

```
  location ~/pub/(\w+) {
    nchan_publisher;
    nchan_channel_id $1;
    nchan_channel_group "chat";

    # Will dispatch each new pub message request to the chat service
    nchan_publisher_upstream_request /hook/pub;

    nchan_redis_pass redis_cluster; # for redis cluster
  }

  # hooks

  location = /hook/pub {
    proxy_pass http://0.0.0.0:5000/messages/?token=
    proxy_set_header X-Publisher-Type $nchan_publisher_type;
    proxy_set_header X-Prev-Message-Id $nchan_prev_message_id;
    proxy_set_header X-Channel-Id $nchan_channel_id;
    proxy_set_header X-Original-URI $request_uri;
  }
```

I've downgrade my NCHAN back to `1.0.3` and it worked again.

Any idea?
Thanks in advance.

**Comment by slact** [comment]
Hey, I'm unable to reproduce this with 1.1.1

If you're getting a 500 response, there should be something about it in the error logs. What do your error logs look like?

What version of Nginx are you using?

And can you include your complete nginx config? (edit out anything you need to keep private)

**Comment by michaeltcoelho** [comment]
Hi slact, the issue was on my side, sorry, i'll close this PR!
