### ISSUE TITLE
Not persist messages on NCHAN side

### ISSUE THREAD

**Issue by michaeltcoelho** [slact/nchan#320]
Hi people,

I have a scenario where i open a websocket connection to NCHAN listening to many channels, i pub messages to those channels, on the other side i have a microservice app where i persist my messages coming from NCHAN `message forwarding` callback, i do not want NCHAN store those messages on disk or redis, i just want it be a "message exchanger" not publishing  those messages again and again to subscribers each time i refresh my page and it open a new websocket connection to NCHAN. Is there a way where i can tell to NCHAN not to re-publish the same message to the subscribers?

**Comment by slact** [comment]
set [`nchan_subscriber_first_message`](https://nchan.io/#nchan_subscriber_first_message)to `newest`

**Comment by michaeltcoelho** [comment]
Nice Leo!

**Comment by slact** [comment]
Nchan automatically handles CORS. You don't need that if block there. You can configure it with [nchan_access_control_allow_origin](https://nchan.io/#nchan_access_control_allow_origin)

**Comment by michaeltcoelho** [comment]
Hey Leo, 
thanks for your answer but it seems not working well, i tried using `nchan_access_control_allow_origin` in many ways, i'm using it on the `subscriber` endpoint and it's working fine, but not on the publisher endpoint.

The subscriber endpoint:

```bash
location ~ /sub/(\w+)$ {
  nchan_subscriber;
  nchan_channel_id "$1";
  nchan_channel_group "chat";
  nchan_channel_id_split_delimiter ",";
  nchan_access_control_allow_origin *;
  nchan_subscriber_first_message newest;
  
  nchan_redis_pass redis_cluster;
}
```

 The publisher endpoint
```bash
location ~ /pub/(\w+)$  {
  nchan_publisher;
  nchan_channel_id "$1";
  nchan_channel_group "chat";
  nchan_access_control_allow_origin "*";
  
  # Will dispatch each new pub message request to the chat service
  nchan_publisher_upstream_request /hook/pub;
  
  nchan_redis_pass redis_cluster;
}
```
