### ISSUE TITLE
how to get a horizontal scalability of nchan with redis?

### ISSUE THREAD

**Issue by liunian-robert** [slact/nchan#324]
Hi,
I am getting a horizontal scalability of nchan with redis, this is my some configuration:

```
user  root;
worker_processes  3;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
#pid        logs/nginx.pid;
events {
    worker_connections  8192;
}
http {
    #nchan_redis_url redis://192.168.40.128:6379;
    include       mime.types;
    include       proxy.conf;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    #gzip  on;

    nchan_storage_engine redis;

    nchan_redis_storage_mode distributed;

    upstream redis_cluster {
     nchan_redis_server redis://192.168.40.128:6379;
     # you don't need to specify all the nodes, they will be autodiscovered
     # however, it's recommended that you do specify at least a few master nodes.
    }
    upstream authentication {
      server 192.168.40.128;
    }    
    server {
        listen       80;
        server_name localhost default;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
        location / {
            root   html;
            index  index.html index.html;
            proxy_pass http://127.0.0.1:8080;
        }
        #error_page  404              /404.html;
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        location = /auth {
            proxy_pass http://authentication/ims/validate;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Cookie $http_cookie;
            proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
            proxy_set_header X-Publisher-Type $nchan_publisher_type;
            proxy_set_header X-Prev-Message-Id $nchan_prev_message_id;
            proxy_set_header X-Channel-Id $nchan_channel_id;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
        location = /sub {
            nchan_subscriber;
            nchan_authorize_request /auth;
            nchan_subscriber_first_message newest;
            nchan_subscriber_timeout 60;
            nchan_channel_id $arg_id;
            #nchan_max_channel_subscribers 100000;
            #nchan_subscriber eventsource longpoll chunked multipart-mixed http-raw-stream;
            #push_subscriber_concurrency broadcast;
            #nchan_channel_group broadcast;
            nchan_redis_pass redis_cluster;
            #nchan_use_redis on;
        }
        location = /pub {
            nchan_publisher;
            nchan_authorize_request /auth;
            nchan_channel_id $arg_id;
            #nchan_channel_group broadcast;
            nchan_redis_pass redis_cluster;
            #nchan_use_redis on;
        }
    }
}
```
but there is some error, The flowing is error log:

`2017/03/17 16:06:34 [alert] 7162#0: worker process 7227 exited on signal 11 (core dumped)`

so I need some help to right config nchan, after configurating it, I hope to get a horizontal scalability of nchan.

**Comment by slact** [comment]
``` nchan_storage_engine redis; ```
Read the [documentation](https://nchan.io/#nchan_storage_engine). It clearly says, "Development directive to completely replace default storage engine. Don't use unless you are an Nchan developer."

Beyond that, are you using Redis as a single server or as a cluster? For single server, use `nchan_redis_url redis://192.168.40.128:6379`. For clusters, use the `upstream {  }` block with `nchan_redis_pass` -- as [described in the docs](https://nchan.io/#redis).

**Comment by liunian-robert** [comment]
Thank you for your response.

The problem has been solved.The flowing is right configuration:

`user  root;
worker_processes  3;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
#pid        logs/nginx.pid;
events {
    worker_connections  8192;
}
http {
    include       mime.types;
    include       proxy.conf;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    #gzip  on;

     nchan_redis_url redis://192.168.40.128:6379/0;
    upstream authentication {
      server 192.168.40.128;
    }    
    server {
        listen       80;
        server_name localhost default;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
        location / {
            root   html;
            index  index.html index.html;
            proxy_pass http://127.0.0.1:8080;
        }
        #error_page  404              /404.html;
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        location = /auth {
            proxy_pass http://authentication/ims/validate;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Cookie $http_cookie;
            proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
            proxy_set_header X-Publisher-Type $nchan_publisher_type;
            proxy_set_header X-Prev-Message-Id $nchan_prev_message_id;
            proxy_set_header X-Channel-Id $nchan_channel_id;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
        location = /sub {
            nchan_subscriber;
            nchan_authorize_request /auth;
            nchan_subscriber_first_message newest;
            nchan_subscriber_timeout 60;
            nchan_channel_id $arg_id;
            #nchan_max_channel_subscribers 100000;
            #nchan_subscriber eventsource longpoll chunked multipart-mixed http-raw-stream;
            #push_subscriber_concurrency broadcast;
            #nchan_channel_group broadcast;
            nchan_use_redis on;
        }
        location = /pub {
            nchan_publisher;
            nchan_authorize_request /auth;
            nchan_channel_id $arg_id;
            #nchan_channel_group broadcast;
            nchan_use_redis on;
        }
    }
}`

After configure it, The message is sent correctly. thanks again.

**Comment by slact** [comment]
> But I do not quite understand how to get redis to achieve nchan horizontal scalability ?

Connect multiple nginx instances to the same redis server. your subscribers can now scale up horizontally. To scale publishing as well, you need to run a Redis cluster. The larger the cluster, the more message publishing per channel can scale. I explain this in some detail in the second half of my [Nginxconf talk](https://www.youtube.com/watch?v=TVgQSmqWm60).
