### ISSUE TITLE
message  cann't send back to upstream and redis cann't recongnized correct master node 

### ISSUE THREAD

**Issue by liurongwei** [slact/nchan#327]
```
bupstream redis_cluster {
        nchan_redis_server redis://172.17.4.217:6379;
        #nchan_redis_server redis://172.17.4.218:6379;
        #nchan_redis_server redis://172.17.4.219:6379;
        # you don't need to specify all the nodes, they will be autodiscovered
        # however, it's recommended that you do specify at least a few master nodes.    
    }
	
	upstream backend {
        server	172.17.2.122:9292;
    }
	
    server {
	
		error_log  /var/log/nginx/nchan.error.log  info;
		access_log  /var/log/nginx/nchan.access.log  main;
	
		server_name ws.ycapp.yiche.com;
  
        listen  8000;
		
		location = /auth {
			proxy_pass http://backend/nchan/auth;
			proxy_pass_request_body off;
			proxy_set_header Content-Length "";
			proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
			proxy_set_header X-Publisher-Type $nchan_publisher_type;
			proxy_set_header X-Prev-Message-Id $nchan_prev_message_id;
			proxy_set_header X-Channel-Id $nchan_channel_id;
			proxy_set_header X-Original-URI $request_uri;
			proxy_set_header X-Forwarded-For $remote_addr;
		}

		location = /connect {
			nchan_pubsub;
			nchan_channel_id $arg_id;  #id parameters
			nchan_channel_group test;  #the group
			nchan_redis_pass redis_cluster;  #redis cluster
			nchan_message_timeout 5m;	#message timeout
			nchan_message_buffer_length 5;  #buffter size
			nchan_publisher_upstream_request /upstream_pub;  #pub message upstream
			#nchan_authorize_request /auth;  #authrization
		}
		
		location = /upstream_pub {
			proxy_pass http://backend/nchan/pub;
			proxy_set_header X-Publisher-Type $nchan_publisher_type;
			proxy_set_header X-Prev-Message-Id $nchan_prev_message_id;
			proxy_set_header X-Channel-Id $nchan_channel_id;
			proxy_set_header X-Original-URI $request_uri;
		} 
    }`
```
2017/03/18 22:48:17 [error] 34249#0: REDIS SCRIPT ERROR: subscriber_register : @user_script:35: @user_script: 35: -READONLY You can't write against a read only slave.   
2017/03/18 22:48:17 [error] 34249#0: SPOOL:Unexpected spool == nuspool during spool fetch_msg_callback. This is weird, please report this to the developers. findmsg_status: 4
ker process: ../nchan/src/store/spool.c:397: spool_fetch_msg_callback: Assertion `0' failed.
2017/03/18 22:48:17 [notice] 34224#0: signal 17 (SIGCHLD) received
2017/03/18 22:48:17 [alert] 34224#0: worker process 34249 exited on signal 6
2017/03/18 22:48:17 [notice] 34224#0: start worker process 34250
2017/03/18 22:48:17 [notice] 34224#0: signal 29 (SIGIO) received
2017/03/18 22:48:17 [notice] 34250#0: nchan: Established connection to redis at redis://172.17.4.218:6379.
2017/03/18 22:48:17 [notice] 34250#0: nchan: Established connection to redis at redis://172.17.4.219:6379.
2017/03/18 22:48:17 [notice] 34250#0: nchan: Established connection to redis at redis://172.17.4.217:6379.
2017/03/18 22:48:17 [error] 34248#0: REDIS SCRIPT ERROR: add_fakesub : @user_script:24: @user_script: 24: -READONLY You can't write against a read only slave.   
2017/03/18 22:48:36 [error] 34248#0: REDIS SCRIPT ERROR: add_fakesub : @user_script:24: @user_script: 24: -READONLY You can't write against a read only slave.   
2017/03/18 22:48:39 [error] 34248#0: REDIS SCRIPT ERROR: publish : @user_script:164: @user_script: 164: -READONLY You can't write against a read only slave.   
2017/03/18 22:48:51 [error] 34248#0: REDIS SCRIPT ERROR: publish : @user_script:164: @user_script: 164: -READONLY You can't write against a read only slave.   
2017/03/18 22:48:51 [error] 34248#0: REDIS SCRIPT ERROR: publish : @user_script:164: @user_script: 164: -READONLY You can't write against a read only slave.   
2017/03/18 22:48:52 [error] 34248#0: REDIS SCRIPT ERROR: publish : @user_script:164: @user_script: 164: -READONLY You can't write against a read only slave.   
2017/03/18 22:48:52 [error] 34248#0: REDIS SCRIPT ERROR: publish : @user_script:164: @user_script: 164: -READONLY You can't write against a read only slave.   
2017/03/18 22:48:52 [error] 34248#0: REDIS SCRIPT ERROR: publish : @user_script:164: @user_script: 164: -READONLY You can't write against a read only slave.   
2017/03/18 22:48:56 [error] 34248#0: REDIS SCRIPT ERROR: publish : @user_script:164: @user_script: 164: -READONLY You can't write against a read only slave.
```

**Comment by slact** [comment]
the syntax 
```
upstream redis_cluster {
        nchan_redis_server redis://172.17.4.217:6379;
    }
```
can currently be used only for redis *clusters*. You appear to be using a single redis master with slaves.

To do this, you should use the `nchan_redis_url` and `nchan_use_redis` settings. See https://nchan.io/#redis for details.

**Comment by liurongwei** [comment]
thanks ,  with nchan_redis_url & nchan_use_redis it worked，but I still has some question :
nchan_redis_url directive for the single master with slave , when master down failover to other slave nodes ,dose nchan will auto swich to the new master node ?

it seems connect to the specified node only .

the log below :
2017/03/19 18:38:55 [info] 12022#0: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:121
2017/03/19 18:38:55 [notice] 12024#0: using the "epoll" event method
2017/03/19 18:38:55 [notice] 12024#0: nginx/1.10.1
2017/03/19 18:38:55 [notice] 12024#0: OS: Linux 3.10.0-327.el7.x86_64
2017/03/19 18:38:55 [notice] 12024#0: getrlimit(RLIMIT_NOFILE): 1024:4096
2017/03/19 18:38:55 [notice] 12026#0: start worker processes
2017/03/19 18:38:55 [notice] 12026#0: start worker process 12027
2017/03/19 18:38:55 [notice] 12026#0: start worker process 12028
2017/03/19 18:38:55 [notice] 12026#0: start worker process 12029
2017/03/19 18:38:55 [notice] 12026#0: start worker process 12030
2017/03/19 18:38:55 [notice] 12030#0: nchan: Established connection to redis at redis://172.17.4.217:6379.
2017/03/19 18:38:55 [notice] 12027#0: nchan: Established connection to redis at redis://172.17.4.217:6379.
2017/03/19 18:38:55 [notice] 12028#0: nchan: Established connection to redis at redis://172.17.4.217:6379.
2017/03/19 18:38:55 [notice] 12029#0: nchan: Established connection to redis at redis://172.17.4.217:6379.

**Comment by liurongwei** [comment]
@slact thanks ,as you said, i have found the problem ,it was my redis is not the HA mode , so I can only use nchan_redis_url  directive ，please close the issue .

**Comment by slact** [comment]
> for the single master with slave , when master down failover to other slave nodes ,dose nchan will auto switch to the new master node ?

Not yet.  This feature might be added in a future version.

**Comment by terranisu** [comment]
@slact is any news on supporting Redis Sentinel?

**Comment by slact** [comment]
Slave failover is now supported in master, and will be included in the next release.
I will post more details on this as I polish up the rough edges.
