### ISSUE TITLE
Questions about message order, websocket resume, metadata

### ISSUE THREAD

**Issue by vish-k** [slact/nchan#331]
Hello,
Thanks for sharing the product. We are evaluating it for one use case and have following questions -

1. The document mentions the messages are delivered in order, but can you pls elaborate what guarantees message order?
2. Websocket resume: if we use redis cluster to persists messages and a websocket subscriber disconnects for few hours/days, how can it resume from the point it got disconnected? We want the subscriber to get only the messages published after it got disconnected instead of entire messages stored on the channel?
3. How can the subscriber get message metadata? i tried the ws+meta.nchan protocol but the metadata wasn't returned.
4. We want to implement OAuth2 client credential folw and allow only certain apps to publish to a channel and certain apps to subscriber to the channel. How can we do this? Is there documentation/example for this?

Thanks again for your help.

**Comment by slact** [comment]
> 1. The document mentions the messages are delivered in order, but can you pls elaborate what guarantees message order?

Messages are delivered in the order that they are received by the server. For persistent connections, this is guaranteed by the internals of Nchan. For connections that are interrupted, the _message id_ is used to resume from the last received message in a channel. 

> 2. Websocket resume: if we use redis cluster to persists messages and a websocket subscriber disconnects for few hours/days, how can it resume from the point it got disconnected? We want the subscriber to get only the messages published after it got disconnected instead of entire messages stored on the channel?

You will need to make sure the channel has its buffer set to retain messages for the expected number of days. You will need to use the ws+meta.nchan subprotocol, which sends message IDs along with messages. Lastly, you will need to send the last-received message ID when re-initiating an interrupted connection to resume it from that last-received message. By default you can do this by passing the last message ID as the `last_event_id` querystring parameter (configurable via [nchan_subscriber_last_message_id](https://nchan.io/#nchan_subscriber_last_message_id)). 

> 3. How can the subscriber get message metadata? i tried the ws+meta.nchan protocol but the metadata wasn't returned.

The metadata right now consists of the message id and the message's content-type, if given during the publishing POST request. See https://nchan.io/#websocket for info about it. You can also look at the js implementation of the ws+meta.nchan subprotocol in Nchan.js.

> 4. We want to implement OAuth2 client credential folw and allow only certain apps to publish to a channel and certain apps to subscriber to the channel. How can we do this? Is there documentation/example for this?

Yes, you can do this with a combination of [request authorization](https://nchan.io/#request-authorization) to validate the client's Oauth2 token, and possibly using [internal redirects](https://nchan.io/#x-accel-redirect) if you wish to hide the channel id from the subscriber.

Let me know if you have any more questions.

**Comment by vish-k** [comment]
Thanks for the reply. Most of your suggestions helped.Can you pls comment on these follow up questions - 

- How can a particular web-socket subscriber scale horizontally ? e.g. If I have APP1 that subscribes to a channel and APP1 scales horizontally, then each node of APP1 will make a websocket connection to NCHAN and each node will receive all the messages. This will lead to lot of processing on APP1 side to make sure the message is processed by only one node of APP1. Instead, is there a way in NCHAN to group multiple subscriber connections and send a message to only one of the connection in that group?

- I was able to use lua JWT verification module to authenticate client and implement access rules. Although I had to use proxy pass from /auth location to another location which is doing JWT verification. Can I implement JWT verification in /auth location itself and then configure "nchan_authorize_request /auth;" on publish location ? If so what do I need to return from /auth back to publish location? Is returning HTTP 200 sufficient?

- Few minor things I observed related to message ID.... the message IDs were not incremented by 1 but by a random number. Is that on purpose? Also, when I use $nchan_prev_message_id, it appeds 3 at the end e.g. the message ID 1490732477:0 becomes 1490732477:3 when another message is published.

**Comment by slact** [comment]
> How can a particular web-socket subscriber scale horizontally? ]...] is there a way in NCHAN to group multiple subscriber connections and send a message to only one of the connection in that group?

I don't understand your question. But perhaps it might be answered with [channel multiplexing](https://nchan.io/#channel-multiplexing).


> Can I implement JWT verification in /auth location itself and then configure "nchan_authorize_request /auth;" on publish location ? If so what do I need to return from /auth back to publish location? Is returning HTTP 200 sufficient?

Yes. This is thoroughly documented here: https://nchan.io/#request-authorization

> Few minor things I observed related to message ID.... the message IDs were not incremented by 1 but by a random number. Is that on purpose? Also, when I use $nchan_prev_message_id, it appeds 3 at the end e.g. the message ID 1490732477:0 becomes 1490732477:3 when another message is published.

The message ID is made up of the current timestamp and a per-second counter. But this is really an implementation detail and you don't need to concern yourself with its format.

**Comment by vish-k** [comment]
Thanks for your reply.

> > How can a particular web-socket subscriber scale horizontally? ]...] is there a way in NCHAN to group multiple subscriber connections and send a message to only one of the connection in that group?
> 
> I don't understand your question. But perhaps it might be answered with channel multiplexing.
My question is about horizontal scaling of _subscribing (& publishing) apps_.
In my use case, we have one application (java web application) publishing messages and one java web app subscribing messages. These apps publish and subscribe over websocket. 
My problem is, when subscribing application is horizontally scaled, it may endup creating multiple subscribing websockets to the nchan channel. Each published message will be received by each websocket client of the subscribing app. So different nodes of same subscribing app will end up with a copy of same message. Instead, is there a way to group/cluster subscribing websocker clients so that nchan pushes published message, from the channel, to only one of the web socket in that websocker client cluster/group?
If there is no option in nchan/nginx for such grouping of websocket clients, are you aware of technique/s used on websocket client side to create a cluster of websocket clients so only one client in the cluster receives a message (e.g. in round robin fashion)? 
Hope I was able to explain the problem. Thanks in advance for your input. Appreciate your time and efforts.

**Comment by vish-k** [comment]
Closing issue. I got into different topic than the initial question. Will open separate issue for handling horizontally scaled subscribers.
