### ISSUE TITLE
Sending message from Rest Servers to Subscriber tasks?

### ISSUE THREAD

**Issue by nginxsantos** [slact/nchan#333]
I am on need of a webserver to the front end of my susbcriber tasks (1:N, 1 Rest Server for N Subscriber Tasks). The communication between the webservers and my tasks would be over TCP. 
So, can I used nchan for this purpose? The Nchan receives the HTTP messages, it will parse the message and then put to those registerd TCP clients. Any idea how can this be done. 
Thanks, Santos

**Comment by slact** [comment]
This would require integration with the Nginx stream module, which is tricky, as Nchan in an HTTP module. Another way would be to add a Lua API to Nchan, and have the Nginx Lua Stream module perform the hand-off between the TCP client and Nchan. The second approach is currently more feasible. Either way, doing this requires a fair amount of dev time. 

Is there a way you could use websocket or http-stream subscribers? If so, you could use Nchan directly. What kind of subscriber tasks do you have?

**Comment by nginxsantos** [comment]
Thanks. Is the LUA capable enough to exchange between HTTP module to TCP module?
Any reference?
Thanks. Santos

**Comment by slact** [comment]
I don't know. The HTTP an Stream lua modules are separate, but I will probably be able to register the future Nchan Lua API in both. But I have yet to fully explore and implement this feature, so I'm not 100% certain.
