### ISSUE TITLE
Nchan NGINX config settings behind AWS ELB - Load Balancer ?

### ISSUE THREAD

**Issue by bgildea** [slact/nchan#336]
I have NGINX running on port 80 behind an Amazon Web Services ELB Load balancer which has an SSL cert installed with a https listener.

What should my NGINX config be to get nchan working for pub sub?

- The ELB handles the SSL cert
- NGINX server does port 80 --> port 443

**Screenshot of ELB**
https://ibb.co/eLU3rF

**Listener Rule:**
HTTPS 443 --> HTTP 80 --> with SSL Cert

**My NGINX config is set like this:**

```
server {
    listen       80;
#    server_name  new.mydomain.com www.mydomain.com;
    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;

# Where I am redirecting http to https using NGINX server variables

location / {
        if ($http_x_forwarded_proto != 'https') {
       return         301 https://$server_name$request_uri;
        }

        root   /var/www/html/app;
        index  index.php index.html index.htm;

    add_header  X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

    # NCHAN
    
    location = /sub {
      nchan_subscriber;
      nchan_channel_id $arg_id;
    }
    location = /pub {
      nchan_publisher;
      nchan_channel_id $arg_id;
    }
    #NCHAN ends

    # redirect server error pages to the static page /50x.html
        error_page 404 /404.html;
        location /404.html {
        root /var/www/html/app/errors;
        internal;
}

# pass the PHP scripts to FastCGI server listening on /var/run/php5-fpm.sock
   location ~ \.php$ {
           root /var/www/html/app;
           try_files $uri =404;
           fastcgi_pass unix:/var/run/php5-fpm.sock;
           fastcgi_index index.php;
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           include fastcgi_params;

}

# deny access to .htaccess files, if Apache's document root
# concurs with nginx's one
#
location ~ /\.ht {
   deny  all;
}

}
```

**What would I then set my eventsource pub sub URL's to allow Nchan to work?**

- 127.0.0.1/pub
- http://MyIP/pub
- https://DomainName/pub?

**Websockets? :**
ws://127.0.0.1/pub
wss://127.0.0.1/pub

**Comment by slact** [comment]
First, it depends on where you're accessing it from. Locally, 127.0.0.1/... would work, from the outside, I guess it would be https://DomainName/... . That's kind of up to your load balancer. 

Second, Eventsource can't be a publisher, but only a subscriber. Websocket could be a publisher or subscriber, so you could connect to either location, or a combined `pubsub` location if you wanted to.

**Comment by supertong** [comment]
@bgildea My 2 cents here. We are using TCP protocol instead of HTTP between the connection of ELB and Nchan. I don't go into much detail because I don't think I fully understand how ELB works, but if you have problems with random connection dropping, try TCP. It was manly due to the HTTP `keep live` header.

**Comment by slact** [comment]
I think this has been adequately answered. Please reopen if not.
