### ISSUE TITLE
Websockets client behind University firewall/proxy

### ISSUE THREAD

**Issue by iNDicat0r** [slact/nchan#340]
Installed a websocket client, works fine within my network when connecting to nchan, however when i am behind a university network some strange things are going on.
First, when i connect to a sub endpoint the connection seems to be established but i am not getting updates.
Second, when i connect to a pub endpoint and publish message to that channel i get the indication that the message has been sent, but actually the message hasnt been sent since i am subscribing to that channel from another open network(4g) and can't see the published message:

```
queued messages: 2
last requested: ....
..
```

Any idea?

Regards

**Comment by slact** [comment]
This is a general issue of running a websocket server behind a proxy. It's not strictly related to Nchan.

For maximum compatibility, it's recommended that websocket servers are run over TLS/SSL, that way proxies are much less likely to mess with the connection.

**Comment by iNDicat0r** [comment]
OK thanks. Can i use a self signed certificate without getting warning etc? or is it gonna shout ?

**Comment by slact** [comment]
You can use a self-signed cert for testing, but of course browsers are going to complain about it.

**Comment by iNDicat0r** [comment]
Perfect!! Thanks
