### ISSUE TITLE
How to handle horizontally scaled websocket subscriber/publisher?

### ISSUE THREAD

**Issue by vish-k** [slact/nchan#341]
In my use case, we have one application (java web application) publishing messages and one java web app subscribing messages (more will be added later). 
These apps publish and subscribe over websocket.

My problem is, when subscribing application is horizontally scaled, each of it's node creates subscribing websocket to the _nchan_ channel. Each published message will be received by each websocket client of that subscribing app. So different nodes of same subscribing app will end up with a copy of same message. 

Instead, is there a way to group/cluster subscribing websocket clients so that _nchan_ pushes published message, from the channel, to only one of the web socket in that websocket client cluster/group? I have searched for options but haven't found any.

_If there is no option in nchan/nginx for such grouping of websocket clients, are you aware of technique/s used on websocket client side to create a cluster of websocket clients so only one client in the cluster receives a message (e.g. in round robin fashion)?_

Hope I was able to explain the problem. Thanks in advance for your input. Appreciate your time and efforts.

**Comment by slact** [comment]
I've given it some thought, and I don't think this is possible with Nchan. But because you don't need to *broadcast* messages, most event-driven frameworks will handle what you want to do quite well. So you could write something in Node.js if you wanted to, or maybe using Python's Twisted, or whatever else is out there.

**Comment by vish-k** [comment]
Thanks! That helps.
