### ISSUE TITLE
nchan_redis_server failed

### ISSUE THREAD

**Issue by minminmsn** [slact/nchan#342]
hello
redis3.0.7 cluster
coffig
upstream redis_cluster {
    nchan_redis_server redis://172.17.1.17:6379;
    nchan_redis_server redis://172.17.1.18:6379;
    nchan_redis_server redis://172.17.1.19:6379;
}

location = /sub {
    nchan_subscriber;
    nchan_channel_id $arg_vid;
    nchan_redis_pass redis_cluster;
  }

logs
cess: ../nchan-1.1.3/src/store/redis/cluster.c:559: cluster_run_retry_commands: Assertion `cluster->status == CLUSTER_READY' failed.

**Comment by rgshare** [comment]
I am his colleague and we are working together to solve this problem.<br/>
The NGINX config is set like this:
```nginx
upstream redis_cluster {
  nchan_redis_server redis://172.17.1.17:6379;
  nchan_redis_server redis://172.17.1.18:6379;
  nchan_redis_server redis://172.17.1.19:6379;
}

server { 
  listen       80;
  root  /usr/local/nginx/html;

  location = /sub {
    nchan_subscriber;
    nchan_channel_id $arg_vid;
    nchan_redis_pass redis_cluster;
  }

  location = /pub {
    nchan_publisher;
    nchan_channel_id $arg_vid;
    nchan_redis_pass redis_cluster;
  }

  location = /status {
    internal;
    nchan_stub_status;
  }
}
```
And the `nchan_stub_status` Response:
```
total published messages: 3
stored messages: 3
shared memory used: 12K
channels: 0
subscribers: 0
redis pending commands: 1
redis connected servers: 1590502
total interprocess alerts received: 0
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
```
I think these something wrong with `redis connected servers`.

**Comment by slact** [comment]
Hah, yeah, I doubt you're actually connected to 1.5 million redis servers : )

So I need some more info to debug this:
- Nchan version
- Nginx version (nginx -v and nginx -V)
- Redis cluster status when this error happened.
- What you were doing with Nchan when this error happened
- Steps to reproduce the error, if possible

**Comment by rgshare** [comment]
Os version is `CentOS Linux release 7.2.1511 (Core)`
Nchan version is `1.1.3`.
Nginx is build from source , and the version info
```
nginx version: nginx/1.10.3
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
configure arguments: --sbin-path=/usr/local/nginx --conf-path=/usr/local/nginx.conf --pid-path=/usr/local/nginx/nginx.pid --with-http_realip_module --with-http_sub_module --add-module=../nchan-1.1.3
```
Redis cluster status is normal, but Redis cluster' server NIC traffic is very large.
When configured the config and restart nginx,  I only accessed and refreshed the status page and found that the  `redis connected servers` statistics were growing fast. Then, I use `curl` to send messages, the response sometimes normal, sometimes empty.

```bash
curl --request POST --data "test message" -H "Accept: text/json" http://localhost/pub?vid=5201314
```

**Comment by minminmsn** [comment]
redis cluster status 

[root@redis17 ~]# redis-trib.rb check 172.17.1.17:6379
>>> Performing Cluster Check (using node 172.17.1.17:6379)
M: 5882abf414ac96828eaa2e66d3ef5de27caa5f45 172.17.1.17:6379
   slots:0-5460 (5461 slots) master
   1 additional replica(s)
M: 52712bf739d4de63284710b7ddd9a3c982192356 172.17.1.19:6379
   slots:10923-16383 (5461 slots) master
   1 additional replica(s)
M: 2774b572770b184ea72b28904f44386ac65a18d8 172.17.1.18:6379
   slots:5461-10922 (5462 slots) master172.1
   1 additional replica(s)
S: 227e1e820b8877684690b706be796ebd360d0fc7 172.17.1.18:6380
   slots: (0 slots) slave
   replicates 5882abf414ac96828eaa2e66d3ef5de27caa5f45
S: 3a535ce5d39a1e2ff1135eef0385e23c907299fb 172.17.1.17:6380
   slots: (0 slots) slave
   replicates 52712bf739d4de63284710b7ddd9a3c982192356
S: d8a688d058dfbe36bc36449d8038455c2b61b75a 172.17.1.19:6380
   slots: (0 slots) slave
   replicates 2774b572770b184ea72b28904f44386ac65a18d8
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.

**Comment by slact** [comment]
Ok, thanks for that info. The next thing I need is a log of this crash, and also a coredump if possible.

Here's what you'll need to do to get those: 

1. Get Nchan from the 342-debug branch. It just enabled debug logging for the redis cluster code.
2. Build Nginx with that Nchan version and this option: `--with-cc-opt="-ggdb -fvar-tracking-assignments -O0"` . This ensures that a readable coredump will be generated. (Do **not** configure with `--with-debug`, it's too verbose.)
3. Ensure Nginx can drop coredump when it crashes. You can test it manually by sending a SIGABRT (6) or SIGSEGV (11) to an nginx worker.
4. Make sure you have an `error_log` configured in the root-level of your nginx.conf . That means it should be outside of any http {} or stream {} blocks, probably on the first few lines. Set it to `notice` level: `error_log /path/to/error.log notice;`

Then, run Nginx as usual. When you observe the error, send me the coredump from the *first* observed crash, the nginx binary, and the error log. You can post it somewhere or email it to me at leo@nchan.io .

**Comment by rgshare** [comment]
Hi,  I didn't see the 342-debug branch.

**Comment by slact** [comment]
My bad, I forgot to push the branch. [342-debug](/slact/nchan/tree/342-debug)

**Comment by rgshare** [comment]
I have sent you the email.🙂

**Comment by slact** [comment]
Thanks. Not sure why, but gdb can't read the coredump. Can you double check it? Run `gdb /path/to/nginx/binary /path/to/coredump`, and pust the output of `bt full`

**Comment by slact** [comment]
Nevermind, the coredump isn't important, I've found the issue. Looks like I left in an unnecessary assert() in 1.1.3. I've updated master and 342-debug, you can use either branch to test the fix. Once you can verify it I will tag and release a new version with this fix.

**Comment by rgshare** [comment]
I recompile and run the code and it looks good.

**Comment by slact** [comment]
Great, thanks for your bug report. I'll be releasing a version with this fix shortly.
