### ISSUE TITLE
publish through redis

### ISSUE THREAD

**Issue by notedit** [slact/nchan#343]
hi:

my use case is that we have so much publish message,   100ms per channel.  so publish through http publish is a little expensive.  can we use  redis to publish message?

**Comment by notedit** [comment]
maybe something like  admin publisher.    make a  long  conection ,  can send message to  any channel.

**Comment by slact** [comment]
You can use HTTP2 if the HTTP overhead is too much for your use case. I have no plans for a way to publish messages directly through Redis.

**Comment by notedit** [comment]
HTTP2 looks good.    i will try it.
