### ISSUE TITLE
How to define dynamic groups while using nchan_channel_id_split_delimiter?

### ISSUE THREAD

**Issue by Revisor** [slact/nchan#347]
When using channel multiplexing with `nchan_channel_id_split_delimiter`, can I further split the channel IDs and use parts of them to assign channels to groups?

For example:

The subscription location is `sub/messages_123,thread_456`

Using `nchan_channel_id_split_delimiter ",";` I get two channel IDs: `messages_123` and `thread_456`.

Can I split this further so that I can tell Nchan that the channel `messages_123` belongs to the group `messages` and the channel `thread_456` belongs to the group `thread`?

**Comment by slact** [comment]
That's currently not possible, Right now, you can assign only one group per location, regardless of how many channels are multiplexed on it. 

Would you mind explaining your use case? I chose not to implement multi-group location because it's a bit tricky to implement and even more difficult to document its usage -- and I wasn't sure the users would need it. So if I know why you need it i might be persuaded to implement group multiplexing -- or maybe I could suggest an alternative way of solving your problem.

**Comment by Revisor** [comment]
This is all still in the planning stage, anything can be changed. I'll just write down all my reasoning.

1. Why dynamic channels?
We want to be able to deploy new channels without having to change the configuration of Nginx/Nchan

2. Why multiplexing?
[Based on your advice](https://github.com/slact/nchan/issues/298#issuecomment-269839064), I want all subscriptions that require an authorization go through a single endpoint.

```
location ~ /live/channel/private/(\d+)/(.+) {
  nchan_subscriber;
  nchan_channel_id user_$1 "$2";
  nchan_channel_id_split_delimiter ",";
  nchan_authorize_request /live/channel/private/authorize;
}
```
So that all authorized subscriptions also subscribe to the channel `user_foo` and when user foo logs out, we can automatically stop all his authorized subscriptions by deleting the channel `user_foo`.

Btw. will that definition of channel IDs work? Will `nchan_channel_id_split_delimiter` understand that one variable needs to be split and the other not?

3. Why groups?
There will be more authorized channels, say `private_messages`, `new_posts` etc. I would like to watch the stats for these channels as a group, eg. all `private_messages_foo|bar|baz`, all `new_posts_foo|bar|baz` etc.

It is not neccessary, but it would be nice.

Is the plan sound? Will it work, or does it need changes?

**Comment by slact** [comment]
It is sound. The first configuration you have, 
```nginx
location ~ /live/channel/private/(\d+)/(.+) {
  nchan_subscriber;
  nchan_channel_id user_$1 "$2";
  nchan_channel_id_split_delimiter ",";
  nchan_authorize_request /live/channel/private/authorize;
}
```
will work as intended and is easier to understand, so go with that one. Bear in mind that you should check the values if `$1` and `$2` in your authorization code to make sure the user is authorized to subscribe to all the provided channels.

As for groups -- yeah, that makes sense. Unfortunately, I designed groups mainly for non-overlapping channels, so you can't really keep track of stats they way you would like. I can see yours as a pretty common use case, but I don't know yet how to address it cleanly. For now, you'll need to make do with non-granular stats tracking.

**Comment by Revisor** [comment]
Thank you very much for having a look at it.
The groups are no big problem.

Thanks a lot for Nchan and for your help!
