### ISSUE TITLE
Worker Crash (Assertion `!msg_in_shm' failed.) with Redis

### ISSUE THREAD

**Issue by Jamie0** [slact/nchan#351]
Often, when using a REDIS backed nchan, one of the workers ungracefully quits due to an assertion error. I am not sure the exact circumstance that causes the crash, but it happens every ~30 minutes when there is a very light load (2-3 clients).  

As a result, this renders the nchan server completely unusuable until nginx is restarted or reloaded. For instance, if I were to run `curl -v http://webapi.insanityradio.com/subscribe?id=1`, TCP handshake is ok but there is no response from nginx at all - the connection completely hangs. 

	2017/04/29 12:38:17 [notice] 16596#16596: signal process started
	2017/04/29 12:38:17 [info] 16599#16599: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:73
	2017/04/29 12:38:17 [error] 16603#16603: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{16603:time:1493465897} (1 total)
	2017/04/29 12:38:17 [error] 16605#16605: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{16605:time:1493465897} (1 total)
	2017/04/29 12:38:17 [error] 16603#16603: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{16603:time:1493465897} (1 total)
	2017/04/29 12:38:17 [error] 16605#16605: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{16605:time:1493465897} (1 total)
	2017/04/29 12:38:17 [error] 16602#16602: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{16602:time:1493465897} (1 total)
	2017/04/29 12:38:17 [error] 16602#16602: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{16602:time:1493465897} (1 total)
	2017/04/29 12:38:17 [error] 16606#16606: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{16606:time:1493465897} (1 total)
	2017/04/29 12:38:17 [error] 16606#16606: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{16606:time:1493465897} (1 total)

	ker process: /build/nginx/debian/modules/nchan/src/store/memory/memstore.c:3150: nchan_store_publish_message_to_single_channel_id: Assertion `!msg_in_shm' failed.
	2017/04/29 12:50:39 [alert] 16601#16601: worker process 16606 exited on signal 6 (core dumped)
	2017/04/29 12:50:39 [error] 28712#28712: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{28712:time:1493466639} (1 total)
	2017/04/29 12:50:39 [error] 28712#28712: REDISTORE: REDIS: PUB/SUB subscribed to nchan_worker:{28712:time:1493466639} (1 total)

The following data was the body of the posted message:

	{"nowPlaying":{"song":"Life Itself","artist":"Glass Animals","external_id":61596878,"nerve_id":1864,"external_urls":{"spotify":"https://open.spotify.com/track/3HVRywtkhSjhpmkaeaYTgh"},"album_art":"https://i.scdn.co/image/1bd2aa194cd3fdf54ce5bcc1064ec52a28f7c5d2"},"currentShow":{"dayOfTheWeek":"saturday","showName":"Best Of The Playlist","showPresenters":"Insanity Radio"},"now":"2017-04-29T12:50:39+0100"}

This is the configuration being used (nginx/1.10.1-2ubuntu1 with nginx-extras.deb):

	nchan_redis_url "redis://127.0.0.1:6379";
	nchan_use_redis on;
	nchan_redis_storage_mode backup;
	nchan_message_timeout 0;
	nchan_message_buffer_length 60;

	location = /subscribe {
		nchan_subscriber;
		nchan_channel_id $arg_id;
		
		nchan_channel_group public;
		nchan_subscriber_first_message -10;
	}

	location = /publish {
		allow 10.32.0.0/24;
		deny all;
		
		nchan_publisher;
		nchan_channel_id $arg_id;
		nchan_channel_group public;
	}

(I've tried several combinations of settings, but the bug only seems to occur whenever we're using a redis-backed store. Redis is configured to factory defaults. )

**Comment by slact** [comment]
I'm working on a fix right now to #345, which I suspect is caused by the same issue. I'll have the fix later today, but will need a few days to test. 

I see you're using the packaged ubuntu version, which is a couple months behind the latest release. If you're up for rebuilding Nchan and want to help test the fix, let me know.

**Comment by slact** [comment]
Please try version 1.1.5, which probably fixes this issue.

**Comment by Jamie0** [comment]
I can't seem to replicate this with 1.1.6. Seems to be solved! :-)
