### ISSUE TITLE
Suspicious subscriber count

### ISSUE THREAD

**Issue by caseyf** [slact/nchan#358]
I just ran out of worker connections and checked my nchan stats and saw that my subscriber count was 412,286

This is at least 10x higher than what I'd consider to be a "normal" number. 

All of the clients are using nchan.js with the default 1 second reconnection. I restarted nginx  and after waiting for a bit, it is showing 21,000 subscribers, which is typical.

**Comment by caseyf** [comment]
(on second thought, I'll come back with more information next time. Now that I've restarted it, it's too late to look at netstat etc)

**Comment by slact** [comment]
Ok, reopen this if it keeps being suspicious.
