### ISSUE TITLE
Get only new messages after subscribe

### ISSUE THREAD

**Issue by surajsavita** [slact/nchan#360]
Thanks for such a great module.

I am planning to use nchan for notification system where on page load client will subscribe to channel and then publisher will publish to user specific channels and notifications will be sent to client via SSE.

So the problem I am facing with this solution is that on first subscription to nchan it gets older messages as well which are already present using REST call. Though I can use timestamp based message id but that requires clock sync on both client and server which is hard implement.

So if there is any configuration or workaround I can do to implement this please let me know, it'll be of great help.

Cheers.

**Comment by slact** [comment]
Easy - https://nchan.io/#nchan_subscriber_first_message

**Comment by surajsavita** [comment]
Thanks it works perfectly.
