### ISSUE TITLE
last_message_id using Redis always "0:0"

### ISSUE THREAD

**Issue by CheAlex** [slact/nchan#363]
Hi Leo

Can you please recheck this issue https://github.com/slact/nchan/issues/169 in redis context? I build latest Nginx (1.13.1) with latest Nchan(1.1.6) and if using shared memory, so it's work perfect:

`curl --request POST --data "test message" -H "Accept: text/json" http://myip:8080/pub`
`{"messages": 1, "requested": 22, "subscribers": 1, "last_message_id": "1496660639:0" }`

`curl -v --request GET -H "Accept: text/json" http://myip:8080/pub`
`{"messages": 1, "requested": 28, "subscribers": 1, "last_message_id": "1496660639:0" }`

but using redis (2.8.23) "requested" field has strange value "-1" and "last_message_id" is empty:

`curl --request POST --data "test message" -H "Accept: text/json" http://myip:8080/pub`
`{"messages": 1, "requested": 0, "subscribers": 1, "last_message_id": "1496663600:0" }`

`curl -v --request GET -H "Accept: text/json" http://myip:8080/pub`
`{"messages": 1, "requested": -1, "subscribers": 1, "last_message_id": "0:0" }`

Data in Redis:

![](https://raw.githubusercontent.com/CheAlex/images/master/slact_nchan_issues_363/2017-06-05%2014%3A54%3A01.png)
![](https://raw.githubusercontent.com/CheAlex/images/master/slact_nchan_issues_363/2017-06-05%2014%3A54%3A06.png)
![](https://raw.githubusercontent.com/CheAlex/images/master/slact_nchan_issues_363/2017-06-05%2014%3A54%3A11.png)

Config:

```
server {
  listen 8080;

  location = /sub {
    nchan_subscriber;
    nchan_channel_id foobar;
    #nchan_use_redis on;
    #nchan_redis_url "redis://redis-master:6379";
  }

  location = /pub {
    nchan_publisher;
    nchan_channel_id foobar;
    #nchan_use_redis on;
    #nchan_redis_url "redis://redis-master:6379";
  }
}
```

**Comment by slact** [comment]
Fixed in commit 894d3b32029e0a65b473ec3a8178080dd1c6dd52
