### ISSUE TITLE
Weird behaviour after hitting nchan_max_reserved_memory and nchan_message_buffer_length

### ISSUE THREAD

**Issue by b1c9g76** [slact/nchan#364]
Hi Mate,

What we've found (albeit an earlier branch 1.0.8) is that once we hit the max reserved memory we get slow / irregular message delivery afterwards on SSE.

To reproduce we send large messages (around 16k of xml a pop) and when it hits the memory and message limit we get server errors. That's fine we know this happens when you hit the limit. But what happens afterwards is that we still seem to get messages through in dribs and drabs and then the messages never seem to timeout or properly accept all new messages - even before re-hitting the limit. Often new messages will get accepted but won't get delivered for a while. Sometimes 30 minutes or more. No errors observed in the logs.

In production we generally run with 1024M of reserved memory so it takes a while to show up but I can reproduce with the config below.

Ring any bells?

Thanks,
Brad

 

 nchan_max_reserved_memory 1M; 

        location /placement/sse/ {
            nchan_pubsub;
            nchan_channel_id outgoing_all;
            nchan_message_buffer_length 1000;
        }

        location /outgoing/sse/ {
            nchan_pubsub;
            nchan_channel_id outgoing_all;
            nchan_message_buffer_length 1000;
        }

        # outgoing and bet placement are the same
        location ~ /outgoing/sse/(.+)$ {
            nchan_pubsub;
            nchan_channel_id "$1";
            nchan_message_buffer_length 1000;
        }

        location ~ /placement/sse/(.+)$ {
            nchan_pubsub;
            nchan_channel_id "$1";
            nchan_message_buffer_length 1000;
        }

**Comment by b1c9g76** [comment]
I've had more of a look this morning. Setting nchan_message_timeout to 1m seems to prevent me from reproducing this. In production here we were relying on the 1h default.

**Comment by b1c9g76** [comment]
So it might need the hour to occur. Did some more testing today with it relying on the 1h default for message timeouts and set the nchan_message_buffer_length to 100.

Put in 60 odd messages to hit the low limit of 1M. Kept adding more messages past this limit.

Waited more than 1 hour. Added another 10 messages. On the first message nchan returns with queued messages of 58. Shouldn't it have gone back to 0?

So I'm wondering that are these extra messages that were over the memory limit somehow still getting added into a queue and then don't get expired when they should? This would match what we're seeing in production of a "lower limit" of messages hanging around consuming resources.

Thanks.

**Comment by b1c9g76** [comment]
I think I've managed to explain this one our side with a rogue process posting messages when I wasn't expecting it. However we are still experiencing odd behaviour. Will have to investigate further.

**Comment by slact** [comment]
Things get quite weird with memory running out for Nchan < 1.1.5. Version 1.1.5 and later handle out-of-memory conditions much more gracefully and stuck messages like you've described should no longer occur.

**Comment by b1c9g76** [comment]
Hi Leo,

Yeah, problem is I don't think it's hitting the memory limit now in prod. Something else is going on which i havent managed to catch yet. Only thing I can see is interprocess alerts in transit getting stuck.

I'll have to bite the bullet and upgrade prod and see if it goes away.

Thanks,
Brad

Bradley Goldsmith
+61 414 514 077
