### ISSUE TITLE
Is there any way to directly publish a message to redis without going through nginx?

### ISSUE THREAD

**Issue by rishiloyola** [slact/nchan#368]

**Comment by slact** [comment]
For the same of experimentation, yes. You could run the lua script that handles publishing directly on the Redis server. In practice, this is a very very bad idea, as the script's hash may change from release to release, as may the script parameters.

**Comment by rishiloyola** [comment]
We have around 20k users. And each user has unique URL to get the notification data. Sometimes we have to do bulk operations to send the notification to all the users. In this case rather than creating 5k or 10k HTTP post(publisher endpoint) requests, we want to make a single connection to publish all the data together. Is there any way to do this? 

We are planning to make one single connection between redis and our backend and then we are planning to publish data directly to the redis channels.

**Comment by slact** [comment]
For bulk notifications, you should make use of [channel multiplexing](https://nchan.io/#channel-multiplexing). Set up each user to subscribe to his own channel and a shared channel.
