### ISSUE TITLE
nchan not loading lua scripts into redis

### ISSUE THREAD

**Issue by benwilber** [slact/nchan#370]
I am trying to configure a redis backend but it appears that the lua scripts are not getting loaded initially:

```
2017/07/03 20:06:43 [error] 22031#0: REDIS REPLY ERROR: NOSCRIPT No matching script. Please use EVAL.
```

I checked `redis-cli monitor` and see that it is making this redis command:

```
1499112473.517179 [1 127.0.0.1:40500] "EVALSHA" "c7abd99d4fb2717fb1f3b16013baa778fe0a0828" "0" "" "/foo" "1499112473" "Hello World" "application/x-www-form-urlencoded" "" "3600" "0" "5120"
```

My configuration looks like this:

```nginx
  location ~ /chan/(.+)$ {
    expires -1d;
    nchan_pubsub;
    nchan_channel_id $1;
    nchan_channel_id_split_delimiter ",";
    nchan_store_messages off;
    nchan_use_redis on;
    nchan_redis_url redis://127.0.0.1:6379/1;
  }
```

Is there something additional that I need to do to make sure the lua scripts get loaded?  This is the publish command that I'm using:

```shell
$ curl -X POST -d "Hello World" http://localhost:8080/chan/foo
```

I'm using nginx 1.10.2, nchan 1.1.6, and redis 3.2.3 just in single standalone mode.

Thanks!

**Comment by slact** [comment]
The scripts are loaded automatically when Nchan connects to redis. Can you post the output of `redis-cli monitor` started *before* nginx? Also, can I see the full Nginx config? (edit out whatever you need to keep private)

**Comment by benwilber** [comment]
This is the output of `redis-cli monitor` before I restart nginx:

```shell
# redis-cli monitor
OK
1499271443.293964 [0 127.0.0.1:34640] "SELECT" "1"
1499271443.293991 [0 127.0.0.1:34642] "SELECT" "1"
1499271443.294943 [0 127.0.0.1:34644] "SELECT" "1"
1499271443.294961 [0 127.0.0.1:34646] "SELECT" "1"
```

Those look like the nginx processes connecting and selecting the database, but there aren't any Lua scripts getting loaded.


Here's the full nginx config:


```nginx
user nginx;
worker_processes auto;
worker_rlimit_nofile 65535;
error_log /var/log/nginx/error.log warn;
pid /run/nginx.pid;

events {
    worker_connections 10240;
    multi_accept on;
    use epoll;
}

http {
    log_format  main  '"$http_x_forwarded_for" - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_host" "$http_x_forwarded_proto" "$http_referer" '
                      '"$http_user_agent" "$request_time"';

    access_log  /var/log/nginx/access.log  main;
    resolver 127.0.0.1 valid=300s;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    client_max_body_size 10G;

    include             mime.types;
    default_type        application/octet-stream;

    server {
        listen 8080;
        server_name _;
        root /var/www;

        location ~ /chan/(.+)$ {
            expires -1d;
            nchan_pubsub;
            nchan_channel_id $1;
            nchan_channel_id_split_delimiter ",";
            nchan_store_messages off;
            nchan_use_redis on;
            nchan_redis_url redis://127.0.0.1:6379/1;
        }
    }
}
```

**Comment by benwilber** [comment]
UPDATE:

I do indeed see the Lua scripts get loaded if I don't specify a database in the redis url

```
nchan_redis_url redis://127.0.0.1:6379;
```

So it appears to happen only when a database is selected

**Comment by slact** [comment]
I am unable to reproduce this. I see scripts being loaded regardless of the database number. Would it be possible for me examine this on the machine where this is happening?

**Comment by benwilber** [comment]
@slact yeah sure, email me benwilber@gmail.com and I'll send you some login info

**Comment by slact** [comment]
¯\_(ツ)_/¯
