### ISSUE TITLE
Rising interprocess_alerts_in_transit / interprocess_queued_alerts after nginx reload

### ISSUE THREAD

**Issue by maximsnezhkov** [slact/nchan#372]
Hello, @slact we need your advice
nginx 1.11.3 + nchan 1.1.6
nginx custom build:
`
nginx -V
nginx version: nginx/1.11.3
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
built with OpenSSL 1.0.2k  26 Jan 2017 (running with OpenSSL 1.0.2h-fips  3 May 2016)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_perl_module=dynamic --add-dynamic-module=njs-0.1.0/nginx --with-threads --with-stream --with-stream_ssl_module --with-stream_geoip_module=dynamic --with-http_slice_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-http_v2_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --add-dynamic-module=nchan-1.1.6
`

nginx.conf:

```
load_module "modules/ngx_nchan_module.so";
```

after some failure we enable stab status on localhost,:
```
server {
listen 127.0.0.1:80;
server_name  localhost;

location /nchan_stub_status {
    nchan_stub_status;
    }
}
```
publisher:
```
server {
    listen 127.0.0.1:1181;
    access_log /var/log/nginx/nchan_access.log main;
    error_log /var/log/nginx/nchan_error.log;
    location ~ /pub/(\w+)$ {
        nchan_publisher;
        nchan_channel_id "$1";
        nchan_message_timeout 3m;
        nchan_message_buffer_length 1000;
    }
```
subscribers:
```
server {
    listen 172.25.25.25:443 ssl;
    include         include/example_cert.conf;
    server_name example.net;
    location ~ /sub/(\w+)$ {
        nchan_subscriber;
        nchan_subscriber_timeout 3600;
        nchan_channel_id "$1";
        nchan_channel_events_channel_id evt;
    }
}
```
graph with this config:
![nchan-1 1 6](https://user-images.githubusercontent.com/3039558/27900812-ed81b4be-6259-11e7-803c-d42c4aab53c5.png)

Same vhosts + update nginx to last stable version and nchan to last version
`
nginx -V
nginx version: nginx/1.12.0
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
built with OpenSSL 1.0.2k  26 Jan 2017 (running with OpenSSL 1.0.2h-fips  3 May 2016)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie' --add-dynamic-module=nchan-1.1.7
`
graph:
![nchan-1 1 7](https://user-images.githubusercontent.com/3039558/27900859-1b4b7696-625a-11e7-8f0d-3ff01fb93819.png)

Our questions:
1. Are there any settings which would allow to avoid the continuous growth interprocess because according to the documentation they should tend to zero
2. None of the timeouts have not configured it for 30 minutes why the graphs clearly pulsation every 30 minutes?

**Comment by slact** [comment]
Thanks for this detailed report. Can you disable the `nchan_channel_events_channel_id` setting and see if this problem persists?

**Comment by snezhkov** [comment]
The results of our research revealed that the scheduler(cron) had the script
`nginx -s reload` every 30 minutes. It became clear that the reload has a negative impact on the work of nchan and we rewrote the script to avoid this. I apologize for the inconvenience. This problem can be closed.

**Comment by slact** [comment]
Ok, thanks for the clarification. That's still a bug, those stats should not grow after a reload. I'll update this when I figure out the cause.

**Comment by slact** [comment]
foxed a long time ago, just never updated the ticket. my bad.
