### ISSUE TITLE
memstore.c:3053:44: error: variable 'err' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]

### ISSUE THREAD

**Issue by SunChero** [slact/nchan#373]
compilation error  with freebsd 11 ( nchan v1.1.7)
initializing the variable fix the problem

```
- char   *err;
+ char   *err = NULL;
```

**Comment by slact** [comment]
GCC's equivalent "-Wmaybe-uninitialzied" didn't pick this up. I've added "-Wconditional-uninitialized" to the clang dev & testing build, and also fixed the warning. 

Fixed in 57d08aa9.
