### ISSUE TITLE
Nginx with nchan crashing in ubuntu xenial

### ISSUE THREAD

**Issue by cyberinferno** [slact/nchan#376]
I downloaded latest .deb files from nchan.io and installed it in my Ubuntu 16.04 server. I'm using this server only for pub/sub . After running it for a while Nginx crashes and in it's error log there is only 1 error message i.e. "Invalid directive 'nchan_subscribe'".  I cannot start Nginx again as it keeps showing the same error message. The issue is solved only after I reinstall Nginx using .deb files again. Is this some known issue? Is there some solution?

**Comment by slact** [comment]
There is no issue here. The nginx + nchan package replaces ubuntu's nginx-extras. You should lock the package so that it doesn't get automatically updated and replaced. Here's how: https://askubuntu.com/questions/18654/how-to-prevent-updating-of-a-specific-package

**Comment by cyberinferno** [comment]
Ok I will try this solution!
