### ISSUE TITLE
nchan 配置了redis缓存消息

### ISSUE THREAD

**Issue by zhourongfu** [slact/nchan#378]
nchan 配置了redis缓存消息 为什么线上测试配置redis会影响线上的消息存储

**Comment by zhourongfu** [comment]
upstream timed out (110: Connection timed out)
upstream timed out (110: Connection timed out)
upstream timed out (110: Connection timed out)
upstream timed out (110: Connection timed out)

MEMSTORE:03: multimsg 00007F219AD69070 timeout!!
MEMSTORE:03: multimsg 00007F219AD69070 timeout!!
MEMSTORE:03: multimsg 00007F219AD69070 timeout!!

**Comment by slact** [comment]
I don't understand.

**Comment by slact** [comment]
Closing. Please reopen if you have more information that I can understand.
