### ISSUE TITLE
Dynamic module for Ubuntu nginx.org's Linux packages

### ISSUE THREAD

**Issue by tflin** [slact/nchan#380]
Thanks for writing this great nchan module.

We are using the nginx.org's Linux packages on Ubuntu at http://nginx.org/en/linux_packages.html#mainline
There are already some other dynamic module packages available and they always keep compatible with latest nginx mainline release (almost monthly updated). It will be very useful to provide nchan as a dynamic module on Ubuntu not just Debian since Ubuntu is more popular. Currently the provided nginx and nchan for Ubuntu are static linked which is not usable for users using the mainline release from nginx.org.

**Comment by jails** [comment]
I'm working on Unbuntu and after adding this PPA `https://launchpad.net/~nginx/+archive/ubuntu/stable`, I was able to install nchan as a dynamic module like so:
`apt-get install libnginx-mod-nchan`

**Comment by slact** [comment]
@tflin : @jails ' solution is probably the best way to go. Is there any particular reason you _need_ to use nginx's mainline packages?

**Comment by tflin** [comment]
Nginx's mainline package is always with latest bug fixes and features. Nginx.org also recommended to use mainline version: "We recommend that in general you deploy the NGINX mainline branch at all times." in https://www.nginx.com/blog/nginx-1-6-1-7-released/
So it is reasonable to use mainline package in Ubuntu from nginx.org.

**Comment by slact** [comment]
Well, it's true that Ubuntu's packages lag behind by a version or two. I will try to add support for the Nginx mainline package in the near future. Thanks for the recommendation.

(If you're so inclined, I could be incentivized to do it soon.)

**Comment by tflin** [comment]
Sure, we have been using Ubuntu nginx mainline package for years and it works well with features we want such as http/2...etc. We would like to use nchan dynamic module with the mainline package rather than the statically built old nginx package. Hopefully it will be available soon.

**Comment by jails** [comment]
@tflin, @slact ngninx also provide [a PPA for its mainline version](https://launchpad.net/~nginx/+archive/ubuntu/development). I didn't test it personally but should work the same way.
