### ISSUE TITLE
Detect which websocket subscriber disconnected?

### ISSUE THREAD

**Issue by nlyan** [slact/nchan#383]
Hi,

Sorry if this is a duplicate of #315 but, despite scouring the docs and fiddling with it, i can't figure out how to do this. 

Is there a way to get some sort of "subscriber id" when a subscriber connects such that it can be included in the unsubscribe callback when they disconnect?

**Comment by nlyan** [comment]
One way to do this seems to be use the nginx $connection variable to get the connection serial number.

**Comment by slact** [comment]
You can have each websocket url subscribe to a url with a different query string:

`/sub/channel_id?websocket_id=1`
`/sub/channel_id?websocket_id=2`

Then, your unsubscribe callback could look like this:
```nginx
location /unsub {
  proxy_pass http://127.0.0.1/unsub?ws_id=$arg_websocket_id;
  #...
}
```

**Comment by nlyan** [comment]
Ah, obviously! That would save maintaining a map between subscriber id and nginx's connection id

Keep up the great work, absolutely fantastic project
