### ISSUE TITLE
Pub in NchanSubscriber.js

### ISSUE THREAD

**Issue by arnuschky** [slact/nchan#384]
Is publishing supported by the NchanSubscriber.js? I can't figure out how to send data.

**Comment by slact** [comment]
No, that library is for subscribing only. You can, however, use its websocket object to publish to a pubsub location.  see https://github.com/slact/nchan.js/issues/1

**Comment by arnuschky** [comment]
Ah, I didn't realize that there's a separate repo. A pity that we can't use it. Maybe I misunderstand, but what use has publishing to the websocket object if the connection goes via eg longpolling?

**Comment by slact** [comment]
Yes, I think you misunderstood. IF you use NchanSubscriber to connect with websocket, THEN you could use the websocket object for publishing. This is the only case where publishing from NchanSubscriber could make sense.

In all other cases, you should send a POST requst to the publishing URL to publish messages, as described at https://nchan.io
