### ISSUE TITLE
MJPEG - Streamer

### ISSUE THREAD

**Issue by uasan** [slact/nchan#387]
Hello.

Can i do as in example `nginx-push-stream-module`?

https://github.com/wandenberg/nginx-push-stream-module/blob/master/docs/examples/m_jpeg.textile#m_jpeg

Thanks.

**Comment by slact** [comment]
Yes, but you will need to publish the stream chunks pre-formatted. Use the raw-stream subscriber and publish the messages with a multipart/x-mixed-replace content-type.

(Nchan has a multipart/mixed subscriber type already that takes care of the chunking, but it uses the `multipart/mixed` content-type and not `multipart/x-mixed-replace`. I can add a setting for the multipart subtype in a future version of Nchan.

push-stream module has message formatting.

**Comment by uasan** [comment]
>  I can add a setting for the multipart subtype in a future version of Nchan.

It will be very good.
Thanks.

**Comment by uasan** [comment]
My usecase:
There is an IP camera that gives the MPEG stream, according to the HTTP request
```
GET /cgi-bin/mjpg HTTP/1.0

HTTP Code: 200 OK
Content-Type: multipart/x-mixed-replace; boundary=<boundary>

--<boundary>
Content-Type: image/jpeg
Content-Length:<image size>
```
We need to send this stream copy, to many users.

**Comment by uasan** [comment]
How do i post a video stream from ip-camera to Nginx (nchan) channel?

Should I use ffmpeg?
`ffmpeg -i http://ip-camera/mjpeg -o http://nginx/pub`

Or, nchan can send HTTP request to ip-camera to receive the stream?
Thanks.

**Comment by slact** [comment]
I don't tyink you will not be able to hook up ffmpeg directly to Nchan. You will need to transform ffmpeg output to individual Nchan post requests.

If you need help putting the two together, please contact me via https://nchan.io/support .

**Comment by toke** [comment]
I've experimented a bit with it (just for learning – I won't use it for anything) and wrote down some notes: https://toke.de/blog/20190613-nchan-mjpg/ if you're interested.
