### ISSUE TITLE
another client nchan

### ISSUE THREAD

**Issue by subhanshuja** [slact/nchan#394]
Hi slact,
i like with nginx, after i saw nchan. Nchan is awesome, make me like nginx more than before. I need your help, i have projects on mobile application and web application. aren't there client for mobile application, for example java-nchan-client. my web application doesn't need composer or nodejs because my partner said that i don't need those. i think nchan client is possible have another client without composer and nodejs.

thanks a lot 
slact

**Comment by slact** [comment]
You can use EventSource or Websocket clients native to the mobile platform.

**Comment by subhanshuja** [comment]
okey, what about web application are same with mobile platform. i want to create by myself client, any suggestion. or i have to fork your client javascript inside nchan.

thanks a lot 
slact
