### ISSUE TITLE
nginx behind a proxy + websockets

### ISSUE THREAD

**Issue by ReubenM** [slact/nchan#397]
I have nginx behind a proxy that is set to pass websocket connections to nginx. However that means that the upgrade headers get removed, so nginx is getting a direct websocket connection, and mistakenly treats it as an http/1.1 connection. Is there any effective way to deal with this in an nchan endpoint without resorting to using wss:// connections?

**Comment by slact** [comment]
This is a websocket issue outside the scope of Nchan. The Websocket authors recommend using https:// to intiate the connection. This way, the headers are opaque to the proxy, and it will pass everything to your server.

**Comment by ReubenM** [comment]
Yeah, I was just hoping there might be a way for an endpoint to receive a connection directly in websocket mode if there was presence of something like a websockets version header, but without the connection update header.

No worries though. It's mostly a matter of me being lazy and not wanting to manage certificates on ec2 hosts and aws load balancers.
