### ISSUE TITLE
Change Channel using NchanSubscriber

### ISSUE THREAD

**Issue by tpneumat** [slact/nchan#399]
What is the best what to ‘change’ channels from with the NchanSubscriber.js.  We’ve resorted to having to completely destroy the subscriber object and connection every-time we need to add/remove a channel from the client.  Other things we've tried (like disconnect/connect) result in receiving dupe messages.  Is there some other supported way to just update the channels listened too that destroy, recreate?

**Comment by slact** [comment]
Reconnecting is currently the only way to switch channels. Other options may be offered in the future if there is enough interest and incentive.
