### ISSUE TITLE
Last request to channel in seconds in JSON

### ISSUE THREAD

**Issue by kilgor** [slact/nchan#402]
I think it will be good idea if you can add "last requested in seconds" in JSON resp after publishing message
with Accept: text/json
 
https://github.com/slact/nchan#publishing-messages

Currently only text response have this information.

**Comment by slact** [comment]
In theory, yes. In practice, I won't be changing the name of this already well-established JSON attribute, even if it is a bit ambiguously named. Too much backwards compatibility to worry about.

**Comment by kilgor** [comment]
Sorry for my mistake 
requested in JSON is equal to last requested in plain text?
The value of requested  in JSON is always in seconds?

**Comment by slact** [comment]
Correct. I have edited the documentation to make this more clear ( d2ac3fda ).
