### ISSUE TITLE
Message size limit? Causing "broken" channels

### ISSUE THREAD

**Issue by Cowa** [slact/nchan#403]
Hello 👋 

Is there a size limit on messages getting through channels? I haven't seen anything related to this in the documentation.

I'm facing this issue: everything works but once a "big" message is sent (example in my case: 13803 char length), then this error is logged:

`SUB:WEBSOCKET:ws_recv NOT OK when receiving payload`

And then the channel is closed.
`"GET /channel/debugger/user/xxxx HTTP/1.1" 499`

Here is my setup if it can help:

```nginx
location ~/channel/debugger/user/(.*)$ {
      nchan_pubsub;

      nchan_subscriber_channel_id "debugger_command_{$1}";
      nchan_publisher_channel_id "debugger_response_{$1}";

      nchan_subscribe_request /upstream/sub;
      nchan_unsubscribe_request /upstream/unsub;

      nchan_websocket_ping_interval 10;
}

location ~/channel/debugger/admin/(.*)$ {
      nchan_pubsub;

      nchan_publisher_channel_id "debugger_command_{$1}";
      nchan_subscriber_channel_id "debugger_response_{$1}";

      # nchan_authorize_request /authorized;
      nchan_websocket_ping_interval 10;
}
```

Do you have any idea why? And how to solve this?

Thank you for your help! 😇

**Comment by slact** [comment]
You might be running into nginx's body size limit. Try increasing the [client_max_body_size](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) setting.

**Comment by Cowa** [comment]
I just tested with `client_max_body_size 100M;` and `client_max_body_size 0;`, the same error occured.

**Comment by slact** [comment]
How are the clients connecting to nginx? Is there some proxy in between? `499` errors are produced when the client aborts the connection on its own.

**Comment by Cowa** [comment]
Clients use Websocket to connect to Nginx, no proxy in between.

**Comment by slact** [comment]
Sorry, I don't know what's happening here. I don't think this is an nginx/nchan issue, though. I'd recommend firing up wireshark and checking what's going on at the packet level. Do let me know if you make any progress, or if there's some other way I could help.

**Comment by slact** [comment]
Closing for now. please reopen if you have any more information.
