### ISSUE TITLE
Modified response in nchan_publisher_upstream_request  does not return JSON

### ISSUE THREAD

**Issue by maddygoround** [slact/nchan#405]
When using nchan_publisher_upstream_request ,request is received by the application correctly , but after modify the JSON when the server returns modified JSON back to the subscriber ,subscriber receives some arbitrary data instead of JSON

**Following is the original POST data** 
`{"path":"AC76D89A-F40D-4327-9D1F-4EAA471D96FF","messageType":"joinAdmin","data":{"playerId":"D4E97BA6-63CF-4B46-A035-9D0165E5FC56","eventId":"AC76D89A-F40D-4327-9D1F-4EAA471D96FF","isAdmin":true,"userId":"123456789"}}`

**Following is the modified data**
`"{\"userDetails\":{\"playerId\":\"D4E97BA6-63CF-4B46-A035-9D0165E5FC56\",\"eventId\":\"AC76D89A-F40D-4327-9D1F-4EAA471D96FF\",\"isAdmin\":true,\"userId\":\"123456789\"},\"totalUserSessions\":0,\"messages\":[]}"`

**And received data on the subscriber end looks like**
![issues_nchan](https://user-images.githubusercontent.com/7420749/31660667-c1573bb4-b355-11e7-923c-6409638397b1.png)

**Comment by kilgor** [comment]
@maddygoround maybe script which you use to publish information escape json?

**Comment by slact** [comment]
My giess is your upstream server is gzipping the response when it shouldn't, and Nginx isn't deflating the response before passing it on as the message published via Nchan. I can confirm if you show me where this is happening. Email me at leo@nchan.io if you have a link or a server for me to look at.

**Comment by slact** [comment]
unable to reproduce and never got a followup to this
