### ISSUE TITLE
multimsg timeout!! and sub->request corruption

### ISSUE THREAD

**Issue by michaelfig** [slact/nchan#406]
[nchanbug.tar.gz](https://github.com/slact/nchan/files/1409409/nchanbug.tar.gz)
Hi,

Attached is a core dump, error.log file, and gdb sesson on CentOS 7, where I've installed nchan-1.7.1 and nginx-1.12.1.  Also is my nginx.conf.

I can get this crash to happen quite quickly when I load test 6000 client sockets, receiving 1000 messages each (sent by a separate publisher websocket connection to a channel that they all subscribe to).

The GDB session shows that somewhere along the line, the memory that is supposed to contain the Nginx request pointer (ngx_http_request_t *, found in fsub->sub->request), contains one of the JSON messages I sent instead of the request struct.  This then crashes the code that attempts to dereference the struct's pointers.

Any help would be much appreciated... I'm just barely getting my feet wet in the Nchan implementation.

Thanks,
Michael.

**Comment by michaelfig** [comment]
It looks like the ngx_http_request_t->signature field is supposed to equal NGX_HTTP_MODULE ("HTTP" as an integer).  Perhaps we can find this one by sprinkling around:
assert(sub->request->signature == NGX_HTTP_MODULE);

Thoughts?

**Comment by michaelfig** [comment]
I can't reproduce the crash under nginx-1.12.2, but the errors still happen.

**Comment by michaelfig** [comment]
When I reduce worker_processes to 1, I don't get any errors.

**Comment by slact** [comment]
Sorry, no time this week. I'll look at this issue next Tuesday.

**Comment by michaelfig** [comment]
Ok, thanks for letting me know.

**Comment by slact** [comment]
Hey @michaelfig , would it be possible for me to observe this bug on your server? email me at leo@nchan.io if we can set that up.

**Comment by michaelfig** [comment]
This is fixed in release v1.9.10.

Thanks,
Michael.
