### ISSUE TITLE
CORS: Why can't I use `nchan_access_control_allow_origin` in an `if` block?

### ISSUE THREAD

**Issue by Revisor** [slact/nchan#409]
Hello,
I would like to use `nchan_access_control_allow_origin` in an `if` block, but that is not allowed right now. Is there a particular reason for this?

An example of what I want to achieve:

```
location = / {
  nchan_subscriber;

  nchan_access_control_allow_origin '';
  if ($http_origin = 'http://example.com') {
    nchan_access_control_allow_origin $http_origin;
    add_header Access-Control-Expose-Headers *;
    add_header Access-Control-Allow-Credentials true;
  }
}
```
But
```
nginx: [emerg] "nchan_access_control_allow_origin" directive is not allowed here
```
Is there another way to do this? Is it a good idea? Bad idea?

If I don't use the `if` block, I simply allow everyone to connect to the subscriber from anywhere, no? Not sure I want to do it.

Thanks for your ideas.

**Comment by slact** [comment]
Just set `nchan_access_control_allow_origin http://example.com`, you don't need it in an if block;

**Comment by Revisor** [comment]
I probably left out too much from my concise example.

I need to allow three different origins.

**Comment by slact** [comment]
I see. If blocks are extra tricky and require more careful testing. I'll check how reliably `nchan_access_control_allow_origin` can work in a n `if` block.

**Comment by slact** [comment]
Good news, it works without modification. I've added the ability to use `nchan_access_control_allow_origin` in `if` blocks and some tests along with it : 9b5081d35a13811cd84d4fb747a40389509efb0d

**Comment by Revisor** [comment]
Wow, thank you very much for such a quick solution!

**Comment by slact** [comment]
You're quite welcome. It will be included in the next release. If you're feeling generous, you can [contribute](https://nchan.io/#contribute) to the project. 

And don't forget, `if` in Nginx [is evil](https://duckduckgo.com/), but sometimes you just need to make a deal with the Devil.
