### ISSUE TITLE
Returning a "reason" through nchan with nchan_authorize_request

### ISSUE THREAD

**Issue by nlyan** [slact/nchan#410]
We've been using nchan_authorize_request with proxy_pass to authenticate our websocket client against a backend API server, but haven't been able to figure out how to return a "reason" code (preferably via a HTTP header) back to the client when a user is not authorized.

Is there any way to achieve this?

**Comment by slact** [comment]
There is no way to do this right now, but it definitely makes sense as a feature. It's easier to implement passing the HTTP status code and response body; passing headers is trickier.

**Comment by slact** [comment]
ready for testing in master from commit c0934727d1674711911195224db153378681b020

**Comment by slact** [comment]
released in 1.1.10
