### ISSUE TITLE
Create Standard Response for publisher

### ISSUE THREAD

**Issue by scashin133** [slact/nchan#42]
In the "Basic HTTP Push Relay Protocol" there is currently nothing specified for what the publisher should expect to get back.

Currently when doing a GET request a publisher is receiving "queued messages: 0\r\nlast requested: 1912 sec. ago (-1=never)\r\nactive subscribers: 0".

Having a standard would give the publisher some guarantee about what to expect back especially from version to version.

**Comment by slact** [comment]
the response can be plaintext, JSON, XML, or Yaml, depending on the request's Accept header.
