### ISSUE TITLE
support@nchan.io does not function anymore

### ISSUE THREAD

**Issue by cloudspeech** [slact/nchan#420]
Hi Leo,

email sent to support@nchan.io appears to crash nchan's spamfilter with a core dump.

Since Google didn't reveal any other way to reach you, I open this issue hoping for a quick response.

Feel free to ask me to resend the original email that caused this.

Cheers, M.

**Comment by slact** [comment]
The host switched up the hardware under my VM, and it led to some segfaults. Thanks for the heads-up, fixed.
