### ISSUE TITLE
Keeping a Channel Private - X-Accel-Redirect

### ISSUE THREAD

**Issue by fatalbert75** [slact/nchan#424]
**nginx version** : 1.2.1
**nchan** : 1.1.10

Hello ,

I try since 5 days to use nchan with X-Accel-Redirect for hide channel and auth subscriber.  (When I use nchan with simple configuration all is good.)

**_My Nginx configuration file :_** 

```
load_module "modules/ngx_nchan_module.so";

http {
    nchan_redis_url "redis://127.0.0.1:6379";

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    upstream app {
	server 127.0.0.1:81;
    }
	    
    server {

        listen       81;
        #charset koi8-r;

        #access_log  logs/host.access.log  main;
        
        access_log /home/www/auth/nginx-access.log;
        error_log /home/www/auth/nginx-error.log;

        location / {
            try_files $uri $uri/ =404;
            root   /home/www/pubsub/;
            index index.php index.html; #this is my path where I included nchan.js
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    
        location = /auth {
            proxy_pass http://app/redirect;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
    
        # information - stats about nchan
            location /nchan_stub_status {
            nchan_stub_status;
        }

        location ~ /sub/internal/(\w+)$ {
            internal;
            nchan_subscriber;
            nchan_channel_id $1;
            nchan_use_redis on; 
        }

        location = /pub {
            nchan_publisher;
            nchan_channel_id $arg_id;
            nchan_use_redis on;
        }

        location = /redirect {
            root  /home/www/auth;
            index index.php;
        }
}
```

**_And my PHP script in auth/redirect :_** 

```
<?php
header('X-Accel-Redirect: /sub/internal/4');
header('X-Accel-Buffering: no');
header('HTTP/1.1 200 OK');
die;
?>
```

So, when I open browser http://[ip_server]:81/index.html , inside include nchan.js with :
 
```
var url = 'http://[IP-SERVER]:81/auth';
opt = {
[...]
}
var sub = new NchanSubscriber(url, opt);
```

I have two situation : 

code 301 or 301 and 404 infinite loop.

someone has succeeded to use  "Keeping a Channel Private" with nchan ?

Maybe I may to send my problem at support nchan 

Thank you all

**Comment by slact** [comment]
I don't think this produces a valid response:

```php
<?php
header('X-Accel-Redirect: /sub/internal/4');
header('X-Accel-Buffering: no');
header('HTTP/1.1 200 OK');
die;
?>
```

the `die;` call prevents the Content-Length header from being sent in the reply.

**Comment by fatalbert75** [comment]
Hello slact,
thank you for your quick response  

I removed `die;` , I have same situation , loop .

![capture d ecran 2017-12-01 a 12 08 58](https://user-images.githubusercontent.com/34157362/33480512-2d30ad44-d691-11e7-9f7b-c1ac937de6c1.png)

**Comment by slact** [comment]
Please make sure you have the X-accel-redirect feature working on its own. Serve a static file from an internal location and try to use X-Accel-Redirect to point to it.

**Comment by fatalbert75** [comment]
When I check modules : 

```
$ nginx -V

nginx version: nginx/1.12.2
built by gcc 4.7.2 (Debian 4.7.2-5) 
configure arguments: --add-dynamic-module=/home/nginx/nchan-1.1.10/
```

I compiled nginx myself , so do you think X-accel-redirect is not installed ?

**Comment by slact** [comment]
X-Accel-Redirect is a built-in  reature of proxying. The  issue lies  with your configuration, not nginx.

**Comment by fatalbert75** [comment]
Hello 
In your example you have : 

`upstream my_app `

then

`proxy_pass http://upstream_app/subscriber_x_accel_redirect;`

It's wrong , right ? the good way is ? : 

`proxy_pass http://my_app/subscriber_x_accel_redirect;`

Thanks

**Comment by slact** [comment]
Yes, there is an error in the readme. It has now been [fixed.](bf02bc45ccca68a1bdab9c59da635f3162650cf3)

**Comment by fatalbert75** [comment]
I think there are no problem, nginx configuration is hard to understand with proxy_pass & x-accel-redirect.

**Comment by fatalbert75** [comment]
Right nginx configuration : 

server {

        listen       81;

        server_name  [IP-SERVER]:81;
        charset UTF-8;

        access_log /home/www/pubsub/nginx-access.log addHeaderlog;
        error_log /home/www/pubsub/nginx-error.log;
	
	root /home/www/pubsub;	
	index index.php index.html;

        location / {
	    proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://[IP-SERVER]:81/auth/$uri;
        }

	location = /auth {
	    try_files $uri =404;
	}

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    
        location /nchan_stub_status {
            nchan_stub_status;
        }

        location ~ /sub/(\w+)$ {
            internal;
            nchan_subscriber;
            nchan_channel_id $1;
            nchan_use_redis on; 
        }

        location = /pub {
            nchan_publisher;
            nchan_channel_id $arg_id;
            nchan_use_redis on;
        }
}


then add "auth" folder, inside index.php with this code : 

```
<?php
header('X-Accel-Redirect: /sub/4?last_event_id=1512953078%3A0');
header('X-Accel-Buffering: no');
http_response_code(200);
?> 
```
