### ISSUE TITLE
long-poll subscribe will cause "zero size buf in output"  for version above 1.1.10

### ISSUE THREAD

**Issue by mapledan** [slact/nchan#427]
I try to upgrade my version from 1.1.7 to 1.1.13.
When subscribe request sent, Nginx alert the "zero size buf in output".
Then I request again the nginx worker will core dump.

I have tried the 1.1.7 ~ 1.1.13 versions.
It work fine below 1.1.9 verions.

```
        location ~ /sub/(\w+) {
            nchan_channel_id $1;
            nchan_subscriber longpoll;
            nchan_authorize_request /auth.php;
            nchan_redis_pass redis_cluster;
            nchan_longpoll_multipart_response raw;
            nchan_subscriber_compound_etag_message_id on;
        }

```

**Comment by mapledan** [comment]
When long-poll sub was break, then re-sub same channel will cause the "zero size buf in output" error.

**Comment by slact** [comment]
fixed a long time ago
