### ISSUE TITLE
channel multiplexing

### ISSUE THREAD

**Issue by morganchristiansson** [slact/nchan#43]
This has been requested before in other forums and tickets (1. http://github.com/slact/nginx_http_push_module/issues#issue/40 and 2. http://forum.nginx.org/read.php?2,23916 ). I'm putting it in as a separate issue so that it's not forgotten and can be subscribed to.

Make it possible to be a member of multiple channels using only one connection. Like being in a chat with 3 people. I could open 3 long polling requests but would have to trick around with domain names due to the 2-connection limit then.

something like http://server/sub/?channel_id=channel1,channel23,channel42

**Comment by slact** [comment]
I's finished. The upcoming nchan release supports up to 4 multiplexed channels from one location. It's limited to 4 for space considerations, but coild be rebuilt supporting up to 16 (at the price of a few dozen bytes overhead per message per subscriber per channel)
