### ISSUE TITLE
Redis & Message Buffer

### ISSUE THREAD

**Issue by sailerinteractive** [slact/nchan#430]
I'm trying to disable message buffering since i'm only interested in new messages that are sent after a client has subscribed and i came across the following behavior:

nchan 1.1.13 compiled as dynamic module for nginx 1.12.2, redis 4.0.6 running is cluster mode with 3 masters / 3 slaves. This is the redis config:

>   upstream redis_cluster {
>        nchan_redis_server redis://127.0.0.1:6380;
>        nchan_redis_server redis://127.0.0.1:6381;
>        nchan_redis_server redis://127.0.0.1:6382;
>     }
> ...
>    location = /sub {
>            nchan_subscriber;
>            nchan_channel_id $arg_stream $arg_user;           
>            nchan_redis_pass redis_cluster;
>         }    
> 

First, it seems to me that the directives "nchan_store_messages" and "nchan_message_buffer_length" have no impact when running with redis. On subscription the clients always receive all messages that are available in the redis store. Im not sure whether this a bug or the desired behavior?

In nchan 1.1.7 i was able to use "nchan_subscriber_first_message newest". Using this directive with any value from version 1.1.8 onward breaks message delivery completely in my setup (no messages are delivered at all, old or new). The directive seems to work fine without redis. 

I'm happy to run any further tests or provide additional info if needed.

**Comment by sailerinteractive** [comment]
I did some further testing and it seems that "nchan_subscriber_first_message" set to any other value than "1" or "oldest" breaks message delivery on versions above 1.1.7 when redis is enabled. 

Could this be a side effect of: https://github.com/slact/nchan/commit/eda2667ab8fc719084124297ebcaa9889dc3ee6a

**Comment by slact** [comment]
I'll be investigating this next week. Will let you know what I find.

**Comment by qhenkart** [comment]
any update with this? I am also trying to figure out a similar issue as the OP. Redis seems to dump all available messages regardless of settings

**Comment by SilentCicero** [comment]
@slact any word on this?

**Comment by slact** [comment]
@SilentCicero @sailerinteractive ok, it should be fixed. See #445 and please verify the fix for yourself if you are able.
