### ISSUE TITLE
CORS preflight issue when POSTing with X-EventSource-Event

### ISSUE THREAD

**Issue by cloudspeech** [slact/nchan#431]
Hi,

I'm trying to POST to a pubsub location configured like this:

`location ~ ^/chat/(\w+)$ {
		 nchan_pubsub;
	    	 nchan_channel_id "$1";
    		 nchan_channel_group chat;
		 nchan_channel_id_split_delimiter "_";
}`

Unfortunately I get this message in the Chrome Developer console:

`Failed to load <url redacted>: Request header field x-eventsource-event is not allowed by Access-Control-Allow-Headers in preflight response.`

 The excerpt from the Network panel:

`Request Method: OPTIONS
Status Code: 200 
Remote Address: 176.9.73.150:443
Referrer Policy: no-referrer-when-downgrade
access-control-allow-headers: Content-Type
access-control-allow-methods: GET, POST, PUT, DELETE
access-control-allow-origin: https://localhost
allow: GET, POST, PUT, DELETE
content-length: 0
date: Sat, 06 Jan 2018 14:05:46 GMT
server: openresty/1.13.6.1
status: 200
strict-transport-security: max-age=15768000

Access-Control-Request-Headers: x-eventsource-event
Access-Control-Request-Method: POST
Origin: https://localhost
`
Question: is nchan.io's built-in CORS support enough to handle this scenario? Is this supposed to work? Any workaround?

Thanks a lot in advance!

**Comment by slact** [comment]
I'm going to consider this a bug in Nchan. Will have it fixed shortly.

**Comment by slact** [comment]
Well, I wouldn't call 6 months fixing it "shortly", but it's now fixed with a7a42173, and will be included in the next release.
