### ISSUE TITLE
Unsubscription callback not always called 

### ISSUE THREAD

**Issue by carlosdagos** [slact/nchan#434]
Hello Leo,

I'm having an issue with the unsubscription callback.

For a configuration such as (which I'm guessing it's pretty standard)

```
# callback endpoints
location = /cb/sub {
    internal;
    proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
    proxy_set_header X-Channel-User  $nchan_channel_id1;
    proxy_set_header X-Channel-Name $nchan_channel_id2;
    proxy_set_header X-Original-Uri $request_uri;
    proxy_pass http://backend/cb/sub;
}

location = /cb/unsub {
    internal;
    proxy_ignore_client_abort on;
    proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
    proxy_set_header X-Channel-User $nchan_channel_id1;
    proxy_set_header X-Channel-Name $nchan_channel_id2;
    proxy_set_header X-Original-Uri $request_uri;
    proxy_pass http://backend/cb/unsub;
}

location ~ /sub/(.*)/(.*) {
    # This location only accessible for internal nginx redirects
    internal;
    nchan_subscribe_request /cb/sub;
    nchan_unsubscribe_request /cb/unsub;

    nchan_subscriber http-raw-stream;
    nchan_channel_id $1 $2;
}

location = /pub {
    nchan_publisher;
    nchan_channel_id $arg_id;
}

# Subscribers' public endpoint
location ~ ^/data/(.+) {
    proxy_pass http://backend/sub?dataset=$1;
    proxy_set_header X-Forwarded-For $remote_addr;
}
```

If I call the endpoint `/data/my-channel`, I can see the following line in my access log

```
127.0.0.1 - - [Wed, 17 Jan 2018 06:14:30 GMT] "GET /sub?channel=my-channel HTTP/1.0" 200 252
127.0.0.1 - - [Wed, 17 Jan 2018 06:14:31 GMT] "GET /cb/sub HTTP/1.0" 200 216
```

And once disconnected, of course I can see

```
127.0.0.1 - - [Wed, 17 Jan 2018 06:14:41 GMT] "GET /cb/unsub HTTP/1.0" 200 205
```

But if I cancel the stream right after I see the the first line, I never see the `/cb/unsub` line in my access log. For example, I can kill the client after some time (seems to be a timing issue) to reproduce

```bash
$ timeout 1.75s http --stream localhost:8888/data/my-channel --verbose
```

On different systems it'll different timeouts, but this is just to illustrate.

Is there a way to guarantee that the unsubscription callback is always called? Or am I missing something from the documentation? Thanks a lot!

**Comment by carlosdagos** [comment]
I've been debugging and looking at logs, because we use {{http-raw-stream}}, which uses {{longpoll_dequeue}} when the user disconnects, the line [186@longpoll.c|https://github.com/slact/nchan/blob/master/src/subscribers/longpoll.c#L186] is being called.

So according to the logs the unsubscribe callback _is_ being requested to the upstream server. However, I'm not seeing it on my logs. Could it be that there's something later that fails?

**Comment by carlosdagos** [comment]
In addition to my above comment, I'm seeing in the logs

```
20:28:00 [debug] 1519#0: *3 http finalize request: -4, "/cb/unsub?" a:0, c:3
2018/01/17 20:28:00 [debug] 1519#0: *3 http request count:3 blk:1
2018/01/17 20:28:00 [debug] 1519#0: *3 http terminate cleanup count:2 blk:1
```

**Comment by carlosdagos** [comment]
So I've dug a little deeper today, I've noticed that in [longpoll_enqueue](https://github.com/slact/nchan/blob/master/src/subscribers/longpoll.c#L160), the subcriber's request's `read_event_handler` is set to `nchan_subscriber_unsubscribe_callback_http_test_reading`.

In a normal situation, this handler is triggered. However in the cases where I'm not seeing the unsubscription callback, it's not at all triggered. However `longpoll_dequeue` _is_. Still digging around, though, [I'll change some code](https://cdn-images-1.medium.com/max/455/1*snTXFElFuQLSFDnvZKJ6IA.png).

**Comment by carlosdagos** [comment]
Looks like that `read_event_handler` not triggering is okay in this case (though I might be wrong).

Still looking at `longpoll_dequeue` eventually leads to `generic_susbscriber_subrequest_old` which uses [`nginx_http_subrequest`](https://github.com/slact/nchan/blob/master/src/subscribers/common.c#L145) which is what actually performs the request, and this is always returning `NGX_OK`. I've tried changing the `flag` provided to it to `NGX_HTTP_SUBREQUEST_BACKGROUND` (just to test), and now I do get the callback, but it's unordered (I guess this makes sense?).

I'm not sure if `ngx_http_subrequest` actually checks upstream server responses or if that's up to the developer. It just always seems to return `NGX_OK`, but I don't get the request on the upstream server.

**Comment by slact** [comment]
The subscriber subrequest pipeline i have set up is a hell of a hack. It had to be this way to not eat up RAM and patch into the Nginx upstream cycle, but it's a mess at this point that _someone_ really should do _something_ about. 

I don't have `http-raw-stream` in all my regression tests, so it's possible I broke something. I'll be looking into this over the weekend.

**Comment by carlosdagos** [comment]
Thanks for the help!

**Comment by slact** [comment]
Following up on this, the unsubscribe callback is called only if the subscribe callback has already been called. If you cancel the request before you see `GET /cb/sub` in your logs, that means Nchan hasn't run the 'subscribe' callback, so it won't call the 'unsubscribe' either.
