### ISSUE TITLE
Add support for ARMHF architecture to Ubuntu/Debian .deb builds

### ISSUE THREAD

**Issue by SlvrEagle23** [slact/nchan#435]
Hello all! I've integrated nchan into a software toolkit I work on, and it has been an amazing tool with excellent performance and ease of configuration out of the box.

Prior to the addition of nchan to the software, though, the application was able to fully support the ARMHF platform, which includes the Raspberry Pi and a number of other economy devices.

Users have reported that the Debian/Ubuntu .deb packages (which my tool uses to easily install nchan) aren't built to include support for ARM architectures. This causes failed installations in these instances.

I'm not sure of the logistics of building out .deb packages, otherwise I would contribute the changes myself, but it appears to be possible to integrate cross-architecture building into the build process.

Thank you all for your hard work on this project, and thank you for your help. :)

**Comment by slact** [comment]
The core debian nginx package [libnginx-mod-nchan](https://packages.debian.org/sid/libnginx-mod-nchan) has an ARM build. I have very little control over how quickly they upgrade versions though -- but it is there.

**Comment by SlvrEagle23** [comment]
@slact I'm more referring to the prebuilt static module files served directly via nchan.io. We can't use Debian itself in our environment and would prefer to use Ubuntu, but I'm not sure what the differences are between the Debian and Ubuntu packages distributed there.

**Comment by slact** [comment]
I see. Sorry, i don't have any cross-compliling tooling set up for my package builds. I'd be open to it if you could help me out with it.

**Comment by slact** [comment]
Closing this since I haven't gotten any help with it so far. :Please reopen if you're someone that can help set up the tooling to make this happen.
