### ISSUE TITLE
nchan: Out of shared memory while sending IPC subscribe alert

### ISSUE THREAD

**Issue by saurabhguptag** [slact/nchan#438]
Hi,
Today I have noticed millions of errors logged where the logs were filled with only the following error.

`2018/02/01 03:42:01 [error] 12985#12985: nchan: Out of shared memory while sending IPC subscribe alert for channel /xyz_gzip. Increase nchan_max_reserved_memory.`
`2018/02/01 03:42:01 [crit] 12985#12985: ngx_slab_alloc() failed: no memory`
`2018/02/01 03:42:01 [error] 12985#12985: shpool alloc failed`

"nchan_max_reserved_memory" is no more available I am on nchan-1.1.14. Is there something I need to take care.  my  "nchan_shared_memory_size" is set to default. the stat says. but 
"shared memory limit: 131072K". It looked like the program went to infinite loop.

**Comment by saurabhguptag** [comment]
same thing today..  I had upgraded to 1.1.14  two days back. and since then. I will be downgrading this version.

**Comment by saurabhguptag** [comment]
To give you more details.

1. Nginx version - 1.12.2
2. Nchan Version - 1.1.14

The data is only getting stuck when trying to send binary content.  Attached is the nchan config file.
[nchan.txt](https://github.com/slact/nchan/files/1688347/nchan.txt)

**Comment by slact** [comment]
Is there some way for you to reliably reproduce this issue? I also don't understand what you mean by "when trying to send binary content".

**Comment by saurabhguptag** [comment]
we send out gzipped content on long polling. I donno how to reproduce. we were earlier using 1.1.9 which is stable a stable version.

**Comment by slact** [comment]
would you be able to send me a fresh error log fron nginx start to the time it runs out of shared memory? I would also like your nginx config (edit out whatever you need to keep private).

**Comment by saurabhguptag** [comment]
Attached is the tar.gz file containing few of the errors of many and also the conf file ( contains data of only code inside server block)
[nchan_errs_n_conf.tar.gz](https://github.com/slact/nchan/files/1703350/nchan_errs_n_conf.tar.gz)

**Comment by saurabhguptag** [comment]
Hi Were you able to replicate the issue?

**Comment by slact** [comment]
Unfortunately, I have not. Have you tried increasing `nchan_shared_memory_size` to 512M or 1024M?

**Comment by slact** [comment]
Closing this for now -- please reopen if you're still having this issue after increasing `nchan_shared_memory_size`.
