### ISSUE TITLE
nginx: [emerg] unknown directive "nchan_subscriber"

### ISSUE THREAD

**Issue by mohsalsaleem** [slact/nchan#440]
I have built nginx from source with nchan. 
The following is the output of nginx -V

> nginx version: nginx/1.10.3
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --with-ld-opt=' -Wl,-E' --with-ld-opt=-Wl,-rpath,/usr/local/lib --add-module=/home/mohsal/softwares/lua-nginx-module --add-module=/home/mohsal/softwares/ngx_devel_kit-0.3.0 --add-dynamic-module=/home/mohsal/softwares/nchan-1.1.14

Can someone please help me?

**Comment by mohsalsaleem** [comment]
Fixed it. It was due to another issue in the configuration file.

**Comment by mohsalsaleem** [comment]
The following is the nginx configuration I use.
```
 server {
        listen 80;
        server_name localhost;

        location = /sub {
                nchan_subscriber;
                nchan_channel_id $arg_id;
        }

        location = /pub {
                nchan_publisher;
                nchan_channel_id $arg_id;
        }
}
```

**Comment by mohsalsaleem** [comment]
My bad. It was a problem specifying right nginx binary path.

**Comment by yydzxz** [comment]
how do you fix it?
