### ISSUE TITLE
Websocket connection gets disconnected after 40s - 50s. 

### ISSUE THREAD

**Issue by mohsalsaleem** [slact/nchan#443]
Local websocket connection works without any issue. At the server, it is disconnecting after 40 to 50s.
Nginx seems to disconnect the subscriber no matter there were messages sent to the subscribers.

The behavior is the same even with EventSource.

This is the configuration that I'm using.
server {
    listen 80;

    location = /sub {
        nchan_subscriber;
        nchan_channel_id $arg_id;
        nchan_authorize_request /trivia/auth;
        nchan_subscriber_first_message new;
        nchan_subscriber_timeout 0;
    }

    location = /pub {
        nchan_publisher;
        nchan_channel_id $arg_id;
    }
}

**Comment by mohsalsaleem** [comment]
Setting nchan_subscriber_timeout 3600s; does not seem to be working either.

**Comment by mohsalsaleem** [comment]
Here is the debug log of 2 websocket connections
https://pastebin.com/6vEwqySk

**Comment by mohsalsaleem** [comment]
Here is the log of a single websocket connect request till the websocket connection disconnected.
https://pastebin.com/HXY0SLWj

**Comment by slact** [comment]
Sounds like your host may not like idle TCP connections. You may need to add [`nchan_websocket_ping_interval`](https://nchan.io/#nchan_websocket_ping_interva) to your config.

**Comment by SilentCicero** [comment]
@mohsalsaleem did the above resolve your issue?

**Comment by slact** [comment]
Closing this, please reopen if the issue persists after setting `nchan_websocket_ping_interval`.
