### ISSUE TITLE
Nginx stops with error: nchan_store_init_worker: Assertion `procslot_found == 1' failed.

### ISSUE THREAD

**Issue by mohsalsaleem** [slact/nchan#446]
Can someone tell me why this is happening?

**Comment by slact** [comment]
Nchan version? Nginx version? Nginx config? Steps to reproduce?

**Comment by hoexter** [comment]
By coincidence I just see crashes with the error message. The system is running Debian/stretch with nginx/nchan package version 1.10.3-1+deb9u1.
I'm not yet sure if and how this is reproducible.

**Comment by slact** [comment]
The Debian repo is very far behind on Nchan updates, I think something like this issue was fixed over a year ago.

**Comment by dedajuno** [comment]
Hello @slact 
I have the similar issue. And i can't reproduce it, to check what causes this issue. It fails randomly unexpected.  
How can i unload it from my working nginx? Do i have to rebuild nginx from sources without this module?
nginx: v1.14.0 
Part of my error.log
```2018/08/22 00:56:00 [alert] 30511#30511: worker process 13864 exited on signal 6
2018/08/22 00:56:00 [alert] 30511#30511: shared memory zone "memstore" was locked by 13864
ter process /usr/sbin/nginx -g daemon on; master_process on;: /build/nginx-1.14.0/debian/modules/nchan/src/store/memory/memstore.c:708: nchan_store_init_worker: Assertion `procslot_found == 1' failed.
2018/08/22 00:56:00 [alert] 30511#30511: worker process 13866 exited on signal 6
2018/08/22 00:56:00 [alert] 30511#30511: shared memory zone "memstore" was locked by 13866
ter process /usr/sbin/nginx -g daemon on; master_process on;: /build/nginx-1.14.0/debian/modules/nchan/src/store/memory/memstore.c:708: nchan_store_init_worker: Assertion `procslot_found == 1' failed.
2018/08/22 00:56:00 [alert] 30511#30511: worker process 13867 exited on signal 6
2018/08/22 00:56:00 [alert] 30511#30511: shared memory zone "memstore" was locked by 13867
ter process /usr/sbin/nginx -g daemon on; master_process on;: /build/nginx-1.14.0/debian/modules/nchan/src/store/memory/memstore.c:708: nchan_store_init_worker: Assertion `procslot_found == 1' failed.```

Do i have another option to fix it without disturbance on prod server?
Could you help, please?

**Comment by slact** [comment]
@dedajuno If you got Nchan from a Debian or Ubuntu repository, I'm afraid you'll have to rebuild it. I fixed this bug quite a while ago and theit versions are at least a year old.

**Comment by hoexter** [comment]
@dedajuno workaround, if you **don't** use the module at all: rm the link from /etc/nginx/modules-enabled and restart nginx

**Comment by dedajuno** [comment]
@slact Thanks. 
@hoexter there is no such kind of folder. If there would any folder like this or in /usr/share/nginx - it would be so easy and good for me, but NO :D

**Comment by fmonts** [comment]
Got the same problem on Nginx mainline 1.17.3, what could it be the reason if the bug was fixed?

![image](https://user-images.githubusercontent.com/8755314/64475679-5dc0fa00-d18e-11e9-883e-e4a580cfb42c.png)

**Comment by slact** [comment]
@fmonts what version of Nchan are you using?

**Comment by fmonts** [comment]
@slact how can I get this information? I'm using the ppa by ondrej ( https://launchpad.net/~ondrej/+archive/ubuntu/nginx-mainline )

**Comment by gr8bit** [comment]
@fmonts try `dpkg -l | grep nchan` as root. If it was installed via apt, it outputs something like
`ii  libnginx-mod-nchan                    1.14.0-0ubuntu1.6                 amd64        Fast, flexible pub/sub server for Nginx`

Unfortunately, that is on Ubuntu 18.04 LTS and I just experienced the above error, too. :(

**Comment by fmonts** [comment]
> @fmonts what version of Nchan are you using?

I got
> ii  libnginx-mod-nchan                    1.17.3-1+ubuntu18.04.1+deb.sury.org+1                    amd64        Fast, flexible pub/sub server for Nginx

It seems that the error disappeared with one of the latest updates

**Comment by gr8bit** [comment]
@fmonts Ok, you're using the PPA repo, not the ubuntu releases (which sticks to 1.14.0)... the problem disappeared on nginx restart, but I bet it will be coming back.

**Comment by gtwy** [comment]
> > @fmonts what version of Nchan are you using?
> 
> I got
> 
> > ii  libnginx-mod-nchan                    1.17.3-1+ubuntu18.04.1+deb.sury.org+1                    amd64        Fast, flexible pub/sub server for Nginx
> 
> It seems that the error disappeared with one of the latest updates

Do you mind pasting the results of "apt policy" for us?

**Comment by GeorgFleig** [comment]
I experienced the same error this morning. Several reloads were triggered by certbot for let's encrypt certificate renewal. One of them killed nchan/nginx.

nginx error log (note: the two lines tat look truncated are like this in the log file):

```
2019/12/06 07:30:43 [notice] 18812#18812: signal process started
2019/12/06 07:30:48 [notice] 18815#18815: signal process started
2019/12/06 07:30:49 [info] 18816#18816: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:66
2019/12/06 07:30:51 [notice] 18818#18818: signal process started
ter process /usr/sbin/nginx -g daemon on; master_process on;: /build/nginx-IP2kgO/nginx-1.16.1/debian/modules/nchan/src/store/memory/memstore.c:701: nchan_store_init_worker: Assertion `procslot_found == 1' failed.
2019/12/06 07:30:56 [alert] 26384#26384: worker process 18820 exited on signal 6 (core dumped)
2019/12/06 07:30:56 [alert] 26384#26384: shared memory zone "memstore" was locked by 18820
ter process /usr/sbin/nginx -g daemon on; master_process on;: /build/nginx-IP2kgO/nginx-1.16.1/debian/modules/nchan/src/store/memory/memstore.c:701: nchan_store_init_worker: Assertion `procslot_found == 1' failed.
```
After this the nginx process was still running but not accepting any connections.

Versions
```
# installed via deb http://ppa.launchpad.net/nginx/stable/ubuntu xenial main
ii  nginx                                 1.16.1-0+xenial1                              all          small, powerful, scalable web/proxy server
ii  libnginx-mod-nchan                    1.16.1-0+xenial1                              amd64        Fast, flexible pub/sub server for Nginx

Linux interim-api 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ctrlventure** [comment]
> @dedajuno workaround, if you **don't** use the module at all: rm the link from /etc/nginx/modules-enabled and restart nginx

My installation doesn't have that folder, how can i disable this module?
I've installed nginx-extras via apt-get on ubuntu 16, currently nginx 1.18.0

**Comment by asveloper** [comment]
@slact My installation doesn't have that folder, how can i disable this module?

**Comment by slact** [comment]
@asveloper I have no idea what the context of your question is. What module are you trying to disable?

**Comment by asveloper** [comment]
@slact this is the error i am receiving [info] 6495#6495: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:70

due to which server goes down again and again, how i can disable nchan module on nginx as i am not using it?

**Comment by jbeccia** [comment]
We are seeing the same issue when testing a build of the nchan dynamic library with nginx 1.15.8 (or 1.16.1) and nchan 1.2.7.  The problem does not occur in a similar build with nchan 1.2.6 and nginx 1.15.8 (via openresty 1.15.8.2):

2020/08/12 14:23:38 [notice] 13991#13991: start worker process 14279
2020/08/12 14:23:38 [debug] 14279#14279: REAPER: start reaper memstore message with tick time of 5 sec
2020/08/12 14:23:38 [debug] 14279#14279: REAPER: start reaper memstore nobuffer message with tick time of 2 sec
2020/08/12 14:23:38 [debug] 14279#14279: REAPER: start reaper chanhead with tick time of 4 sec
2020/08/12 14:23:38 [debug] 14279#14279: REAPER: start reaper chanhead churner with tick time of 10 sec
2020/08/12 14:23:38 [debug] 14279#14279: MEMSTORE:04: init memstore worker pid:14279 slot:4 max workers :0 or 0
2020/08/12 14:23:38 [notice] 13991#13991: signal 17 (SIGCHLD) received from 14272
2020/08/12 14:23:38 [alert] 13991#13991: worker process 14272 exited on signal 6 (core dumped)
2020/08/12 14:23:38 [alert] 13991#13991: shared memory zone "memstore" was locked by 14272
2020/08/12 14:23:38 [notice] 13991#13991: start worker process 14282
2020/08/12 14:23:38 [debug] 14282#14282: REAPER: start reaper memstore message with tick time of 5 sec
2020/08/12 14:23:38 [debug] 14282#14282: REAPER: start reaper memstore nobuffer message with tick time of 2 sec
2020/08/12 14:23:38 [debug] 14282#14282: REAPER: start reaper chanhead with tick time of 4 sec
2020/08/12 14:23:38 [debug] 14282#14282: REAPER: start reaper chanhead churner with tick time of 10 sec
2020/08/12 14:23:38 [debug] 14282#14282: MEMSTORE:02: init memstore worker pid:14282 slot:2 max workers :0 or 0
nginx: master process nginx: /xdds/nchanbld/nchan-1.2.7/src/store/memory/memstore.c:718: nchan_store_init_worker: Assertion `procslot_found == 1' fail
2020/08/12 14:23:38 [notice] 14281#14281: signal process started
2020/08/12 14:23:38 [notice] 13991#13991: signal 15 (SIGTERM) received from 14281, exiting
2020/08/12 14:23:38 [notice] 13991#13991: signal 17 (SIGCHLD) received from 14282
2020/08/12 14:23:38 [alert] 13991#13991: worker process 14282 exited on signal 6 (core dumped)


The error occurs regardless of what compilation switches are specified in the dynamic library build, including an exact match with those used to build nginx (via nginx -V).

**Comment by ctrlventure** [comment]
@slact I'm getting the error as well, I have a Rails app that creates vhosts and generates the SSL certificates and reloads Nginx 3 times (3 seconds between the reloads) and often that crashes Nchan:

```
2020/08/23 10:03:18 [alert] 4205#4205: worker process 9199 exited on signal 6
2020/08/23 10:03:18 [alert] 4205#4205: shared memory zone "memstore" was locked by 9199
ter process /usr/sbin/nginx -g daemon on; master_process on;: /build/nginx-1.18.0/debian/modules/nchan/src/store/memory/memstore.c:708: nchan_store_init_worker: Assertion `procslot_found == 1' failed.
```

I don't load Nchan anywhere, i've tried to locate any reference to it but didn't find any, i do use Nginx Amplifier Agent to monitor the server and i wonder if that's related.

Here's my nginx.conf:

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;

        server_names_hash_bucket_size 128;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        proxy_buffers 16 16k;
        proxy_buffer_size 16k;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        log_format  main_ext  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '"$host" sn="$server_name" '
                      'rt=$request_time '
                      'ua="$upstream_addr" us="$upstream_status" '
                      'ut="$upstream_response_time" ul="$upstream_response_length" '
                      'cs=$upstream_cache_status' ;

        access_log /var/log/nginx/access.log  main_ext;
        error_log /var/log/nginx/error.log warn;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";

        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_min_length    256;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Phusion Passenger config
        ##
        # Uncomment it if you installed passenger or passenger-enterprise
        ##

        include /etc/nginx/passenger.conf;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```

Additional information:

```
$ uname -a
Linux cs2665 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
````

`dpkg -l | grep nchan` shows nothing, even as root

```
$ sudo apt-cache policy nginx-extras
nginx-extras:
  Installed: 1:1.18.0-8.6.0.6~xenial1
  Candidate: 1:1.18.0-8.6.0.6~xenial1
  Version table:
 *** 1:1.18.0-8.6.0.6~xenial1 500
        500 https://oss-binaries.phusionpassenger.com/apt/passenger xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1:1.18.0-8.6.0.5~xenial1 500
        500 https://oss-binaries.phusionpassenger.com/apt/passenger xenial/main amd64 Packages
    ...
```

I don't even know how i can disable it considering there is no `/etc/nginx/modules-enabled` folder in my installation. Any idea how can i sort this out?

**Comment by teward** [comment]
> I don't even know how i can disable it considering there is no /etc/nginx/modules-enabled folder in my installation. Any idea how can i sort this out?

@ctrlventure only way to 'disable' nchan is to use a different version of NGINX - i.e. NOT from the passenger repositories.  (Especially since `passenger` is... not kind)

**Comment by slact** [comment]
The issue occurs when Nchan is built under Openresty, and run under vanilla Nginx. Apparently the Openresty changes inside Nginx don't play well with vanilla Nginx.

The solution is to use the Nchan module built with Nginx if you are using it with vanilla Nginx, and built with Openresty if you're using it with Openresty.

**Comment by gingerlime** [comment]
Seeing this issue suddenly with vanilla nginx 1.18.0 on Ubuntu 22.04 (no passenger, no openresty).

```shell
# nginx -v
nginx version: nginx/1.18.0 (Ubuntu)

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

# dpkg -l |grep nchan
ii  libnginx-mod-nchan                    1.18.0-3ubuntu1+focal2            amd64        Fast, flexible pub/sub server for Nginx
```

**Comment by jfoclpf** [comment]
@slact why did you close the issue if the problem seems to persist with recent versions of Nginx, as @gingerlime suggests?

**Comment by teward** [comment]
> @slact why did you close the issue if the problem seems to persist with recent versions of Nginx, as @gingerlime suggests?

I would suggest

> Seeing this issue suddenly with vanilla nginx 1.18.0 on Ubuntu 22.04 (no passenger, no openresty).
> 
> ```shell
> # nginx -v
> nginx version: nginx/1.18.0 (Ubuntu)
> 
> # lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.3 LTS
> Release:        20.04
> Codename:       focal
> 
> # dpkg -l |grep nchan
> ii  libnginx-mod-nchan                    1.18.0-3ubuntu1+focal2            amd64        Fast, flexible pub/sub server for Nginx
> ```

`lsb_release` says 20.04 not 22.04, double check your assertions of it being 22.04

**Comment by jfoclpf** [comment]
@teward what are your suggestions to solve this issue? I am having the same

```
jfolpf@contabo:~$ nginx -v
nginx version: nginx/1.14.0 (Ubuntu)

jfolpf@contabo:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

jfolpf@contabo:~$ dpkg -l |grep nchan
ii  libnginx-mod-nchan                     1.14.0-0ubuntu1.9                                                  amd64        Fast, flexible pub/sub server for Nginx
```

**Comment by teward** [comment]
@jfoclpf @gingerlime with regards to Ubuntu, unless there are cherry picked fixes for issues the nchan module updates do not land in Ubuntu as part of the [Stable Release Updates][(https://wiki.ubuntu.com/StableReleaseUpdates) process.  It is generally 'not acceptable' to simply bump the version of a library to fix a bug when there's also new features, etc. involved.  It does not reach the justification of SRU.

I don't have any suggestions for you to solve the issue, but I will point out that @slact has closed the issue because in the earlier issues of the bug here such as in the Passenger repositories, nchan doesn't work because it's a contaminated build.  This was closed over 2 years ago, so anyone having this problem now likely has some sort of mixed binaries problem.

If you are using Ubuntu and *not* using the PPA, you need to file a bug against the package in Ubuntu.  If you are using a PPA, then you have to go find the person who runs that PPA and let them know the bug.  (`apt-cache policy libnginx-mod-nchan` will get you that information pretty easily).

HOWEVER, the version of nchan in Ubuntu is outdated - 18.04 was released in 2018.  20.04 was released in 2020.  22.04 didn't get any updates to underlying custom third party modules because the package in Debian went unmaintained and had some SERIOUS QA problems (which myself and another have now adopted and fixed in Debian upstream).  However, again, due to Ubuntu's SRU policy, a cherry-picked narrow fix needs to be used.  There are known issues with 18.04's version as well that the module is just "broken" being outdated, but a version bump to fix it never reached approval from the Ubuntu Release Team and the SRU team, therefore it never was bumped/fixed.

Therefore, I don't really have a solution to offer anyone for this issue.  However, it's pretty apparent if you're still having issues, they *aren't* the same as the original bug posted here most likely.

**Comment by gingerlime** [comment]
Sorry, I wrote 22.04, but I meant 20.04 (as you can also see from the `lsb_release -a` output). I updated my comment to avoid confusion.

We ended up disabling nchan. My familiarity with the debian/ubuntu package update process is virtually nonexistent, but I can see how this can be frustrating to both users and developers when updates and fixes can be so difficult to get into the distros.

**Comment by gingerlime** [comment]
> But how do I know if I need or am using nchan?

I was asking myself the same question :) I eventually disabled it and noticed no issues, so that's how I knew I didn't need it. 

> If I am not using it, how can I disable it?

If you're on Ubuntu, then look for a symlink and remove it. In my case it was `rm -f /etc/nginx/modules-enabled/50-mod-nchan.conf` and then restarting nginx.

**Comment by jfoclpf** [comment]
@gingerlime apparently you need to use the directive `nchan_subscriber` to activate it, thus

```
grep -R nchan /etc/nginx/
```

will tell you if you're using it. Cause I don't, I will remove that symlink indeed

thanks

**Comment by slact** [comment]
If you are using any Nginx that starts with `nchan_*`, you're using Nchan. Otherwise you don't need it. Ubuntu and Debian's versions of Nchan are woefully obsolete and they don't seem to want to update them. I don't really want to get involved in the package maintainer bureaucracy of those organizations to right this issue. If you want to use Nchan, please build it from source or use a docker image. If you don't need it, and have the vanilla Ubuntu or Debian package, please uninstall it.

**Comment by SarvarRaxmonov** [comment]
is it still not solved
