### ISSUE TITLE
Discussion: tuning for 1-100 pubs | 600k / per second | w/ 1-10 million subs

### ISSUE THREAD

**Issue by SilentCicero** [slact/nchan#447]
Hi NChan devs/lovers,

I want to run a hypothetical by everyone. In a world where I was say receiving about 600k msgs/per second from about 1-100 pub servers, and had about 1-10m subs listening on a variety of channels. How does that look like scaling wise?

Would I run a single instance that would forward to multiple nchan instancs using the same redis cluster?

Note, I'm a devops noob, so go easy..

I'm of course over engineering / code golfing here. But I would love to know what the ramifications of something like this are.

**Comment by slact** [comment]
The _fastest_ scalability setup you can have is a cluster of nchan instances sharded at the client-side by channel keyspace. Beyond that you can use several Nchan instances sharing the same Redis cluster -- but this will be slower for high publishing rates, simply  because publishing involves sending data to a remote server.

One other point is how many channels you expect these messages to be published on. If it's all on one channel, it won't scale -- parallelization in Nchan is achieved on a per-channel bases. If you've got more channels than CPU cores, you're good.

**Comment by SilentCicero** [comment]
Thanks so much for the answer @slact your really solving all my problems here, a donation to come!

1) For the redis cluster, can I just spin up a bunch of vanilla redis instances on DO and throw the URLs in NChan, or do they have to be connected to each other in some special way?
2) Could I use a load balancer (balancing over HTTPS) over a set of NChan instances using the same redis cluster? Would that actually work, if someone post message Y on channel X on one NChan instance, due to NChan, anyone subscribed to channel X on any other NChan instance would get message Y?

This all seems so great, thank you  for your help and NChan.

**Comment by slact** [comment]
> For the redis cluster, can I just spin up a bunch of vanilla redis instances on DO and throw the URLs in NChan, or do they have to be connected to each other in some special way?

A single redis server might not be able to handle the publishing traffic. But when using a Redis Cluster, Nchan shards the channel keyspace between the nodes, so the more nodes you have in the cluster, and  the more channels you use, the more bang you get for your buck.

To be specific, the Redis servers will all need to talk to each other in a cluster, and cheap DO instances probably won't have enough bandwidth or RAM to handle the traffic you seem to have in mind.

> Could I use a load balancer (balancing over HTTPS) over a set of NChan instances using the same redis cluster? Would that actually work, if someone post message Y on channel X on one NChan instance, due to NChan, anyone subscribed to channel X on any other NChan instance would get message Y?

It would work, but it would defeat much of the benefit you get from Nchan being the entry-point into your network.

> I also dont need immediate message delivery, it can be delayed a few seconds, and client-side messages are posted ahead of state anyway.
This wouldn't affect the archutecture much, save that you may not need to cluster your nodes in the same data center.

Consider going through my presentation on Nchan at Nginx conf 2016 - https://www.youtube.com/watch?v=TVgQSmqWm60 -- it covers a lot of your scalability questions. And if you need more in-depth support, you can contact me through https://nchan.io/support .

**Comment by SilentCicero** [comment]
@slact I went through your presentation, fantastic stuff!

1) Redis: I'm thinking of have about one master / two slaves for a basic setup. I will try a few configs.
2) I wanted people to use a specific sub URL like sub.mydomain.com to listen for changes. That is where I wanted to use the load balancer. Would it reduce speed / traffic to do this, even if it is a pass through of some kind?
3) In depth support: I am going to email about you for a quick consultation / conversation. I should be paying you for your time.

Thanks agian.

**Comment by SilentCicero** [comment]
Heyo,

We can try this hangouts link:
https://hangouts.google.com/call/NKM9X3UaQE8Ca3iXQ85NAAEE

If not we can try Zoom, Signal, or Whatsapp (+1 647 234 0812)

Best,
nick
