### ISSUE TITLE
brew nginx-full is no longer present

### ISSUE THREAD

**Issue by gpip** [slact/nchan#456]
Looks like earlier this month `brew install nginx-full` stopped working, an alternative is to run (I had to `brew unlink nginx` first):

```
brew tap denji/nginx
brew install nginx-full --with-nchan-module
```

Do you know if currently that's the expected way to install nchan on macos?

**Comment by slact** [comment]
Uh... I guess so. I've updated the readme in d9e688c2 to reflect this change.
