### ISSUE TITLE
cross domain connection

### ISSUE THREAD

**Issue by pokal4u** [slact/nchan#457]
Hi,
We are using auto scaling servers for load balancing, so we don't know how many servers added automatically based on traffic. nginx configurations same in all servers

All servers mapping to single domain, and those IPs are different.

Ex:
a,b,c connected to Server 1
d,e,f connected to Server2

So long polling connection for a->f, d->b, etc. is working in nchan?

Thanks

**Comment by slact** [comment]
I don't think I understand your question. If you need horizontal scaling, multiple servers can share the state and channel data using Redis.

**Comment by pokal4u** [comment]
HI,
How can I use redis for instant messages(chat) exchange from two users ?

**Comment by slact** [comment]
Sorry, that kind of question is more fitting for professional support : https://nchan.io/support
