### ISSUE TITLE
Unexpected publisher message request body buffer location

### ISSUE THREAD

**Issue by warmaris** [slact/nchan#460]
I've got some trouble with publisher upstream, when return "200 OK" from upstream. If I don't set header `Content-Length`, I get empty message in channel. If I set content length, I get this error:
```
[error] 9#9: *4 nchan: unexpected publisher message request body buffer location. please report this to the nchan developers. while sending to client, client: 172.18.0.1, server: , request: "POST /pub/4cf6afe1-6c12-47de-af90-d849f9a4e6c9/17efec9b-0b41-4f22-ae4f-3ef056e9b8c5 HTTP/1.1", subrequest: "/upstream_pub", upstream: "http://172.18.0.1:8001/upstream_pub", host: "127.0.0.1:8084"
```
With codes 204 and 304 everything good. Tried `proxy_buffering off`, no change.
Tried builds on nginx 1.13.12 and 1.15.0 with nchan 1.1.6, 1.1.14 and 1.1.15.

**Comment by slact** [comment]
fixed in 4de21c39

**Comment by warmaris** [comment]
It works now. Thanks!

**Comment by gdamjan** [comment]
_sigh_
this means Ubuntu and Debian are shipping incompatible nchan 1.0.8  with nginx 1.14/1.17
