### ISSUE TITLE
chan_message_buffer_length 1 seems to be ignored

### ISSUE THREAD

**Issue by vlcinsky** [slact/nchan#461]
I am trying to create publishing solution, where only latest file version is always available. NCHAN can enhance the solution in that it would support websocket, long polling, SSE etc.

My plan was to set `chan_message_buffer_length 1;` on given channel.

Expected behaviour is:

- when storing multiple messages into given channel, only the last one will be available
- plain GET request will always immediately return the latest published content
- GET request with If-Modified-Since header might return immediately, or wait till new update arrives.

What I have seen is quite different:

- I was able to store 5 messages like "one", "two", "three" ...(and possibly would be able to store more) and the I was able to fetch them all back using If-Modified-Since header.
- plain GET always returned the oldest message "one"

My config is:

```
server {
	listen 81 default_server;
	listen [::]:81 default_server;

    # nchan ruling here

    location = /sub {
      nchan_subscriber;
      nchan_channel_id $arg_id;
      nchan_message_buffer_length 1;
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_id $arg_id;
    }
}
```

**Comment by vlcinsky** [comment]
Moving the `nchan_message_buffer_length` into publisher section resolves the problem:
```
server {
	listen 81 default_server;
	listen [::]:81 default_server;

    # nchan ruling here

    location = /sub {
      nchan_subscriber;
      nchan_channel_id $arg_id;
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_id $arg_id;
      nchan_message_buffer_length 1;
    }
}
```

It would be great if documentation mentions the fact, **the `nchan_message_buffer_length` instruction is supposed to be used  in the publisher section.**

**Comment by slact** [comment]
Here's how it's documented right now: 
https://nchan.io/#nchan_message_buffer_length
"Publisher configuration setting the maximum number of messages to store per channel. A channel's message buffer will retain a maximum of this many most recent messages. An Nginx variable can also be used to set the buffer length dynamically. "

I think this is pretty clear as it is.

**Comment by vlcinsky** [comment]
@slact Yes, you are right.

I was reading that section in terms of "this instructions affects publisher" and not "it shall appear in publisher section".

Now I know better how to read it (and it looks perfectly correct as it is), so I close it.
