### ISSUE TITLE
Upstream hooks not having headers with Nchan variables 

### ISSUE THREAD

**Issue by hermanbanken** [slact/nchan#463]
I have a sub/unsub hook setup like below, which has the NCHAN variables like `$nchan_channel_id`
````
location = /upstream/sub {
  internal;
  proxy_pass http://upstream/pubsub/sub;
  proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
  proxy_set_header X-Message-Id $nchan_message_id;
  proxy_set_header X-Channel-Id $nchan_channel_id;
  proxy_set_header X-Original-URI $request_uri;
}
````

On the upstream host I don't receive those headers however, only the `X-Original-URI` is filled and any other request header set on the subscription endpoint is also propagated (eg. `curl localhost:8080/sub -H "Foo: bar"` is received on the /pubsub/sub hook endpoint too).

I noticed you said the hooks where 'a giant hack' in some of the other issue, could that be the reason it doesn't work? Are there any requirements for the `$nchan_channel_id` variables to show up? Does this require a specific NGINX version?

I'm using NGINX 1.15.0 and building NCHAN 1.1.15 like so:
https://gist.github.com/hermanbanken/96f0ff298c162a522ddbba44cad31081

**Comment by hermanbanken** [comment]
It seems that the values are not persisted by the $nchan_channel_id variables, while they are if I set them manually using the `set` directive.

```
# Subscribe endpoint
location ~ /sub/authenticated/([\w\-]+)$ {
  internal;
  nchan_subscriber websocket eventsource;
  nchan_channel_id $1;
  set $channel $1; # <=========================
  nchan_channel_group "global";
  nchan_subscribe_request /upstream/sub;
  nchan_unsubscribe_request /upstream/unsub;
}
location = /upstream/sub {
  internal;
  proxy_pass http://upstream/pubsub/sub;
  proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
  proxy_set_header X-Message-Id $nchan_message_id;
  proxy_set_header X-Channel-Id-A $nchan_channel_id;
  proxy_set_header X-Channel-Id-B $channel;
  proxy_set_header X-Original-URI $request_uri;
}

```
then only `X-Channel-Id-B` is set.

**Comment by slact** [comment]
I'm unable to reproduce this with Nginx 1.15.0.

Here's what I tried:
 * subscribe directly to subscriber location
 * indirectly via X-Accel-Redirect (which appears to be what you're doing)doing), both as a normal and as an internal location
 * EventSource and websocket
 * nchan_subscribe_request location being regular and internal

Would you be able to post your complete nginx.conf? (edit out whatever you need to keep private.) And, if possible, exactly how you are able to reproduce this.
