### ISSUE TITLE
How avoid "nchan client prematurely closed connection" in Nginx logs?

### ISSUE THREAD

**Issue by kajmagnus** [slact/nchan#466]
I use Nchan and long polling. The browser aborts the long polling requests after 30 seconds and sends new requests (so firewalls etc won't kill the connections). This results in this info message in the Nginx error logs: `[info] 11#11: *9979 client prematurely closed connection while sending to client` — and I think I'd rather avoid having it in the logs.

What do people think? Someone who has ... what? Configured Nginx to not log it? Or terminates requests after 30 seconds, via some Nginx timeout instead? and the browser won't call `theHttpRequest.abort()`? Or maybe I'm pedantic who am thinking about maybe removing this message from the logs? Feels as if should be in the *access* log rather than *error* log anyway, since in this case is just expected behavior

(Hmm feels a bit weird to ask this in the issues list ... but where else :- ))

**Comment by slact** [comment]
Best way to do this is to turn down `error_log` to `notice`:

`error_log /path/to_log notice;`

**Comment by kajmagnus** [comment]
Thanks!  Hmm maybe I'd rather keep the log level at `info`, in case some other actually interesting *info* appears.  Maybe what could be interesting to do, is to have those Nchan related messages in the *access* log, rather than the *error* log, ... I suppose that'd mean messing with Nginx internals, not worth the time & complexity I suppose.
