### ISSUE TITLE
Setting message timeout with an if directive causes error

### ISSUE THREAD

**Issue by radalin** [slact/nchan#468]
We are trying to setup nchan where we can define a different timeout value for only some of the messages. From the issues and documentation we understand we should be setting a dynamic value to the "nchan_message_timeout" option. It's OK to setup this option with the following method:

```
location = /publish {
  # Note in our config channel id is dynamic as well
  nchan_channel_id $arg_id;
  nchan_publisher;
  nchan_store_messages on;
  nchan_message_timeout $arg_timeout;
  nchan_message_buffer_length 10;
}
```

If we send a "timeout" parameter as "30s" or "10s" it works great. However this requires us to set a value for the timeout for each request. It would be very nice if we had a default value (and instead of sending arbitrary values, it would be nice if those values were predefined). So we came up with the following approach:

```
location = /publish {
  set $msg_timeout "10s";
  if ($arg_priority = 1) {
    set $msg_timeout "30s";
  }
  nchan_channel_id $arg_id;
  nchan_publisher;
  nchan_store_messages on;
  nchan_message_timeout $msg_timeout;
  nchan_message_buffer_length 10;
}
```

So if a priority argument is send and set to 1 timeout becomes 30s. However this causes an error on the nchan side and subsequent requests to the queue fail as well.

The error we see is this:

```
2018/07/17 13:58:23 [error] 13830#0: MEMSTORE:01: tried adding WAITING chanhead 0000000002AAE290 /channel_name to chanhead_gc. why?
```

Our nginx configuration is like this:
```
nginx version: nginx/1.8.0
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/opt/nginx --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --with-cc-opt=-Wno-error --add-module=/home/deploy/passenger/src/nginx_module/ --add-module=/home/deploy/nchan-update/nchan-1.1.0
```

**Comment by slact** [comment]
`if`s in Nginx are notoriously weird. I recommend avoiding them if possible. Try this instead:

```
location /publish {
  nchan_channel_id $arg_id;
  nchan_publisher;
  nchan_store_messages on;
  nchan_message_timeout 10s;
  nchan_message_buffer_length 10;
  location = /publish/priority {
    nchan_publisher;
    nchan_message_timeout 30s;
  }
}

```

**Comment by slact** [comment]
I hope that helped.
