### ISSUE TITLE
Published message not sent to subscribers after setting server time back

### ISSUE THREAD

**Issue by luckyus** [slact/nchan#469]
Sometimes the server fails sending to the subscribers, with the following response:
`queued messages: 0`
`last requested: -377 sec. ago`
`active subscribers: 1`

this happens when I set the time of the server to say 30 mins backwards.  For examples, when I set the time of the server from 14:00 to 13:30.

I tried to set the nchan_message_timeout value to zero but no luck.

Is there any way to always send to the subscribers even the "last requested" is a negative number?

**Comment by slact** [comment]
Nchan expects to have a consistent increasing timestamp. Changing the server's time will result in missed messages.
