### ISSUE TITLE
Install specific Nchan version for Ubuntu

### ISSUE THREAD

**Issue by concreted** [slact/nchan#472]
Is there a way to specify an Nchan version when installing from https://nchan.io/download/nginx-common.ubuntu.deb? I see the link resolves to nginx-common_1.10.1-2ubuntu1_all.deb, with no Nchan version specified. Would like to be able to lock down the version when I deploy, and this package is more convenient than building from source. Thanks!

**Comment by slact** [comment]
Yup, build from source or use docker.
