### ISSUE TITLE
worker process exited on signal 11

### ISSUE THREAD

**Issue by tflin** [slact/nchan#473]
After updating nchan from 1.1.15 to 1.2.0, our websocket app will make our nginx server log a lot of the following errors:
2018/07/27 06:28:11 [alert] 6203#6203: worker process 6204 exited on signal 11 (core dumped)

In the nginx access.log, the last lines are:
59.120.186.12 - - [27/Jul/2018:06:28:10 +0000] "GET /ws1/sub/fb6bJkiX?accesstoken=xxxxx HTTP/1.1" 499 11 "-" "-" "-"
127.0.0.1 - - [27/Jul/2018:06:28:10 +0000] "GET /api1/nchan_unsub.php?accesstoken=xxxxx HTTP/1.0" 200 0 "-" "-" "-" 

When our app was turned to background or closed on iPhone, its websocket with server will be closed and the server will call our unsubscribe callback. After the unsubscribe callback was called, the worker process exited.

If we rollback nchan to 1.1.15, then there is no such error.

More info:
nginx version 1.15.2
nchan version 1.2.0
No redis.

nchan related configurations:

    # For nchan_authorize_request sub request
    location = /app/nchan_auth {
	proxy_pass http://localhost/api1/nchan_sub_auth.php;
	proxy_pass_request_body off;
	proxy_set_header Content-Length "";
	proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
	proxy_set_header X-Channel-Id $nchan_channel_id;
    }
    # For nchan_subscribe_request sub request
    location = /app/nchan_sub {
	proxy_pass http://localhost/api1/nchan_sub.php;
	proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
	proxy_set_header X-Channel-Id $nchan_channel_id;
    }
    # For nchan_unsubscribe_request sub request
    location = /app/nchan_unsub {
	proxy_pass http://localhost/api1/nchan_unsub.php;
	proxy_ignore_client_abort on;  #!!!important!!!!
        proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
        proxy_set_header X-Channel-Id $nchan_channel_id;
    }

    location ~ /ws1/sub/(\w+)$ {
        nchan_subscriber;
	nchan_channel_id $1; #first capture of the location match
        nchan_subscriber_first_message newest;
	nchan_authorize_request /app/nchan_auth;
	nchan_subscribe_request /app/nchan_sub;
	nchan_unsubscribe_request /app/nchan_unsub;
    }

    location ~ /ws1/pub/(\w+)$ {
	allow 127.0.0.1;
	allow 59.120.186.0/24;
	deny all;
        nchan_publisher;
        nchan_channel_id $1; #first capture of the location match
        nchan_deflate_message_for_websocket on;
	nchan_message_timeout 10m;
    }

**Comment by slact** [comment]
Looking into this.

**Comment by slact** [comment]
@tflin I haven't been able to reproduce this so far -- is there any chance I could take a look at your server? Email me at support@nchan.io and we can work out the details.

**Comment by tflin** [comment]
@slact This problem happened on our customer's server so we cannot provide you the login access. I have emailed you the core dump file and hopefully it helps you to find this problem.

**Comment by tflin** [comment]
The problem seems to be solved now. I have tested with latest 1.2.2 and it works fine. I think it was fixed at https://github.com/slact/nchan/commit/465663e681f77736350eae8b34c1fcad4316426e
So closing it.
