### ISSUE TITLE
How to avoid duplicate messages on multiplexed channels

### ISSUE THREAD

**Issue by qhenkart** [slact/nchan#474]
Hi Slact,

I've run into a minor issue and I'm wondering if this might be something that is already possible within nchan, although I could not find a solution in the docs or previous github issues.

I multiplex each subscription with a user so that I can handle permission changes etc. There are several subscriptions per user depending on their activity (again each multiplexed).

I want to publish an event that is specific to that user, so naturally I publish to their user channel, however because of multiplexing, they are going to receive that same message multiplied by the number of subscriptions they have.

My question is: Is there a way to publish to a multiplex combination to avoid duplicates

Ex.

 ```
location ~ /multipub/(\w+)/(\w+)$ {
    nchan_publisher;
    nchan_channel_id "$1" "$2" "another_channel";
    #POST /multipub/foo/bar will publish to **The Combination of :**
    # channels 'foo', 'bar', 'another_channel'
  }
```

**Comment by slact** [comment]
You are publishing to all 3 channels with that location. To publish only to the user channel, use

```
location ~ /pub/user/(\w+)$ {
    nchan_publisher;
    nchan_channel_id "$1";
  }
```

Also, to avoid channel overlap from different publisher locations, you should make your channels something like "user_$1" and "group_$1" rather than just "$1" and "$2".

**Comment by slact** [comment]
Ah, okay. Your solution is what I would have recommended in that case.
