### ISSUE TITLE
Error when compiling nchan

### ISSUE THREAD

**Issue by GilbertDaariked** [slact/nchan#475]
I`m using CentOS 6 and trying to make nginx with nchan, but I get:
/tmp/nchan/src/util/nchan_util.c: In function ‘nchan_inflate’:
/tmp/nchan/src/util/nchan_util.c:941: error: ‘mm_instr.data’ may be used uninitialized in this function
/tmp/nchan/src/util/nchan_util.c:941: error: ‘mm_instr.len’ may be used uninitialized in this function
/tmp/nchan/src/util/nchan_util.c: In function ‘nchan_common_deflate’:
/tmp/nchan/src/util/nchan_util.c:846: error: ‘mm_instr.data’ may be used uninitialized in this function
/tmp/nchan/src/util/nchan_util.c:846: error: ‘mm_instr.len’ may be used uninitialized in this function

**Comment by slact** [comment]
This is a warning from within the zlib version you're using, and I can't really fix it in Nchan. You can still build Nchan by removing -Werror from the cflags passed to the compiler.

**Comment by GilbertDaariked** [comment]
Year, it works, thanks.
