### ISSUE TITLE
No messages after worker crash

### ISSUE THREAD

**Issue by neben** [slact/nchan#477]
If an nginx worker process dies and gets respawned, some existing and future nchan subscriptions cease to work correctly (no more messages for certain channels). This can be reproduced easily by killing an nginx worker process. In contrast, if the nginx master process is signaled to reload the config and respawn the worker processes (SIGHUP on the master process), new subscriptions and messages will work fine.

Nchan version 1.2.0
Openresty 1.13.6.2

**Comment by neben** [comment]
Ok, thanks! Is this documented somewhere? Unfortunately we don't have the funds to sponsor that (yet). Our current workaround is to SIGHUP the master process if we detect a worker crash. Alternatively, running with a single worker should solve it, too. For now, we'll focus on figuring out why the worker is crashing in the first place.

**Comment by slact** [comment]
I guess this isn't explicitly documented -- I figured it's common sense that if a worker crashes you should expect some data loss and some undefined behavior. It wouldn't hurt to document that though.

**Comment by kajmagnus** [comment]
@neben  I have this problem too, that Nchan in effect stops working after a worker crash, and can stay broken until the next restart which might not be until weeks later (no live notifications, until then).  How do you detect a crash and send a SIGHUP, you don't happen to have to have a reusable script or something?

**Comment by ivanovv** [comment]
@kajmagnus the easiest fix for this is to have only one worker, then nginx master process will auto restart it and everything works again. I guess that needs to go into the README as it is non obvious thing and many had prod servers stuck

**Comment by kajmagnus** [comment]
@ivanovv  Thanks I'll try this. My VPS servers don't have more than 1 or 2 vCPUs anyway.

**Comment by ivanovv** [comment]
@kajmagnus well, nginx by default comes with `worker_processes 1;` and unless you are sure that nginx uses something close to 100% of one core there is no good reason to set it to auto or any other number.

It is all a bit different for `nchan` as having more workers helps a lot with scaling (channels are spread between workers) as @slact has mentioned in one of the issues. But again, that all starts to play a role only when you have a lot of subscribers anyway.

**Comment by kajmagnus** [comment]
@ivanovv ok thanks for the info.  I had previously changed from `worker_processes 1` to `auto` based on https://www.nginx.com/blog/tuning-nginx/: *"we recommend setting this directive to auto"* but yes I agree, anything above 1 seems like a bit overkill in most cases. Now back to 1.  I did quick tests:

`wrk  -t 6  -c 100  -d 10  http://site-3.localhost/-/ping-nginx`  —>
77 k req/seq, with `auto`, and 35 k req/seq, with `1`  on my core i7 laptop.

And 35 k is faster than fast enough in my case :- ) Ok so hopefully all fine here then ... for the nearest ... years.

**Comment by slact** [comment]
fixed in 1.3.0 or thereabout
