### ISSUE TITLE
Feature request: multipart/mixed subscriber support

### ISSUE THREAD

**Issue by nabucho** [slact/nchan#48]
I would greatly appreciate (and I am willing to sponsor that feature) if there was a posibility to issue a request ( not long-poll ), that will return whole buffer, or messages newer than I-M-S + Etag, in one response. Response could be multipart/mixed for example to stay standardized.

The data is there, so it should be fairly easy to traverse the buffer.

Thank you very much for consideration.

**Comment by slact** [comment]
This is now possible with EventSource and websocket. I might add multipart/mixed support as well, depending on whether there's enough interest. We're in an HTML5 world now, after all...

**Comment by amcgregor** [comment]
Interesting blast from the ticket past; thanks for the update!  I actually do continue to make use of mime multipart to deliver paired JSON and HTML DOM content.  However, for realtime, I agree that EventSource and websockets are both far superior solutions.

**Comment by slact** [comment]
This is now nearly-trivial to implement, so I'll probably get around to it after the upcoming release. Right now I have other priorities.

**Comment by amcgregor** [comment]
Indeed.  The facility for modern _browser_ user agents to utilize superior technologies doesn't eliminate the use case of "dumber" systems wishing to "extremely long poll", say, once every four hours.  (As some of our systems at work do—for third-party business reasons, sadly.)

**Comment by slact** [comment]
You've asked for it, and 5 years later -- it's done ( 9d4462704af45144e396bc9341d8c7b16165bbc1 ). Nchan now has chunked and multipart/message support. These will be included in the next version once I road-test them a bit more.

documentation: https://nchan.slact.net/#http-chunked-transfer and https://nchan.slact.net/#http-multipart-mixed

**Comment by amcgregor** [comment]
Interesting!  :D  The intent was to use them together: each multipart part would be a chunk, and the joy of multipart is the ability to pass through additional headers.  I'll be sure to test this out soon.

**Comment by slact** [comment]
Closing this because it's been pretty well-tested at this point.
