### ISSUE TITLE
nchan_publisher_upstream_request pub to another channel when upstream

### ISSUE THREAD

**Issue by dungdev** [slact/nchan#483]
I use nchan_publisher_upstream_request. How to assign pub to another channel id.

location ~ /pub-streaming/level1/(.*)$ {
        nchan_publisher;
        nchan_channel_id "$1";
        nchan_channel_group level1;
        nchan_websocket_client_heartbeat _ping _pong;
        nchan_publisher_upstream_request /upstream_pub/$1;
   }

location = /upstream_pub {
        proxy_pass http://127.0.0.1:4000;
        proxy_pass_request_body on;
        proxy_set_header X-Publisher-Type $nchan_publisher_type;
        proxy_set_header X-Prev-Message-Id $nchan_prev_message_id;
        proxy_set_header X-Channel-Id $nchan_channel_id;
        proxy_set_header X-Original-URI $request_uri;
    } 
I use websocket on pub-streaming/level1/DMS, channel id is DMS. After upstream I want to pub to channel id as ABC
I tried to fix the X-Channel-Id in the header but failed.

**Comment by slact** [comment]
If I understand your question correctly, you need to issue a separate POST request in your upstream app.

**Comment by slact** [comment]
:man_shrugging:
