### ISSUE TITLE
Error Insufficient Storage with Redis

### ISSUE THREAD

**Issue by dungvu-qe** [slact/nchan#487]
When I test push data to nchan with redis in version 1.2.1, I have this issues, here the snapshot in redis-db of nchan:
![2018-09-17 at 23 26 47](https://user-images.githubusercontent.com/9478537/45636333-9e34ed00-bad1-11e8-9681-800c3725021f.jpeg)
And if I subscribe these channels via SSE, this throws the exception: "Insufficient Storage".
@slact could you support me, please?

**Comment by slact** [comment]
I need more information. Your Nginx config, Nchan version, NGinx version, Redis version, server OS, etc. Give me a way to reproduce this issue and then I can help.

**Comment by dungvu-qe** [comment]
work great in 1.2.2

**Comment by dungvu-qe** [comment]
thanks dev
