### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Terrorist-1** [slact/nchan#489]
Hi i found build errors by centos6.5
1.yum install nginx //nginx-1.14.0
2.i download nginx-source-1.14.0 and nchan-1.2.1 source
2.1cd nginx-source-1.14.0 
2.2 ./configure  --add-module=/root/nchan-1.2.1 =>ok
2.3 make  && make install  =>error
 
![image](https://user-images.githubusercontent.com/22310979/46190481-4e062800-c326-11e8-9265-eccafdc81a0e.png)

I am a beginner. Can you describe the steps?

**Comment by slact** [comment]
This is an erroneous compiler warning being treated as an error. I've fixed it in e1a532d1. For now, you can build it by adding --with-cc-opt="$CFLAGS -Wno-error" to the `./configure` command

**Comment by Terrorist-1** [comment]
ok
thanks ...i  have 
 "make CFLAGS=-Werror" to avoid error
