### ISSUE TITLE
Worker crash on subscription

### ISSUE THREAD

**Issue by dungvu-qe** [slact/nchan#492]
On nchan 1.2.2, we have facing with lost subscription from nchan on errors, it happens every 3-5s : 

> Assertion failed: d->multi_chanhead->multi_waiting > 0 (/usr/src/nchan-1.2.2/src/subscribers/memstore_multi.c: sub_enqueue: 47)
> worker process 24 exited on signal 6

We use:
NCHAN 1.2.2
NGINX: 1.15.5
OS: Alpine 3.8 via docker

We publish data on the nchan server in about ~1000 channels with ~10msg/s per channel, but the service publisher only run in the working hours (8h per day). And I should add the time ping msg, only time data in every 5s to keep the client connections all works.
Another side, we use the nchan.js to sub the channels, about 200-300 concurrents connections.

 And here my config:

```
user  nginx;

worker_processes 1;
worker_rlimit_core    1024M;
worker_rlimit_nofile  10000;

load_module "modules/ngx_nchan_module.so";

events {
   worker_connections  1024;
   accept_mutex on;
}

http {
   include       /etc/nginx/mime.types;
   default_type  application/octet-stream;

   sendfile        on;
   
   client_body_timeout 5;
   client_header_timeout 5;
   send_timeout 5;
   keepalive_timeout 30;

   nchan_max_reserved_memory 128M;

  upstream redis_cluster {
       nchan_redis_server redis://redis-service:6379;
       nchan_redis_storage_mode distributed;
       nchan_redis_connect_timeout 2s;
 }

server {
    listen 80;

    keepalive_timeout  30s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;

    nchan_store_messages on;
    nchan_message_buffer_length 50;
    nchan_message_timeout 30s;

    nchan_redis_storage_mode distributed;
    nchan_redis_idle_channel_cache_timeout 30s;
    nchan_redis_ping_interval 5s;

    nchan_subscriber_timeout 30;
    nchan_subscriber_first_message oldest;

    nchan_access_control_allow_origin *;
    add_header 'Access-Control-Allow-Headers' 'If-None-Match, If-Modified-Since, Content-Type, Cache-Control, X-EventSource-Event, Last-Event-ID, Authorization';

    location / {
        return 200; 
        add_header Content-Type text/plain;
    }
   
    # test
    location ~ /sub/(.*)$ {\
        nchan_subscriber websocket eventsource;
        nchan_channel_id "$1,ping";
        nchan_channel_group "streaming_test";
        nchan_channel_id_split_delimiter ",";
        nchan_redis_pass redis_cluster;
    }
 }

server {
    listen 8081;
    listen 8080 http2;

    keepalive_timeout  30s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;

    nchan_store_messages on;
    nchan_message_buffer_length 50;
    nchan_message_timeout 30s;

    nchan_redis_storage_mode distributed;
    nchan_redis_idle_channel_cache_timeout 30s;
    nchan_redis_ping_interval 5s;

    nchan_subscriber_timeout 30;
    nchan_subscriber_first_message oldest;
    
    location ~ /pub/(.*)$ {
        nchan_publisher;
        nchan_channel_id "$1";
        nchan_channel_group "streaming_test";
        nchan_redis_pass redis_cluster;
    }

    # ping
    location ~ /ping/(.*)$ {
        nchan_publisher;
        nchan_channel_id ping;
        nchan_channel_group $1;
        nchan_redis_pass redis_cluster;
    }
 }
}
```

Could you check it for me?

**Comment by dungvu-qe** [comment]
Addition info, I use separate the subscriber services and the publisher services in each server/docker but use same the config above. All the subs/pubs shared with the same redis DB and only the sub can NAT to internet. Is this normal case?

**Comment by pacotarancon** [comment]
Hi there,

I'm also facing the same issues mentioned above:

> ../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
> 2018/11/13 20:03:53 [alert] 2966#0: worker process 2969 exited on signal 6 (core dumped)
> ../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
> 2018/11/14 00:17:38 [alert] 2966#0: worker process 16010 exited on signal 6 (core dumped)
> ../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
> 2018/11/14 04:31:26 [alert] 2966#0: worker process 28986 exited on signal 6 (core dumped)
> 2018/11/14 10:00:01 [notice] 26358#0: signal process started

My versions are:
NCHAN 1.2.1 (Also tried upgrading to 1.2.2)
NGINX: 1.14.0

What is weird in my case is regarding the core dump itself.... Although I have configured (and tested by killing via kill -6, the same signal as above) the ability to create cores, nginx is not able to create the cores when the workers crashs and is restarted.

I have uploaded some nginx logs in debug mode when the worker crushes (only during the timestamp when the crash happened), hope it helps.

[nginx_debugmode_errors.zip](https://github.com/slact/nchan/files/2581546/nginx_debugmode_errors.zip)

**Comment by slact** [comment]
looking into this. I'll probably need to look at the coredumps if I can't reproduce it.

**Comment by pacotarancon** [comment]
Hi again,

It is happening very often since the last days.

../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2018/11/17 15:03:28 [alert] 3706#0: worker process 11903 exited on signal 6 (core dumped)
../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2018/11/17 19:17:09 [alert] 3706#0: worker process 4023 exited on signal 6 (core dumped)
../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2018/11/18 00:54:06 [alert] 3706#0: worker process 16959 exited on signal 6 (core dumped)
../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2018/11/18 05:07:44 [alert] 3706#0: worker process 1751 exited on signal 6 (core dumped)
../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2018/11/18 11:28:18 [alert] 3706#0: worker process 14729 exited on signal 6 (core dumped)
../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2018/11/18 15:41:59 [alert] 3706#0: worker process 1717 exited on signal 6 (core dumped)
../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2018/11/18 19:55:43 [alert] 3706#0: worker process 14645 exited on signal 6 (core dumped)
../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2018/11/19 03:15:50 [alert] 3706#0: worker process 27552 exited on signal 6 (core dumped)
../nchan-1.2.1//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2018/11/19 07:29:35 [alert] 3706#0: worker process 17645 exited on signal 6 (core dumped)

By the way, I have attached our nginx.conf file.... hope it helps
[nginx.txt](https://github.com/slact/nchan/files/2603716/nginx.txt)

**Comment by scarrascoso** [comment]
Hi! I'm having a similar problem too (symptoms are the same as described here). I can provide logs if needed, to help with the investigation. Thanks!

**Comment by ZUBAT** [comment]
hi. i'm having a similar problem.
ker process: /build/nginx-0TiIP5/nginx-1.10.3/debian/modules/nchan/src/store/memory/ipc-handlers.c:417: memstore_ipc_send_get_message: Assertion `data.shm_chid->len>1' failed.
2019/01/30 21:35:15 [alert] 16704#16704: worker process 16710 exited on signal 6
2019/01/30 21:36:44 [error] 16705#16705: MEMSTORE:00: tried adding WAITING chanhead 0000556DBFC32D20 /USER_107311 to chanhead_gc. why?
2019/01/30 21:37:09 [error] 16716#16716: MEMSTORE:11: tried adding WAITING chanhead 0000556DBFB52E30 /USER_161200 to chanhead_gc. why?
2019/01/30 21:37:10 [error] 16716#16716: MEMSTORE:11: tried adding WAITING chanhead 0000556DBFD18240 /USER_160496 to chanhead_gc. why?
2019/01/30 21:37:30 [error] 16709#16709: MEMSTORE:04: tried adding WAITING chanhead 0000556DBFC7B560 /USER_154760 to chanhead_gc. why?
2019/01/30 21:37:40 [error] 27337#27337: MEMSTORE:05: tried adding WAITING chanhead 0000556DBF9D91B0 /ALL_USERS to chanhead_gc. why?
2019/01/30 21:38:52 [error] 16711#16711: MEMSTORE:06: tried adding WAITING chanhead 0000556DBFD60230 /USER_161204 to chanhead_gc. why?

**Comment by ZUBAT** [comment]
libnginx-mod-nchan/stable,now 1.10.3-1+deb9u2 amd64 [installed,automatic]
nginx-common/stable,now 1.10.3-1+deb9u2 all [installed,automatic]
nginx-extras/stable,now 1.10.3-1+deb9u2 amd64 [installed]
Install from apt.
OS Debian 9

**Comment by pacotarancon** [comment]
I'm still facing the same issues as commented before.
I tried with the latest version of nechan: 1.2.4 but I'm afraid that issues is far to be solved:

../nchan-1.2.4//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
--
2019/03/20 13:45:55 [alert] 32397#0: worker process 21414 exited on signal 6
../nchan-1.2.4//src/subscribers/memstore_multi.c:47: sub_enqueue: Assertion `d->multi_chanhead->multi_waiting > 0' failed.
2019/03/20 14:08:00 [alert] 32397#0: worker process 30716 exited on signal 6

Any update on your investigations slact?

**Comment by slact** [comment]
I need a core dump from someone that's observed this problem, as so far I haven't been able to reproduce it. Whoever wants to take that up, I'll help you set it up if you want help.

**Comment by pacotarancon** [comment]
Hi @slact I sent you an email with a link to download the coredump.
The version installed is the environment is the following: 

> nginx version: nginx/1.14.2
> nchan version: 1.2.5

Thanks for your help

**Comment by rmartin-rp** [comment]
Hi @slact, I'm interested on speed up this investigation. Would some sponsoring help?

**Comment by slact** [comment]
@rmartin-rp : I'm usually not one to turn down a financial incentive, but I'm already scheduled to get to the bottom of this next week. I can't promise to fix it any faster in this case, sponsorship or not, as my time this week is already spoken for.

I would, however, graciously accept any sponsorship you can provide after I have this thing fixed.

**Comment by slact** [comment]
Alright, I don't have a fix yet, but I do have a debug build for you guys to try. This doesn't fix the problem, but catches it at an earlier stage. @pacotarancon , would you be able to build Nginx with `-O0 -ggdb` from the debug-492 branch, and send me the coredump + nginx binary when it crashes?

**Comment by pacotarancon** [comment]
I tried what you commented, but looks like I'm facing compilation errors.
I had this error when "make install"

/nchan-debug-492/src \
	-o objs/addon/subscribers/memstore_multi.o \
	../nchan-debug-492/src/subscribers/memstore_multi.c
../nchan-debug-492/src/subscribers/memstore_multi.c: In function ‘sub_enqueue’:
../nchan-debug-492/src/subscribers/memstore_multi.c:52:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i=0; i<d->multi_chanhead->multi_count; i++) {
   ^
../nchan-debug-492/src/subscribers/memstore_multi.c:52:3: note: use option -std=c99 or -std=gnu99 to compile your code
../nchan-debug-492/src/subscribers/memstore_multi.c: In function ‘memstore_multi_subscriber_create’:
../nchan-debug-492/src/subscribers/memstore_multi.c:185:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i=0; i<chanhead->multi_count; i++) {
   ^
make[1]: *** [objs/addon/subscribers/memstore_multi.o] Error 1
make[1]: Leaving directory `/root/nginx-nchan-echo/PRE-version/nginx-1.14.2'
make: *** [install] Error 2

**Comment by pacotarancon** [comment]
by the way, I used the following to compile:

./configure --with-http_ssl_module              	\
            --with-http_stub_status_module      	\
            --with-debug                        	\
            --add-module=../nchan-debug-492			\
            --add-module=../echo-nginx-module-0.61 	\
            --with-cc-opt='-ggdb -O0 -fvar-tracking-assignments' \
            --prefix=/usr/local/nginx-debug492

and the following compiler:

libgcc-4.8.5-28.el7_5.1.x86_64
gcc-4.8.5-28.el7_5.1.x86_64
gcc-c++-4.8.5-28.el7_5.1.x86_64

**Comment by slact** [comment]
I guess you're building is C89 mode... pretty oldschool, but that's fine by me. branch updated, give it another try.

**Comment by slact** [comment]
Ok, that did it. I've got a fix in branch `fix-492` . Please test it in your environment to confirm it.

**Comment by pacotarancon** [comment]
It seems working, Before, I could reproduce the problem in minutes. Now it's not failing. Anyways, give me a couple of days for heavy testing it and I will confirm you this issue is fixed :) Thanks!

**Comment by pacotarancon** [comment]
Hi @slact 
After several days of testing I'm happy to say this problem is fixed :)
Thank you so much for your help.

PD: During all this tests, I've faced with another problem related with messages in memory not being dropped. I'll open other issue for this so it gets documented (you are gonna hate me :D)
