### ISSUE TITLE
Modify channel subscriptions w/o reestablishing websocket

### ISSUE THREAD

**Issue by neben** [slact/nchan#493]
Our clients use websockets to subscribe to a list of channels, and this list changes frequently. The client thus has to tear down the websocket connection and establish a new one containing the updated list for each and every change.

It would be great to be able to dynamically update the list of channel subscriptions over the connected websocket. The message protocol wouldn't have to be defined by nchan: one could process the message in LUA, and then call some nchan function to update the list of subscribers.

**Comment by andrisi** [comment]
Indeed, this would very useful. With Websockets, but with EventSource et al. too.

**Comment by slact** [comment]
This will be available in Nchan 2. Best timeframe I can give is sometime in 2021.
