### ISSUE TITLE
nchan_redis_ping_interval has no effect in server context

### ISSUE THREAD

**Issue by neben** [slact/nchan#501]
Setting `nchan_redis_ping_interval` in server context has no effect, pings are still sent using the 4m default setting. It does work, however, in the location context. The documentation states it should work in http, server, and location context. This can be easily verified using redis' `monitor` command.

**Comment by slact** [comment]
Tested. can't reproduce. Can you post your config and your Nchan version?

**Comment by slact** [comment]
never got the config from submitter.
