### ISSUE TITLE
Nchan Redis Namespace Prefix Overflow Error

### ISSUE THREAD

**Issue by sshquack** [slact/nchan#504]
Hello @slact, First off, thanks for creating Nchan 🙏 

There seems to be a bug in using `nchan_redis_namespace` prefix per https://nchan.io/#nchan_redis_namespace where after the 8th character, there is an overflow that causes the nginx config to be read. 

To illustrate the issue, I've put together a full working example at https://github.com/sshquack/nchan-namespace-repro

## Versions

- Nchan 1.2.3
- Nginx 1.15.7
- Redis 5.0

## How to reproduce issue

- Clone repo

```
$ git clone https://github.com/sshquack/nchan-namespace-repro
$ cd nchan-namespace-repro
```

- Start Nchan locally on port 8080 using `docker-compose`

```
$ make build run logs
```

- Publish a message

```
$ curl -XPOST -d test http://localhost:8080/pub
```

- Check redis keys

```
$ make redis-cli
127.0.0.1:6379> keys *
1) "12345678location{channel:/foobar}"
2) "12345678location{channel:/foobar}:msg:1545456206:0"
3) "12345678location{channel:/foobar}:messages"
```

- Notice that `nchan_redis_namespace "123456789012345";`
- Expected key prefix: `123456789012345`
- Asserted key prefix: `12345678location`

Seems like some sort of overflow after the 8th character is causing the Nginx config to be read. Could you please investigate this issue?

**Comment by slact** [comment]
oops. fixed in 93007012

**Comment by sshquack** [comment]
Thanks @slact! Looking forward to the next Nchan release version. Please feel free to close this issue.

**Comment by slact** [comment]
and thank you for your very thorough bug report
