### ISSUE TITLE
Messages hanging in redis

### ISSUE THREAD

**Issue by qhenkart** [slact/nchan#510]
I've been trying to get to the bottom of some instability with nchan we've been dealing with. We use redis to handle a distributed setup. It seems that messages only _sometimes_ get published to subscribers, and other times they don't.

Currently, I have an active subscriber to `p/1234` utilizing long-polling, the request is waiting for a response.
in redis I see the subscriber
`"{channel:/p1234}"` for 5 seconds and then it disappears

After publishing a message, I see the following in redis
```
6) "{channel:/p1234}:messages"
7) "{channel:/p1234}:msg:1548221637:0"
8) "{channel:/p1234}"
```

and these entries persist beyond 5 seconds

The message is obviously there, but the http request on the client does not always receive it. This happens about 50% of the time.

The configuration looks like the following
```  
upstream redisdb {
    nchan_redis_server "123.123.123/1";
  }
```

```
location ~* "^/subscribe/((p)[|0-9])$" {
    nchan_subscriber;
    nchan_subscriber_first_message newest;
    nchan_subscriber_compound_eta g_message_id on;
    nchan_channel_id $sent_http_x_channel_id
    nchan_redis_pass redisdb;
    add_header Cache-Control 'no-store';
  }

  location ~ ^/publish/(.*)$ {
    nchan_publisher;
    nchan_channel_id $1;
    nchan_redis_pass redisdb;
  }
```

**Comment by slact** [comment]
i think the best way for me to debug this is to take a look at your servers. If that's possible, email me at leo@nchan.io and we'll arrange a debugging session.

**Comment by qhenkart** [comment]
I believe this is a result to my workarounds and Etag stripping by cloudfront, more info here: https://github.com/slact/nchan/issues/499
