### ISSUE TITLE
nchan/nginx memory usage grows when messages are over 10000 bytes

### ISSUE THREAD

**Issue by rexroof** [slact/nchan#511]
I have (what I think is) a relatively simple nchan & redis setup running in docker/kubernetes.  It exposes one pub/sub endpoint and stores messages in redis.    This nginx instance is only used for this single purpose of processing nchan requests.  Other containers are used to serve other content and using kubernetes ingress rules only the nchan endpoints are routed to this container. 

I started to try and diagnose this problem after I noticed that our nchan containers would grow in memory and never release it.   After much testing I came to understand that when our messages published to nchan were under 10,000 bytes, no more memory would be consumed.  the container would use less than 10Mb of total memory usage.   Our normal message size is around 36,000 bytes.  this will cause our nchan containers to grow ~ 6Mb every 10 minutes and never reduce in size.  I've seen some nchan containers consume over 2Gb of memory.

[nchan config nchan-nginx.txt](https://github.com/slact/nchan/files/2789079/nchan-nginx.txt)

I am creating a docker container using `debian:buster-slim` and then the tar file from nchan.io/download/nginx-nchan-latest.tar.gz.     This is nchan version 1.2.3 and nginx 1.10.1.

I will say that I do see my messages in redis and they keep updated.

I am happy to provide any more details as needed.

**Comment by rexroof** [comment]
during my tests I would submit messages every second or every 5 seconds, in either case the message size always dictated if the memory grew and not the timing of the messages.

**Comment by slact** [comment]
Is the nginx process itself consuming memory, or the container?

**Comment by rexroof** [comment]
well, nginx is the only thing in the container, but the memory consumption I'm seeing is via the kubernetes metrics.

here is some PS output from inside the container:

```
# ps -auwwx
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1 143416 10012 ?        Ss   Jan23   0:00 nginx: master process nginx -g daemon off;
www-data     6  0.0  0.1 144192  9860 ?        S    Jan23   0:08 nginx: worker process
root         7  0.0  0.0   2388  1560 ?        Ss   01:59   0:00 sh
root       296  0.0  0.0   9676  2704 ?        R+   02:02   0:00 ps -auwwx
# pmap -x 1 | grep total
total kB          143420   10012    4252
#
```

the kubernetes metrics say this container is using 234 MB of memory right now.

**Comment by rexroof** [comment]
those are great ideas.  I tried a few things but wasn't able to get the memory usage to stop growing. 

I noticed that the default place for the client_body_temp_path was already /var/cache/nginx/client_temp.  /var/cache is part of / in this container, an overlay filesystem.   I tried some other spots, but everything in the container that is writable is part of that root overlay filesystem. 

I also tried expanding the size of client_body_buffer_size but I never got it to stop writing the temp files.

**Comment by slact** [comment]
Please set `nchan_message_timeout` to 1-2 minutes and see how this affects memory usage.

**Comment by rexroof** [comment]
I went ahead and set it to 1m and didn't see much difference in memory growth.   I did notice that fewer messages were resting in redis, but that is to be expected. 

I increased my client_body settings but I'm still seeing files being written to the cache folder. 

This is what my nginx config looks like right now: 
https://gist.github.com/rexroof/4fe410f077d644eb97aeb07390c1e31b

I enabled debug logging and here are a few hundred lines of that, if you care to look.
https://gist.github.com/rexroof/4648c9218e63e6672cceaf19bad639b8
I'm curious what the **recv() not ready (11: Resource temporarily unavailable)** could be.

I appreciate you spending time to look at this.

**Comment by rexroof** [comment]
@slact any better information I can provide to help debug?

**Comment by rexroof** [comment]
This ended up being a problem with nginx in docker.  writing files to client_temp was causing memory growth in the pod/container.   I fixed this by setting body buffer size and max body size to the same thing:

```
client_body_buffer_size 10m;
client_max_body_size    10m;

```

This advice came from this medium post about running nginx inside docker:
https://medium.com/urban-massage-product/nginx-with-docker-easier-said-than-done-d1b5815d00d0
