### ISSUE TITLE
websocket.c:570: websocket_publish_upstream_handler: Assertion `d->subrequest' failed

### ISSUE THREAD

**Issue by sg-jorrit** [slact/nchan#512]
Hi, I am getting an error and as a result an exiting worker process as soon as I try to pass along newly received messages from pubsub location to upstream handler. In this case, I'd like to use Lua to modify message contents or directly handle that message from OpenResty without having to pass it through. 

This because I already verify the session/authorization on the Websocket connection once it's open and I think it's not really efficient to re-do all that later when handling the message.

```
    location = /queue {
        # Restrict access by JWT token and set session vars
        access_by_lua_file lua/tvapi-jwt.lua;

        # Handle request as pubsub
        nchan_pubsub;

        # Timeout for longpoll, websocket inactivity
        nchan_subscriber_timeout 60;

        # Websocket settings
        nchan_websocket_client_heartbeat PING PONG;
        nchan_websocket_ping_interval 30;

        # We publish all incoming messages to user's channel
        nchan_publisher_channel_id user:$session_user;

        # Subscribe to all required subchannels (based on session vars)
        nchan_subscriber_channel_id user:$session_user serial:$session_serial device:$session_devtype $session_channels;
        nchan_channel_id_split_delimiter ",";

        # Set group to isolate based on aud of JWT (environment)
        nchan_channel_group $session_aud;

        # Determine first message order
        nchan_subscriber_first_message oldest;

        # Pass to message handler
        nchan_publisher_upstream_request /queue_msg;
    }

    location = /queue_msg {
        # Here I'd really like to re-use the session vars set by the lua/tvapi-jwt.lua script
        content_by_lua_file lua/queue-msg.lua;
    }
```
Inside lua/queue-msg.lua I take care of returning a status 304, 200 or 204. It seems like whatever I try to do, the worker always exits and closes the Websocket connection to the client after every received message. The error I see in the log is as follows;
```
/tmp/nchan-1.2.3/src/subscribers/websocket.c:570: websocket_publish_upstream_handler: Assertion `d->subrequest' failed.
2019/02/11 15:24:17 [alert] 1#1: worker process 86 exited on signal 6
```
How would I go about making this possible? Or do I really need to proxypass to another server running on the same nginx host on another port, and then passing through all or this by GET args (preferably not)? I also tried the OpenResty/Lua examples found in other issues, but they also do not work.

I currently use these versions;

```
ARG RESTY_VERSION="1.13.6.2"
ARG RESTY_LUAROCKS_VERSION="2.4.4"
ARG RESTY_OPENSSL_VERSION="1.1.0i"
ARG RESTY_PCRE_VERSION="8.42"
ARG NCHAN_VERSION="1.2.3"
```
Thanks in advance.

**Comment by slact** [comment]
> do I really need to proxypass to another server running on the same nginx host on another port

Unfortunately, this is currently the case. I'd say this will be fixed in future versions, but the plan is to move away from Nginx anyway, so this will be incidentally fixed in the future.

**Comment by sg-jorrit** [comment]
Ah okay. So you are saying you'll eventually move to OpenResty instead of nginx? Or completely away from nginx?

If OpenResty, then it'd also be more trivial to support the Lua directives more deeply, maybe even expose a new directive for handling messages directly. Sounds good.

In the meantime we found that building everything into one big appliance is too complex - currently putting everything into microservices where another instance will process the messages anyways. So the proxypass method is fine for now. :-)

**Comment by slact** [comment]
Away from the Nginx platform to a standalone server. So this will become a non-issue altogether.

**Comment by sg-jorrit** [comment]
Okay, that's good to know. Sounds good! I'll close this issue for now.
