### ISSUE TITLE
Allow multiple origins

### ISSUE THREAD

**Issue by neben** [slact/nchan#515]
Is it possible to specify a set of allowed origins using `nchan_access_control_allow_origin`? I don't want to allow all origins ('*'), but I need to allow more than one (one for production, one for testing).

**Comment by slact** [comment]
```
nchan_access_control_allow_origin origin1 origin2;
```

**Comment by neben** [comment]
That doesn't work, if I use
```
nchan_access_control_allow_origin https://origin1 https://origin2:8443 https://origin3:9876;
``` 
I get:
```
nginx: [emerg] invalid number of arguments in "nchan_access_control_allow_origin" directive in /etc/nginx/nginx.conf:77
```
Am I missing something?

**Comment by slact** [comment]
Ah, right. Put it in quotes then:
```
nchan_access_control_allow_origin "origin1 origin2";
```

**Comment by neben** [comment]
Great, that works. Can you update the documentation? Thanks!

**Comment by slact** [comment]
documented in aba598e9fd3ee997e
