### ISSUE TITLE
Empty PONG from NChan

### ISSUE THREAD

**Issue by i-93** [slact/nchan#521]
It looks like NChan replies on client PING with empty PONG, while by [RFC](https://tools.ietf.org/html/rfc6455#section-5.5.3) it should send back the data received in PING. 

That breaks keep-alive for some clients

**Comment by slact** [comment]
fixed in eb3c6cdc

**Comment by slact** [comment]
err, make that 2f6f22e5 . Just build from master and give it a try.

**Comment by slact** [comment]
This fix has already been released.
