### ISSUE TITLE
Channel Multiplexing: With multiple channel subscribers nchan return 403 code 

### ISSUE THREAD

**Issue by solofeed** [slact/nchan#524]
NGINX_VERSION 1.15.9
NCHAN_VERSION 1.2.5

It sounds weird, but if channels string length more than 1024 characters, 403 is returned
Tested with string "channel_name,channel_name,..."(1025 characters)

```
location ~ /multisub-split/(.*)$ {
            nchan_authorize_request /auth;
            nchan_subscriber;
            nchan_redis_pass redis_server;
            nchan_channel_id "$1";
            nchan_channel_id_split_delimiter ",";
    }
```

Maybe I missed some rules? Or maybe this problem related with authorizing directive?
In documentation did not find any helpful information for this case

**Comment by slact** [comment]
Increase (`nchan_max_channel_id_length`)[https://nchan.io/#nchan_max_channel_id_length] to whatever limit you need.

**Comment by solofeed** [comment]
@slact Sorry! I am blind.
