### ISSUE TITLE
How are Redis Publish commands encoded?

### ISSUE THREAD

**Issue by xiskoct** [slact/nchan#525]
Hello,

First of all, give congratulations to @slact , since in my point of view it seems to me one of the best solutions in the market :)

On the other hand, I'm evaluating getting the data in my backend from the channel that publishes the Nchan data, since I understand that it should be faster than connecting my backend to Nchan by websocket

Do you think it is a correct solution?

I have extracted the data from the Redis monitor and I have seen that the data is published in coded redis:

1555342304.907479 [0 lua] "PUBLISH" "{channel:/foobar}:pubsub" "\x9b\xacmax_msgs+msg\n\xcd\x0e\x10\xce\\\xb4\xa3\xe0\x00\x00\x00\xa7asdfasf\xb8text/plain;charset=UTF-8\xa0\x00"

Can someone tell me how to decode the message sent by NCHAN to Redis: "" \ x9b \ xacmax_msgs + msg \ n \ xcd \ x0e \ x10 \ xce \\\ xb4 \ xa3 \ xe0 \ x00 \ x00 \ x00 \ xa7asdfasf \ xb8text / plain; charset = UTF-8 \ xa0 \ x00 ".

I tried to decode it in UTF8 from python, but an error appears: The 'utf-8' codec can not decode byte 0x9a in position 0: invalid start byte

when I open it with mode ignore I get the message, but without any predictable structure: 

^[OSb'\x9a\xa3msg\xcd\x0e\x10\xce\\\xb4\xd4\xbb\x00\xce\\\xb4\xd4\xb5\x00\xa41234\xb8text/plain;charset=UTF-8\xa0\x00'
Got Message: msg\Ի\Ե1234text/plain;charset=UTF-8

b'\x9a\xa3msg\xcd\x0e\x10\xce\\\xb4\xd4\xc6\x00\xce\\\xb4\xd4\xc1\x00\xa4baby\xb8text/plain;charset=UTF-8\xa0\x00'
Got Message: msg\\babytext/plain;charset=UTF-8

How is this message constructed?

Thank you.

**Comment by slact** [comment]
The `PUBLISH` messages are encoded using [MessagePack](https://en.wikipedia.org/wiki/MessagePack), because it's faster than JSON and natively supported by Redis. You can figure out the structure by looking at the (publish.lua)[https://github.com/slact/nchan/blob/master/src/store/redis/redis-lua-scripts/publish.lua#L236-L274] Redis script. I don't recommend messing with the encoding or structure unless you know what you're doing.

**Comment by grinchd** [comment]
> The `PUBLISH` messages are encoded using [MessagePack](https://en.wikipedia.org/wiki/MessagePack), because it's faster than JSON and natively supported by Redis. You can figure out the structure by looking at the [publish.lua](https://github.com/slact/nchan/blob/master/src/store/redis/redis-lua-scripts/publish.lua#L236-L274) Redis script.
> 
> I don't recommend messing with the encoding or structure unless you know what you're doing. I make no guarantees that the message structure will remain the same between different Nchan versions. You should probably use the [upstream publisher hooks](https://nchan.io/#message-forwarding) to load published data into your backend.

Any idea on how to publish message using nodejs?

`    const now = String(new Date().getTime()).slice(0, 10);
    const msg = {
      content_type: 'application/json',
      data: 'quest',
      time: now,
      eventsource_event: '',
      ttl: 300,
      prev_time: 0,
      prev_tag: 0,
      tag: 0,
    };
    await this.redis.publishBuffer(
      `{channel:/${campaignId}}:pubsub`,
      Buffer.from(messagepackEncode(msg)),
    );`
Fails with "REDISTORE: invalid msgpack message from redis: Invalid type" I suppose messagepack npm package just different from redis one.
