### ISSUE TITLE
First large JSON message gets queued

### ISSUE THREAD

**Issue by gazugafan** [slact/nchan#526]
I'm running into a strange problem on a production server that doesn't seem to be happening on development. It seems that when a new subscriber should receive its first new message, it gets queued until the next message is sent. At that point, the previous (first) message is received by the client. The really weird thing is that this only happens when the first message is a large-ish JSON encoded object. Here's what I'm doing to reproduce...

1) Have a new browser client subscribe to a channel using NchanSubscriber via eventsource or websocket (haven't tried anything else).
2) Broadcast a message to this channel with a payload of a large-ish JSON object. The size needs to be around 40KB, it seems. A large payload that's not JSON encoded doesn't seem to cause a problem.
3) You would expect to see that message received by the client, but it's not yet.
4) Broadcast another message on this channel (doesn't matter what size).
5) Suddenly both messages are received by the client.

Any thoughts on what could possibly be the problem, or where I should go next to debug further?

**Comment by slact** [comment]
First I need to know your Nchan version,  Nginx config, and what locations in the config are the ublishers and subscribers hitting.

**Comment by gazugafan** [comment]
Thanks for the quick response!
nginx 1.15.10
nchan 1.2.5

nginx.conf
```
user              nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log;

pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    ##
    # NCHAN
    ##
    nchan_shared_memory_size 1G;
    nchan_message_buffer_length 500;

    sendfile        on;
    #tcp_nopush     on;
    client_max_body_size 100M; #file upload size

    #keepalive_timeout  0;
    #keepalive_timeout  65;
    fastcgi_read_timeout 3600;

    #gzip  on;

    # Load config files from the /etc/nginx/conf.d directory
    # The default server is in conf.d/default.conf
    include /etc/nginx/conf.d/*.conf;
}
```

and the relevant config file...
```
server {
	#publishing is available only on localhost
	listen 127.0.0.1:8080;
	location ~ /pub/(.*)$ {
		nchan_publisher;
		nchan_channel_id "$1";
		nchan_channel_id_split_delimiter ",";
	}
}

server {
	server_name  www.mydomain.com;

	return 301 https://mydomain.com$request_uri;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/www.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/www.mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
	server_name  mydomain.com;

	root /var/www/mydomain/public;

	add_header X-Frame-Options "SAMEORIGIN";
	add_header X-XSS-Protection "1; mode=block";
	add_header X-Content-Type-Options "nosniff";

	index index.php index.html index.htm;

	charset utf-8;
	
	location ~ /sub/(.*)$ {
		nchan_subscriber;
		nchan_authorize_request /_nchan_auth;
		nchan_channel_id "$1";
		nchan_channel_id_split_delimiter ",";
		nchan_subscriber_first_message oldest;
	}

	location = /_nchan_auth {
		proxy_pass https://mydomain.com/nchan_authorize;
		proxy_pass_request_body off;
		proxy_set_header Content-Length "";
		proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
		proxy_set_header X-Publisher-Type $nchan_publisher_type;
		proxy_set_header X-Prev-Message-Id $nchan_prev_message_id;
		proxy_set_header X-Channel-Id $nchan_channel_id;
		proxy_set_header X-Original-URI $request_uri;
		proxy_set_header X-Forwarded-For $remote_addr;
	}

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}

	location = /favicon.ico { access_log off; log_not_found off; }
	location = /robots.txt  { access_log off; log_not_found off; }

	error_page 404 /index.php;

	location ~ \.php$ {
		fastcgi_pass unix:/var/run/php73-php-fpm.sock;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
		include fastcgi.conf;
	}

	location ~ /\.(?!well-known).* {
		deny all;
	}

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen       80;
    server_name  mydomain.com *.mydomain.com;
    return 404; # managed by Certbot
}
```

Publishing to ```/pub/channelname```
Subscribing to ```/sub/channelname?last_event_id=xxxx```
These are the only pub/sub locations I've configured.

**Comment by slact** [comment]
Let's try to simplify that config a bit. First, can you confirm that the issue persists if you remove `nchan_authorize_request`?

**Comment by gazugafan** [comment]
Yes, the problem persists with ```nchan_authorize_request``` removed.

**Comment by slact** [comment]
Ok, next: does this persist if you remove NchanSubscriber and use raw EventSource or Websocket?

**Comment by gazugafan** [comment]
Yes, same problem using either raw EventSource or Websocket. Here's my simple implementations...
```
var evtSource = new EventSource('https://domain.com/sub/channelname?last_event_id=1556672645:0');
evtSource.onmessage = function(e) {
	console.log("message: " + e.data);
};
```
```
var socket = new WebSocket("wss://domain.com/sub/channelname?last_event_id=1556672645:0");
socket.onmessage = function (e) {
	console.log("message: " + e.data);
};
```
...and removing the query string doesn't change anything.

A couple other observations I've made that could maybe help...
1) It seems the JSON must also contain many elements. For example, an object like ```{"test":"a very long string here"}``` will not be a problem even if it is very large, but a similarly sized object like ```{"test":["an", "array", "with", "many", "elements", "here"]}``` does cause the problem.
2) Running the same client-side raw EventSource or WebSocket code, but connecting to my local dev VM, and broadcasting exactly the same messages from the local dev VM works as expected. On my local dev VM I'm running nginx 1.10.1. Not sure what version of nchan, though. I guess it's whatever was in the nginx-common.ubuntu.deb and nginx-extras.ubuntu.deb files at version 1.10.1-2ubuntu1?

**Comment by gazugafan** [comment]
Thanks for your help with this @slact . Any other thoughts on what could be going on yet? I'm thinking about rebuilding with v1.2.6 just to see if that makes any difference.

**Comment by gazugafan** [comment]
Update: Rebuilt our application server and installed v1.2.7. Never got to the root of the issue, but this seems to have fixed the problem, so closing!
