### ISSUE TITLE
Subscriber Presence callbacks 

### ISSUE THREAD

**Issue by i-93** [slact/nchan#528]
Subscriber Presence callbacks seem to work only when proxying to upstream.

E.g the following doesn't work:

```
    nchan_subscribe_request /presence;
    nchan_unsubscribe_request /presence;
    
    location = /presence {
      internal;
      content_by_lua_block {
         ... some processing ...
      }
    }

```
while the following works fine:

```
    nchan_subscribe_request /presence;
    nchan_unsubscribe_request /presence;
    
    location = /presence {
      internal;
      proxy_pass http://localhost/_presence;
    }

    location = /_presence {
      content_by_lua_block {
         ... some processing ...
      }
    }

```
Why is that?

**Comment by ekifox** [comment]
Huh, I can't get callbacks from nchan after subscribing at all.
Without any lua blocks and something.
P.S.: Auth callback calls normally.

**Comment by ekifox** [comment]
And I have another problem, callbacks are not constantly called. Strange.

**Comment by slact** [comment]
> Subscriber Presence callbacks seem to work only when proxying to upstream.
> Why is that?

The complexity of plugging Nchan into Nginx's upstream request code in a way it was not designed for at all (that is, without affecting the downstream request).

> And I have another problem, callbacks are not constantly called. Strange.

You'll need to be more specific about that for me to be able to help.

**Comment by slact** [comment]
Closing pending further feedback.
