### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by mzubala** [slact/nchan#529]
I'm trying to use nchan as a pub/sub server. I'm facing an issue which looks like a memory leak. It happens when I run a program that publishes short text (5 characters) messages in a infinite loop through a websocket and no subscribers are connected. After about 30sec I observe following error messages appearing in nginx error logs:

2019/05/19 16:26:57 [error] 21713#21713: nchan: Sending 3864 interprocess alerts delayed by 2 sec.
2019/05/19 16:26:58 [error] 21713#21713: nchan: Sending 4312 interprocess alerts delayed by 3 sec.
2019/05/19 16:26:59 [error] 21713#21713: nchan: Sending 5264 interprocess alerts delayed by 3 sec.
2019/05/19 16:26:59 [crit] 21708#21708: ngx_slab_alloc() failed: no memory
2019/05/19 16:26:59 [error] 21708#21708: shpool alloc failed
2019/05/19 16:26:59 [error] 21708#21708: MEMSTORE:00: can't allocate 'shared' memory for msg for channel id
2019/05/19 16:26:59 [crit] 21708#21708: ngx_slab_alloc() failed: no memory
2019/05/19 16:26:59 [error] 21708#21708: shpool alloc failed
....
2019/05/19 16:27:02 [alert] 21707#21707: worker process 4615 exited on signal 6
ker process: /build/nginx-FIJPpj/nginx-1.14.0/debian/modules/nchan/src/subscribers/websocket.c:892: websocket_release: Assertion `self->reserved > 0' failed.
 
and in syslog:

May 19 18:27:00 quikpoc kernel: [3035124.365412] nginx[21708]: segfault at 7ffe7587bfe8 ip 0000555f00c3da3a sp 00007ffe7587bfd0 error 6 in nginx[555f00c15000+fc000]

After the failure I need to restart nginx to be able to pub/sub again.

My setup is really simple:

server {
	server_name pub.xxx.com;

	location ~ /(\w+)$ {
		nchan_publisher;
		nchan_channel_id $1;
		#nchan_message_timeout 5s; --> I've tried with and without this setting and getting same behavior
		nchan_channel_group xxx;
	}

    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/pub.xxx.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pub.xxx.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

}

server {
	server_name sub.xxx.com;

	location ~ /(\w+)$ {
		nchan_subscriber;
		nchan_channel_id $1;
		nchan_channel_group xxx;
	}

    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/pub.xxx.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pub.xxx.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

I'm using ubuntu and nginx 1.14.0 and libnginx-mod-nchan 1.14.0-0ubuntu1.
I've also tried compiling nginx and nchan from source using latest versions (nginx 1.16.0 and nchan 1.2.5) but I get exactly the same results. Is this a bug or am I configuring it wrong?

**Comment by slact** [comment]
"It's not a bug, it's a feature."

https://nchan.io/#nchan_shared_memory_size

You're running into the low default shared memory limit of 128Mb. This is usually not enough for fast publishing rates and production use.  Set it to 1 or 2 GB and see how it works out.

The reason memory needs to be set up like this in the configuration is arcane and has to do with how Nginx handles shared memory slab initialization.

You can monitor the shared memory use with https://nchan.io/#nchan_stub_status-stats

**Comment by mzubala** [comment]
I've set:

push_max_reserved_memory 2048M;

This only postpones the issue in time. Still after it happens the server needs to be restarted to become functional again.

I'd expect that when the message buffer gets filled up, the new messages start replacing the oldest ones. Isn't that the case?

I've also tried these settings:

nchan_message_timeout 1s;
nchan_message_buffer_length 0;

With these 2, I'd expect that messages are not buffered for future subscribers at all and only currently connected subscribers get them. Is that the correct understanding of these options?

**Comment by slact** [comment]
> I'd expect that when the message buffer gets filled up, the new messages start replacing the oldest ones. Isn't that the case?


Yep that's how it works, provided the messages bring replaced are expired. Unexpired messages are not evicted.
All messages are buffered internally for about 5 seconds.

What is the average publishing rate and message size?

**Comment by mzubala** [comment]
I have a test program like this pseudo code:

socket = open the ws to nchan
sentMessages = 0
while(socket.write("hello")) {
    sentMessages++;
    // sleep(10) --- adding this solves the issue
}

I've just measured the time it works. When I run this, it works for certain period of time. After that errors start to appear in logs and the connection is lost and I cannot send any more messages through nchan unless I restart the server.

Now, the time this program can work before blowing up the server varies. Here are few test runs figures:
Time (s) | Messages sent count | Rate msg/s
38.757 | 692484477 | 17867339.499961298
11.566 | 148163355 | 12810250.302611101
12.322 | 168084971 | 13641046.177568577

I'm not saying that such huge rates per second are realistic on production but it looks like a security vulnerability since I'm able to write 3 lines of code that blow the server. Do you know any ways to protect the server from this happening?

If I decrease the rate by adding sleep(10), the problem is gone and I see no errors, so looks like the problem is way too high message rate and the server not managing to GC the messages fast enough.

**Comment by solofeed** [comment]
@mzubala Are you use default storage mode or redis? Looks like I have a similar problem with redis mode.

**Comment by mzubala** [comment]
@solofeed I use default memory storage.

**Comment by slact** [comment]
> Do you know any ways to protect the server from this happening?

Two approaches: [Group limits](https://nchan.io/#channel-groups) and [secure publisher endpoints](https://nchan.io/#securing-publisher-endpoints). I know it's pretty lame to have a DDoS-able server configuration by default -- the reason it's been this way is the vast majority of users don't expose publisher endpoints directly to the wild.

>  looks like the problem is way too high message rate and the server not managing to GC the messages fast enough.

That's probably what is happening. This will be fixed in a few months in Nchan 2 as I'm in the process of moving the codebase from an Nginx module to a standalone server.
