### ISSUE TITLE
How to install latest version (such as v1.2.5) on Ubuntu 18.04?

### ISSUE THREAD

**Issue by larryli** [slact/nchan#532]
The apt package version is still [v1.0.8](https://salsa.debian.org/nginx-team/nginx/commit/5140bc7eae4c595e8f2eb20ac3f1f8ec5d986df1) on Debian and Ubuntu.

**Comment by pbirkants** [comment]
I use the following script to build nchan in a Docker image based on Ubuntu 18.04 LTS.
Afterwards install the resulting `libnginx-mod-nchan_*.deb` package.

```
#!/bin/sh

MOD_PATH=nginx-$NGINX_VERSION/debian/modules/nchan

apt-get update
apt-get build-dep -y nginx
apt-get source -y nginx

rm -r $MOD_PATH/*

curl https://codeload.github.com/slact/nchan/tar.gz/v$NCHAN_VERSION | tar xz --strip-components=1 -C $MOD_PATH

cd nginx-$NGINX_VERSION

debuild -uc -us -i -b
```

**Comment by mikesi** [comment]
@pbirkants Thank you very much for sharing, this is by far the easiest way to make your own module.

**Comment by larryli** [comment]
> libnginx-mod-nchan_*.deb

d

**Comment by larryli** [comment]
@pbirkants ths very much

Two questions:

1. How to build only nchan module? 
2. How to change `libnginx-mod-nchan_1.14.0-0ubuntu1.6_amd64.deb` version?  Such as patch the version of nchan source, like `libnginx-mod-nchan_1.14.0-0ubuntu1.6-nchan1.2.6_amd64.deb`, and depends `nginx-common_1.14.0-0ubuntu1.6`.

I want to create a private apt repos.

**Comment by larryli** [comment]
```shell
cd /
mkdir nchan
dpkg-deb -R libnginx-mod-nchan_*.deb nchan
rm *.deb
sed -i "s/Version:\(.*\)$/Version:\1+$NCHAN_VERSION/g" nchan/DEBIAN/control
dpkg-deb -b nchan $(awk '/^Package:/ { P=$2 } /^Version:/ { V=$2 }/^Architecture:/ { print P "_" V "_" $2 ".deb" }' nchan/DEBIAN/control)
```
