### ISSUE TITLE
nchan_channel_timeout default behaviour

### ISSUE THREAD

**Issue by cexmmaqsood** [slact/nchan#533]
I noticed after my channel's age grew a few days, it was deleted in nchan. I couldn't see any channel keys, and a request to `nchan_stub_stats` resulted in 0 for `channels`

I create one channel for the lifetime of my app, shared by all users. I don't have a need for private channels, only authenticated ones, so I didn't see a reason to bother managing channels per users.

I then noticed the `nchan_channel_timeout` directive but there wasn't much information about the default behaviour of this setting, found a commit of it's former name (`push_channel_timeout`), and in the commit it said "if you want to the channel to be deleted right away, set this to 0, default: 0"

So I guess my questions is what is the default behaviour of `nchan_channel_timeout`? Are channels meant to be short lived?

**Comment by slact** [comment]
Channels live as long as there is at least 1 subscriber or at least 1 message. With 0 subscribers and 0 messages stored, channels are subject to garbage collection.

**Comment by cexmmaqsood** [comment]
Awesome, thx for response can we add this info to the docs?

**Comment by emschwartz** [comment]
Is the `nchan_channel_timeout` how long a channel lives after the last message is deleted and the last subscriber unsubscribes?
