### ISSUE TITLE
Question about unsubscribe callback 

### ISSUE THREAD

**Issue by chienhsingwu** [slact/nchan#539]
I have maybe a basic question about the condition for making that unsubscrcibe callback inside NCHAN. I plan to use Event Source or Raw Stream with long lived connection for subscribers to get messages. 

Does it happen when the HTTP DELETE call to delete a channel? Does it happen when that long lived connection is closed at the client side? If a client calls HTTP DELETE and then close the long lived connection, would NCHAN make two callbacks?

Thanks!

**Comment by slact** [comment]
> Does it happen when the HTTP DELETE call to delete a channel?

yes

>  Does it happen when that long lived connection is closed at the client side?

yes

> If a client calls HTTP DELETE and then close the long lived connection, would NCHAN make two callbacks?

No, just one.

**Comment by chienhsingwu** [comment]
Thanks
