### ISSUE TITLE
HTTP Raw Stream request header support

### ISSUE THREAD

**Issue by chienhsingwu** [slact/nchan#541]
Hi,

I am thinking of using HTTP Raw Stream option for subscribers of an application we are building. Is there a way to require a request header similar to "Accept: text/event-stream" in SSE? For example, "Accept: application/stream+json".

Thanks,

**Comment by slact** [comment]
Yes, you can do by using nginx's http header filters, or by passing the request to you upstream I prior to accepting the subscriber using [https://nchan.io/#nchan_authorize_request](nchan_authorize_request)

**Comment by chienhsingwu** [comment]
Thanks. IF I use the nginx header filter, what would be the http response if client does not have that header?

**Comment by slact** [comment]
@chienhsingwu  Sorry, I can't help you with that here. Please consult the Nginx documentation.
