### ISSUE TITLE
redis pending commands increments indefinitely

### ISSUE THREAD

**Issue by mzdeb** [slact/nchan#543]
Hi,

When nchan (I'm using version 1.2.6) is configured with redis cluster (`nchan_redis_storage_mode nostore`) AND `nchan_redis_nostore_fastpublish` is off then `redis pending commands` in stats raises indefinitely.

If I undestand the code correctly, problem lies in lines: https://github.com/slact/nchan/blob/master/src/store/redis/rdsstore.c#L2208-L2241

counter is incremented 4 times and decremented only once here: https://github.com/slact/nchan/blob/master/src/store/redis/rdsstore.c#L2240

**Comment by slact** [comment]
Quite right, thank you once again.
