### ISSUE TITLE
HTTP DELETE on publisher endpoint doesn't close the subscriber connections

### ISSUE THREAD

**Issue by i-93** [slact/nchan#545]
After issuing HTTP DELETE request to publisher endpoint, the subsequent GET and DELETE requests for the same channel return 404 as described. However the subscribers (both Websockets and EventSource) stay connected and continue to receive POSTed messages.

I use Redis as storage backend with the options:
```
  nchan_redis_storage_mode nostore;
  nchan_redis_nostore_fastpublish on;
```

**Comment by mzdeb** [comment]
Hi,

I've encountered this issue as well, I belive this PR solves it: #548

**Comment by slact** [comment]
@i-93 yep, @mzdeb spotted the problem and I've already merged the fix into master. It will be included in the next release.
