### ISSUE TITLE
OPTIONS request method 

### ISSUE THREAD

**Issue by j0r0** [slact/nchan#56]
Hi ,
I am trying to make a cross-domain ajax request. The problem comes when i try to POST .
Then Firefox makes "preflighted" request to see if it is OK to go ahead.
Here is the request :

OPTIONS /publish/?id=123 HTTP/1.1
Host: 10.1.2.50:8002
User-Agent: Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid) Firefox/3.6.8
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip,deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Keep-Alive: 115
Connection: keep-alive
Origin: http://10.1.2.50
Access-Control-Request-Method: POST

and response :

HTTP/1.1 405 Not Allowed
Server: nginx/0.7.67
Date: Fri, 20 Aug 2010 07:11:52 GMT
Content-Type: text/html
Content-Length: 173
Connection: keep-alive
Allow: GET, POST, PUT, DELETE

I posted in nginx forum here :
http://forum.nginx.org/read.php?2,121635

One user suggest this may be http_push issue

**Comment by 1371030** [comment]
XMLHttpRequest cannot load http://c.apple.net/chat/pub. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.apple.net' is therefore not allowed access.

**Comment by slact** [comment]
this should be fixed in the upcoming nchan release
