### ISSUE TITLE
Support message template

### ISSUE THREAD

**Issue by rita-liu** [slact/nchan#560]
Hi,

I'm upgrading from `nginx-push-stream-module` and find that `push_stream_message_template` is no longer supported. Is it possible to add this feature back?

The use case is when publisher sends `foobar`, we hope the subscribers to receive something like
```json
{
  "channel": "~channel~",
  "message": "foobar",
}
```

More templating options from HTTP_PUSH_STREAM are:
- push_stream_header_template
- push_stream_message_template
- push_stream_footer_template

as in https://www.nginx.com/resources/wiki/modules/push_stream/#push-stream-message-template.

I'm new to nchan so please correct me if I'm missing out something :)

**Comment by slact** [comment]
Nchan and the push stream module are two different projects. Both derive from my original Nginx HTTP Push Module, but they have gone in very different directions.
