### ISSUE TITLE
pubsub disable echo

### ISSUE THREAD

**Issue by 0x1de** [slact/nchan#563]
Hello.I'm trying to use nchan for connect client A and client B in room. The problem is every message from client A come back echo. This produce unnecessary traffic. How to disable echo while sending data from client?

     location /room {
            nchan_store_messages off;
            nchan_message_buffer_length 0;
            nchan_subscriber_timeout 0;
            nchan_subscriber_first_message newest; 
            nchan_channel_id $arg_r;
            nchan_message_timeout 240s;
            nchan_pubsub;
            }

**Comment by vsbc2010** [comment]
Same issue.
