### ISSUE TITLE
Failure to build 1.2.7

### ISSUE THREAD

**Issue by DigitalCyberSoft** [slact/nchan#577]
As of Fedora 32 I am unable to build nchan. It still builds fine on Fedora 31

nginx-1.18.0
nchan-1.2.7
gcc-10.1.1
perl-5.30.2

The only major change here from Fedora 31 to 32 appears to be GCC 9.3.1 to 10.1.1

[nchan.log](https://github.com/slact/nchan/files/4802274/nchan.log)

**Comment by slact** [comment]
Fixed in f484c603

**Comment by gdamjan** [comment]
maybe this should be promoted to a new 1.2.8 release?

**Comment by slact** [comment]
I have a couple of other things queued up for 1.2.8. I I don't get them done in time I'll release without them.

**Comment by gdamjan** [comment]
ping :D

**Comment by slact** [comment]
Version 1.2.8, released on April 12th,  includes a fix for this issue.
