### ISSUE TITLE
Feature request: extend ws+meta.nchan subprotol

### ISSUE THREAD

**Issue by M1ha-Shvn** [slact/nchan#582]
Hi.
Nowadays ws+meta.nchan subprotocol returns only message_id and Content-Type. It would be great if it could:
1. Return ETag and LastModified for message, in order to switch easily between Websocket and Polling protocols;
2. Return channel, message has been sent to. Channel can be used by clients to make some identification (sent event type, for instance). But if client has subscribed to many channels at once (thanks to channel multiplexing), there's no way to understand, what channel message came to. Publisher can also send message to multiple channels in one request and can't add channel to data, as well as subscriber can not get this information anywhere.

**Comment by neben** [comment]
This can be done as follows:
1. Check the documentation for `last_event_id`.
2. This is described in the following comment: https://github.com/slact/nchan/issues/562#issuecomment-612924853
