### ISSUE TITLE
Message buffer behavior

### ISSUE THREAD

**Issue by emschwartz** [slact/nchan#590]
I have a pubsub endpoint set up with the following settings, but the message buffer doesn't seem to have an effect.
```nginx
nchan_pubsub websocket http;
nchan_message_buffer_length 1;
nchan_message_timeout 30m;
nchan_subscriber_first_message newest;
```
I would expect that publishing a message via http or websocket before there's a subscriber would cause that message to be stored and then sent to a subscriber that connects later. However, connecting a websocket client or doing an HTTP GET on the endpoint does not return any message.

Am I doing something wrong or is message buffering not supported for pubsub endpoints?

**Comment by sobitcorp** [comment]
It's because of the last line in your config
`nchan_subscriber_first_message newest;`
Check the documentation at https://nchan.io/#nchan_subscriber_first_message :
`'newest' waits until a message arrives`, hence no stored messages get retrieved.

**Comment by emschwartz** [comment]
Oh damn, you're right. Guess I didn't read that property's description closely enough. Thanks for pointing that out!

**Comment by slact** [comment]
Yeah, that name 'newest" doesn't mean what you think it means. Unfortunately, it's here to stay for backwards compatibility, and that's on me.

**Comment by emschwartz** [comment]
Oh well, it happens! If you want, I can try to add some more details to that section in the PR I submitted or in a separate one
