### ISSUE TITLE
pubsub disable echo

### ISSUE THREAD

**Issue by vsbc2010** [slact/nchan#602]
A send pubsub to channel test. But A get echo message . How to disable echo?

**Comment by vsbc2010** [comment]
A send pubsub to channel test.  But A get echo message . How to disable echo?

**Comment by vsbc2010** [comment]
A send pubsub to channel test. But A get echo message . How to disable echo?

**Comment by slact** [comment]
there is no feature to disable to echo If you subscribe to the same message you publish to, you will receive the message you published.
