### ISSUE TITLE
Upstream subrequests crash on nginx 1.19.9

### ISSUE THREAD

**Issue by tflin** [slact/nchan#607]
The nchan 1.2.7 does not work with the new nginx 1.19.9. It always caused the worker thread abort. Please help to check this problem. The nchan 1.2.7 was built as a module of nginx. It works well on previous nginx versions (e.g. 1.19.8)

**Comment by tflin** [comment]
There is the same problem on nginx 1.19.10 with nchan. FYI

**Comment by slact** [comment]
It's running my test suite just fine on 1.19.9 and 1.19.10.  I'll at least need to see your config to reproduce this.

**Comment by tflin** [comment]
The NChan config is for websocket with auth and presence as the following. The worker process/thread aborted every time when websocket client connected to the nginx server:

    # For nchan_authorize_request sub request
    location = /app/nchan_auth {
        proxy_pass http://localhost/api1/nchan_sub_auth.php;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
        proxy_set_header X-Channel-Id $nchan_channel_id;
    }
    # For nchan_subscribe_request sub request
    location = /app/nchan_sub {
        proxy_pass http://localhost/api1/nchan_sub.php;
        proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
        proxy_set_header X-Channel-Id $nchan_channel_id;
    }
    # For nchan_unsubscribe_request sub request
    location = /app/nchan_unsub {
        proxy_pass http://localhost/api1/nchan_unsub.php;
        proxy_ignore_client_abort on;  #!!!important!!!!
        proxy_set_header X-Subscriber-Type $nchan_subscriber_type;
        proxy_set_header X-Channel-Id $nchan_channel_id;
    }

    location ~ /ws1/sub/(\w+)$ {
        nchan_subscriber;
        nchan_channel_id $1; #first capture of the location match
        nchan_subscriber_first_message newest;
        nchan_authorize_request /app/nchan_auth;
        nchan_subscribe_request /app/nchan_sub;
        nchan_unsubscribe_request /app/nchan_unsub;
        nchan_websocket_ping_interval 20;
    }

Hopefully the above information is correct for reproducing this problem.

**Comment by topalex** [comment]
Same problem on nginx 1.20.0 with nchan 1.2.8

Nginx error.log:
```
2021/05/22 19:47:00 [notice] 31491#31491: signal 17 (SIGCHLD) received from 19394
2021/05/22 19:47:00 [alert] 31491#31491: worker process 19394 exited on signal 11
2021/05/22 19:47:00 [notice] 31491#31491: start worker process 19407
2021/05/22 19:47:00 [notice] 31491#31491: signal 29 (SIGIO) received
2021/05/22 19:47:09 [notice] 31491#31491: signal 17 (SIGCHLD) received from 19400
2021/05/22 19:47:09 [alert] 31491#31491: worker process 19400 exited on signal 11
2021/05/22 19:47:09 [notice] 31491#31491: start worker process 19413
2021/05/22 19:47:09 [notice] 31491#31491: signal 29 (SIGIO) received
2021/05/22 19:47:16 [notice] 31491#31491: signal 17 (SIGCHLD) received from 19407
2021/05/22 19:47:16 [alert] 31491#31491: worker process 19407 exited on signal 11
2021/05/22 19:47:16 [notice] 31491#31491: start worker process 19417
2021/05/22 19:47:16 [notice] 31491#31491: signal 29 (SIGIO) received
2021/05/22 19:47:25 [notice] 31491#31491: signal 17 (SIGCHLD) received from 19413
2021/05/22 19:47:25 [alert] 31491#31491: worker process 19413 exited on signal 11
2021/05/22 19:47:25 [notice] 31491#31491: start worker process 19420
2021/05/22 19:47:25 [notice] 31491#31491: signal 29 (SIGIO) received
```

**Comment by srjlewis** [comment]
Hi

I can also confirm this in nginx 1.20.0 with nchan 1.2.8 on CentOS 7.9

nginx installed from nginx's own repo and nhan 1.2.8 built with gcc 7.3.1

using the following config
```
server {
    listen 90 default_server;
    server_name  ws.test.company.com;

    location ~ /socket {
        nchan_subscriber;
        nchan_subscriber_first_message newest;
        nchan_channel_id $arg_s $arg_u;
        nchan_authorize_request /auth;
    }

    location = /auth {
        proxy_pass https://api.test.company.com/validate$is_args$args;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
    }
}

server {
    listen 91 default_server;
    server_name  ws.test.company.com;
    location = /status {
        nchan_stub_status;
    }
    location ~ /push/(.*)$ {
        nchan_publisher;
        nchan_channel_id $1;
    }
}
```

And here is the build script I use
```
#!/bin/bash
nginxversion="1.19.8"
#nginxversion="1.21.0"
nchanversion="1.2.8"
cd ~
rm -rf ~/nchan-*
rm -rf ~/nginx-*
wget -O nchan-$nchanversion.tar.gz  https://github.com/slact/nchan/archive/v$nchanversion.tar.gz
wget http://nginx.org/download/nginx-$nginxversion.tar.gz
tar -xvzf ./nginx-$nginxversion.tar.gz
tar -xvzf ./nchan-$nchanversion.tar.gz
cd ~/nginx-$nginxversion
./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie' --add-dynamic-module=/root/nchan-$nchanversion
make
cp ~/nginx-$nginxversion/objs/ngx_nchan_module.so /usr/lib64/nginx/modules/ngx_nchan_module.so
```

**Comment by fiveways** [comment]
any update on this ?

**Comment by slact** [comment]
I've been able to reproduce this issue and am working on a fix. Nginx changed some guts around and now I need to find some workarounds.

**Comment by ghostmaster-ai** [comment]
@tflin I tried using nginx module "auth_request" which is similar to "nchan_authorize_request" with http and websockets at subscriber location, it works just fine.
i am using:
ubuntu 20.04 LTS
nginx 1.20.1
nchan 1.2.12

**Comment by tflin** [comment]
@ghostmaster-ai It's a good catch. In our config, the presence (i.e. nchan_subscribe_request, nchan_unsubscribe_request) subrequests are also crucial. So the auth_request can not fit all our needs.
@slact Maybe it is a good hint to check if the subrequest method used in "auth_request" can help to solve this issue.

**Comment by slact** [comment]
fixed in 03074850

**Comment by slact** [comment]
finally fixed in 1.2.14

**Comment by ledil** [comment]
Still have this issue with nginx 1.22 and nchan 1.3.5

**Comment by ledil** [comment]
> @ghostmaster-ai It's a good catch. In our config, the presence (i.e. nchan_subscribe_request, nchan_unsubscribe_request) subrequests are also crucial. So the auth_request can not fit all our needs. @slact Maybe it is a good hint to check if the subrequest method used in "auth_request" can help to solve this issue.

Do you have an example for me?  I'm having the same issue

**Comment by tetlika** [comment]
@ledil have you managed to fix that? I see the issue when auth is enabled, when disabled - it seems working good

**Comment by ledil** [comment]
> @ledil have you managed to fix that? I see the issue when auth is enabled, when disabled - it seems working good

sure I fixed it by replacing nchan with an own implementation.
