### ISSUE TITLE
nchan as audio visual streamer

### ISSUE THREAD

**Issue by haristku** [slact/nchan#608]
it is not an issue..

i just wondering, is it possible to create your own audio-visual meeting conference "service" like zoom or gmeet with nchan pub/sub? stream the audio-visual data via nchan channel?

**Comment by slact** [comment]
yes, if you can split it into chunks you can stream it with Nchan.

**Comment by tihoho** [comment]
@slact it would be great to look at a simple example of broadcasting through nchan chunks :)
