### ISSUE TITLE
Multipub POST fails with 403 on URIs longer than 1081 bytes

### ISSUE THREAD

**Issue by yerkanian** [slact/nchan#611]
> POST /pub/users/user_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed02123456789999999999999 HTTP/1.1
> Host: XXXXXXXXX
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 202 Accepted

vs.

> POST /pub/users/user_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed029fc2%7Cuser_69bff47b-66f5-4400-a511-9347ed021234567899999999999999 HTTP/1.1
> Host: XXXXXXXXX
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 403 Forbidden

For example clarity, I've replaced the real UUIDs with the single one. The error persists when the channel names are unique.

**Comment by neben** [comment]
You need to increase the max channel id length: https://nchan.io/#nchan_max_channel_id_length
