### ISSUE TITLE
Segfault when publishing to multiple channels

### ISSUE THREAD

**Issue by eretan** [slact/nchan#612]
I'm getting a segfault with vanilla Nginx 1.19.10 and Nchan 1.2.8 on Ubuntu 20.04.  The code crashes reliably on my machine after a couple thousand GET requests.  I can get it to crash with as few as 2 channels and varying message sizes but fewer channels take longer.  It doesn't matter if I set nchan_message_buffer_length to 1.

I'm not using the message buffer because I don't need any old messages when establishing a WS connection, and there will be a lot of ad-hoc channels so don't want old messages eating up memory.

```
nginx[426422]: segfault at 20 ip 00007f0a5ab81e8e sp 00007ffc0afb9f40 error 4 in ngx_nchan_module.so[7f0a5ab4c000+56000]
Code: 08 c3 f3 0f 1e fa 53 48 89 d3 48 81 ff f4 01 00 00 74 13 48 81 ff 28 23 00 00 75 0e 48 81 7a 08 f4 01 00 00 74 04 48 89 7b 08 <48> 8b 46 20 48 39 43 30 7d 04 48 89 43 30 48 8b 46 10 48 39 43 20
```

Nginx config:
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
load_module modules/ngx_nchan_module.so;

events {
    worker_connections 768;
}

http {
	nchan_shared_memory_size 4096M;
	server {
		listen 127.0.0.1:1649;
		client_max_body_size 20M;
		client_header_buffer_size 32K;
		large_client_header_buffers 4 32K;
		location = /pub {
			nchan_publisher;
			nchan_channel_id $arg_channels;
			nchan_channel_id_split_delimiter ",";
			nchan_message_buffer_length 0;
			nchan_max_channel_id_length 20000;
		}
	}
}
```

PHP 8.0 script causing crash:
```php
<?php

$broadcastEndpoint = 'http://localhost:1649/pub?channels=';

function base64url_encode( string $data ): string { return rtrim( strtr( base64_encode( $data ), '+/', '-_' ), '=' ); }

$ct = 0;
$requestContext = stream_context_create( [
    'http' => [
        'method'  => 'POST',
        'content' => base64url_encode( random_bytes( 3000 ) ),
        'header'  => 'Content-Type: text/plain',
        'timeout' => 5
    ]
] );
while( ++ $ct ) {
    $channels = implode( ',', array_map( fn(): string => base64url_encode( random_bytes( 57 ) ), range( 1, 255 ) ) );
    if( file_get_contents( $broadcastEndpoint . $channels, context: $requestContext ) === false ) {
        echo( "\nRuns: $ct\n" );
        throw new Exception( 'Broadcast failed.' );
    }
    if( !($ct % 10000) ) echo( $ct );
    elseif( !($ct % 1000) ) echo( '.' );
}

```

**Comment by slact** [comment]
Here's the part you'll like: fixed in fb1155abd4f9a8ca99ee3e9f0c903f28fd512f52 . 

And here's the one you're not gonna like:

Even though you set `nchan_message_buffer_length 0;`, Nchan still stores the incoming messages internally for about 5 seconds. So this resulted in an out-of-memory condition that was being handled incorrectly, resulting in a crash. 
There is no way to configure this storage behavior, the only way to change it is to rewrite Nchan -- which, incidentally, is what i'm doing.

So in your case, the solution would be to increase the shared memory limit until you stop seeing out-of-memory errors.

**Comment by eretan** [comment]
I've recompiled and no more crashes.  Thanks!

**Comment by qhenkart** [comment]
@slact I am experiencing the same issue here. Beyond this fix I realize we need to increase the shared memory size to scale with the amount of users we are having. But I'm a bit confused by this. We use redis, shouldn't redis be used as the cache and therefore scale better?

We are having a hard time understanding why there is a cache that requires so much space (we are running out of space with the default 128m), and if we need to manually scale it depending on how many subscribers we have
