### ISSUE TITLE
Nchan memory full when using multiple cpu

### ISSUE THREAD

**Issue by traquila** [slact/nchan#613]
Hello, 

I am having an issue with shared memory when using multiple workers on multiple processors. (Dual CPU 10 cores with hyperthreading) 

Neither the _nchan_message_buffer_length_ nor _nchan_message_timeout_ directives have any effect causing an endless increase in memory usage. 

When I reduce the worker count to 1 or when I apply a CPU affinity to run all workers on the same CPU everything works fine.
I am experiencing this problem on both versions 1.2.6 and 1.2.8. nginx version: 1.18.0

**Configuration :**
```
    location = /test/pub {
        allow 127.0.0.1;
        deny all;
        nchan_publisher http;
        nchan_channel_id test;
        nchan_message_buffer_length 1000;
        nchan_message_timeout 1m;
    }
```

**Test with 100 000 events and only 1 worker**
```
total published messages: 100000
stored messages: 1000
shared memory used: 1020K
shared memory limit: 524288K
channels: 1
subscribers: 1
redis pending commands: 0
redis connected servers: 0
total interprocess alerts received: 0
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
nchan version: 1.2.8
```

**Test with 100 000 events and 4 workers**
```
total published messages: 100000
stored messages: 100000
shared memory used: 100016K
shared memory limit: 524288K
channels: 1
subscribers: 1
redis pending commands: 0
redis connected servers: 0
total interprocess alerts received: 517962
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
nchan version: 1.2.8
```

Do you have any advice ?
Thank you in advance.

**Comment by matth-c3** [comment]
Hello @traquila , 

Did you find a solution ? 

Thanks

**Comment by traquila** [comment]
> Hello @traquila ,
> 
> Did you find a solution ?
> 
> Thanks

No, we no longer use nchan and had to implement a new event management module.
Regards,
Traquila

**Comment by xvaara** [comment]
nchan has a little wonky memory management it seems. I've had problems with it and required nginx restarts on crontab. My recommendation would be "use redis". 😅

**Comment by slact** [comment]
A little wonky indeed. The garbage collector I wrote is a bit lazy, but also bear in mind that there is a sizable memory overhead for sharing messages between workers. That's a result of working within the Nginx architecture.

If you don't need websocket or SSE, i also recommend using Redis : )
