### ISSUE TITLE
nginx kernel broken websocket pub/sub

### ISSUE THREAD

**Issue by thanghl** [slact/nchan#616]
kernel: nginx[114440]: segfault at 1b82080 ip 00000000005919d0 sp 00007fff43b61018 error 4 in nginx[46f000+324000]
Jun  2 15:42:53  kernel: Code: 00 00 48 8d b5 b8 00 00 00 bf e0 c5 c0 00 e8 f7 d4 ee ff 80 a5 99 00 00 00 f7 eb 8d 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 <48> 8b 87 10 01 00 00 c3 0f 1f 84 00 00 00 00 00 48 89 37 31 c0 c3

09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 0000000098744AE0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #-1 for 00000000986F8FB0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #2 for 0000000098674C80 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 000000009862F690 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 00000000985FB070 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 0000000078FE9620 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 0000000096B104F0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 000000008B9D5470 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 000000008F8A8680 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 0000000096BDC580 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #-1 for 0000000096B9C1D0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 0000000098943930 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 0000000098926200 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 0000000098904270 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 00000000988F23F0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 0000000098890B30 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 0000000098702440 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 00000000986DF370 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #2 for 00000000985FFBE0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #2 for 00000000985BF770 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 000000009735FEE0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 0000000098755B10 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #-1 for 00000000078B80E0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 000000009330A5A0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 00000000986168E0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 000000008F790FE0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 0000000096AF76B0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #-1 for 0000000098515750 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #2 for 000000008EB12630 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #4 for 0000000088EA5FD0 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 000000009877CD20 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 0000000098191620 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #2 for 0000000096E34F90 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 000000009732FF70 received after expiring at 1622687421 status 4 msg 0000000000000000
2021/06/03 09:30:21 [error] 51332#51332: MEMSTORE:108: multimsg callback #3 for 0000000097312390 received after expiring at 1622687421 status 4 msg 0000000000000000

OS : Centos 7
Nchan 1.2.8
nginx version: nginx/1.19.6
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
built with OpenSSL 1.1.1i  8 Dec 2020
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-ld-opt=-Wl,-rpath,/usr/local/luajit/lib --with-file-aio --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module=dynamic --with-http_stub_status_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-threads --with-stream --with-http_slice_module --with-file-aio --with-http_ssl_module --with-cc-opt=-O2 --with-http_perl_module --with-http_v2_module --add-dynamic-module=/opt/src/nginx/njs/nginx --add-module=/opt/src/nginx/ngx_devel_kit-0.3.1 --add-module=/opt/src/nginx/echo-nginx-module-0.62 --add-module=/opt/src/nginx/headers-more-nginx-module-0.33 --with-openssl=/opt/src/nginx/openssl-1.1.1i --add-module=/opt/src/nginx/nginx-statsd --add-module=/opt/src/nginx/nginx-module-vts-0.1.18 --add-module=/opt/src/nginx/nchan-1.2.8 --add-module=/opt/src/nginx/redis2-nginx-module-0.15

About 300k sockets , i have problem, how i fix it

Many thanks !

**Comment by binhbo12456** [comment]
same issue, any help ?

**Comment by slact** [comment]
Please see if this issue persists with Nchan v1.2.13 or above

**Comment by slact** [comment]
stale
