### ISSUE TITLE
Nchan as backend for push api?

### ISSUE THREAD

**Issue by deltasystems-pl** [slact/nchan#617]
Hi, it is possible to use this piece of software as a backend for push notification? 

I need to create a notification system that works even when the user are not on the website which means that sse or long pooling is not a option because u can not run it in service worker or maybe I don't understand something 🤔😉

Have someone a example of background notification system using nchan?

Cheers Damien

**Comment by slact** [comment]
> Hi, it is possible to use this piece of software as a backend for push notification?

Yes

> I need to create a notification system that works even when the user are not on the website which means that sse or long pooling is not a option because u can not run it in service worker or maybe I don't understand something

This is an out of scope frontend implementation question. Off the top of my head, I don't know.
