### ISSUE TITLE
Can nchan support multiple redis cluster?

### ISSUE THREAD

**Issue by AngryMills** [slact/nchan#619]
Take the chat room as an example，if one has too many messages，but others have little.
Can nchan support multiple redis cluster?
The big one has its own redis cluster，and others have the other one，so as to avoid problems.

**Comment by morya** [comment]
Channels that don't use Redis can be configured side-by-side with Redis-backed channels, provided the endpoints never overlap. (This can be ensured, as above, by setting separate nchan_channel_groups.). Different locations can also connect to different Redis servers.

in Chinese

简单来说，通过 配置不同的 location + group + channel_id ， 依赖redis的channel 与 不依赖redis channel 完全互相独立且并存。

不同的location 也可以使用不同的redis配置，也就是，不同的redis cluster也是可行的。

**Comment by AngryMills** [comment]
> copied from [docs](https://nchan.io/#connecting-to-a-redis-server)
> 
> Channels that don't use Redis can be configured side-by-side with Redis-backed channels, provided the endpoints never overlap. (This can be ensured, as above, by setting separate nchan_channel_groups.). Different locations can also connect to different Redis servers.
> 
> in Chinese
> 
> 简单来说，通过 配置不同的 location + group + channel_id ， 依赖redis的channel 与 不依赖redis channel 完全互相独立且并存。
> 
> 不同的location 也可以使用不同的redis配置，也就是，不同的redis cluster也是可行的。

thanks for answering
