### ISSUE TITLE
Should not use `typeof` macro

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [slact/nchan#620]
https://gcc.gnu.org/onlinedocs/gcc/Typeof.html

`typeof` is GNU GCC construction.
You should use `__typeof__` - it's more compatible way.

Or you could define `CFLAGS="$CFLAGS -I$ngx_addon_dir -std=gnu99"` line in `config` file.
And prefer GCC compiler.

There an errors then compile it under Ubuntu 14 via gcc-4.8.

**Comment by slact** [comment]
fixed in 1.2.14
