### ISSUE TITLE
Unknown directive nchan_deflate_message_for_websocket

### ISSUE THREAD

**Issue by imslp** [slact/nchan#625]
I'm using a custom built Nchan 1.2.12 with Nginx 1.18.0 and I get this error:

nginx: [emerg] unknown directive "nchan_deflate_message_for_websocket" in /etc/nginx/sites-enabled/site.conf:57

The directive is in a location {} block with other nchan_ directives.  The same configuration works fine using the Ubuntu package of Nchan 1.2.7.

Any ideas?

**Comment by slact** [comment]
please include your nginx config
