### ISSUE TITLE
nchan 1.2.13 cannot built without OpenSSL due to a typo

### ISSUE THREAD

**Issue by tflin** [slact/nchan#627]
Error when building nchan 1.2.13:

../nchan/src/store/redis/redis_nodeset.c: In function ‘nodeset_create_ssl_ctx’:
../nchan/src/store/redis/redis_nodeset.c:271:79: error: expected ‘;’ before ‘)’ token
  271 | reate Redis SSL context: Nginx was built without SSL support");

It's just a typo.

**Comment by slact** [comment]
fixed in 1.2.14. I also need to add CI tests for building without the SSL module now.
