### ISSUE TITLE
NGINX Not starting after Openssl update 

### ISSUE THREAD

**Issue by nidiculageorge** [slact/nchan#630]
Hi Team,

We have done an update in our nginx server in which the open ssl package was updated to version openssl-libs-1.0.2k-23.el7_9.x86_64

We have reinstalled the Nginx with the new version of open ssl and it got installed successfully

![image](https://user-images.githubusercontent.com/43850474/149318441-397360bc-e653-4bce-8608-e07447c91fd1.png)

When checked the issue when we put the following value in nginx.conf

ssl_stapling on;
 ssl_stapling_verify on;

The nginx service fail to start and we are getting the below error

*** Error in `nginx': double free or corruption (fasttop): 0x0000563cef974af0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7fd807313329]
/lib64/libcrypto.so.10(CRYPTO_free+0x1d)[0x7fd8078e496d]
/lib64/libcrypto.so.10(sk_pop_free+0x30)[0x7fd80799c360]
/lib64/libcrypto.so.10(+0x170ed5)[0x7fd8079e6ed5]
/lib64/libcrypto.so.10(X509_get1_ocsp+0x80)[0x7fd8079e7120]
nginx(ngx_ssl_stapling+0x2cc)[0x563cee2593fc]
nginx(+0xb30c0)[0x563cee2ad0c0]
nginx(+0x614c5)[0x563cee25b4c5]
nginx(ngx_conf_parse+0xd47)[0x563cee239c87]
nginx(ngx_init_cycle+0x625)[0x563cee237055]
nginx(main+0xac1)[0x563cee224311]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fd8072b4555]
nginx(+0x2a55f)[0x563cee22455f]
======= Memory map: ========
563cee1fa000-563cee323000 r-xp 00000000 08:02 16800386                   /usr/sbin/nginx
563cee523000-563cee525000 r--p 00129000 08:02 16800386                   /usr/sbin/nginx
563cee525000-563cee546000 rw-p 0012b000 08:02 16800386                   /usr/sbin/nginx
563cee546000-563cee566000 rw-p 00000000 00:00 0
563cef441000-563cef98b000 rw-p 00000000 00:00 0                          [heap]
7fd800000000-7fd800021000 rw-p 00000000 00:00 0
7fd800021000-7fd804000000 ---p 00000000 00:00 0
7fd80589e000-7fd8058b3000 r-xp 00000000 08:02 16824251                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fd8058b3000-7fd805ab2000 ---p 00015000 08:02 16824251                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fd805ab2000-7fd805ab3000 r--p 00014000 08:02 16824251                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fd805ab3000-7fd805ab4000 rw-p 00015000 08:02 16824251                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fd805ab4000-7fd805ab9000 r-xp 00000000 08:02 588530                     /usr/lib64/nginx/modules/ngx_http_headers_more_filter_module.so
7fd805ab9000-7fd805cb8000 ---p 00005000 08:02 588530                     /usr/lib64/nginx/modules/ngx_http_headers_more_filter_module.so
7fd805cb8000-7fd805cb9000 r--p 00004000 08:02 588530                     /usr/lib64/nginx/modules/ngx_http_headers_more_filter_module.so
7fd805cb9000-7fd805cba000 rw-p 00005000 08:02 588530                     /usr/lib64/nginx/modules/ngx_http_headers_more_filter_module.so
7fd805cba000-7fd805cc6000 r-xp 00000000 08:02 16844961                   /usr/lib64/libnss_files-2.17.so
7fd805cc6000-7fd805ec5000 ---p 0000c000 08:02 16844961                   /usr/lib64/libnss_files-2.17.so
7fd805ec5000-7fd805ec6000 r--p 0000b000 08:02 16844961                   /usr/lib64/libnss_files-2.17.so
7fd805ec6000-7fd805ec7000 rw-p 0000c000 08:02 16844961                   /usr/lib64/libnss_files-2.17.so
7fd805ec7000-7fd805ecd000 rw-p 00000000 00:00 0
7fd805ecd000-7fd805ef1000 r-xp 00000000 08:02 16807739                   /usr/lib64/libselinux.so.1
7fd805ef1000-7fd8060f0000 ---p 00024000 08:02 16807739                   /usr/lib64/libselinux.so.1
7fd8060f0000-7fd8060f1000 r--p 00023000 08:02 16807739                   /usr/lib64/libselinux.so.1
7fd8060f1000-7fd8060f2000 rw-p 00024000 08:02 16807739                   /usr/lib64/libselinux.so.1
7fd8060f2000-7fd8060f4000 rw-p 00000000 00:00 0
7fd8060f4000-7fd80610a000 r-xp 00000000 08:02 16885935                   /usr/lib64/libresolv-2.17.so
7fd80610a000-7fd80630a000 ---p 00016000 08:02 16885935                   /usr/lib64/libresolv-2.17.so
7fd80630a000-7fd80630b000 r--p 00016000 08:02 16885935                   /usr/lib64/libresolv-2.17.so
7fd80630b000-7fd80630c000 rw-p 00017000 08:02 16885935                   /usr/lib64/libresolv-2.17.so
7fd80630c000-7fd80630e000 rw-p 00000000 00:00 0
7fd80630e000-7fd806311000 r-xp 00000000 08:02 16839417                   /usr/lib64/libkeyutils.so.1.5
7fd806311000-7fd806510000 ---p 00003000 08:02 16839417                   /usr/lib64/libkeyutils.so.1.5
7fd806510000-7fd806511000 r--p 00002000 08:02 16839417                   /usr/lib64/libkeyutils.so.1.5
7fd806511000-7fd806512000 rw-p 00003000 08:02 16839417                   /usr/lib64/libkeyutils.so.1.5
7fd806512000-7fd806520000 r-xp 00000000 08:02 16788377                   /usr/lib64/libkrb5support.so.0.1
7fd806520000-7fd806720000 ---p 0000e000 08:02 16788377                   /usr/lib64/libkrb5support.so.0.1
7fd806720000-7fd806721000 r--p 0000e000 08:02 16788377                   /usr/lib64/libkrb5support.so.0.1
7fd806721000-7fd806722000 rw-p 0000f000 08:02 16788377                   /usr/lib64/libkrb5support.so.0.1
7fd806722000-7fd806753000 r-xp 00000000 08:02 16788357                   /usr/lib64/libk5crypto.so.3.1
7fd806753000-7fd806952000 ---p 00031000 08:02 16788357                   /usr/lib64/libk5crypto.so.3.1
7fd806952000-7fd806954000 r--p 00030000 08:02 16788357                   /usr/lib64/libk5crypto.so.3.1
7fd806954000-7fd806955000 rw-p 00032000 08:02 16788357                   /usr/lib64/libk5crypto.so.3.1
7fd806955000-7fd806958000 r-xp 00000000 08:02 16828155                   /usr/lib64/libcom_err.so.2.1
7fd806958000-7fd806b57000 ---p 00003000 08:02 16828155                   /usr/lib64/libcom_err.so.2.1
7fd806b57000-7fd806b58000 r--p 00002000 08:02 16828155                   /usr/lib64/libcom_err.so.2.1
7fd806b58000-7fd806b59000 rw-p 00003000 08:02 16828155                   /usr/lib64/libcom_err.so.2.1
7fd806b59000-7fd806c32000 r-xp 00000000 08:02 16788375                   /usr/lib64/libkrb5.so.3.3
7fd806c32000-7fd806e31000 ---p 000d9000 08:02 16788375                   /usr/lib64/libkrb5.so.3.3
7fd806e31000-7fd806e3f000 r--p 000d8000 08:02 16788375                   /usr/lib64/libkrb5.so.3.3
7fd806e3f000-7fd806e42000 rw-p 000e6000 08:02 16788375                   /usr/lib64/libkrb5.so.3.3
7fd806e42000-7fd806e8c000 r-xp 00000000 08:02 16788154                   /usr/lib64/libgssapi_krb5.so.2.2
7fd806e8c000-7fd80708c000 ---p 0004a000 08:02 16788154                   /usr/lib64/libgssapi_krb5.so.2.2
7fd80708c000-7fd80708d000 r--p 0004a000 08:02 16788154                   /usr/lib64/libgssapi_krb5.so.2.2
7fd80708d000-7fd80708f000 rw-p 0004b000 08:02 16788154                   /usr/lib64/libgssapi_krb5.so.2.2
7fd80708f000-7fd807091000 r-xp 00000000 08:02 16782064                   /usr/lib64/libfreebl3.so
7fd807091000-7fd807290000 ---p 00002000 08:02 16782064                   /usr/lib64/libfreebl3.so
7fd807290000-7fd807291000 r--p 00001000 08:02 16782064                   /usr/lib64/libfreebl3.so
7fd807291000-7fd807292000 rw-p 00002000 08:02 16782064                   /usr/lib64/libfreebl3.so
7fd807292000-7fd807456000 r-xp 00000000 08:02 16788883                   /usr/lib64/libc-2.17.so
7fd807456000-7fd807655000 ---p 001c4000 08:02 16788883                   /usr/lib64/libc-2.17.soAborted (core dumped)

But when we remove the following parameters the service is up and running fine

ssl_stapling on;
ssl_stapling_verify on;

**Comment by slact** [comment]
Sir, this is a Wendy's
