### ISSUE TITLE
What is the environment used to generate the benchmark results?

### ISSUE THREAD

**Issue by kant777** [slact/nchan#644]
I see the benchmark results posted on the website but can you please share the environment details such as 

1. How many Nginx workers are being used?

2. How many concurrent connections per worker?

3. How many machines and what is the CPU/Memory used per machine?

4. How many clients are used and what is the machine configuration for each client?

**Comment by slact** [comment]
> 1. How many Nginx workers are being used?

   Look at the benchmark graphic

> 2. How many concurrent connections per worker

  Look at the benchmark graphic. The connections are distributed fairly.

> 3. How many machines and what is the CPU/Memory used per machine?
 
 1 server machine. I don't have the CPU load & memory use information anymore for this particular benchmark. I was primarily measuring response time, not machine load. You can infer whether the system was overloaded from the response times. But I can't give you details CPU & RAM use.

> 4. How many clients are used and what is the machine configuration for each client?

  Look at the benchmark graphic for the client number. It's literally the X axis. Machine configuration was the same as the server machine. I don't have all the kernel turnings for the test anymore, sorry.

**Comment by kant777** [comment]
Thanks. What about the message size?

**Comment by slact** [comment]
the message size was on the order of a few bytes. I did not want to saturate bandwidth or spend time benching TCP buffers.

**Comment by kant777** [comment]
I am trying to see how to support large number of websocket connection while deliver/broadcast notifications of size 5KB under 5ms. From the initial number crunching this is what I got, please let me know if it makes sense or suggest an appropriate path

Input

Message size = 5KB
Bandwidth = 10Gbps ~ 1.25GB/sec
Target latency = 5ms

To Find?

Max number of concurrent connections to broadcast

1.25GB/5KB = 250,000 messages per second => 250 per ms => 1250 per 5ms

so the max number of concurrent connections = 1250


I know this is theory and in practice it would be lower but if I can support over 1K sockets under 5ms that would be great. I wonder nchan can get to this number?

**Comment by slact** [comment]
It's fine for napkin calculations, but I encourage you to actually test this out and report your results.

**Comment by slact** [comment]
no further info provided from submitter -- closing
