### ISSUE TITLE
Authentication via message

### ISSUE THREAD

**Issue by KamranBiglari** [slact/nchan#663]
Is there any possibility of using the message body for authentication instead of the header? I want my client to connect to the WebSocket and send the login command and if the login was successful send the command for subscribing to the channel. 

Login command:
```
{"command":"login","username":"USERNAME","password":"PASSWORD"}
```

Subscribe command:
```
{"command":"subscribe","channel":"CHANNEL_NAME"}
```

**Comment by bublikOff** [comment]
You can try to use alternative events stream code (JavaScript) ... for eg I do auth over jwt token in url
