### ISSUE TITLE
nchan_subscriber_info no longer works with nchan 1.3.0

### ISSUE THREAD

**Issue by mkdewidar** [slact/nchan#671]
In nchan 1.3.0 support was added for Redis sharded pubsub, however the `request_subscriber_info` script which is used to push results to the subscriber request channel, uses PUBLISH, instead of SPUBLISH which causes no data to reach the subscriber request caller.

I may look into creating a PR for this as the change seems simple, but wanted to create this in the meantime to track the issue.

**Comment by slact** [comment]
fixed in 693417038c79728493ea464d7ead215c12abdd26
