### ISSUE TITLE
Missed message for websocket subscriber.

### ISSUE THREAD

**Issue by keepthemomentum** [slact/nchan#689]
I'm using nchan for chat, there is a lot of warning messages in the log, these are only subscriber events. 
what does it mean? I would like to understand what these messages are and why i receive them though i can send and receive messages. Is it something that i need to be worried about?

**nchan: Missed message for websocket subscriber: previous message id times don't match. The message probably expired**

**Comment by slact** [comment]
It means the publishing rate per channel is too high for some subscribers that reconnect to catch up. Try extending the buffer length or time.
