### ISSUE TITLE
Feature request: Flash patch, another approach

### ISSUE THREAD

**Issue by herby** [slact/nchan#77]
I will be really happy to use it from Flash, which does only serve the content, not the headers...
Only two headers are in fact important, so the subscriber can reliably poll the next message: ETag and Last-Modified.
Could you, please, include a (at least I hope) minimalistic patch option, which, when included with (or a flag to) push_subscriber would send

    etag*lastModified*body

instead of body (where * is any suitable delimiter which is known not to be present in any etag nor date?
Alternative subscriber paths could then be configured for flash (and any other platforms where headers cannot be read).
(of course if appending is better than prepending, it is ok, too).

I believe this is much simpler change than the alternative with counters, which require more bookkeeping and a _lot_ of testing (for this, one test (and maybe one for non-20x) would be enough for me if I'd be the developer to be sure it works).

Thanx, Herby

**Comment by slact** [comment]
an update 4 years later: ... I don't think this is going to happen for mainline nchan. At least not in the requested form. I might do something with the multipart mimetype to include the headers though. Let me know if you're still interested.
