### ISSUE TITLE
failed to register channel handler while initializing push module worker on Start nginx

### ISSUE THREAD

**Issue by blacknot** [slact/nchan#83]
**nginx -V**
nginx version: nginx/1.3.7
TLS SNI support enabled
configure arguments: --prefix=/usr --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error_log --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --with-cc-opt=-I/usr/include --with-ld-opt=-L/usr/lib --http-log-path=/var/log/nginx/access_log --http-client-body-temp-path=/var/tmp/nginx/client --http-proxy-temp-path=/var/tmp/nginx/proxy --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi --http-scgi-temp-path=/var/tmp/nginx/scgi --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi --with-ipv6 --with-pcre --without-http_browser_module --without-http_charset_module --without-http_empty_gif_module --without-http_geo_module --without-http_limit_req_module --without-http_limit_conn_module --without-http_map_module --without-http_referer_module --without-http_scgi_module --without-http_split_clients_module --without-http_upstream_ip_hash_module --without-http_userid_module --without-http_uwsgi_module --with-http_flv_module --with-http_gzip_static_module --with-http_stub_status_module --with-http_realip_module --add-module=/var/tmp/portage/www-servers/nginx-1.3.7/work/agentzh-headers-more-nginx-module-b7c8cfc --add-module=/var/tmp/portage/www-servers/nginx-1.3.7/work/nginx_http_push_module-0.692 --with-http_ssl_module --without-mail_imap_module --without-mail_pop3_module --without-mail_smtp_module --user=nginx --group=nginx

**tail -20 error_log**
2012/11/23 00:04:53 [info] 12041#0: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:66
2012/11/23 00:04:53 [notice] 12044#0: using the "epoll" event method
2012/11/23 00:04:53 [notice] 12044#0: nginx/1.3.7
2012/11/23 00:04:53 [notice] 12044#0: OS: Linux 2.6.36-gentoo-r6
2012/11/23 00:04:53 [notice] 12044#0: getrlimit(RLIMIT_NOFILE): 1024:1024
2012/11/23 00:04:53 [notice] 12045#0: start worker processes
2012/11/23 00:04:53 [notice] 12045#0: start worker process 12046
2012/11/23 00:04:53 [notice] 12045#0: start worker process 12047
2012/11/23 00:04:53 [notice] 12045#0: start cache manager process 12048
2012/11/23 00:04:53 [notice] 12045#0: start cache loader process 12050
2012/11/23 00:04:53 [alert] 12048#0: epoll_ctl(1, 0) failed (1: Operation not permitted)
2012/11/23 00:04:53 [alert] 12048#0: failed to register channel handler while initializing push module worker (1: Operation not permitted)
2012/11/23 00:04:53 [notice] 12045#0: signal 17 (SIGCHLD) received
2012/11/23 00:04:53 [notice] 12045#0: cache manager process 12048 exited with code 2
2012/11/23 00:04:53 [alert] 12045#0: cache manager process 12048 exited with fatal code 2 and cannot be respawned
2012/11/23 00:04:53 [alert] 12050#0: epoll_ctl(1, 0) failed (1: Operation not permitted)
2012/11/23 00:04:53 [alert] 12050#0: failed to register channel handler while initializing push module worker (1: Operation not permitted)
2012/11/23 00:04:53 [notice] 12045#0: signal 17 (SIGCHLD) received
2012/11/23 00:04:53 [notice] 12045#0: cache loader process 12050 exited with code 2
2012/11/23 00:04:53 [notice] 12045#0: signal 29 (SIGIO) received

**Comment by s-a-s-k-i-a** [comment]
seeing this error with current nginx mainline and fastcgi cache enabled.
error.log
````
Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:114
````

my config:
```
root@server:~# nginx -V
nginx version: nginx/1.9.9
built with OpenSSL 1.0.2e 3 Dec 2015
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_random_index_module --with-http_secure_link_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-http_slice_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --with-threads --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-dav-ext-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/ngx-fancyindex --add-module=/usr/src/packages/BUILD/debian/modules/nginx-http-push --add-module=/usr/src/packages/BUILD/debian/modules/nginx-lua --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upload-progress --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-development-kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/ngx_pagespeed
````

This is part of my nginx.conf

````
user www-data;
worker_processes 8;
worker_rlimit_nofile 100000;
pid /run/nginx.pid;

events {
	worker_connections 4096;
	multi_accept on;
}
```

Do you need anymore info? user www-data is user id 33 group id 33

**Comment by slact** [comment]
It looks like you're using Debian's nginx-extras package, which bundles the Nginx HTTP Push module, an old version of Nchan. The logged message is not an error.

**Comment by vikasnetbeam** [comment]
i am getting this error: 
2016/12/24 00:03:04 [notice] 12849#0: using inherited sockets from "6;7;8;"
2016/12/24 00:03:07 [info] 12876#0: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:59

    user www-data;
    worker_processes 4;
    pid /run/nginx.pid;
    events {
        worker_connections 768;
        # multi_accept on;
    }
    http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # set client body size to 2M #
        client_max_body_size 50M;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
     }`
