### ISSUE TITLE
If-Modified-Since via GET parameters instead of headers

### ISSUE THREAD

**Issue by crodjer** [slact/nchan#84]
I am trying to use Nginx HTTP push as a notification service, as a trigger to fetch notification from the main server to be precise.
For this I need to use `jsonp` instead of direct request. So it is not possible for me to set If-Modified-Since header. Can it be passed via some other means, like say GET parameter.

**Comment by 1371030** [comment]
XMLHttpRequest cannot load http://c.apple.net/chat/sub. Request header field Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers.
