### ISSUE TITLE
use CORS, No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by 1371030** [slact/nchan#96]
XMLHttpRequest cannot load http://c.apple.net/chat/sub. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.apple.net' is therefore not allowed access. The response had HTTP status code 404.

**Comment by slact** [comment]
I'll get back to you about this very soon.

**Comment by slact** [comment]
i think this is fixed in the upcoming release
